// Code generated by tools/base_stats_parser.py. DO NOT EDIT.
//
// Client build: 1.60.1.69893
// Source:       assets/db_inputs/gametables/1.60.1.69893/{combatratings.txt,basemp.txt,hppersta.txt}
//
// Regenerate with:
//     python3 tools/base_stats_parser.py --build 1.60.1.69893 --inputs assets/db_inputs/gametables/1.60.1.69893

package core

// BaseStatsBuild is the client build these constants were read from.
const BaseStatsBuild = "1.60.1.69893"

// combatratings.txt is present in this build and IS read (see the
// values below), but is not the rule: research/08-stats.md 2 settles
// Forever's rules as flat percentages, full stop, and this table's
// entire purpose is rating-to-percent conversion. Its own columns
// carry the tell: every one of the 123 level rows is identical (a
// live rating table scales with level; this one is a level-invariant
// stub), and it sits next to Mastery/Versatility/Corruption/PvP-Power
// columns and the crit-taken-reduction stat Task 4 deleted from the
// enum - none of which Forever has either. So every value below is
// read from the table and then NOT applied - the constant stays 1.
// combatratings.txt level 60 (read, not applied):
//   Defense Skill = 1
//   Dodge = 12
//   Parry = 15
//   Block = 5
//   Hit - Melee = 10
//   Crit - Melee = 14
//
// basemp.txt and hppersta.txt ARE two of the same three confirmed
// GameTables files, and their values genuinely confirm two of the
// fork's existing hand-typed numbers - they are not redefined here
// (that stays in sim/core/base_stats.go's ClassBaseStats and
// sim/core/character.go's Stamina->Health dependency, to avoid a
// second source of truth), but the match is pinned by
// sim/core/base_stats_test.go so a future mismatch is caught.
// source build: 1.60.1.69893 (basemp.txt level 60 Mana, confirms sim/core/base_stats.go's ClassBaseStats):
//   Warrior = 0
//   Paladin = 1512
//   Hunter = 1720
//   Rogue = 0
//   Priest = 1376
//   Shaman = 1520
//   Mage = 1213
//   Warlock = 1373
//   Druid = 1244
// source build: 1.60.1.69893 (hppersta.txt level 60 Health-per-Stamina, confirms sim/core/character.go:283):
//   Health = 10
//
// Absent tables (do not exist for build 1.60.1.69893; not among the
// three confirmed GameTables files) and what each would supply:
//   chancetomeleecrit.txt / chancetomeleecritbase.txt
//     -> per-class melee crit base values (kept as Era's in sim/core/base_stats.go's ClassBaseCrit)
//   chancetospellcrit.txt / chancetospellcritbase.txt
//     -> per-class spell crit base values (same table; dropped from ClassBaseCrit by the Hit/Crit merge)
//   octbasempbyclass.txt / octclasscombatratingscalar.txt
//     -> an Era-era alternate mana/rating-scalar encoding, superseded by basemp.txt above
//   a per-race/per-class basestats/ mining directory
//     -> Str/Agi/Sta/Int/Spirit/Health/AttackPower allocations (kept as Era's in ClassBaseStats/RaceOffsets)

// Forever: one crit stat for spells and melee.
// Ratings are straight percentages in the Classic lineage.
const CritRatingPerCritChance = 1

// Forever: one hit stat for spells, melee and ranged.
// Ratings are straight percentages in the Classic lineage.
const HitRatingPerHitChance = 1

// Forever keeps melee, ranged and spell haste separate.
// Ratings are straight percentages in the Classic lineage.
const HasteRatingPerHastePercent = 1

// The item unit is a percentage (Edgemaster's 1.0%), not expertise points.
// Ratings are straight percentages in the Classic lineage.
const ExpertiseRatingPerExpertiseChance = 1

// combatratings.txt carries a 'Defense Skill' column, but it is not the rule (see header).
// Ratings are straight percentages in the Classic lineage.
const DefenseRatingPerDefense = 1

// combatratings.txt carries a 'Dodge' column, but it is not the rule (see header).
// Ratings are straight percentages in the Classic lineage.
const DodgeRatingPerDodgeChance = 1

// combatratings.txt carries a 'Parry' column, but it is not the rule (see header).
// Ratings are straight percentages in the Classic lineage.
const ParryRatingPerParryChance = 1

// combatratings.txt carries a 'Block' column, but it is not the rule (see header).
// Ratings are straight percentages in the Classic lineage.
const BlockRatingPerBlockChance = 1
