package core

import (
	"os"
	"strings"
	"testing"

	"github.com/wowsims/classic/sim/core/proto"
	"github.com/wowsims/classic/sim/core/stats"
)

// Pins the H3 ruling from the Task 4 fix round: research/08-stats.md §7
// leaves the baseline Agility/Intellect-to-Crit conversion "entirely
// unpublished" for the unified model, so every class keeps its pre-merge
// sources — a hybrid that converted both keeps both (stacking, marked
// unconfirmed); a class that converted only one keeps only that one,
// unchanged. All nine classes that wire a base-stat-to-Crit dependency are
// asserted here against the one table (sim/core/base_stats.go), which is
// the single place a later ruling edits instead of the nine
// AddStatDependency call sites across sim/druid, sim/shaman,
// sim/paladin, sim/warlock, sim/hunter, sim/rogue, sim/mage, sim/priest
// and sim/warrior.
func TestCritStatSourcesArePinned(t *testing.T) {
	expected := map[proto.Class]CritStatSources{
		// Hybrids: stack Agility- and Intellect-derived Crit, unconfirmed.
		proto.Class_ClassDruid:   {Agility: true, Intellect: true},
		proto.Class_ClassShaman:  {Agility: true, Intellect: true},
		proto.Class_ClassPaladin: {Agility: true, Intellect: true},
		proto.Class_ClassWarlock: {Agility: true, Intellect: true},
		proto.Class_ClassHunter:  {Agility: true, Intellect: true},
		// Single-source: unchanged from before the merge.
		proto.Class_ClassRogue:   {Agility: true},
		proto.Class_ClassWarrior: {Agility: true},
		proto.Class_ClassMage:    {Intellect: true},
		proto.Class_ClassPriest:  {Intellect: true},
	}

	if len(ClassCritStatSources) != len(expected) {
		t.Fatalf("ClassCritStatSources has %d entries, want %d — a class was added or removed without updating this pin",
			len(ClassCritStatSources), len(expected))
	}
	for class, want := range expected {
		got, ok := ClassCritStatSources[class]
		if !ok {
			t.Errorf("ClassCritStatSources is missing %v", class)
			continue
		}
		if got != want {
			t.Errorf("ClassCritStatSources[%v] = %+v, want %+v", class, got, want)
		}
	}
}

// Demonstrates (and pins) the actual arithmetic: a hybrid class's Agility
// and Intellect both add into the one Crit stat, because
// StatDependencyManager sums every enabled dependency into its
// destination (see TestMultipleStatDep in sim/core/stats/deps_test.go for
// the same behaviour at the mechanism level). If a later ruling on
// research/08-stats.md §7 decides a hybrid should draw from only one
// source, this is the test that must change, alongside
// ClassCritStatSources.
func TestCritStatSourcesStackForHybrids(t *testing.T) {
	class := proto.Class_ClassDruid
	agi, intel := 100.0, 200.0

	character := &Character{}
	AddCritStatDependencies(character, class)

	result := character.SortAndApplyStatDependencies(stats.Stats{
		stats.Agility:   agi,
		stats.Intellect: intel,
	})

	wantCrit := agi*CritPerAgiAtLevel[class]*CritRatingPerCritChance + intel*CritPerIntAtLevel[class]*CritRatingPerCritChance
	if result[stats.Crit] != wantCrit {
		t.Fatalf("Crit = %v, want %v (Agility and Intellect contributions summed)", result[stats.Crit], wantCrit)
	}
}

// A class absent from ClassCritStatSources (every class that wires a
// base-stat-to-Crit dependency is listed — see TestCritStatSourcesArePinned)
// gets neither dependency, and the helper must not panic on an unlisted
// class.
func TestCritStatSourcesNoOpForUnlistedClass(t *testing.T) {
	character := &Character{}
	AddCritStatDependencies(character, proto.Class_ClassUnknown)

	result := character.SortAndApplyStatDependencies(stats.Stats{
		stats.Agility:   100,
		stats.Intellect: 100,
	})
	if result[stats.Crit] != 0 {
		t.Fatalf("Crit = %v, want 0 for a class with no CritStatSources entry", result[stats.Crit])
	}
}

// A single-source class (e.g. Rogue: Agility only) draws Crit from only
// that stat — the Intellect it also has does not leak in, unlike a
// hybrid's deliberate stacking in TestCritStatSourcesStackForHybrids.
func TestCritStatSourcesSingleSourceDoesNotStack(t *testing.T) {
	class := proto.Class_ClassRogue
	agi, intel := 100.0, 200.0

	character := &Character{}
	AddCritStatDependencies(character, class)

	result := character.SortAndApplyStatDependencies(stats.Stats{
		stats.Agility:   agi,
		stats.Intellect: intel,
	})

	wantCrit := agi * CritPerAgiAtLevel[class] * CritRatingPerCritChance
	if result[stats.Crit] != wantCrit {
		t.Fatalf("Crit = %v, want %v (Agility only; Intellect must not contribute)", result[stats.Crit], wantCrit)
	}
}

// Every rating constant must come from the client tables, not from a
// literal somebody typed. The generated file names the build it came
// from, and the test refuses a file that has been hand-edited.
func TestBaseStatsFileIsGenerated(t *testing.T) {
	b, err := os.ReadFile("base_stats_auto_gen.go")
	if err != nil {
		t.Fatal(err)
	}
	src := string(b)
	if !strings.Contains(src, "Code generated by tools/base_stats_parser.py. DO NOT EDIT.") {
		t.Error("base_stats_auto_gen.go is missing the generated-code header")
	}
	if strings.Contains(src, "TODO") {
		t.Error("base_stats_auto_gen.go contains a TODO; it is generated, so a TODO means it was hand-edited")
	}
	if BaseStatsBuild == "" {
		t.Error("BaseStatsBuild is empty; the generator must record the client build")
	}
	// Every constant carries a note saying which build its value actually
	// came from, so the file is readable line by line rather than being
	// labelled wholly one thing or another.
	if BaseStatsBuild != "" && !strings.Contains(src, "// source build:") {
		t.Error("base_stats_auto_gen.go carries no per-constant source-build notes")
	}
}

// Ratings are straight percentages in the Classic lineage and Forever
// keeps that (research/08-stats.md 2: "FLAT PERCENTAGES...the major
// engine decision and it is settled"), so each of these eight is exactly
// 1: one point of rating is one percent. Defense/Dodge/Parry/Block are
// here too, not exempted: combatratings.txt carries those four columns
// for build 1.60.1.69893, but the table is level-invariant lineage
// boilerplate (identical across all 123 rows) sitting next to Mastery/
// Versatility/Corruption/PvP-Power columns Forever provably does not
// have - it is not the rule, exactly like the Hit/Crit columns of the
// same table this generator already declines to apply. A regeneration
// that silently started reading any of these eight from a table would
// scale every hit, crit, dodge, parry, block and defense chance in the
// engine, so the exact value is asserted rather than its sign, and the
// header's disclaimer is asserted too so a change of heart cannot happen
// silently.
func TestRatingConstantsAreOneToOnePercentages(t *testing.T) {
	cases := []struct {
		name string
		got  float64
	}{
		{"CritRatingPerCritChance", CritRatingPerCritChance},
		{"HitRatingPerHitChance", HitRatingPerHitChance},
		{"HasteRatingPerHastePercent", HasteRatingPerHastePercent},
		{"ExpertiseRatingPerExpertiseChance", ExpertiseRatingPerExpertiseChance},
		{"DefenseRatingPerDefense", DefenseRatingPerDefense},
		{"DodgeRatingPerDodgeChance", DodgeRatingPerDodgeChance},
		{"ParryRatingPerParryChance", ParryRatingPerParryChance},
		{"BlockRatingPerBlockChance", BlockRatingPerBlockChance},
	}
	for _, c := range cases {
		if c.got != 1 {
			t.Errorf("%s = %v, want exactly 1 (Forever uses flat percentages, research/08-stats.md 2)", c.name, c.got)
		}
	}

	b, err := os.ReadFile("base_stats_auto_gen.go")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "is not the rule") {
		t.Error("base_stats_auto_gen.go no longer documents combatratings.txt as present-but-not-the-rule; if it now reads Defense/Dodge/Parry/Block from that table, research/08-stats.md 2 (flat percentages) has been silently reversed")
	}
}

// basemp.txt and hppersta.txt are two of the three GameTables files the
// data lane has confirmed exist for build 1.60.1.69893. They are not
// wired in as new runtime constants - ClassBaseStats' Mana fields and
// character.go's Stamina->Health dependency already carry these exact
// values, and duplicating them would just be a second source of truth -
// but this test pins that the vendored tables and the fork's hand-typed
// values still agree, so a future drift is caught rather than silently
// mislabelled unconfirmed.
func TestBaseManaAndHealthPerStaminaConfirmedAgainstTheTable(t *testing.T) {
	// basemp.txt, build 1.60.1.69893, level 60.
	wantMana := map[proto.Class]float64{
		proto.Class_ClassWarrior: 0,
		proto.Class_ClassPaladin: 1512,
		proto.Class_ClassHunter:  1720,
		proto.Class_ClassRogue:   0,
		proto.Class_ClassPriest:  1376,
		proto.Class_ClassShaman:  1520,
		proto.Class_ClassMage:    1213,
		proto.Class_ClassWarlock: 1373,
		proto.Class_ClassDruid:   1244,
	}
	for class, want := range wantMana {
		got := ClassBaseStats[class][stats.Mana]
		if got != want {
			t.Errorf("ClassBaseStats[%v][stats.Mana] = %v, want %v (basemp.txt, build 1.60.1.69893, level 60)", class, got, want)
		}
	}

	// hppersta.txt, build 1.60.1.69893, level 60, is a flat 10 (verified
	// flat across every level in the vendored file). character.go itself
	// is outside this task's file list, so this is asserted by reading
	// its source rather than by adding a named constant there.
	b, err := os.ReadFile("character.go")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "AddStatDependency(stats.Stamina, stats.Health, 10)") {
		t.Error("character.go's Stamina->Health dependency no longer reads 10; hppersta.txt (build 1.60.1.69893) confirms 10, so update this test's expectation together with the source")
	}
}

// Expertise is already modelled in the attack table (spell_outcome.go
// reduces dodge and parry by stats.Expertise/100) and is dormant in
// vanilla but live for Forever.
func TestExpertiseIsAFlatPercentage(t *testing.T) {
	// The item unit is a percentage (Edgemaster's is 1.0%), not
	// expertise points, so the conversion is 1:1 and the quarter-percent
	// quantisation from later expansions must not come back.
	if ExpertiseRatingPerExpertiseChance != 1 {
		t.Errorf("ExpertiseRatingPerExpertiseChance = %v, want 1", ExpertiseRatingPerExpertiseChance)
	}
	b, err := os.ReadFile("base_stats_auto_gen.go")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(b), "ExpertisePerQuarterPercentReduction") {
		t.Error("the quarter-percent expertise quantisation is back; Forever's item unit is a percentage")
	}
	if strings.Contains(string(b), "Resilience") {
		t.Error("a resilience constant is back; Forever adds no resilience")
	}
}

// Until the per-race/class base-stat table is mined for Forever, every
// name here still carries an unconfirmed value. The engine says so out
// loud, and the spec support page repeats it, rather than letting a
// player assume the numbers are Forever's.
func TestProvisionalConstantsAreDeclared(t *testing.T) {
	got := ProvisionalConstants()
	if len(got) == 0 {
		t.Skip("no provisional constants: the Forever tables have landed, and this test has done its job")
	}
	for _, name := range got {
		if name == "" {
			t.Error("ProvisionalConstants() contains an empty name")
		}
	}
	b, err := os.ReadFile("base_stats_provisional.go")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "unconfirmed") {
		t.Error("base_stats_provisional.go must mark its values unconfirmed")
	}
}

// Skyborne base stats are not in any mined table. They ship as clones of
// a vanilla row, marked, and named by ProvisionalConstants, so nobody
// mistakes a Skyborne sim's numbers for measured ones. When the real
// table lands this test fails, which is the point.
//
// Asserted against RaceOffsets and getBaseStatsCombo - what
// character.go:153 actually reads to compute a character's base stats -
// rather than the BaseStatsKey-keyed BaseStats map: that map is
// unpopulated and unread by any runtime path in this fork, so comparing
// through it would pass vacuously (two absent entries are both the zero
// value). Standing ruling (Task 9): no production behaviour, including a
// package init(), exists purely to give a test something to compare.
func TestSkyborneBaseStatsAreDeclaredClones(t *testing.T) {
	al := getBaseStatsCombo(proto.Race_RaceHighOrderSkyborne, proto.Class_ClassWarrior)
	human := getBaseStatsCombo(proto.Race_RaceHuman, proto.Class_ClassWarrior)
	if al != human {
		t.Log("Skyborne base stats are no longer a clone of Human: a real table has landed. Remove the clone, remove this test, and drop the two entries from ProvisionalConstants.")
		t.Fail()
	}
	var named int
	for _, n := range ProvisionalConstants() {
		if strings.Contains(n, "Skyborne") {
			named++
		}
	}
	if named != 2 {
		t.Errorf("ProvisionalConstants names %d Skyborne entries, want 2", named)
	}
}

// The Crit column of ClassBaseCrit is max(SpellCrit, MeleeCrit) over Era's
// pair, with one exception the table documents: upstream's MeleeCrit column
// is its Dodge column duplicated for all nine classes, so where that value
// would win the max it is discarded and the spell value taken. This test
// pins the nine merged values, and separately pins the rule that no class
// takes a Crit equal to its Dodge while a lower spell value exists — the
// shape that would mean the duplicated column crept back in.
func TestClassBaseCritDropsTheDuplicatedMeleeColumn(t *testing.T) {
	// Era's pair per class, read from master:sim/core/base_stats.go:84-130.
	type eraPair struct{ spell, melee float64 }
	era := map[proto.Class]eraPair{
		proto.Class_ClassWarrior: {0.0, 0.0},
		proto.Class_ClassPaladin: {3.5, 0.7},
		proto.Class_ClassHunter:  {3.6, 0.0},
		proto.Class_ClassRogue:   {0.0, 0.0},
		proto.Class_ClassPriest:  {0.8, 3.0},
		proto.Class_ClassShaman:  {2.3, 1.7},
		proto.Class_ClassMage:    {0.2, 3.2},
		proto.Class_ClassWarlock: {1.7, 2.0},
		proto.Class_ClassDruid:   {1.8, 0.9},
	}
	want := map[proto.Class]float64{
		proto.Class_ClassWarrior: 0.0,
		proto.Class_ClassPaladin: 3.5,
		proto.Class_ClassHunter:  3.6,
		proto.Class_ClassRogue:   0.0,
		proto.Class_ClassPriest:  0.8, // melee 3.0 == Dodge 3.0, discarded
		proto.Class_ClassShaman:  2.3,
		proto.Class_ClassMage:    0.2, // melee 3.2 == Dodge 3.2, discarded
		proto.Class_ClassWarlock: 1.7, // melee 2.0 == Dodge 2.0, discarded
		proto.Class_ClassDruid:   1.8,
	}
	for class, wantCrit := range want {
		row := ClassBaseCrit[class]
		gotCrit := row[stats.Crit] / CritRatingPerCritChance
		if gotCrit != wantCrit {
			t.Errorf("%v base Crit is %.4f, want %.4f", class, gotCrit, wantCrit)
		}
		gotDodge := row[stats.Dodge] / DodgeRatingPerDodgeChance
		if gotDodge != era[class].melee {
			t.Errorf("%v base Dodge is %.4f, want Era's %.4f", class, gotDodge, era[class].melee)
		}
		if gotCrit == gotDodge && era[class].spell < gotDodge {
			t.Errorf("%v takes base Crit %.4f, which is its Dodge value, over a lower spell value %.4f: the duplicated melee column is back", class, gotCrit, era[class].spell)
		}
	}
	if len(ClassBaseCrit) != len(want)+1 { // +1 for ClassUnknown
		t.Errorf("ClassBaseCrit has %d entries, want %d; a new class needs a row here", len(ClassBaseCrit), len(want)+1)
	}
}
