// Code generated by tools/base_stats_parser.py. DO NOT EDIT.
//
// Client build: 1.60.1.69893
// Source:       assets/db_inputs/gametables/1.60.1.69893/combatratings.txt
//
// Regenerate with:
//     python3 tools/base_stats_parser.py --build <build> --inputs <dir>

package core

// BaseStatsBuild is the client build these constants were read from.
const BaseStatsBuild = "1.60.1.69893"

// source build: 1.60.1.69893 (combatratings.txt column 'Defense Skill')
const DefenseRatingPerDefense = 1.000000

// source build: 1.60.1.69893 (combatratings.txt column 'Dodge')
const DodgeRatingPerDodgeChance = 12.000000

// source build: 1.60.1.69893 (combatratings.txt column 'Parry')
const ParryRatingPerParryChance = 15.000000

// source build: 1.60.1.69893 (combatratings.txt column 'Block')
const BlockRatingPerBlockChance = 5.000000

// Forever: one crit stat for spells and melee.
// Ratings are straight percentages in the Classic lineage.
const CritRatingPerCritChance = 1

// Forever: one hit stat for spells, melee and ranged.
// Ratings are straight percentages in the Classic lineage.
const HitRatingPerHitChance = 1

// Forever keeps melee, ranged and spell haste separate.
// Ratings are straight percentages in the Classic lineage.
const HasteRatingPerHastePercent = 1

// The item unit is a percentage (Edgemaster's 1.0%), not expertise points.
// Ratings are straight percentages in the Classic lineage.
const ExpertiseRatingPerExpertiseChance = 1
