package shaman

import (
	"time"

	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/stats"
)

// The Restoration tree's numbers, each from talents/shaman.json's text for
// the node named beside it.
const (
	// Improved Healing Wave (104739): "Reduces the casting time of your
	// Healing Wave spell by 0.1 sec" per rank.
	improvedHealingWaveCastTimePerRank = 100 * time.Millisecond
	// Tidal Focus (104735): "Reduces the Mana cost of your healing spells
	// by 1% and improves your chance to hit by 1%" per rank.
	tidalFocusManaCostPercentPerRank = 1
	tidalFocusHitPercentPerRank      = 1
	// Tidal Mastery (104738): "Increases the critical effect chance of
	// your healing spells by 1%" per rank.
	tidalMasteryCritPercentPerRank = 1
	// Purification (104725): "Increases the effectiveness of your healing
	// spells by 2%" per rank.
	purificationPercentPerRank = 2
	// Natural Grace (104736): "Reduces the threat generated by your spells
	// by 5%" per rank.
	naturalGraceThreatReductionPerRank = 0.05
	// Restorative Totems (104730): "Increases the effect of your Mana
	// Spring Totem by 5% and increases the effect of your Healing Stream
	// Totem by 10%" per rank.
	restorativeManaSpringPerRank    = 0.05
	restorativeHealingStreamPerRank = 0.10
)

// healingWayPercent is Healing Way's three ranks (104727): "Increases the
// amount healed by your Healing Wave spell by 8%, 17%, 25%".
var healingWayPercent = [4]int64{0, 8, 17, 25}

// mindfulnessRegenWhileCasting is Mindfulness's three ranks (104734):
// "Allows 17%, 33%, 50% of your Mana regeneration to continue while
// casting".
var mindfulnessRegenWhileCasting = [4]float64{0, 0.17, 0.33, 0.50}

// applyRestorationTalents applies the Restoration talents that modify the
// healing spells (or the shaman's regeneration). The cooldown talents
// (Nature's Swiftness, Mana Tide Totem, Riptide) and Water Shield register
// spells and are applied in their own files.
func (shaman *Shaman) applyRestorationTalents() {
	t := shaman.Talents

	if t.ImprovedHealingWave > 0 {
		shaman.AddStaticMod(core.SpellModConfig{
			Kind:      core.SpellMod_CastTime_Flat,
			ClassMask: ShamanSpellMaskHealingWave,
			TimeValue: -improvedHealingWaveCastTimePerRank * time.Duration(t.ImprovedHealingWave),
		})
	}

	if t.TidalFocus > 0 {
		shaman.AddStaticMod(core.SpellModConfig{
			Kind:      core.SpellMod_PowerCost_Pct,
			ClassMask: ShamanSpellMaskHealing,
			IntValue:  -tidalFocusManaCostPercentPerRank * int64(t.TidalFocus),
		})
		shaman.AddStat(stats.Hit, tidalFocusHitPercentPerRank*float64(t.TidalFocus)*core.HitRatingPerHitChance)
	}

	if t.TidalMastery > 0 {
		shaman.AddStaticMod(core.SpellModConfig{
			Kind:       core.SpellMod_BonusCrit_Flat,
			ClassMask:  ShamanSpellMaskHealing,
			FloatValue: tidalMasteryCritPercentPerRank * float64(t.TidalMastery) * core.CritRatingPerCritChance,
		})
	}

	if t.Purification > 0 {
		shaman.AddStaticMod(core.SpellModConfig{
			Kind:      core.SpellMod_DamageDone_Flat,
			ClassMask: ShamanSpellMaskHealing,
			IntValue:  purificationPercentPerRank * int64(t.Purification),
		})
	}

	if t.HealingWay > 0 {
		shaman.AddStaticMod(core.SpellModConfig{
			Kind:      core.SpellMod_DamageDone_Flat,
			ClassMask: ShamanSpellMaskHealingWave,
			IntValue:  healingWayPercent[rankIndex(t.HealingWay, len(healingWayPercent))],
		})
	}

	if t.NaturalGrace > 0 {
		shaman.AddStaticMod(core.SpellModConfig{
			Kind:       core.SpellMod_Threat_Pct,
			SpellFlags: SpellFlagShaman,
			FloatValue: 1 - naturalGraceThreatReductionPerRank*float64(t.NaturalGrace),
		})
	}

	if t.Mindfulness > 0 {
		shaman.PseudoStats.SpiritRegenRateCasting += mindfulnessRegenWhileCasting[rankIndex(t.Mindfulness, len(mindfulnessRegenWhileCasting))]
	}
}

// purificationHealingModifier is Purification as a fraction, for the
// Healing Stream Totem's heal, which is not a cast spell the class mask
// reaches.
func (shaman *Shaman) purificationHealingModifier() float64 {
	return float64(purificationPercentPerRank*shaman.Talents.Purification) / 100
}

// restorativeHealingStreamModifier is Restorative Totems' share of the
// Healing Stream Totem's effect, as a fraction.
func (shaman *Shaman) restorativeHealingStreamModifier() float64 {
	return restorativeHealingStreamPerRank * float64(shaman.Talents.RestorativeTotems)
}

// restorativeManaSpringMultiplier is the factor Restorative Totems puts on
// Mana Spring's regeneration.
func (shaman *Shaman) restorativeManaSpringMultiplier() float64 {
	return 1 + restorativeManaSpringPerRank*float64(shaman.Talents.RestorativeTotems)
}
