package paladin

import (
	"time"

	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/stats"
)

// The Protection tree, as the live client states it (talents/paladin.json,
// build 1.60.1.70009 with Wowhead's 2026-10-07 hotfix overlay). Every
// constant quotes the rank text it came from; where the text leaves a
// number out, the constant says "unconfirmed" and what was assumed.

// ForeverProtectionTalents is the fixed tank input the regression suite
// and the level smoke run, so a change in the golden is attributable to
// the engine rather than to a build edit. It is the build the site's
// Protection paladin guide gives and its tank ranker runs, written against
// the live tree: Holy 17, Protection 16, Retribution 17 characters
// (TalentTreeSizes). Spend:
//
//	Holy 8:         Divine Strength 5, Improved Seals 3
//	Protection 38:  Toughness 5, Redoubt 5, Precision 3, Anticipation 5,
//	                Improved Seal of Fury 1, Improved Righteous Fury 3,
//	                Shield Specialization 3, Sacred Duty 2, Swift
//	                Judgement 1, One-Handed Weapon Specialization 3,
//	                Templar's Bulwark 1, Iron Creed 5, Holy Shield 1
//	Retribution 5:  Deflection 5
//
// Holy Shield is the 31-point talent: it needs 30 points in the tree and
// Templar's Bulwark. The 20 points past it went into the Holy tree's
// healing talents in the first draft of this build, and the same boss
// killed that tank in a real share of fights; Deflection (+5% parry, the
// only parry a paladin can take), Sacred Duty (+4% Stamina) and Iron Creed
// (-10% damage taken for 6 s after Holy Strike) cut that many times over.
// Reckoning priced at threat only and is left out
// (TestForeverProtectionTalentsAreLegal checks the tiers and
// prerequisites against the client's tree).
const ForeverProtectionTalents = "50003000000000000-5530513321301051-50000000000000000"

const (
	// Anticipation (node 105636): "Increases your Defense Skill by 4" at
	// rank 1, 20 at rank 5. Defense feeds dodge, parry, block and crit
	// reduction through the character's defense dependencies.
	anticipationDefensePerRank = 4.0

	// Toughness (node 105630): "Increases your armor value from items by
	// 2%" a rank, 10% at rank 5.
	toughnessArmorPctPerRank = 0.02

	// Precision (node 105638): "Improves your chance to hit by 1%" a rank.
	precisionHitPctPerRank = 1.0

	// Sacred Duty (node 105632): "Increases your total Stamina by 2% and
	// reduces the cooldown of your Divine Shield, Divine Protection, and
	// Templar's Bulwark spells by 30 sec", 4% and 60 sec at rank 2.
	sacredDutyStaminaPerRank           = 0.02
	sacredDutyCooldownReductionPerRank = 30 * time.Second

	// Shield Specialization (node 110874): "Increases the amount of damage
	// absorbed by your shield by 10%, and gives your blocks a 33% chance
	// to restore 6% of your maximum Mana. May only occur once every 3
	// sec." 20% and 66% at rank 2, 30% and 100% at rank 3.
	shieldSpecializationAbsorbPerRank = 0.10
	shieldSpecializationManaFraction  = 0.06
	shieldSpecializationManaICD       = 3 * time.Second
	shieldSpecializationActionID      = 20150

	// Redoubt (node 105626): "Damaging melee attacks against you have a
	// 10% chance to increase your chance to block by 4%. Lasts 10 sec or
	// 5 blocks.", 20% at rank 5 (Blizzard's 1 October 2026 notes, "Redoubt
	// 4-20%"; it triggers on any damaging melee hit, no longer a crit).
	redoubtProcChance         = 0.10
	redoubtBlockChancePerRank = 4.0
	redoubtDuration           = 10 * time.Second
	redoubtBlocks             = 5
	redoubtActionID           = 20134

	// Reckoning (node 105627): "Gives you a 8% chance to gain an extra
	// attack after Blocking a melee attack and a 20% chance to gain an
	// extra attack after being the victim of a non-periodic critical
	// strike", 40% and 100% at rank 5.
	reckoningBlockChancePerRank = 0.08
	reckoningCritChancePerRank  = 0.20
	reckoningActionID           = 20178

	// Iron Creed (node 110879): "Increases the threat generated by your
	// Holy Strike ability by 5%. While Righteous Fury is active, Holy
	// Strike also reduces your damage taken by 2% for 6 sec.", 25% and 10%
	// at rank 5. 1311033 is the id of the trigger the client names.
	ironCreedThreatPerRank      = 0.05
	ironCreedDamageTakenPerRank = 0.02
	ironCreedDuration           = 6 * time.Second
	ironCreedActionID           = 1311033

	// Improved Seal of Fury (node 110875): "When Seal of Fury's shield is
	// fully absorbed, restore 0 Mana, increased by 15% per level the
	// attacker is above you, up to 45%." The base the client prints is 0
	// (an unresolved value in the tooltip), so the amount is UNCONFIRMED:
	// it is assumed to be 1% of maximum mana, scaled by the stated 15% a
	// level up to three levels (the published boss is three above).
	improvedSealOfFuryManaFraction   = 0.01
	improvedSealOfFuryBonusPerLevel  = 0.15
	improvedSealOfFuryMaxLevelsAbove = 3
	improvedSealOfFuryActionID       = 1314103
)

var (
	// shieldSpecializationManaChance is the block-to-mana chance by rank.
	shieldSpecializationManaChance = [4]float64{0, 0.33, 0.66, 1.00}

	// oneHandedWeaponSpecializationPct is "Increases the damage you deal
	// with one-handed melee weapons by 3%/7%/10%" (node 105629): not a
	// clean multiple of rank 1.
	oneHandedWeaponSpecializationPct = [4]float64{0, 0.03, 0.07, 0.10}
)

// applyProtectionTalents applies the Protection tree's passive effects.
// Righteous Fury's own talent (Improved Righteous Fury) is read by
// righteous_fury.go, and Holy Shield, Templar's Bulwark and Swift
// Judgement by their abilities.
func (paladin *Paladin) applyProtectionTalents() {
	t := paladin.Talents

	paladin.AddStat(stats.Hit, precisionHitPctPerRank*float64(t.Precision)*core.HitRatingPerHitChance)
	if t.Toughness > 0 {
		paladin.ApplyEquipScaling(stats.Armor, 1.0+toughnessArmorPctPerRank*float64(t.Toughness))
	}
	paladin.AddStat(stats.Defense, anticipationDefensePerRank*float64(t.Anticipation))
	paladin.MultiplyStat(stats.Stamina, 1.0+sacredDutyStaminaPerRank*float64(t.SacredDuty))

	// Shield Specialization's absorb is the shield's block value, which
	// BlockValue() scales for item block value only (Strength's share is
	// not "damage absorbed by your shield").
	paladin.PseudoStats.BlockValueMultiplier += shieldSpecializationAbsorbPerRank * float64(t.ShieldSpecialization)

	paladin.applyShieldSpecializationMana()
	paladin.applyRedoubt()
	paladin.applyReckoning()
	paladin.applyIronCreed()
	paladin.applyImprovedSealOfFury()
}

func (paladin *Paladin) applyShieldSpecializationMana() {
	rank := paladin.Talents.ShieldSpecialization
	if rank == 0 {
		return
	}

	manaMetrics := paladin.NewManaMetrics(core.ActionID{SpellID: shieldSpecializationActionID})
	core.MakeProcTriggerAura(&paladin.Unit, core.ProcTrigger{
		Name:       "Shield Specialization",
		ActionID:   core.ActionID{SpellID: shieldSpecializationActionID},
		Callback:   core.CallbackOnSpellHitTaken,
		Outcome:    core.OutcomeBlock,
		ProcChance: shieldSpecializationManaChance[rank],
		ICD:        shieldSpecializationManaICD,
		Handler: func(sim *core.Simulation, _ *core.Spell, _ *core.SpellResult) {
			paladin.AddMana(sim, shieldSpecializationManaFraction*paladin.MaxMana(), manaMetrics)
		},
	})
}

// applyRedoubt: any damaging melee hit has a chance to give the block
// bonus, which a refresh brings back to five blocks. One aura owns the
// proc and the spending, so a hit never spends a block of the bonus it
// has just granted.
func (paladin *Paladin) applyRedoubt() {
	rank := paladin.Talents.Redoubt
	if rank == 0 {
		return
	}

	blockBonus := redoubtBlockChancePerRank * float64(rank) * core.BlockRatingPerBlockChance

	paladin.redoubtAura = paladin.RegisterAura(core.Aura{
		Label:     "Redoubt",
		ActionID:  core.ActionID{SpellID: redoubtActionID},
		Duration:  redoubtDuration,
		MaxStacks: redoubtBlocks,
		OnGain: func(_ *core.Aura, sim *core.Simulation) {
			paladin.AddStatDynamic(sim, stats.Block, blockBonus)
		},
		OnExpire: func(_ *core.Aura, sim *core.Simulation) {
			paladin.AddStatDynamic(sim, stats.Block, -blockBonus)
		},
	})

	paladin.RegisterAura(core.Aura{
		Label:    "Redoubt Trigger",
		Duration: core.NeverExpires,
		OnReset: func(aura *core.Aura, sim *core.Simulation) {
			aura.Activate(sim)
		},
		OnSpellHitTaken: func(_ *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
			if result.DidBlock() && paladin.redoubtAura.IsActive() {
				paladin.redoubtAura.RemoveStack(sim)
			}
			if spell.ProcMask.Matches(core.ProcMaskMelee) && result.Landed() && sim.Proc(redoubtProcChance, "Redoubt") {
				paladin.redoubtAura.Activate(sim)
				paladin.redoubtAura.SetStacks(sim, redoubtBlocks)
			}
		},
	})
}

// applyReckoning grants the extra attack on two triggers: blocking a
// melee attack, and any non-periodic critical strike taken (a periodic
// tick reaches OnPeriodicDamageTaken, not OnSpellHitTaken).
func (paladin *Paladin) applyReckoning() {
	rank := float64(paladin.Talents.Reckoning)
	if rank == 0 {
		return
	}

	procID := core.ActionID{SpellID: reckoningActionID}
	grantExtraAttack := func(sim *core.Simulation, spell *core.Spell, _ *core.SpellResult) {
		paladin.AutoAttacks.ExtraMHAttack(sim, 1, procID, spell.ActionID)
	}

	core.MakeProcTriggerAura(&paladin.Unit, core.ProcTrigger{
		Name:       "Reckoning Block Trigger",
		Callback:   core.CallbackOnSpellHitTaken,
		Outcome:    core.OutcomeBlock,
		ProcMask:   core.ProcMaskMelee,
		ProcChance: reckoningBlockChancePerRank * rank,
		Handler:    grantExtraAttack,
	})
	core.MakeProcTriggerAura(&paladin.Unit, core.ProcTrigger{
		Name:       "Reckoning Crit Trigger",
		Callback:   core.CallbackOnSpellHitTaken,
		Outcome:    core.OutcomeCrit,
		ProcChance: reckoningCritChancePerRank * rank,
		Handler:    grantExtraAttack,
	})
}

// applyIronCreed: Holy Strike's threat, and the damage-taken window it
// opens while Righteous Fury is active (the aura is only built for a
// paladin that has Righteous Fury on).
func (paladin *Paladin) applyIronCreed() {
	rank := float64(paladin.Talents.IronCreed)
	if rank == 0 {
		return
	}

	paladin.AddStaticMod(core.SpellModConfig{
		Kind:       core.SpellMod_Threat_Pct,
		ClassMask:  PaladinSpellMaskHolyStrike,
		FloatValue: 1 + ironCreedThreatPerRank*rank,
	})

	if !paladin.Options.RighteousFury {
		return
	}
	paladin.ironCreedAura = paladin.newDamageTakenReductionAura(
		"Iron Creed", core.ActionID{SpellID: ironCreedActionID}, ironCreedDuration, ironCreedDamageTakenPerRank*rank)
}

// newDamageTakenReductionAura is a timed "all damage taken reduced by
// reduction" buff (Iron Creed, Divine Protection).
func (paladin *Paladin) newDamageTakenReductionAura(label string, actionID core.ActionID, duration time.Duration, reduction float64) *core.Aura {
	multiplier := 1 - reduction
	return paladin.RegisterAura(core.Aura{
		Label:    label,
		ActionID: actionID,
		Duration: duration,
		OnGain: func(aura *core.Aura, _ *core.Simulation) {
			aura.Unit.PseudoStats.DamageTakenMultiplier *= multiplier
		},
		OnExpire: func(aura *core.Aura, _ *core.Simulation) {
			aura.Unit.PseudoStats.DamageTakenMultiplier /= multiplier
		},
	})
}

func (paladin *Paladin) applyImprovedSealOfFury() {
	if paladin.Talents.ImprovedSealOfFury {
		paladin.improvedSealOfFuryManaMetrics = paladin.NewManaMetrics(core.ActionID{SpellID: improvedSealOfFuryActionID})
	}
}

// restoreManaForImprovedSealOfFury is Seal of Fury's shield running out:
// mana scaled by how many levels the attacker (three, for the published
// boss) stands above the paladin.
func (paladin *Paladin) restoreManaForImprovedSealOfFury(sim *core.Simulation, attacker *core.Unit) {
	if paladin.improvedSealOfFuryManaMetrics == nil {
		return
	}
	levelsAbove := min(max(attacker.Level-paladin.Level, 0), improvedSealOfFuryMaxLevelsAbove)
	scale := 1 + improvedSealOfFuryBonusPerLevel*float64(levelsAbove)
	paladin.AddMana(sim, improvedSealOfFuryManaFraction*paladin.MaxMana()*scale, paladin.improvedSealOfFuryManaMetrics)
}

// activateIronCreed opens Iron Creed's damage-taken window; it is a no-op
// without the talent or without Righteous Fury.
func (paladin *Paladin) activateIronCreed(sim *core.Simulation) {
	if paladin.ironCreedAura != nil {
		paladin.ironCreedAura.Activate(sim)
	}
}
