package warrior

import (
	"time"

	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/stats"
)

// FOREVER: the Protection tree, written against the client's rank texts
// for build 1.60.1.70009 (data/builds/1.60.1.70009/talents/warrior.json,
// tree "Protection"). Talents that are plain modifiers on a set of spells
// live in applyDeclarativeTalents (Improved Revenge, Improved Thunder
// Clap, Improved Sunder Armor, Focused Rage, Bastion); the ones with
// state, a trigger or a cooldown are here.

const (
	// Shield Specialization: "Increases your chance to Block attacks with
	// your shield by 1% and grants you a 20% chance to generate 5 Rage when
	// you Block" at rank 1, rising to 5% and 100% at rank 5.
	shieldSpecializationBlockPercentPerRank = 1
	shieldSpecializationProcChancePerRank   = 0.2
	shieldSpecializationRage                = 5.0

	// Master of Defense: "Grants you a 50% chance to generate 5 Rage when
	// you Dodge or Parry while a shield is equipped" at rank 1, 100% at
	// rank 2.
	masterOfDefenseProcChancePerRank = 0.5
	masterOfDefenseRage              = 5.0

	// Defiance: "Increases all threat generated in Defensive stance by an
	// additional 5% while a shield is equipped" at rank 1, 15% at rank 3.
	// It is additive to the stance's own +30% (Kenco's measured 1.45 with
	// five vanilla ranks; research/07-simulator.md).
	defianceThreatPerRank = 0.05

	// Improved Bloodrage: "Increases all the Rage generated by your
	// Bloodrage ability by 25%" at rank 1, 50% at rank 2.
	improvedBloodrageRagePerRank = 0.25

	// Last Stand: "temporarily grants you 30% of your maximum health for
	// 20 sec. After the effect expires, the health is lost."
	lastStandHealthFraction = 0.3
	lastStandDuration       = 20 * time.Second
)

// improvedShieldWallCooldownReduction is Improved Shield Wall: "Reduces
// the cooldown of your Shield Wall ability by 5.5 min" at rank 1 and
// "by 11.0 min" at rank 2. The vanilla talent lengthened the duration;
// Forever's cuts the cooldown (Blizzard's reworked-talent notes), and the
// figures are the client's own text, unusually large against the 15 minute
// base (a rank-2 Shield Wall is available every 4 minutes).
var improvedShieldWallCooldownReduction = [3]time.Duration{0, 330 * time.Second, 660 * time.Second}

func (warrior *Warrior) applyProtectionTalents() {
	warrior.applyShieldSpecialization()
	warrior.applyMasterOfDefense()
	warrior.registerLastStandCD()
}

// rageOnHitTaken grants rage with a fixed chance when an incoming attack
// has the outcome matches reports on. Shield Specialization (blocks) and
// Master of Defense (dodges and parries) are the same shape.
func (warrior *Warrior) rageOnHitTaken(label string, spellID int32, chance, rage float64, matches func(*core.SpellResult) bool) {
	rageMetrics := warrior.NewRageMetrics(core.ActionID{SpellID: spellID})

	warrior.RegisterAura(core.Aura{
		Label:    label,
		Duration: core.NeverExpires,
		OnReset: func(aura *core.Aura, sim *core.Simulation) {
			aura.Activate(sim)
		},
		OnSpellHitTaken: func(_ *core.Aura, sim *core.Simulation, _ *core.Spell, result *core.SpellResult) {
			if matches(result) && sim.Proc(chance, label) {
				warrior.AddRage(sim, rage, rageMetrics)
			}
		},
	})
}

// applyShieldSpecialization is Shield Specialization's block chance and
// its rage on a block.
func (warrior *Warrior) applyShieldSpecialization() {
	points := warrior.Talents.ShieldSpecialization
	if points == 0 {
		return
	}

	warrior.AddStat(stats.Block, core.BlockRatingPerBlockChance*shieldSpecializationBlockPercentPerRank*float64(points))

	spellIDs := TalentSpellIDs["shield_specialization"]
	warrior.rageOnHitTaken(
		"Shield Specialization",
		spellIDs[rankIndex(points-1, spellIDs)],
		shieldSpecializationProcChancePerRank*float64(points),
		shieldSpecializationRage,
		(*core.SpellResult).DidBlock,
	)
}

// applyMasterOfDefense is Master of Defense: rage when the warrior dodges
// or parries with a shield equipped.
func (warrior *Warrior) applyMasterOfDefense() {
	points := warrior.Talents.MasterOfDefense
	if points == 0 || !warrior.PseudoStats.CanBlock {
		return
	}

	spellIDs := TalentSpellIDs["master_of_defense"]
	warrior.rageOnHitTaken(
		"Master of Defense",
		spellIDs[rankIndex(points-1, spellIDs)],
		masterOfDefenseProcChancePerRank*float64(points),
		masterOfDefenseRage,
		func(result *core.SpellResult) bool { return result.DidDodge() || result.DidParry() },
	)
}

// defianceThreat is the extra threat multiplier Defiance adds to Defensive
// Stance's own: nothing without a shield.
func (warrior *Warrior) defianceThreat() float64 {
	if !warrior.PseudoStats.CanBlock {
		return 0
	}
	return defianceThreatPerRank * float64(warrior.Talents.Defiance)
}

// improvedBloodrageMultiplier scales every point of rage Bloodrage grants.
func (warrior *Warrior) improvedBloodrageMultiplier() float64 {
	return 1 + improvedBloodrageRagePerRank*float64(warrior.Talents.ImprovedBloodrage)
}

// shieldWallCooldown is Shield Wall's cooldown after Improved Shield Wall.
func (warrior *Warrior) shieldWallCooldown() time.Duration {
	base := time.Duration(ShieldWallCooldownMS[0]) * time.Millisecond
	return base - improvedShieldWallCooldownReduction[rankIndex(warrior.Talents.ImprovedShieldWall, improvedShieldWallCooldownReduction[:])]
}

// registerLastStandCD is Last Stand: it grants lastStandHealthFraction of
// maximum health for lastStandDuration, and "After the effect expires, the
// health is lost" - the current health falls back to the (restored) maximum
// without counting as damage.
func (warrior *Warrior) registerLastStandCD() {
	if !warrior.Talents.LastStand {
		return
	}

	actionID := core.ActionID{SpellID: TalentSpellIDs["last_stand"][0]}
	healthMetrics := warrior.NewHealthMetrics(actionID)

	var bonusHealth float64
	lastStandAura := warrior.RegisterAura(core.Aura{
		Label:    "Last Stand",
		ActionID: actionID,
		Duration: lastStandDuration,
		OnGain: func(aura *core.Aura, sim *core.Simulation) {
			bonusHealth = warrior.MaxHealth() * lastStandHealthFraction
			warrior.AddStatsDynamic(sim, stats.Stats{stats.Health: bonusHealth})
			warrior.GainHealth(sim, bonusHealth, healthMetrics)
		},
		OnExpire: func(aura *core.Aura, sim *core.Simulation) {
			warrior.AddStatsDynamic(sim, stats.Stats{stats.Health: -bonusHealth})
			warrior.ClampToMaxHealth()
		},
	})

	lastStandSpell := warrior.RegisterSpell(AnyStance, core.SpellConfig{
		ActionID: actionID,

		RequiredLevel: LastStandLevel[0],

		Cast: core.CastConfig{
			CD: core.Cooldown{
				Timer:    warrior.NewTimer(),
				Duration: time.Duration(LastStandCooldownMS[0]) * time.Millisecond,
			},
		},

		ApplyEffects: func(sim *core.Simulation, _ *core.Unit, spell *core.Spell) {
			lastStandAura.Activate(sim)
		},
	})

	warrior.AddMajorCooldown(core.MajorCooldown{
		Spell: lastStandSpell.Spell,
		Type:  core.CooldownTypeSurvival,
	})
}

// Not modelled, with the reason beside each. All are in the live
// Protection tree and none moves a number a one-boss, stationary tank
// encounter measures.
//
//	Iron Will          - "Reduces the duration of Stun and Fear effects
//	                     inflicted on you by 3%/.../15%." The tank boss
//	                     neither stuns nor fears.
//	Improved Disarm    - "Reduces the cooldown of your Disarm ability by
//	                     7/13/20 secs." No Disarm is registered: a boss
//	                     is not disarmed in the sim.
//	Vanguard           - "Your Charge ability is now usable while in
//	                     Defensive Stance." No Charge is registered (see
//	                     applyImprovedCharge).
//	Improved Shield Bash - "a 50%/100% chance to Silence the target for 3
//	                     sec." The tank boss casts nothing to silence.
//	Concussion Blow    - "Stuns the target for 5 sec." Bosses are
//	                     stun-immune and the spell has no damage or threat
//	                     of its own (the client row carries only the stun
//	                     aura), so it is the Shield Slam prerequisite and
//	                     nothing more here.
