package mage

import (
	"github.com/wowsims/classic/sim/common/guardians"
	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/proto"
	"github.com/wowsims/classic/sim/core/stats"
)

const (
	SpellFlagMage       = core.SpellFlagAgentReserved1
	SpellFlagChillSpell = core.SpellFlagAgentReserved2
)

const (
	SpellCode_MageNone int32 = iota
	SpellCode_MageArcaneExplosion
	SpellCode_MageArcaneMissiles
	SpellCode_MageArcaneMissilesTick
	SpellCode_MageBlastWave
	SpellCode_MageFireball
	SpellCode_MageFireBlast
	SpellCode_MageFlamestrike
	SpellCode_MageFrostbolt
	SpellCode_MageIgnite
	SpellCode_MageScorch
)

// TalentTreeSizes now lives in talents_auto_gen.go, generated by
// tools/talentgen from the client's trait tables: the sizes, the proto
// message's field order and the planner's talent string have to agree,
// and they only can if one file produces all three.

// Spell masks for the declarative talent mods. One bit per ability, so
// a talent that reads "increases the damage done by your Frost spells"
// is a line of config against a set of bits rather than a closure that
// re-derives the set from the school every time a spell registers.
//
// Bits are never renumbered: a mask is also how a saved mod config and
// a log line name an ability. Masks exist for the abilities Forever
// adds that this package does not register yet (Frost Nova, Cone of
// Cold, Frostfire Bolt) so the talents that name them can be written
// once and start working the day the ability lands.
const (
	MageSpellMaskNone uint64 = 0

	MageSpellMaskFrostbolt uint64 = 1 << iota
	MageSpellMaskIceLance
	MageSpellMaskFrostNova
	MageSpellMaskBlizzard
	MageSpellMaskConeOfCold
	MageSpellMaskIceBarrier
	MageSpellMaskFireball
	MageSpellMaskFrostfireBolt
	MageSpellMaskScorch
	MageSpellMaskPyroblast
	MageSpellMaskFireBlast
	MageSpellMaskFlamestrike
	MageSpellMaskBlastWave
	MageSpellMaskIgnite
	MageSpellMaskArcaneExplosion
	MageSpellMaskArcaneMissiles
	MageSpellMaskArcaneMissilesTick
	MageSpellMaskArcaneBlast
	MageSpellMaskEvocation
	MageSpellMaskColdSnap
	MageSpellMaskCounterspell
	MageSpellMaskManaGem
)

// Groups, named after the tooltip phrases they stand for.
const (
	// "your Frost spells" for damage purposes. Ice Barrier is Frost
	// school but deals none, so it is not here; Piercing Ice would
	// otherwise be applying a damage bonus to an absorb.
	MageSpellMaskFrostDamage = MageSpellMaskFrostbolt | MageSpellMaskIceLance |
		MageSpellMaskFrostNova | MageSpellMaskBlizzard | MageSpellMaskConeOfCold |
		MageSpellMaskFrostfireBolt

	// "your Fire spells" for damage purposes. Ignite is excluded: it is
	// a consequence of a Fire crit rather than a Fire spell the mage
	// casts, and Fire Power has never applied to it.
	MageSpellMaskFireDamage = MageSpellMaskFireball | MageSpellMaskScorch |
		MageSpellMaskPyroblast | MageSpellMaskFrostfireBolt | MageSpellMaskFireBlast |
		MageSpellMaskFlamestrike | MageSpellMaskBlastWave

	MageSpellMaskArcaneDamage = MageSpellMaskArcaneExplosion | MageSpellMaskArcaneMissiles |
		MageSpellMaskArcaneMissilesTick | MageSpellMaskArcaneBlast

	// "your Frost spells" for cost and threat purposes, which the
	// tooltips do not restrict to the damaging ones.
	MageSpellMaskFrost = MageSpellMaskFrostDamage | MageSpellMaskIceBarrier
)

func RegisterMage() {
	core.RegisterAgentFactory(
		proto.Player_Mage{},
		proto.Spec_SpecMage,
		func(character *core.Character, options *proto.Player) core.Agent {
			return NewMage(character, options)
		},
		func(player *proto.Player, spec interface{}) {
			playerSpec, ok := spec.(*proto.Player_Mage)
			if !ok {
				panic("Invalid spec value for Mage!")
			}
			player.Spec = playerSpec
		},
	)
}

type Mage struct {
	core.Character

	Talents *proto.MageTalents
	Options *proto.Mage_Options

	activeBarrier *core.Aura

	ArcaneExplosion         []*core.Spell
	ArcaneMissiles          []*core.Spell
	ArcaneMissilesTickSpell []*core.Spell
	BlastWave               []*core.Spell
	Blizzard                []*core.Spell
	Counterspell            *core.Spell
	Evocation               *core.Spell
	Fireball                []*core.Spell
	FireBlast               []*core.Spell
	Flamestrike             []*core.Spell
	Frostbolt               []*core.Spell
	ColdSnap                *core.Spell
	IceBarrier              []*core.Spell
	IceLance                []*core.Spell
	Ignite                  *core.Spell
	igniteTick              *core.Spell
	ManaGem                 []*core.Spell
	PresenceOfMind          *core.Spell
	Pyroblast               []*core.Spell
	Scorch                  []*core.Spell

	ArcanePowerAura     *core.Aura
	ClearcastingAura    *core.Aura
	CombustionAura      *core.Aura
	IceArmorAura        *core.Aura
	IceBarrierAuras     []*core.Aura
	ImprovedScorchAuras core.AuraArray
	MageArmorAura       *core.Aura
}

// Agent is a generic way to access underlying mage on any of the agents.
type MageAgent interface {
	GetMage() *Mage
}

func (mage *Mage) GetCharacter() *core.Character {
	return &mage.Character
}

func (mage *Mage) GetMage() *Mage {
	return mage
}

func (mage *Mage) AddRaidBuffs(raidBuffs *proto.RaidBuffs) {
	raidBuffs.ArcaneBrilliance = true
}
func (mage *Mage) AddPartyBuffs(partyBuffs *proto.PartyBuffs) {
}

func (mage *Mage) Initialize() {
	mage.registerArcaneMissilesSpell()
	mage.registerFireballSpell()
	mage.registerFireBlastSpell()
	mage.registerFrostboltSpell()
	mage.registerPyroblastSpell()
	mage.registerScorchSpell()

	mage.registerArcaneExplosionSpell()
	mage.registerBlastWaveSpell()
	mage.registerBlizzardSpell()
	mage.registerFlamestrikeSpell()

	mage.registerEvocationCD()
	mage.registerManaGemCD()
	mage.registerCounterspellSpell()
}

func (mage *Mage) Reset(sim *core.Simulation) {
}

func NewMage(character *core.Character, options *proto.Player) *Mage {
	mageOptions := options.GetMage()

	mage := &Mage{
		Character: *character,
		Talents:   &proto.MageTalents{},
		Options:   mageOptions.Options,
	}
	fillMageTalents(mage.Talents, options.TalentsString)

	mage.EnableManaBar()

	mage.AddStatDependency(stats.Strength, stats.AttackPower, core.APPerStrength[character.Class])
	core.AddCritStatDependencies(&mage.Character, mage.Class)

	switch mage.Options.Armor {
	case proto.Mage_Options_IceArmor:
		mage.applyFrostIceArmor()
	case proto.Mage_Options_MageArmor:
		mage.applyMageArmor()
	}

	// Set mana regen to 12.5 + Spirit/4 each 2s tick
	mage.SpiritManaRegenPerSecond = func() float64 {
		return 6.25 + mage.GetStat(stats.Spirit)/8
	}

	guardians.ConstructGuardians(&mage.Character)

	return mage
}

// fillMageTalents is the one place a talent string is sliced, so the
// regression suite's build and a player's build are read the same way.
func fillMageTalents(talents *proto.MageTalents, talentsString string) {
	core.FillTalentsProto(talents.ProtoReflect(), talentsString, TalentTreeSizes)
}
