package tankwarrior

import (
	"math"
	"testing"
	"time"

	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/warrior"
)

const (
	defensiveStanceThreat = 1.3 // client spell 7376: +30%
	defiancePerRank       = 0.05
	floatEpsilon          = 1e-9
)

func assertNear(t *testing.T, label string, got, want float64) {
	t.Helper()
	if math.Abs(got-want) > floatEpsilon {
		t.Errorf("%s = %v, want %v", label, got, want)
	}
}

// attackTaken delivers one attack with the outcome to the tank, as the
// boss's swing would.
func attackTaken(sim *core.Simulation, war *warrior.Warrior, outcome core.HitOutcome) {
	boss := sim.Encounter.TargetUnits[0]
	swing := boss.AutoAttacks.MHAuto()
	result := swing.NewResult(&war.Unit)
	result.Outcome = outcome
	war.OnSpellHitTaken(sim, swing, result)
	swing.DisposeResult(result)
}

// Defiance: "Increases all threat generated in Defensive stance by an
// additional 5%/10%/15% while a shield is equipped", added to the stance's
// own 30%.
func TestDefianceAddsToTheStanceThreatWithAShield(t *testing.T) {
	for rank := 0; rank <= 3; rank++ {
		talents := talentsWith(t, emptyTalents, "defiance", rank)

		withShield, _ := buildTank(t, talents, true)
		assertNear(t, "threat with a shield", withShield.PseudoStats.ThreatMultiplier, defensiveStanceThreat+defiancePerRank*float64(rank))

		withoutShield, _ := buildTank(t, talents, false)
		assertNear(t, "threat without a shield", withoutShield.PseudoStats.ThreatMultiplier, defensiveStanceThreat)
	}
}

// Master of Defense: "a 50%/100% chance to generate 5 Rage when you Dodge or
// Parry while a shield is equipped".
func TestMasterOfDefenseGrantsRageOnDodgeAndParry(t *testing.T) {
	for _, outcome := range []core.HitOutcome{core.OutcomeDodge, core.OutcomeParry} {
		war, sim := buildTank(t, talentsWith(t, emptyTalents, "master_of_defense", 2), true)
		before := war.CurrentRage()
		attackTaken(sim, war, outcome)
		assertNear(t, "rage gained at rank 2", war.CurrentRage()-before, 5)
	}

	war, sim := buildTank(t, talentsWith(t, emptyTalents, "master_of_defense", 2), true)
	before := war.CurrentRage()
	attackTaken(sim, war, core.OutcomeHit)
	if war.CurrentRage() != before {
		t.Errorf("a landed hit gave %v rage, want none", war.CurrentRage()-before)
	}

	war, sim = buildTank(t, talentsWith(t, emptyTalents, "master_of_defense", 2), false)
	before = war.CurrentRage()
	attackTaken(sim, war, core.OutcomeDodge)
	if war.CurrentRage() != before {
		t.Errorf("a dodge without a shield gave %v rage, want none", war.CurrentRage()-before)
	}
}

func TestMasterOfDefenseRankOneProcsAboutHalfTheTime(t *testing.T) {
	war, sim := buildTank(t, talentsWith(t, emptyTalents, "master_of_defense", 1), true)
	const attempts = 4000
	procs := 0
	for i := 0; i < attempts; i++ {
		before := war.CurrentRage()
		attackTaken(sim, war, core.OutcomeParry)
		if war.CurrentRage() > before {
			procs++
		}
		war.SpendRage(sim, war.CurrentRage(), war.RageRefundMetrics)
	}
	if share := float64(procs) / attempts; share < 0.46 || share > 0.54 {
		t.Errorf("rank 1 proc share = %v, want about 0.5", share)
	}
}

// Shield Specialization: "grants you a 20% chance to generate 5 Rage when
// you Block" a rank.
func TestShieldSpecializationGrantsRageOnBlock(t *testing.T) {
	war, sim := buildTank(t, talentsWith(t, emptyTalents, "shield_specialization", 5), true)
	attackTaken(sim, war, core.OutcomeBlock)
	assertNear(t, "rage from a block at rank 5", war.CurrentRage(), 5)
}

// Improved Bloodrage: "Increases all the Rage generated by your Bloodrage
// ability by 25%/50%".
func TestImprovedBloodrageScalesTheInstantRage(t *testing.T) {
	for rank, want := range map[int]float64{0: 10, 1: 12.5, 2: 15} {
		war, sim := buildTank(t, talentsWith(t, emptyTalents, "improved_bloodrage", rank), true)
		war.Bloodrage.ApplyEffects(sim, &war.Unit, war.Bloodrage.Spell)
		assertNear(t, "instant rage", war.CurrentRage(), want)
	}
}

// Improved Shield Wall: "Reduces the cooldown of your Shield Wall ability by
// 5.5 min" / "by 11.0 min", off the client's 15 minutes.
func TestImprovedShieldWallCutsTheCooldown(t *testing.T) {
	for rank, want := range map[int]time.Duration{0: 15 * time.Minute, 1: 9*time.Minute + 30*time.Second, 2: 4 * time.Minute} {
		war, _ := buildTank(t, talentsWith(t, emptyTalents, "improved_shield_wall", rank), true)
		wall := war.GetSpell(core.ActionID{SpellID: warrior.ShieldWallSpellId[0]})
		if wall == nil {
			t.Fatal("Shield Wall is not registered")
		}
		if got := wall.CD.Duration; got != want {
			t.Errorf("rank %d: cooldown %v, want %v", rank, got, want)
		}
	}
}

// Shield Wall: -60% damage taken for 12 seconds.
func TestShieldWallCutsDamageTakenBySixtyPercentFor12Seconds(t *testing.T) {
	war, sim := buildTank(t, emptyTalents, true)
	before := war.PseudoStats.DamageTakenMultiplier
	wall := war.GetSpell(core.ActionID{SpellID: warrior.ShieldWallSpellId[0]})
	wall.ApplyEffects(sim, &war.Unit, wall)

	assertNear(t, "damage taken multiplier", war.PseudoStats.DamageTakenMultiplier, before*0.4)
	aura := war.GetAura("Shield Wall")
	if aura == nil || !aura.IsActive() || aura.Duration != 12*time.Second {
		t.Fatalf("Shield Wall aura = %+v, want active for 12s", aura)
	}
	aura.Deactivate(sim)
	assertNear(t, "damage taken multiplier after it ends", war.PseudoStats.DamageTakenMultiplier, before)
}

// Shield Block: +75% block for 7 seconds and two charges, a block spending
// one.
func TestShieldBlockHasTwoChargesAndSevenSeconds(t *testing.T) {
	war, sim := buildTank(t, emptyTalents, true)
	if war.ShieldBlockAura.Duration != 7*time.Second {
		t.Errorf("duration = %v, want 7s", war.ShieldBlockAura.Duration)
	}
	war.ShieldBlock.ApplyEffects(sim, &war.Unit, war.ShieldBlock.Spell)
	if got := war.ShieldBlockAura.GetStacks(); got != 2 {
		t.Fatalf("charges after the cast = %d, want 2", got)
	}

	attackTaken(sim, war, core.OutcomeBlock)
	if got := war.ShieldBlockAura.GetStacks(); got != 1 {
		t.Errorf("charges after one block = %d, want 1", got)
	}
	war.ShieldBlock.ApplyEffects(sim, &war.Unit, war.ShieldBlock.Spell)
	if got := war.ShieldBlockAura.GetStacks(); got != 2 {
		t.Errorf("a recast restores the charges: %d, want 2", got)
	}
	attackTaken(sim, war, core.OutcomeBlock)
	attackTaken(sim, war, core.OutcomeBlock)
	if war.ShieldBlockAura.IsActive() {
		t.Error("the aura outlives its second block")
	}
}

// Last Stand: 30% of maximum health for 20 seconds, then it is lost.
func TestLastStandGrantsAndThenLosesThirtyPercentOfHealth(t *testing.T) {
	war, sim := buildTank(t, talentsWith(t, emptyTalents, "last_stand", 1), true)
	base := war.MaxHealth()
	lastStand := war.GetSpell(core.ActionID{SpellID: warrior.LastStandSpellId[0]})
	lastStand.ApplyEffects(sim, &war.Unit, lastStand)

	assertNear(t, "maximum health", war.MaxHealth(), base*1.3)
	assertNear(t, "current health", war.CurrentHealth(), base*1.3)
	war.GetAura("Last Stand").Deactivate(sim)
	assertNear(t, "maximum health after it ends", war.MaxHealth(), base)
	assertNear(t, "current health after it ends", war.CurrentHealth(), base)
}

// Revenge is cast only after the tank dodges, parries or blocks, at the top
// trainer rank, for the client's 5 rage less Focused Rage.
func TestRevengeNeedsADefensiveOutcomeAndCostsFiveRage(t *testing.T) {
	war, sim := buildTank(t, emptyTalents, true)
	war.SpendRage(sim, war.CurrentRage(), war.RageRefundMetrics)
	war.AddRage(sim, 50, war.RageRefundMetrics)
	if war.Revenge.CanCast(sim, sim.Encounter.TargetUnits[0]) {
		t.Fatal("Revenge is castable before any defensive outcome")
	}
	if war.Revenge.ActionID.SpellID != warrior.RevengeSpellId[warrior.RevengeRanks-1] {
		t.Errorf("Revenge id = %d, want the top trainer rank %d", war.Revenge.ActionID.SpellID, warrior.RevengeSpellId[warrior.RevengeRanks-1])
	}
	for _, outcome := range []core.HitOutcome{core.OutcomeDodge, core.OutcomeParry, core.OutcomeBlock} {
		fresh, freshSim := buildTank(t, emptyTalents, true)
		fresh.AddRage(freshSim, 50, fresh.RageRefundMetrics)
		attackTaken(freshSim, fresh, outcome)
		if !fresh.Revenge.CanCast(freshSim, freshSim.Encounter.TargetUnits[0]) {
			t.Errorf("Revenge is not castable after %v", outcome)
		}
	}
	assertNear(t, "Revenge cost", war.Revenge.Cost.GetCurrentCost(), 5)
}

// Thunder Clap works from Defensive Stance, with the learnable family's 6 s
// cooldown and 20% slow.
func TestThunderClapIsCastableInDefensiveStance(t *testing.T) {
	war, sim := buildTank(t, emptyTalents, true)
	if !war.ThunderClap.StanceMask.Matches(warrior.DefensiveStance) {
		t.Fatal("Thunder Clap is not a Defensive Stance spell")
	}
	war.AddRage(sim, 50, war.RageRefundMetrics)
	if !war.ThunderClap.CanCast(sim, sim.Encounter.TargetUnits[0]) {
		t.Error("Thunder Clap cannot be cast in Defensive Stance")
	}
	if got := war.ThunderClap.CD.Duration; got != 6*time.Second {
		t.Errorf("cooldown = %v, want 6s", got)
	}
	if got := war.ThunderClap.RelatedSelfBuff.Duration; got != 30*time.Second {
		t.Errorf("the slow lasts %v at rank 6, want 30s", got)
	}
}

// Sunder Armor's registered threat is the client's, 206 at the top rank.
func TestSunderArmorRegistersTheClientThreat(t *testing.T) {
	war, _ := buildTank(t, emptyTalents, true)
	if got := war.SunderArmor.FlatThreatBonus; got != 206 {
		t.Errorf("Sunder Armor flat threat = %v, want 206", got)
	}
}
