package main

import (
	"strings"
	"testing"

	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/proto"
	"github.com/wowsims/classic/sim/core/talents"
)

func warriorClass(t *testing.T) talents.Class {
	t.Helper()
	c, err := talents.Load("testdata/warrior.json")
	if err != nil {
		t.Fatal(err)
	}
	return c
}

// The proto message's field order IS the talent string's order, because
// core.FillTalentsProto walks the fields positionally. So the emitted
// message must be the three trees concatenated in position order, each
// tier-then-column, with field numbers 1..N in that order and no gaps.
func TestProtoMessageIsInTalentStringOrder(t *testing.T) {
	c := warriorClass(t)
	got := protoMessage(c)
	lines := []string{}
	for _, l := range strings.Split(got, "\n") {
		l = strings.TrimSpace(l)
		if strings.HasSuffix(l, ";") && !strings.HasPrefix(l, "//") {
			lines = append(lines, l)
		}
	}
	var want int
	for _, tr := range c.Trees {
		want += len(tr.Talents)
	}
	if len(lines) != want {
		t.Fatalf("the message has %d fields, want %d", len(lines), want)
	}
	if !strings.Contains(got, "message WarriorTalents {") {
		t.Errorf("the message is not named WarriorTalents:\n%s", got[:200])
	}
	// First field is Arms tier 0 column 0, last is Protection's last.
	first := c.Trees[0].Talents[0]
	if !strings.Contains(lines[0], c.FieldName(first)+" = 1;") {
		t.Errorf("field 1 is %q, want %q", lines[0], c.FieldName(first))
	}
	last := c.Trees[2].Talents[len(c.Trees[2].Talents)-1]
	if !strings.Contains(lines[len(lines)-1], c.FieldName(last)) {
		t.Errorf("the last field is %q, want %q", lines[len(lines)-1], c.FieldName(last))
	}
}

// A one-rank talent is a bool and a multi-rank talent is an int32, which
// is the convention the nine hand-written messages already use, so
// nothing downstream has to change.
func TestOneRankTalentsAreBools(t *testing.T) {
	c := warriorClass(t)
	got := protoMessage(c)
	for _, tr := range c.Trees {
		for _, ta := range tr.Talents {
			field := c.FieldName(ta)
			wantType := "int32"
			if ta.MaxRank == 1 {
				wantType = "bool"
			}
			if !strings.Contains(got, wantType+" "+field+" =") {
				t.Errorf("%s (max rank %d) is not declared as %s", field, ta.MaxRank, wantType)
			}
		}
	}
}

// The generated Go file carries the sizes, the build, and the two lookup
// maps the spec tasks read instead of typing spell ids.
func TestGoFileCarriesSizesBuildAndIDs(t *testing.T) {
	c := warriorClass(t)
	got := goFile(c)
	for _, want := range []string{
		"// Code generated by tools/talentgen. DO NOT EDIT.",
		"package warrior",
		"var TalentTreeSizes = [3]int{17, 18, 18}",
		`const TalentsBuild = "1.60.1.69893"`,
		"var TalentNodeIDs = map[string]int32{",
		"var TalentSpellIDs = map[string][]int32{",
		`"improved_heroic_strike": 105958,`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("the generated Go file does not contain %q", want)
		}
	}
}

// The UI tree JSON the engine's own talent picker reads must have one
// entry per talent with its grid position, so the fork stays buildable.
// Its fieldName is the LOWER-CAMEL spelling, because the picker indexes
// the generated TypeScript proto object with it and protoc-gen-ts
// camel-cases every field; a snake_case name there type-checks (the
// picker's field is `keyof TalentsProto | string`) and then reads
// undefined for every talent, which is the silent wrongness this whole
// task exists to remove.
func TestUITreeJSONHasEveryTalent(t *testing.T) {
	c := warriorClass(t)
	got := uiTreeJSON(c)
	for _, tr := range c.Trees {
		if !strings.Contains(got, `"name": "`+tr.Name+`"`) {
			t.Errorf("the UI JSON is missing the %s tree", tr.Name)
		}
		for _, ta := range tr.Talents {
			if !strings.Contains(got, `"fieldName": "`+uiFieldName(c.FieldName(ta))+`"`) {
				t.Errorf("the UI JSON is missing %q", ta.Name)
			}
		}
	}
}

// The camel-casing is derived from the proto field name, so the two
// cannot drift: one talent, one name, spelled for each side.
func TestUIFieldNameIsTheProtoFieldCamelCased(t *testing.T) {
	for _, tc := range []struct{ in, want string }{
		{"improved_heroic_strike", "improvedHeroicStrike"},
		{"deflection", "deflection"},
		{"winters_chill", "wintersChill"},
		{"two_handed_weapon_specialization", "twoHandedWeaponSpecialization"},
	} {
		if got := uiFieldName(tc.in); got != tc.want {
			t.Errorf("uiFieldName(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

// The round trip that actually matters: a talent string built from a
// point spend must READ BACK as the same spend, through the same
// core.FillTalentsProto the engine uses and the same generated message.
// A size that is one out does not error, it reads the wrong talent,
// which is why this goes through the real reader rather than measuring
// the string's length.
//
// FillTalentsProto walks the message by FIELD NUMBER (character.go:746,
// fieldDescriptors.ByNumber(offset+talentIdx+1)), which is exactly the
// order protoMessage emits, so this test is what pins the two together.
func TestTalentStringRoundTripsThroughFillTalentsProto(t *testing.T) {
	c := warriorClass(t)
	sizes := c.TreeSizes()

	// Spend one point in every talent that has a rank to spare, and the
	// max in every one-rank talent, so every field is exercised and no
	// value is the zero that a mis-indexed read would also produce.
	spend := make([][]int, 3)
	want := map[string]int{}
	for i, tree := range c.Trees {
		spend[i] = make([]int, len(tree.Talents))
		for j, ta := range tree.Talents {
			v := 1
			if ta.MaxRank > 2 {
				v = 2
			}
			spend[i][j] = v
			want[c.FieldName(ta)] = v
		}
	}

	parts := make([]string, 3)
	for i, tree := range spend {
		var b strings.Builder
		for _, n := range tree {
			b.WriteByte(byte('0' + n))
		}
		parts[i] = b.String()
		if len(parts[i]) != sizes[i] {
			t.Fatalf("tree %d segment is %d characters, want %d", i, len(parts[i]), sizes[i])
		}
	}
	str := strings.Join(parts, "-")

	msg := &proto.WarriorTalents{}
	core.FillTalentsProto(msg.ProtoReflect(), str, sizes)

	// Read every field back by name and compare with what was spent. A
	// bool field is true iff a point was spent; an int32 carries the count.
	fields := msg.ProtoReflect().Descriptor().Fields()
	if fields.Len() != sizes[0]+sizes[1]+sizes[2] {
		t.Fatalf("WarriorTalents has %d fields, the trees have %d talents", fields.Len(), sizes[0]+sizes[1]+sizes[2])
	}
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		name := string(fd.Name())
		w, ok := want[name]
		if !ok {
			t.Errorf("the message has field %q, which is in no tree", name)
			continue
		}
		v := msg.ProtoReflect().Get(fd)
		switch fd.Kind() {
		case protoreflect.BoolKind:
			if v.Bool() != (w == 1) {
				t.Errorf("%s read back as %v, want %v", name, v.Bool(), w == 1)
			}
		default:
			if int(v.Int()) != w {
				t.Errorf("%s read back as %d, want %d", name, v.Int(), w)
			}
		}
		delete(want, name)
	}
	for name := range want {
		t.Errorf("talent %q has no field in the generated message", name)
	}
}
