// Command talentgen writes the engine's talent definitions from the
// client's mined trait trees.
//
// It produces three things per class, all from one input file, because
// three things must agree exactly and only a generator can promise that:
// the <Class>Talents proto message (whose FIELD ORDER is the talent
// string's order, per core.FillTalentsProto), TalentTreeSizes (which
// slices the string), and the UI tree JSON (which the engine's own
// talent picker draws). A mismatch between any two does not error, it
// reads the wrong talent.
//
//	go run ./tools/talentgen -builds ../forever/data/builds -build 1.60.1.69893
//
// then `make proto` and commit both the .proto and the regenerated .pb.go.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/wowsims/classic/sim/core/talents"
)

// classes are the nine, by slug. The proto message name is the slug
// title-cased plus "Talents", which is what the nine existing messages
// are already called.
var classes = []string{"druid", "hunter", "mage", "paladin", "priest", "rogue", "shaman", "warlock", "warrior"}

func main() {
	builds := flag.String("builds", "../forever/data/builds", "the site repo's data/builds directory")
	build := flag.String("build", "1.60.1.69893", "which client build to generate from")
	flag.Parse()

	for _, slug := range classes {
		in := filepath.Join(*builds, *build, "talents", slug+".json")
		c, err := talents.Load(in)
		if err != nil {
			log.Fatalf("%s: %v", slug, err)
		}
		if c.Slug != slug {
			log.Fatalf("%s declares class_slug %q", in, c.Slug)
		}
		if err := spliceProto(filepath.Join("proto", slug+".proto"), c); err != nil {
			log.Fatalf("%s: %v", slug, err)
		}
		if err := os.WriteFile(filepath.Join("sim", slug, "talents_auto_gen.go"), []byte(goFile(c)), 0o644); err != nil {
			log.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join("ui", "core", "talents", "trees", slug+".json"), []byte(uiTreeJSON(c)), 0o644); err != nil {
			log.Fatal(err)
		}
		sizes := c.TreeSizes()
		log.Printf("%-8s %d talents %v from build %s", slug, sizes[0]+sizes[1]+sizes[2], sizes, c.Build)
	}
	log.Print("now run: make proto && gofmt -w ./sim ./tools")
}

func messageName(slug string) string {
	return strings.ToUpper(slug[:1]) + slug[1:] + "Talents"
}

// protoMessage renders the <Class>Talents message. Field numbers are
// 1..N in talent-string order and are never reused: the message is
// regenerated whole on every data change, and nothing persists a talent
// message on the wire (the wire form is the positional talent string),
// so renumbering is safe here in a way it is not for RaidSimRequest.
func protoMessage(c talents.Class) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/talentgen from client build %s. DO NOT EDIT.\n", c.Build)
	fmt.Fprintf(&b, "// Field order is the talent string's order: the three trees in the\n")
	fmt.Fprintf(&b, "// client's own order, each tier then column. core.FillTalentsProto\n")
	fmt.Fprintf(&b, "// reads it positionally, so a reorder silently reads the wrong talent.\n")
	fmt.Fprintf(&b, "message %s {\n", messageName(c.Slug))
	n := 0
	for i, tr := range c.Trees {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "\t// %s (tree %d, client id %d)\n", tr.Name, tr.Position, tr.ID)
		for _, ta := range tr.Talents {
			n++
			typ := "int32"
			if ta.MaxRank == 1 {
				typ = "bool"
			}
			// The node id, grid position, rank count and spell id go on
			// their own line: a trailing comment would make the field
			// declaration's line no longer end at its semicolon, and the
			// generator's test reads the declarations by that shape.
			fmt.Fprintf(&b, "\t// node %d, tier %d col %d, %d rank(s), spell %d\n",
				ta.NodeID, ta.Tier, ta.Column, ta.MaxRank, ta.SpellID)
			fmt.Fprintf(&b, "\t%s %s = %d;\n", typ, c.FieldName(ta), n)
		}
	}
	b.WriteString("}\n")
	return b.String()
}

var msgRe = regexp.MustCompile(`(?ms)^(//[^\n]*\n)*message \w+Talents \{.*?^\}\n`)

// spliceProto replaces only the <Class>Talents message in a .proto file.
// Every other message in the file - the spec's options, its rotation -
// is hand-written and must survive untouched.
func spliceProto(path string, c talents.Class) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	src := string(b)
	if !msgRe.MatchString(src) {
		return fmt.Errorf("%s: no %s message found to replace", path, messageName(c.Slug))
	}
	out := msgRe.ReplaceAllLiteralString(src, protoMessage(c))
	return os.WriteFile(path, []byte(out), 0o644)
}

// goFile writes sim/<class>/talents_auto_gen.go: the sizes the talent
// string is sliced with, the build they came from, and two lookups the
// spec packages read instead of typing spell ids.
func goFile(c talents.Class) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/talentgen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: the client's trait tables, build %s.\n\n", c.Build)
	fmt.Fprintf(&b, "package %s\n\n", c.Slug)
	s := c.TreeSizes()
	fmt.Fprintf(&b, "// TalentTreeSizes is what core.FillTalentsProto slices the talent\n")
	fmt.Fprintf(&b, "// string with: %s %d, %s %d, %s %d.\n",
		c.Trees[0].Name, s[0], c.Trees[1].Name, s[1], c.Trees[2].Name, s[2])
	fmt.Fprintf(&b, "var TalentTreeSizes = [3]int{%d, %d, %d}\n\n", s[0], s[1], s[2])
	fmt.Fprintf(&b, "// TalentsBuild is the client build these trees came from.\n")
	fmt.Fprintf(&b, "const TalentsBuild = %q\n\n", c.Build)

	fmt.Fprintf(&b, "// TalentNodeIDs maps each talent's proto field name to the client's\n")
	fmt.Fprintf(&b, "// trait node id, so a log or a planner build can be matched to a\n")
	fmt.Fprintf(&b, "// talent without a second table.\n")
	fmt.Fprintf(&b, "var TalentNodeIDs = map[string]int32{\n")
	for _, tr := range c.Trees {
		for _, ta := range tr.Talents {
			fmt.Fprintf(&b, "\t%q: %d,\n", c.FieldName(ta), ta.NodeID)
		}
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// TalentSpellIDs maps each talent's proto field name to its spell id\n")
	fmt.Fprintf(&b, "// per rank, in rank order. A talent's behaviour file reads this\n")
	fmt.Fprintf(&b, "// rather than typing an id, so a patch that renumbers a rank is a\n")
	fmt.Fprintf(&b, "// regeneration and not a code edit.\n")
	fmt.Fprintf(&b, "var TalentSpellIDs = map[string][]int32{\n")
	for _, tr := range c.Trees {
		for _, ta := range tr.Talents {
			ids := make([]string, len(ta.RankSpellIDs))
			for i, id := range ta.RankSpellIDs {
				ids[i] = fmt.Sprint(id)
			}
			fmt.Fprintf(&b, "\t%q: {%s},\n", c.FieldName(ta), strings.Join(ids, ", "))
		}
	}
	fmt.Fprintf(&b, "}\n")
	return b.String()
}

// uiTreeJSON writes ui/core/talents/trees/<class>.json in the shape the
// engine's own talent picker reads. We ship none of that UI, but the fork
// stays buildable and mergeable, so it is regenerated rather than left
// describing vanilla's trees.
func uiTreeJSON(c talents.Class) string {
	var b strings.Builder
	b.WriteString("[\n")
	for i, tr := range c.Trees {
		if i > 0 {
			b.WriteString(",\n")
		}
		fmt.Fprintf(&b, "  {\n    \"name\": %q,\n    \"backgroundUrl\": \"\",\n    \"talents\": [\n", tr.Name)
		for j, ta := range tr.Talents {
			if j > 0 {
				b.WriteString(",\n")
			}
			fmt.Fprintf(&b, "      {\n        \"fieldName\": %q,\n        \"location\": { \"rowIdx\": %d, \"colIdx\": %d },\n        \"spellIds\": [%s],\n        \"maxPoints\": %d\n      }",
				uiFieldName(c.FieldName(ta)), ta.Tier, ta.Column, joinIDs(ta.RankSpellIDs), ta.MaxRank)
		}
		b.WriteString("\n    ]\n  }")
	}
	b.WriteString("\n]\n")
	return b.String()
}

// uiFieldName is the UI tree JSON's spelling of a field name. The picker
// indexes the generated TypeScript proto object with it, and protoc-gen-ts
// lower-camel-cases every field, so improved_heroic_strike must be written
// there as improvedHeroicStrike or the picker reads undefined for every
// talent and says nothing about it.
func uiFieldName(protoField string) string {
	parts := strings.Split(protoField, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func joinIDs(ids []int32) string {
	parts := make([]string, len(ids))
	for i, id := range ids {
		parts[i] = fmt.Sprint(id)
	}
	return strings.Join(parts, ", ")
}
