package conformance

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Levels is the ladder this report walks: level-aware-sim-design's list
// (core.LevelSmokeLevels) minus 1, since level 1 has no spellbook worth
// checking against the client's own constants — the lane brief's own
// levels 10, 20, 30, 38, 40, 50, 60.
var Levels = []int32{10, 20, 30, 38, 40, 50, 60}

// GoldenDir is where every class's committed golden lives. It is under
// sim/core, not this package, because the lane brief fixes that path
// (sim/core/testdata/conformance/<class>.golden.md) regardless of which
// package the test that generates it lives in.
const GoldenDir = "../core/testdata/conformance"

// ClientDir is where this package's copy of the client's per-class spell
// constants lives (sim/core/testdata/conformance/client/<slug>.json,
// copied from the site's data/builds/1.60.1.70291/spellconst/<slug>.json
// — see this package's doc comment for why a copy and not an absolute-path
// read: this repo has no dependency on the site repo's checkout existing
// at a fixed path, and `go test` needs the fixture whether or not
// /Users/jh/code/forever is present on the machine running it).
const ClientDir = "../core/testdata/conformance/client"

func goldenPath(classSlug string) string {
	return filepath.Join(GoldenDir, classSlug+".golden.md")
}

func clientPath(classSlug string) string {
	return filepath.Join(ClientDir, classSlug+".json")
}

// sortRows orders a class's rows for a deterministic golden: spec, then
// level, then spell name, then rank, then spell ID. The spell ID is the
// final tiebreaker rather than an afterthought: several spec/level
// pairs genuinely register more than one spell sharing a name and rank
// (e.g. every Judgement seal-variant reads as "Judgement of X" rank 0,
// and Arcane Missiles rank 1 has eight distinct tick-count ranks all
// named identically) -- distinct rows the seen-map in collectRows never
// collapses, since it keys on spell ID. Without a final tiebreaker,
// sort.Slice (an unstable pdqsort) leaves those rows' relative order
// resting on sort-internal pivot choices rather than any field the
// comparator actually looked at; that direction can flip across Go
// versions or once anything upstream changes the rows' pre-sort order,
// which is the "randomly reports stale" failure mode this fixes. Since
// collectRows' seen-map already guarantees spell ID is unique within a
// tied (spec, level, name, rank) group, it is always a valid total-order
// tiebreaker.
func sortRows(rows []Row) {
	sort.Slice(rows, func(i, j int) bool {
		a, b := rows[i], rows[j]
		if a.Spec != b.Spec {
			return a.Spec < b.Spec
		}
		if a.Level != b.Level {
			return a.Level < b.Level
		}
		if a.SpellName != b.SpellName {
			return a.SpellName < b.SpellName
		}
		if a.Rank != b.Rank {
			return a.Rank < b.Rank
		}
		return a.SpellID < b.SpellID
	})
}

// renderGolden writes one class's golden markdown: a header naming the
// client build and comparison rules, then one table row per spell rank
// per level where it was registered (the lane brief's shape), plus any
// build errors (a spec/level this run could not build at all, e.g. a
// pre-existing talent-rewrite panic) so a reader knows a gap in the level
// column is a recorded skip and not a silently dropped row. talentGatedRows
// renders as its own "Talent-gated spells" section (TalentGatedSpells'
// doc comment explains why those rows cannot live in the main table:
// they do not exist at all without their one granting talent), and
// notes carries every buildForComparison fallback from the empty-talent
// build to the preset's real one.
func renderGolden(classSlug, clientBuild string, rows []Row, talentGatedRows []Row, gaps TrainableGaps, notes []string, buildErrors []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s: engine vs client spell conformance\n\n", strings.ToUpper(classSlug[:1])+classSlug[1:])
	fmt.Fprintf(&b, "Client build: %s. Generated by sim/conformance (FOREVER_UPDATE_GOLDEN=1 go test ./sim/conformance/...).\n\n", clientBuild)
	fmt.Fprintf(&b, "Comparison rules: cost (amount and type: client's cost_type 0/1/2/3 = mana/rage/focus/energy vs the engine's core.CostType, both mapped to a shared name; a rage cost is divided by 10 before comparing, since the client stores rage costs in tenths — Bloodthirst's client cost of 300 is 30 rage, Execute's 150 is 15 — while mana and energy costs are already in player-visible units; a spell the client prices as a percentage of base mana — spellconst cost_pct, from SpellPower.PowerCostPct, with a flat cost of 0 — is compared as that percentage of the preset character's base mana, the same amount the engine's ManaCostOptions.BaseCost resolves to, and the percentage is printed beside it); cooldown (client's cooldown_ms, or category_cooldown_ms when cooldown_ms is 0 — spellconst.Spell.EffectiveCooldownMS — vs the engine's Spell.CD.Duration); cast time (cast_time_ms vs Spell.DefaultCast.CastTime; a negative client cast_time_ms, seen as exactly -1000000 on ranged Hunter abilities, is the client's own sentinel for \"instant, gated by ranged weapon speed\" rather than a literal duration, and is not compared); GCD (gcd_ms vs Spell.DefaultCast.GCD); required level (spell_level vs Spell.RequiredLevel); duration where the spell has one (duration_ms vs the engine's RelatedSelfBuff or Dot aura duration). `match` is every field equal; `client-scripted` is every field but duration equal, where the client states no duration (0, a \"server-side script\" value in this build's own wording) and the engine keeps a known non-zero value; anything else that differs is `mismatch`, with the Diff column naming every field that does not agree.\n\n")
	fmt.Fprintf(&b, "Damage (sim/conformance/damage.go, reported apart from the verdict): for a spell whose client row has a school-damage, periodic-damage, heal, periodic-heal or (when the ability file declares an amount) absorb effect, the client's roll at the preset's level, which is the effect's EffectBasePointsF plus EffectRealPointsPerLevel for each caster level above the spell's own (capped at SpellLevels.MaxLevel), spread by Variance as centre x (1 - Variance/2) through centre x (1 + Variance/2) (spellconst.Spell.DamageRange), against the {min, max} the ability file declares in core.SpellConfig.ClientBaseDamage (per tick for a periodic effect). A spell that declares nothing reads `not declared`, never `match`; `declared, matches` is both ends within 1 and, when the client table states a spell-power coefficient (a coefficient derived from the vanilla convention is shown and not compared), the engine's BonusCoefficient within 0.005; anything else declared is `declared, differs`.\n\n")
	fmt.Fprintf(&b, "Every preset below is built with an EMPTY talent string (see sim/conformance/build.go's buildForComparison): no row in the \"Spells\" table reflects a talent's cost/cooldown/cast-time/GCD modifier, only the engine's own base registration against the client's base spellconst entry. A spell that does not exist at all without a talent (Seal of Command, Ice Lance, Lava Burst, Stormstrike, Mutilate, and the rest TalentGatedSpells names) is therefore absent from that table and instead reported, with one point spent in just that talent, in its own \"Talent-gated spells\" section below it.\n\n")

	if len(notes) > 0 {
		fmt.Fprintf(&b, "## Notes\n\n")
		sort.Strings(notes)
		for _, n := range notes {
			fmt.Fprintf(&b, "- %s\n", n)
		}
		fmt.Fprintf(&b, "\n")
	}

	if len(buildErrors) > 0 {
		fmt.Fprintf(&b, "## Skipped (could not build)\n\n")
		sort.Strings(buildErrors)
		for _, e := range buildErrors {
			fmt.Fprintf(&b, "- %s\n", e)
		}
		fmt.Fprintf(&b, "\n")
	}

	fmt.Fprintf(&b, "## Spells\n\n")
	renderRowsTable(&b, rows)

	if len(talentGatedRows) > 0 {
		fmt.Fprintf(&b, "## Talent-gated spells\n\n")
		fmt.Fprintf(&b, "Each spell below is built with exactly one point in the single talent that grants it (and nothing else), so its base cost/cooldown/cast-time/GCD/duration can still be checked against the client even though it has no row above.\n\n")
		renderRowsTable(&b, talentGatedRows)
	}

	renderTrainableGaps(&b, classSlug, gaps)

	return b.String()
}

// renderRowsTable writes the lane brief's row table shape: it is shared
// by the main "Spells" section and the "Talent-gated spells" section so
// both read as the same table format, just with a different rowset.
func renderRowsTable(b *strings.Builder, rows []Row) {
	fmt.Fprintf(b, "| Spec | Level | Spell | Rank | SpellID | Cost (client→engine) | CostType (client→engine) | Cooldown ms (client→engine) | CastTime ms (client→engine) | GCD ms (client→engine) | ReqLevel (client→engine) | Duration ms (client→engine) | Verdict | Diff | Damage min-max at level (client→engine) | Coefficient (client→engine) | Damage |\n")
	fmt.Fprintf(b, "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n")
	for _, r := range rows {
		duration := "n/a"
		if r.HasDuration {
			duration = fmt.Sprintf("%d→%d", r.ClientDurationMS, r.EngineDurationMS)
		}
		clientCost := fmt.Sprintf("%.2f", r.ClientCostAmt)
		if r.ClientCostPct > 0 {
			// The client prices this spell as a share of base mana; the
			// amount beside it is that share of the preset's base mana.
			clientCost = fmt.Sprintf("%.2f (%g%% base mana)", r.ClientCostAmt, r.ClientCostPct)
		}
		damageRange, damageCoefficient, damageStatus := damageCells(r.Damage)
		fmt.Fprintf(b, "| %s | %d | %s | %d | %d | %s→%.2f | %s→%s | %d→%d | %d→%d | %d→%d | %d→%d | %s | %s | %s | %s | %s | %s |\n",
			r.Spec, r.Level, r.SpellName, r.Rank, r.SpellID,
			clientCost, r.EngineCostAmt,
			r.ClientCostType, r.EngineCostType,
			r.ClientCooldownMS, r.EngineCooldownMS,
			r.ClientCastTimeMS, r.EngineCastTimeMS,
			r.ClientGCDMS, r.EngineGCDMS,
			r.ClientRequiredLevel, r.EngineRequiredLevel,
			duration,
			r.Verdict, r.Diff,
			damageRange, damageCoefficient, damageStatus)
	}
}

func readGolden(classSlug string) (string, error) {
	b, err := os.ReadFile(goldenPath(classSlug))
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func writeGolden(classSlug, content string) error {
	if err := os.MkdirAll(GoldenDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(goldenPath(classSlug), []byte(content), 0o644)
}
