package conformance

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// The damage block in SUMMARY.md is generated, not hand-written: the
// per-class counts come from the same rows the goldens render, so the
// summary cannot drift from them. Everything outside the markers is
// hand-written prose and is left alone.
const (
	damageBlockBegin = "<!-- damage-summary:begin (generated by sim/conformance; do not edit) -->"
	damageBlockEnd   = "<!-- damage-summary:end -->"

	trainablesBlockBegin = "<!-- trainables-summary:begin (generated by sim/conformance; do not edit) -->"
	trainablesBlockEnd   = "<!-- trainables-summary:end -->"
)

var summaryPath = filepath.Join(GoldenDir, "SUMMARY.md")

// renderDamageBlock renders the per-class damage counts, classes in the
// order given.
func renderDamageBlock(classSlugs []string, counts map[string]DamageCounts) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", damageBlockBegin)
	fmt.Fprintf(&b, "## Damage conformance (level %d)\n\n", summaryLevel)
	fmt.Fprintf(&b, "Per spec-and-rank row at level %d whose client spell has a school-damage or periodic-damage effect, compared as damage.go describes. `declared` is an ability file setting `core.SpellConfig.ClientBaseDamage`; `not declared` is the gap the fix lanes close. Rows with no client damage effect (buffs, heals, utility) are `n/a`.\n\n", summaryLevel)
	fmt.Fprintf(&b, "| Class | Declared | Matching | Differing | Not declared | n/a |\n|---|---|---|---|---|---|\n")
	var total DamageCounts
	for _, slug := range classSlugs {
		c := counts[slug]
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %d | %d |\n", strings.ToUpper(slug[:1])+slug[1:], c.Declared, c.Matching, c.Differing, c.Undeclared, c.NotApplicable)
		total.Declared += c.Declared
		total.Matching += c.Matching
		total.Differing += c.Differing
		total.Undeclared += c.Undeclared
		total.NotApplicable += c.NotApplicable
	}
	fmt.Fprintf(&b, "| **Total** | %d | %d | %d | %d | %d |\n\n", total.Declared, total.Matching, total.Differing, total.Undeclared, total.NotApplicable)
	fmt.Fprintf(&b, "%s", damageBlockEnd)
	return b.String()
}

// renderTrainablesBlock renders the per-class count of active trainable
// abilities the engine registers no rank of (the golden's "Trainable
// abilities the engine does not register" section), classes in the order given.
func renderTrainablesBlock(classSlugs []string, gaps map[string]TrainableGaps) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n", trainablesBlockBegin)
	fmt.Fprintf(&b, "## Trainable abilities the engine does not register\n\n")
	fmt.Fprintf(&b, "Per class, the active trainables (power cost, cast time or cooldown; pipeline.trainables) of which no rank is in any spec's spellbook at any level in the report. Utility spells count; the golden's section for each class lists them with their cost and cooldown.\n\n")
	fmt.Fprintf(&b, "| Class | Active trainables | Not registered |\n|---|---|---|\n")
	var active, missing int
	for _, slug := range classSlugs {
		g := gaps[slug]
		fmt.Fprintf(&b, "| %s | %d | %d |\n", strings.ToUpper(slug[:1])+slug[1:], g.Active, len(g.Unregistered))
		active += g.Active
		missing += len(g.Unregistered)
	}
	fmt.Fprintf(&b, "| **Total** | %d | %d |\n\n", active, missing)
	fmt.Fprintf(&b, "%s", trainablesBlockEnd)
	return b.String()
}

// spliceBlock replaces the block between the markers in summary, or appends
// block when the file has none yet.
func spliceBlock(summary, beginMarker, endMarker, block string) string {
	begin := strings.Index(summary, beginMarker)
	end := strings.Index(summary, endMarker)
	if begin < 0 || end < begin {
		return strings.TrimRight(summary, "\n") + "\n\n" + block + "\n"
	}
	return summary[:begin] + block + summary[end+len(endMarker):]
}

func readSummary() (string, error) {
	b, err := os.ReadFile(summaryPath)
	return string(b), err
}

func writeSummary(content string) error {
	return os.WriteFile(summaryPath, []byte(content), 0o644)
}
