package druid

import (
	"time"

	"github.com/wowsims/classic/sim/common/guardians"
	"github.com/wowsims/classic/sim/core"
	"github.com/wowsims/classic/sim/core/proto"
	"github.com/wowsims/classic/sim/core/stats"
)

const (
	SpellFlagOmen    = core.SpellFlagAgentReserved1
	SpellFlagBuilder = core.SpellFlagAgentReserved2
)

// TalentTreeSizes now lives in talents_auto_gen.go, generated by
// tools/talentgen from the client's trait tables: the sizes, the proto
// message's field order and the planner's talent string have to agree,
// and they only can if one file produces all three.

const (
	SpellCode_DruidNone int32 = iota

	SpellCode_DruidClaw
	SpellCode_DruidFaerieFire
	SpellCode_DruidFaerieFireFeral
	SpellCode_DruidFerociousBite
	SpellCode_DruidInsectSwarm
	SpellCode_DruidMoonfire
	SpellCode_DruidRake
	SpellCode_DruidRavage
	SpellCode_DruidRip
	SpellCode_DruidShred
	SpellCode_DruidStarfire
	SpellCode_DruidWrath
	SpellCode_DruidMaul
	SpellCode_DruidSwipe
	SpellCode_DruidLacerate
	SpellCode_DruidPrimalBite
	SpellCode_DruidPounce

	SpellCode_DruidHealingTouch
	SpellCode_DruidRegrowth
	SpellCode_DruidRejuvenation
	SpellCode_DruidSwiftmend
	SpellCode_DruidTranquility
	SpellCode_DruidWildGrowth
)

// DruidSpellMask* identify the subset of this package's spells that a
// declarative talent in talents.go needs to find by ClassMask (PORTING.md
// section spell_mod.go). Only spells a talent implemented below actually
// targets are tagged; a spell with no talent reading its ClassSpellMask
// is left untagged.
const (
	DruidSpellMaskClaw uint64 = 1 << iota
	DruidSpellMaskFerociousBite
	DruidSpellMaskInsectSwarm
	DruidSpellMaskMoonfire
	DruidSpellMaskRake
	DruidSpellMaskRavage
	DruidSpellMaskRip
	DruidSpellMaskShred
	DruidSpellMaskStarfire
	DruidSpellMaskWrath
	DruidSpellMaskTigersFury
	DruidSpellMaskMaul
	DruidSpellMaskSwipe
	DruidSpellMaskLacerate
	DruidSpellMaskPrimalBite
	DruidSpellMaskHealingTouch
	DruidSpellMaskRegrowth
	DruidSpellMaskRejuvenation
	DruidSpellMaskSwiftmend
	DruidSpellMaskTranquility
	DruidSpellMaskWildGrowth
	DruidSpellMaskBerserk
	DruidSpellMaskPounce
)

const (
	// Wrath, Starfire and Moonfire: Nature's Reach's "offensive Balance
	// spells".
	DruidSpellMaskBalanceDirectDamage = DruidSpellMaskWrath | DruidSpellMaskStarfire | DruidSpellMaskMoonfire

	// Wrath, Starfire, Moonfire and Insect Swarm: the Balance damage spells
	// Moonglow and Improved Wrath discount and Nature's Grace's global
	// cooldown cut reaches ("your damaging spells").
	DruidSpellMaskBalanceDamage = DruidSpellMaskWrath | DruidSpellMaskStarfire | DruidSpellMaskMoonfire | DruidSpellMaskInsectSwarm

	// Every healing spell this package registers, for Gift of Nature's
	// "all your healing spells".
	DruidSpellMaskHealing = DruidSpellMaskHealingTouch | DruidSpellMaskRegrowth | DruidSpellMaskRejuvenation |
		DruidSpellMaskSwiftmend | DruidSpellMaskTranquility | DruidSpellMaskWildGrowth

	// Every healing-over-time effect this package registers, for
	// Genesis's "periodic ... healing".
	DruidSpellMaskPeriodicHealing = DruidSpellMaskRegrowth | DruidSpellMaskRejuvenation |
		DruidSpellMaskTranquility | DruidSpellMaskWildGrowth

	// Every damage-over-time effect this package registers, for
	// Genesis's "periodic damage".
	DruidSpellMaskPeriodicDamage = DruidSpellMaskMoonfire | DruidSpellMaskInsectSwarm | DruidSpellMaskRake | DruidSpellMaskRip | DruidSpellMaskPounce

	// Every Nature spell Nature's Swiftness can make instant: the one
	// damage spell and the two cast-time heals the school has.
	DruidSpellMaskNatureCasts = DruidSpellMaskWrath | DruidSpellMaskHealingTouch | DruidSpellMaskRegrowth

	// Every Cat Form melee special this package registers, for
	// Predatory Instincts' "melee abilities".
	DruidSpellMaskMeleeAbilities = DruidSpellMaskClaw | DruidSpellMaskRake | DruidSpellMaskRavage | DruidSpellMaskShred | DruidSpellMaskFerociousBite | DruidSpellMaskPounce |
		DruidSpellMaskMaul | DruidSpellMaskSwipe | DruidSpellMaskLacerate | DruidSpellMaskPrimalBite

	// Claw, Rake, Ravage and Shred: the Cat Form specials that generate
	// a Combo Point, for Berserk's crit bonus and Blood Frenzy's bonus
	// Combo Point chance.
	DruidSpellMaskComboPointBuilders = DruidSpellMaskClaw | DruidSpellMaskRake | DruidSpellMaskRavage | DruidSpellMaskShred | DruidSpellMaskPounce
)

type Druid struct {
	core.Character
	SelfBuffs

	Talents *proto.DruidTalents

	DruidSpells []*DruidSpell

	StartingForm DruidForm

	// CastsNaturesSwiftnessByHand keeps Nature's Swiftness out of the generic
	// major-cooldown pass: the spec's rotation times it itself.
	CastsNaturesSwiftnessByHand bool

	RebirthTiming     float64
	BleedsActive      int
	AssumeBleedActive bool

	ReplaceBearMHFunc core.ReplaceMHSwing

	Barkskin             *DruidSpell
	Berserk              *DruidSpell
	DemoralizingRoar     *DruidSpell
	Enrage               *DruidSpell
	FaerieFire           *DruidSpell
	FerociousBite        *DruidSpell
	ForceOfNature        *DruidSpell
	FrenziedRegeneration *DruidSpell
	GiftOfTheWild        *DruidSpell
	HealingTouch         []*DruidSpell
	Hurricane            []*DruidSpell
	Innervate            *DruidSpell
	InsectSwarm          []*DruidSpell
	Languish             *DruidSpell
	Lacerate             *DruidSpell
	Maul                 *DruidSpell
	MaulQueueSpell       *DruidSpell
	Moonfire             []*DruidSpell
	NaturesSwiftness     *DruidSpell
	PrimalBite           *DruidSpell
	Prowl                *DruidSpell
	Rebirth              *DruidSpell
	Regrowth             []*DruidSpell
	Rejuvenation         []*DruidSpell
	Rake                 *DruidSpell
	Ravage               *DruidSpell
	Pounce               *DruidSpell
	Rip                  *DruidSpell
	ShiftingPower        *DruidSpell
	Shred                *DruidSpell
	Claw                 *DruidSpell
	Starfire             []*DruidSpell
	Swiftmend            *DruidSpell
	SwipeBear            *DruidSpell
	TigersFury           *DruidSpell
	Tranquility          []*DruidSpell
	WildGrowth           []*DruidSpell
	Wrath                []*DruidSpell

	BearForm    *DruidSpell
	CatForm     *DruidSpell
	MoonkinForm *DruidSpell

	BarkskinAura             *core.Aura
	BearFormAura             *core.Aura
	BerserkAura              *core.Aura
	CatFormAura              *core.Aura
	ClearcastingAura         *core.Aura
	DemoralizingRoarAuras    core.AuraArray
	EnrageAura               *core.Aura
	FaerieFireAuras          core.AuraArray
	FrenziedRegenerationAura *core.Aura
	FurorAura                *core.Aura

	// What Furor reads when the druid shifts back into Cat Form: the energy it
	// had on leaving, and when it left.
	energyOnLeavingCat     float64
	leftCatFormAt          time.Duration
	InsectSwarmAuras       core.AuraArray
	MaulQueueAura          *core.Aura
	MoonkinFormAura        *core.Aura
	NaturesGraceProcAura   *core.Aura
	PredatoryInstinctsAura *core.Aura
	ProwlAura              *core.Aura
	TigersFuryAura         *core.Aura

	BleedCategories core.ExclusiveCategoryArray

	form         DruidForm
	disabledMCDs []*core.MajorCooldown
}

type SelfBuffs struct {
	InnervateTarget *proto.UnitReference
}

func (druid *Druid) GetCharacter() *core.Character {
	return &druid.Character
}

func (druid *Druid) AddRaidBuffs(raidBuffs *proto.RaidBuffs) {
	/*
		if (raidBuffs.GiftOfTheWild == proto.TristateEffect_TristateEffectRegular) && (druid.Talents.ImprovedMarkOfTheWild > 0) {
			druid.AddStats(core.BuffSpellValues[core.MarkOfTheWild].Multiply(0.07 * float64(druid.Talents.ImprovedMarkOfTheWild)))
		}
	*/

	// TODO: These should really be aura attached to the actual forms
	if druid.InForm(Moonkin) {
		raidBuffs.MoonkinAura = true
	}

	if druid.InForm(Cat|Bear) && druid.Talents.LeaderOfThePack {
		raidBuffs.LeaderOfThePack = true
	}
}

func (druid *Druid) RegisterSpell(formMask DruidForm, config core.SpellConfig) *DruidSpell {
	prev := config.ExtraCastCondition
	prevModify := config.Cast.ModifyCast

	ds := &DruidSpell{FormMask: formMask}
	config.ExtraCastCondition = func(sim *core.Simulation, target *core.Unit) bool {
		// Check if we're in allowed form to cast
		// Allow 'humanoid' auto unshift casts
		if (ds.FormMask != Any && !druid.InForm(ds.FormMask)) && !ds.FormMask.Matches(Humanoid) {
			if sim.Log != nil {
				sim.Log("Failed cast to spell %s, wrong form", ds.ActionID)
			}
			return false
		}
		return prev == nil || prev(sim, target)
	}
	config.Cast.ModifyCast = func(sim *core.Simulation, s *core.Spell, c *core.Cast) {
		if !druid.InForm(ds.FormMask) && ds.FormMask.Matches(Humanoid) {
			druid.CancelShapeshift(sim)
		}
		if prevModify != nil {
			prevModify(sim, s, c)
		}
	}

	ds.Spell = druid.Unit.RegisterSpell(config)
	druid.DruidSpells = append(druid.DruidSpells, ds)

	return ds
}

func (druid *Druid) Initialize() {
	druid.BleedCategories = druid.GetEnemyExclusiveCategories(core.BleedEffectCategory)

	druid.registerFaerieFireSpell()
	druid.registerInnervateCD()
}

func (druid *Druid) RegisterBalanceSpells() {
	druid.registerHurricaneSpell()
	druid.registerInsectSwarmSpell()
	druid.registerMoonfireSpell()
	druid.registerStarfireSpell()
	druid.registerWrathSpell()
}

// TODO: Classic feral
func (druid *Druid) RegisterFeralCatSpells() {
	druid.registerCatFormSpell()
	druid.registerFerociousBiteSpell()
	druid.registerProwlAura()
	druid.registerProwlSpell()
	druid.registerRakeSpell()
	druid.registerRavageSpell()
	druid.registerPounceSpell()
	druid.registerRipSpell()
	druid.registerShiftingPowerSpell()
	druid.registerShredSpell()
	druid.registerClawSpell()
	druid.registerTigersFurySpell()
	// Cat Form is not learned until level 20 (spellconst: spell 768), so a
	// leveling feral druid below 20 has nothing else to cast; register the same
	// baseline caster kit RegisterBalanceSpells does. Both self-gate by
	// their own per-rank learn level exactly like the Cat-form spells
	// above, and RegisterSpell's existing Humanoid-form auto-unshift
	// (this file, above) lets them fire even while StartingForm still
	// defaults a feral character into Cat Form at every level.
	druid.registerMoonfireSpell()
	druid.registerWrathSpell()
}

// RegisterFeralTankSpells registers the Bear Form kit. Spells self-gate by
// their own learn levels, so a leveling bear has what its level has learned.
func (druid *Druid) RegisterFeralTankSpells() {
	druid.registerBearFormSpell()
	druid.registerEnrageSpell()
	druid.registerMaulSpell()
	druid.registerSwipeBearSpell()
	druid.registerLacerateSpell()
	druid.registerPrimalBiteSpell()
	druid.registerDemoralizingRoarSpell()
	druid.registerFrenziedRegenerationCD()
	druid.registerBarkskinCD()
}

// BreakProwl deactivates Prowl if it is active. This must be called from
// every Cat Form ability whose damage would alert the target (mirrors
// sim/rogue/rogue.go's BreakStealth).
func (druid *Druid) BreakProwl(sim *core.Simulation) {
	if druid.ProwlAura.IsActive() {
		druid.ProwlAura.Deactivate(sim)
	}
}

// IsProwling reports whether the druid is considered Prowling for the
// purpose of casting abilities that require it (e.g. Ravage).
func (druid *Druid) IsProwling() bool {
	return druid.ProwlAura.IsActive()
}

func (druid *Druid) Reset(_ *core.Simulation) {
	druid.BleedsActive = 0
	druid.form = druid.StartingForm
	druid.disabledMCDs = []*core.MajorCooldown{}
}

func New(character *core.Character, form DruidForm, selfBuffs SelfBuffs, talents string) *Druid {
	druid := &Druid{
		Character:    *character,
		SelfBuffs:    selfBuffs,
		Talents:      &proto.DruidTalents{},
		StartingForm: form,
		form:         form,
	}
	core.FillTalentsProto(druid.Talents.ProtoReflect(), talents, TalentTreeSizes)
	druid.EnableManaBar()

	druid.AddStatDependency(stats.Strength, stats.AttackPower, core.APPerStrength[character.Class])
	core.AddCritStatDependencies(&druid.Character, character.Class)
	druid.AddStatDependency(stats.Agility, stats.Dodge, core.DodgePerAgiAtLevel[character.Class]*core.DodgeRatingPerDodgeChance)
	druid.AddStatDependency(stats.BonusArmor, stats.Armor, 1)

	// Druids get extra melee haste
	// druid.PseudoStats.MeleeHasteRatingPerHastePercent /= 1.3

	guardians.ConstructGuardians(&druid.Character)

	return druid
}

type DruidSpell struct {
	*core.Spell
	FormMask DruidForm
}

func (ds *DruidSpell) IsReady(sim *core.Simulation) bool {
	if ds == nil {
		return false
	}
	return ds.Spell.IsReady(sim)
}

func (ds *DruidSpell) CanCast(sim *core.Simulation, target *core.Unit) bool {
	if ds == nil {
		return false
	}
	return ds.Spell.CanCast(sim, target)
}

func (ds *DruidSpell) IsEqual(s *core.Spell) bool {
	if ds == nil || s == nil {
		return false
	}
	return ds.Spell == s
}

// Agent is a generic way to access underlying druid on any of the agents (for example balance druid.)
type DruidAgent interface {
	GetDruid() *Druid
}
