// Code generated by tools/relicmods/gen.py. DO NOT EDIT.
//
// Class: druid
// Client build: 1.60.1.70009
// Relics at item level 40+ whose equip spell is aura 107/108 (spell-family modifier).
// Regenerate with `make relicmods`.

package druid

import "github.com/wowsims/classic/sim/core"

// relicEquipMods is every client equip modifier of this class's relics, keyed by item id.
// Which of them the engine models is the explicit registration list in items.go.
var relicEquipMods = map[int32][]core.EquipSpellMod{
	// 22399 Idol of Health (item level 78)
	// spell 27846 "Faster Healing Touch Cast": Reduces the casting time of your Healing Touch spell by 0.15 sec.
	22399: {
		{ClientSpellID: 27846, Aura: 107, Op: 10, Amount: -150, Families: core.ClientClassMask{32, 0, 0, 0}},
	},
	// 220606 Idol of the Dream (item level 60)
	// spell 446212 "Improved Rip": Increases the duration of Rip by ${$s1/1000} sec.
	220606: {
		{ClientSpellID: 446212, Aura: 107, Op: 1, Amount: 2000, Families: core.ClientClassMask{0, 0, 2097152, 0}},
	},
	// 272427 Howling Idol (item level 65)
	// spell 1291059 "Tiger's Fury Cooldown Reduction": Reduces the cooldown of your Tiger's Fury ability by ${$m1/-1000} sec.
	272427: {
		{ClientSpellID: 1291059, Aura: 107, Op: 11, Amount: -3000, Families: core.ClientClassMask{0, 0, 2048, 0}},
	},
	// 272428 Enraged Idol (item level 65)
	// spell 1291060 "Increased Enrage Rage": Your Enrage ability generates an additional $s1 Rage over its duration.
	272428: {
		{ClientSpellID: 1291060, Aura: 107, Op: 3, Amount: 10, Families: core.ClientClassMask{524288, 0, 0, 0}},
	},
	// 272430 Swarming Idol (item level 65)
	// spell 1291061 "Increased Insect Swarm Duration": Increases the duration of your Insect Swarm ability by ${$m1/1000} sec.
	272430: {
		{ClientSpellID: 1291061, Aura: 107, Op: 1, Amount: 2000, Families: core.ClientClassMask{2097152, 0, 0, 0}},
	},
	// 279250 Idol of Swiftness (item level 65)
	// spell 1306488 "Swiftmend Cooldown Reduction": Reduces the cooldown on your Swiftmend spell by ${$m1/-1000} sec.
	279250: {
		{ClientSpellID: 1306488, Aura: 107, Op: 11, Amount: -3000, Families: core.ClientClassMask{0, 2, 0, 0}},
	},
}

// Relics whose equip spell is not a 107/108 modifier; any model is hand-written in items.go.
// 23004 Idol of Longevity (item level 83): equip spell auras [4]
// 23197 Idol of the Moon (item level 65): equip spell auras [112]
// 213594 Idol of the Heckler (item level 40): equip spell auras [42]
// 220915 Idol of the Raging Shambler (item level 50): equip spell auras [42]
// 227444 Idol of the Huntress (item level 60): equip spell auras [42]
// 249441 Talons of Wrath (item level 45): equip spell auras [42]
// 272429 Idol of Synthesis (item level 65): equip spell auras [4]
// 279251 Idol of the Ursine Twins (item level 65): equip spell auras [4]
