// Code generated by tools/talentgen. DO NOT EDIT.
// Source: the client's trait tables, build 1.60.1.70009.

package druid

// TalentTreeSizes is what core.FillTalentsProto slices the talent
// string with: Balance 16, Feral Combat 20, Restoration 16.
var TalentTreeSizes = [3]int{16, 20, 16}

// TalentsBuild is the client build these trees came from.
const TalentsBuild = "1.60.1.70009"

// TalentNodeIDs maps each talent's proto field name to the client's
// trait node id, so a log or a planner build can be matched to a
// talent without a second table.
var TalentNodeIDs = map[string]int32{
	"improved_wrath":            104923,
	"genesis":                   104924,
	"moonglow":                  104925,
	"improved_moonfire":         104931,
	"natures_majesty":           104927,
	"natures_reach":             104929,
	"improved_entangling_roots": 104926,
	"natures_splendor":          104928,
	"insect_swarm":              104930,
	"vengeance":                 104932,
	"improved_starfire":         104933,
	"overgrowth":                110844,
	"natures_grace":             104934,
	"eclipse":                   104935,
	"moonfury":                  104936,
	"moonkin_form":              104937,
	"ferocity":                  104938,
	"heart_of_the_wild":         104939,
	"feral_swiftness":           104943,
	"feral_instinct":            104940,
	"brutal_impact":             104941,
	"thick_hide":                104942,
	"shredding_attacks":         104945,
	"savage_fury":               104948,
	"feral_charge":              104944,
	"sharpened_claws":           104946,
	"shifting_power":            104951,
	"primal_bite":               104949,
	"predatory_strikes":         104952,
	"blood_frenzy":              104947,
	"improved_shifting_power":   113563,
	"leader_of_the_pack":        104955,
	"predatory_instincts":       104950,
	"natural_reaction":          104954,
	"rend_and_tear":             104953,
	"berserk":                   104956,
	"natures_focus":             104957,
	"furor":                     104958,
	"naturalist":                104922,
	"subtlety":                  104920,
	"natural_shapeshifter":      104919,
	"reflection":                104917,
	"gift_of_nature":            104916,
	"gift_of_the_earthmother":   104918,
	"tranquil_spirit":           104915,
	"improved_rejuvenation":     104914,
	"swiftmend":                 104912,
	"natures_swiftness":         104921,
	"living_spirit":             104911,
	"improved_tranquility":      104909,
	"improved_regrowth":         104913,
	"wild_growth":               104910,
}

// TalentSpellIDs maps each talent's proto field name to the spell id
// the client gives for each of its ranks, in rank order, so a talent's
// behaviour file reads an id rather than typing one and a patch that
// renumbers a rank is a regeneration.
//
// Read the entries before planning around them: in build 1.60.1.70009 the
// client gives ONE spell per talent and repeats it for every rank, so
// each slice here is currently N copies of the same id and carries no
// rank information. The per-rank descriptions in the source do differ,
// so the distinction exists upstream; when the data lane surfaces
// per-rank ids this map fills in by regeneration alone.
var TalentSpellIDs = map[string][]int32{
	"improved_wrath":            {16814, 16814, 16814, 16814, 16814},
	"genesis":                   {1223081, 1223081, 1223081, 1223081, 1223081},
	"moonglow":                  {16845, 16845, 16845},
	"improved_moonfire":         {16821, 16821},
	"natures_majesty":           {1223082, 1223082},
	"natures_reach":             {16819, 16819},
	"improved_entangling_roots": {16918, 16918, 16918},
	"natures_splendor":          {1223083},
	"insect_swarm":              {5570},
	"vengeance":                 {16909, 16909, 16909, 16909, 16909},
	"improved_starfire":         {16850, 16850, 16850, 16850, 16850},
	"overgrowth":                {17245, 17245},
	"natures_grace":             {16880},
	"eclipse":                   {408248, 408248, 408248},
	"moonfury":                  {16896, 16896, 16896, 16896, 16896},
	"moonkin_form":              {24858},
	"ferocity":                  {16934, 16934, 16934, 16934, 16934},
	"heart_of_the_wild":         {17003, 17003, 17003, 17003, 17003},
	"feral_swiftness":           {17002, 17002},
	"feral_instinct":            {16947, 16947, 16947},
	"brutal_impact":             {16940, 16940},
	"thick_hide":                {16929, 16929, 16929},
	"shredding_attacks":         {16966, 16966, 16966},
	"savage_fury":               {16998, 16998},
	"feral_charge":              {1238122},
	"sharpened_claws":           {16942, 16942},
	"shifting_power":            {1322605},
	"primal_bite":               {407995},
	"predatory_strikes":         {16972, 16972, 16972},
	"blood_frenzy":              {16958, 16958},
	"improved_shifting_power":   {1322670, 1322670},
	"leader_of_the_pack":        {17007},
	"predatory_instincts":       {1223242, 1223242},
	"natural_reaction":          {417051, 417051, 417051, 417051, 417051},
	"rend_and_tear":             {1223246, 1223246, 1223246, 1223246, 1223246},
	"berserk":                   {417141},
	"natures_focus":             {17063, 17063, 17063, 17063, 17063},
	"furor":                     {17056, 17056, 17056, 17056, 17056},
	"naturalist":                {17069, 17069, 17069, 17069, 17069},
	"subtlety":                  {17118, 17118, 17118},
	"natural_shapeshifter":      {16833, 16833, 16833},
	"reflection":                {17106, 17106, 17106},
	"gift_of_nature":            {17104, 17104, 17104, 17104, 17104},
	"gift_of_the_earthmother":   {414673},
	"tranquil_spirit":           {24968, 24968, 24968, 24968, 24968},
	"improved_rejuvenation":     {17111, 17111, 17111},
	"swiftmend":                 {18562},
	"natures_swiftness":         {17116},
	"living_spirit":             {1309631, 1309631, 1309631},
	"improved_tranquility":      {17123, 17123},
	"improved_regrowth":         {17074, 17074, 17074, 17074, 17074},
	"wild_growth":               {408120},
}
