#!/usr/bin/env python3
"""Generate sim/core/base_stats_auto_gen.go from the client's CombatRatings
GameTable.

The constants this emits are read straight out of the client's
combatratings.txt; nothing here is typed by hand. Forever's beta client is
1.60.1.69893, and the data lane has confirmed that CombatRatings is one of
only three GameTables files that exist on the Classic lineage (the other
two, basemp.txt and hppersta.txt, carry no columns this generator uses).
Every constant below therefore comes from a real, measured Forever value -
there is no Era fallback path here, because nothing this generator emits is
missing from combatratings.txt.

Usage:
    python3 tools/base_stats_parser.py                                  # 1.60.1.69893, vendored copy
    python3 tools/base_stats_parser.py --build 1.60.2.70000 \\
        --inputs assets/db_inputs/gametables/1.60.2.70000
"""

import argparse
import csv
import sys

MAX_LEVEL = 60

COMBAT_RATINGS = "combatratings.txt"

# Rating constants, in the order the generated file emits them:
#   Go constant name -> combatratings.txt column (exact header spelling)
# Deliberately absent, and each for a reason (research/08-stats.md 12.4):
#   ExpertisePerQuarterPercentReduction - the item unit is a percentage
#     (Edgemaster's is 1.0%), not expertise points, so the quarter-percent
#     quantisation from later expansions is wrong. The attack table reads
#     stats.Expertise/100 directly (sim/core/spell_outcome.go).
#   ResilienceRatingPerCritReductionChance - Forever adds no resilience,
#     and the stat itself is deleted from the enum.
RATING_CONSTANTS = [
    ("DefenseRatingPerDefense", "Defense Skill"),
    ("DodgeRatingPerDodgeChance", "Dodge"),
    ("ParryRatingPerParryChance", "Parry"),
    ("BlockRatingPerBlockChance", "Block"),
]

# Constants that are straight percentages in the Classic lineage, which
# Forever keeps. They are emitted as 1 rather than read from the table
# because the table's value is a rating-to-percent conversion that the
# lineage does not use for these stats.
# Confirmed, not provisional: Forever uses flat percentages
# (research/08-stats.md 2 and 12.4).
PERCENTAGE_CONSTANTS = [
    ("CritRatingPerCritChance", "Forever: one crit stat for spells and melee."),
    ("HitRatingPerHitChance", "Forever: one hit stat for spells, melee and ranged."),
    ("HasteRatingPerHastePercent", "Forever keeps melee, ranged and spell haste separate."),
    ("ExpertiseRatingPerExpertiseChance",
     "The item unit is a percentage (Edgemaster's 1.0%), not expertise points."),
]


def read_column_indexed(path):
    """combatratings.txt is one row per level with named columns. Return
    {column name: [value per level]}."""
    with open(path, newline="") as fh:
        rows = list(csv.reader(fh, delimiter="\t"))
    if not rows:
        raise SystemExit(f"{path} is empty")
    header = [h.strip() for h in rows[0]]
    out = {}
    for col_idx, name in enumerate(header):
        if not name or name == "Level":
            continue
        values = []
        for row in rows[1:]:
            if col_idx < len(row) and row[col_idx].strip():
                values.append(float(row[col_idx]))
        # A repeated header name (this GameTable has several "Unused N"
        # and bare "Unknown" columns) would otherwise silently clobber an
        # earlier column under the same key.
        if name in out:
            raise SystemExit(f"{path} has the column {name!r} more than once")
        out[name] = values
    return out


def at_max_level(table, column, path):
    if column not in table:
        raise SystemExit(
            f"{path} has no column {column!r}; columns are {sorted(table)}")
    values = table[column]
    if len(values) < MAX_LEVEL:
        raise SystemExit(
            f"{path} column {column!r} has {len(values)} rows, need at least {MAX_LEVEL}")
    return values[MAX_LEVEL - 1]


def generate(table, build, inputs_path):
    lines = [
        "// Code generated by tools/base_stats_parser.py. DO NOT EDIT.",
        "//",
        f"// Client build: {build}",
        f"// Source:       {inputs_path}/{COMBAT_RATINGS}",
        "//",
        "// Regenerate with:",
        "//     python3 tools/base_stats_parser.py --build <build> --inputs <dir>",
        "",
        "package core",
        "",
        "// BaseStatsBuild is the client build these constants were read from.",
        f'const BaseStatsBuild = "{build}"',
        "",
    ]
    for name, column in RATING_CONSTANTS:
        value = at_max_level(table, column, inputs_path)
        lines.append(f"// source build: {build} (combatratings.txt column {column!r})")
        lines.append(f"const {name} = {value:f}")
    lines.append("")
    for name, comment in PERCENTAGE_CONSTANTS:
        lines.append(f"// {comment}")
        lines.append("// Ratings are straight percentages in the Classic lineage.")
        lines.append(f"const {name} = 1")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--inputs", default="assets/db_inputs/gametables/1.60.1.69893",
                     help="directory holding the client's combatratings.txt")
    ap.add_argument("--build", default="1.60.1.69893",
                     help="client build string, e.g. 1.60.1.69893")
    ap.add_argument("--out", default="sim/core/base_stats_auto_gen.go")
    args = ap.parse_args()

    table = read_column_indexed(f"{args.inputs}/{COMBAT_RATINGS}")
    out = generate(table, args.build, args.inputs)
    with open(args.out, "w") as fh:
        fh.write(out)
    print(f"wrote {args.out} from build {args.build}", file=sys.stderr)


if __name__ == "__main__":
    main()
