// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: druid.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DruidTalents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Balance
	ImprovedWrath           int32 `protobuf:"varint,1,opt,name=improved_wrath,json=improvedWrath,proto3" json:"improved_wrath,omitempty"`
	NaturesGrasp            bool  `protobuf:"varint,2,opt,name=natures_grasp,json=naturesGrasp,proto3" json:"natures_grasp,omitempty"`
	ImprovedNaturesGrasp    int32 `protobuf:"varint,3,opt,name=improved_natures_grasp,json=improvedNaturesGrasp,proto3" json:"improved_natures_grasp,omitempty"`
	ImprovedEntanglingRoots int32 `protobuf:"varint,4,opt,name=improved_entangling_roots,json=improvedEntanglingRoots,proto3" json:"improved_entangling_roots,omitempty"`
	ImprovedMoonfire        int32 `protobuf:"varint,5,opt,name=improved_moonfire,json=improvedMoonfire,proto3" json:"improved_moonfire,omitempty"`
	NaturalWeapons          int32 `protobuf:"varint,6,opt,name=natural_weapons,json=naturalWeapons,proto3" json:"natural_weapons,omitempty"`
	NaturalShapeshifter     int32 `protobuf:"varint,7,opt,name=natural_shapeshifter,json=naturalShapeshifter,proto3" json:"natural_shapeshifter,omitempty"`
	ImprovedThorns          int32 `protobuf:"varint,8,opt,name=improved_thorns,json=improvedThorns,proto3" json:"improved_thorns,omitempty"`
	OmenOfClarity           bool  `protobuf:"varint,9,opt,name=omen_of_clarity,json=omenOfClarity,proto3" json:"omen_of_clarity,omitempty"`
	NaturesReach            int32 `protobuf:"varint,10,opt,name=natures_reach,json=naturesReach,proto3" json:"natures_reach,omitempty"`
	Vengeance               int32 `protobuf:"varint,11,opt,name=vengeance,proto3" json:"vengeance,omitempty"`
	ImprovedStarfire        int32 `protobuf:"varint,12,opt,name=improved_starfire,json=improvedStarfire,proto3" json:"improved_starfire,omitempty"`
	NaturesGrace            bool  `protobuf:"varint,13,opt,name=natures_grace,json=naturesGrace,proto3" json:"natures_grace,omitempty"`
	Moonglow                int32 `protobuf:"varint,14,opt,name=moonglow,proto3" json:"moonglow,omitempty"`
	Moonfury                int32 `protobuf:"varint,15,opt,name=moonfury,proto3" json:"moonfury,omitempty"`
	MoonkinForm             bool  `protobuf:"varint,16,opt,name=moonkin_form,json=moonkinForm,proto3" json:"moonkin_form,omitempty"`
	// Feral Combat
	Ferocity         int32 `protobuf:"varint,17,opt,name=ferocity,proto3" json:"ferocity,omitempty"`
	FeralAggression  int32 `protobuf:"varint,18,opt,name=feral_aggression,json=feralAggression,proto3" json:"feral_aggression,omitempty"`
	FeralInstinct    int32 `protobuf:"varint,19,opt,name=feral_instinct,json=feralInstinct,proto3" json:"feral_instinct,omitempty"`
	BrutalImpact     int32 `protobuf:"varint,20,opt,name=brutal_impact,json=brutalImpact,proto3" json:"brutal_impact,omitempty"`
	ThickHide        int32 `protobuf:"varint,21,opt,name=thick_hide,json=thickHide,proto3" json:"thick_hide,omitempty"`
	FelineSwiftness  int32 `protobuf:"varint,22,opt,name=feline_swiftness,json=felineSwiftness,proto3" json:"feline_swiftness,omitempty"`
	FeralCharge      bool  `protobuf:"varint,23,opt,name=feral_charge,json=feralCharge,proto3" json:"feral_charge,omitempty"`
	SharpenedClaws   int32 `protobuf:"varint,24,opt,name=sharpened_claws,json=sharpenedClaws,proto3" json:"sharpened_claws,omitempty"`
	ImprovedShred    int32 `protobuf:"varint,25,opt,name=improved_shred,json=improvedShred,proto3" json:"improved_shred,omitempty"`
	PredatoryStrikes int32 `protobuf:"varint,26,opt,name=predatory_strikes,json=predatoryStrikes,proto3" json:"predatory_strikes,omitempty"`
	BloodFrenzy      int32 `protobuf:"varint,27,opt,name=blood_frenzy,json=bloodFrenzy,proto3" json:"blood_frenzy,omitempty"`
	PrimalFury       int32 `protobuf:"varint,28,opt,name=primal_fury,json=primalFury,proto3" json:"primal_fury,omitempty"`
	SavageFury       int32 `protobuf:"varint,29,opt,name=savage_fury,json=savageFury,proto3" json:"savage_fury,omitempty"`
	FaerieFireFeral  bool  `protobuf:"varint,30,opt,name=faerie_fire_feral,json=faerieFireFeral,proto3" json:"faerie_fire_feral,omitempty"`
	HeartOfTheWild   int32 `protobuf:"varint,31,opt,name=heart_of_the_wild,json=heartOfTheWild,proto3" json:"heart_of_the_wild,omitempty"`
	LeaderOfThePack  bool  `protobuf:"varint,32,opt,name=leader_of_the_pack,json=leaderOfThePack,proto3" json:"leader_of_the_pack,omitempty"`
	// Restoration
	ImprovedMarkOfTheWild int32 `protobuf:"varint,33,opt,name=improved_mark_of_the_wild,json=improvedMarkOfTheWild,proto3" json:"improved_mark_of_the_wild,omitempty"`
	Furor                 int32 `protobuf:"varint,34,opt,name=furor,proto3" json:"furor,omitempty"`
	ImprovedHealingTouch  int32 `protobuf:"varint,35,opt,name=improved_healing_touch,json=improvedHealingTouch,proto3" json:"improved_healing_touch,omitempty"`
	NaturesFocus          int32 `protobuf:"varint,36,opt,name=natures_focus,json=naturesFocus,proto3" json:"natures_focus,omitempty"`
	ImprovedEnrage        int32 `protobuf:"varint,37,opt,name=improved_enrage,json=improvedEnrage,proto3" json:"improved_enrage,omitempty"`
	Reflection            int32 `protobuf:"varint,38,opt,name=reflection,proto3" json:"reflection,omitempty"`
	InsectSwarm           bool  `protobuf:"varint,39,opt,name=insect_swarm,json=insectSwarm,proto3" json:"insect_swarm,omitempty"`
	Subtlety              int32 `protobuf:"varint,40,opt,name=subtlety,proto3" json:"subtlety,omitempty"`
	TranquilSpirit        int32 `protobuf:"varint,41,opt,name=tranquil_spirit,json=tranquilSpirit,proto3" json:"tranquil_spirit,omitempty"`
	ImprovedRejuvenation  int32 `protobuf:"varint,42,opt,name=improved_rejuvenation,json=improvedRejuvenation,proto3" json:"improved_rejuvenation,omitempty"`
	NaturesSwiftness      bool  `protobuf:"varint,43,opt,name=natures_swiftness,json=naturesSwiftness,proto3" json:"natures_swiftness,omitempty"`
	GiftOfNature          int32 `protobuf:"varint,44,opt,name=gift_of_nature,json=giftOfNature,proto3" json:"gift_of_nature,omitempty"`
	ImprovedTranquility   int32 `protobuf:"varint,45,opt,name=improved_tranquility,json=improvedTranquility,proto3" json:"improved_tranquility,omitempty"`
	ImprovedRegrowth      int32 `protobuf:"varint,46,opt,name=improved_regrowth,json=improvedRegrowth,proto3" json:"improved_regrowth,omitempty"`
	Swiftmend             bool  `protobuf:"varint,47,opt,name=swiftmend,proto3" json:"swiftmend,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DruidTalents) Reset() {
	*x = DruidTalents{}
	mi := &file_druid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DruidTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DruidTalents) ProtoMessage() {}

func (x *DruidTalents) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DruidTalents.ProtoReflect.Descriptor instead.
func (*DruidTalents) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{0}
}

func (x *DruidTalents) GetImprovedWrath() int32 {
	if x != nil {
		return x.ImprovedWrath
	}
	return 0
}

func (x *DruidTalents) GetNaturesGrasp() bool {
	if x != nil {
		return x.NaturesGrasp
	}
	return false
}

func (x *DruidTalents) GetImprovedNaturesGrasp() int32 {
	if x != nil {
		return x.ImprovedNaturesGrasp
	}
	return 0
}

func (x *DruidTalents) GetImprovedEntanglingRoots() int32 {
	if x != nil {
		return x.ImprovedEntanglingRoots
	}
	return 0
}

func (x *DruidTalents) GetImprovedMoonfire() int32 {
	if x != nil {
		return x.ImprovedMoonfire
	}
	return 0
}

func (x *DruidTalents) GetNaturalWeapons() int32 {
	if x != nil {
		return x.NaturalWeapons
	}
	return 0
}

func (x *DruidTalents) GetNaturalShapeshifter() int32 {
	if x != nil {
		return x.NaturalShapeshifter
	}
	return 0
}

func (x *DruidTalents) GetImprovedThorns() int32 {
	if x != nil {
		return x.ImprovedThorns
	}
	return 0
}

func (x *DruidTalents) GetOmenOfClarity() bool {
	if x != nil {
		return x.OmenOfClarity
	}
	return false
}

func (x *DruidTalents) GetNaturesReach() int32 {
	if x != nil {
		return x.NaturesReach
	}
	return 0
}

func (x *DruidTalents) GetVengeance() int32 {
	if x != nil {
		return x.Vengeance
	}
	return 0
}

func (x *DruidTalents) GetImprovedStarfire() int32 {
	if x != nil {
		return x.ImprovedStarfire
	}
	return 0
}

func (x *DruidTalents) GetNaturesGrace() bool {
	if x != nil {
		return x.NaturesGrace
	}
	return false
}

func (x *DruidTalents) GetMoonglow() int32 {
	if x != nil {
		return x.Moonglow
	}
	return 0
}

func (x *DruidTalents) GetMoonfury() int32 {
	if x != nil {
		return x.Moonfury
	}
	return 0
}

func (x *DruidTalents) GetMoonkinForm() bool {
	if x != nil {
		return x.MoonkinForm
	}
	return false
}

func (x *DruidTalents) GetFerocity() int32 {
	if x != nil {
		return x.Ferocity
	}
	return 0
}

func (x *DruidTalents) GetFeralAggression() int32 {
	if x != nil {
		return x.FeralAggression
	}
	return 0
}

func (x *DruidTalents) GetFeralInstinct() int32 {
	if x != nil {
		return x.FeralInstinct
	}
	return 0
}

func (x *DruidTalents) GetBrutalImpact() int32 {
	if x != nil {
		return x.BrutalImpact
	}
	return 0
}

func (x *DruidTalents) GetThickHide() int32 {
	if x != nil {
		return x.ThickHide
	}
	return 0
}

func (x *DruidTalents) GetFelineSwiftness() int32 {
	if x != nil {
		return x.FelineSwiftness
	}
	return 0
}

func (x *DruidTalents) GetFeralCharge() bool {
	if x != nil {
		return x.FeralCharge
	}
	return false
}

func (x *DruidTalents) GetSharpenedClaws() int32 {
	if x != nil {
		return x.SharpenedClaws
	}
	return 0
}

func (x *DruidTalents) GetImprovedShred() int32 {
	if x != nil {
		return x.ImprovedShred
	}
	return 0
}

func (x *DruidTalents) GetPredatoryStrikes() int32 {
	if x != nil {
		return x.PredatoryStrikes
	}
	return 0
}

func (x *DruidTalents) GetBloodFrenzy() int32 {
	if x != nil {
		return x.BloodFrenzy
	}
	return 0
}

func (x *DruidTalents) GetPrimalFury() int32 {
	if x != nil {
		return x.PrimalFury
	}
	return 0
}

func (x *DruidTalents) GetSavageFury() int32 {
	if x != nil {
		return x.SavageFury
	}
	return 0
}

func (x *DruidTalents) GetFaerieFireFeral() bool {
	if x != nil {
		return x.FaerieFireFeral
	}
	return false
}

func (x *DruidTalents) GetHeartOfTheWild() int32 {
	if x != nil {
		return x.HeartOfTheWild
	}
	return 0
}

func (x *DruidTalents) GetLeaderOfThePack() bool {
	if x != nil {
		return x.LeaderOfThePack
	}
	return false
}

func (x *DruidTalents) GetImprovedMarkOfTheWild() int32 {
	if x != nil {
		return x.ImprovedMarkOfTheWild
	}
	return 0
}

func (x *DruidTalents) GetFuror() int32 {
	if x != nil {
		return x.Furor
	}
	return 0
}

func (x *DruidTalents) GetImprovedHealingTouch() int32 {
	if x != nil {
		return x.ImprovedHealingTouch
	}
	return 0
}

func (x *DruidTalents) GetNaturesFocus() int32 {
	if x != nil {
		return x.NaturesFocus
	}
	return 0
}

func (x *DruidTalents) GetImprovedEnrage() int32 {
	if x != nil {
		return x.ImprovedEnrage
	}
	return 0
}

func (x *DruidTalents) GetReflection() int32 {
	if x != nil {
		return x.Reflection
	}
	return 0
}

func (x *DruidTalents) GetInsectSwarm() bool {
	if x != nil {
		return x.InsectSwarm
	}
	return false
}

func (x *DruidTalents) GetSubtlety() int32 {
	if x != nil {
		return x.Subtlety
	}
	return 0
}

func (x *DruidTalents) GetTranquilSpirit() int32 {
	if x != nil {
		return x.TranquilSpirit
	}
	return 0
}

func (x *DruidTalents) GetImprovedRejuvenation() int32 {
	if x != nil {
		return x.ImprovedRejuvenation
	}
	return 0
}

func (x *DruidTalents) GetNaturesSwiftness() bool {
	if x != nil {
		return x.NaturesSwiftness
	}
	return false
}

func (x *DruidTalents) GetGiftOfNature() int32 {
	if x != nil {
		return x.GiftOfNature
	}
	return 0
}

func (x *DruidTalents) GetImprovedTranquility() int32 {
	if x != nil {
		return x.ImprovedTranquility
	}
	return 0
}

func (x *DruidTalents) GetImprovedRegrowth() int32 {
	if x != nil {
		return x.ImprovedRegrowth
	}
	return 0
}

func (x *DruidTalents) GetSwiftmend() bool {
	if x != nil {
		return x.Swiftmend
	}
	return false
}

type BalanceDruid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *BalanceDruid_Options  `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceDruid) Reset() {
	*x = BalanceDruid{}
	mi := &file_druid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceDruid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDruid) ProtoMessage() {}

func (x *BalanceDruid) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDruid.ProtoReflect.Descriptor instead.
func (*BalanceDruid) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceDruid) GetOptions() *BalanceDruid_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type FeralDruid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rotation      *FeralDruid_Rotation   `protobuf:"bytes,1,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Options       *FeralDruid_Options    `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeralDruid) Reset() {
	*x = FeralDruid{}
	mi := &file_druid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeralDruid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeralDruid) ProtoMessage() {}

func (x *FeralDruid) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeralDruid.ProtoReflect.Descriptor instead.
func (*FeralDruid) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{2}
}

func (x *FeralDruid) GetRotation() *FeralDruid_Rotation {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *FeralDruid) GetOptions() *FeralDruid_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type FeralTankDruid struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Options       *FeralTankDruid_Options `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeralTankDruid) Reset() {
	*x = FeralTankDruid{}
	mi := &file_druid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeralTankDruid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeralTankDruid) ProtoMessage() {}

func (x *FeralTankDruid) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeralTankDruid.ProtoReflect.Descriptor instead.
func (*FeralTankDruid) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{3}
}

func (x *FeralTankDruid) GetOptions() *FeralTankDruid_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type RestorationDruid struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Options       *RestorationDruid_Options `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestorationDruid) Reset() {
	*x = RestorationDruid{}
	mi := &file_druid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestorationDruid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestorationDruid) ProtoMessage() {}

func (x *RestorationDruid) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestorationDruid.ProtoReflect.Descriptor instead.
func (*RestorationDruid) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{4}
}

func (x *RestorationDruid) GetOptions() *RestorationDruid_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type BalanceDruid_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceDruid_Rotation) Reset() {
	*x = BalanceDruid_Rotation{}
	mi := &file_druid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceDruid_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDruid_Rotation) ProtoMessage() {}

func (x *BalanceDruid_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDruid_Rotation.ProtoReflect.Descriptor instead.
func (*BalanceDruid_Rotation) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{1, 0}
}

type BalanceDruid_Options struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InnervateTarget *UnitReference         `protobuf:"bytes,1,opt,name=innervate_target,json=innervateTarget,proto3" json:"innervate_target,omitempty"`
	OkfUptime       float32                `protobuf:"fixed32,2,opt,name=okf_uptime,json=okfUptime,proto3" json:"okf_uptime,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BalanceDruid_Options) Reset() {
	*x = BalanceDruid_Options{}
	mi := &file_druid_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceDruid_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDruid_Options) ProtoMessage() {}

func (x *BalanceDruid_Options) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDruid_Options.ProtoReflect.Descriptor instead.
func (*BalanceDruid_Options) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{1, 1}
}

func (x *BalanceDruid_Options) GetInnervateTarget() *UnitReference {
	if x != nil {
		return x.InnervateTarget
	}
	return nil
}

func (x *BalanceDruid_Options) GetOkfUptime() float32 {
	if x != nil {
		return x.OkfUptime
	}
	return 0
}

type FeralDruid_Rotation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaintainFaerieFire bool                   `protobuf:"varint,1,opt,name=maintain_faerie_fire,json=maintainFaerieFire,proto3" json:"maintain_faerie_fire,omitempty"`
	MinCombosForRip    int32                  `protobuf:"varint,2,opt,name=min_combos_for_rip,json=minCombosForRip,proto3" json:"min_combos_for_rip,omitempty"`
	MaxWaitTime        float32                `protobuf:"fixed32,3,opt,name=max_wait_time,json=maxWaitTime,proto3" json:"max_wait_time,omitempty"`
	PreroarDuration    float32                `protobuf:"fixed32,4,opt,name=preroar_duration,json=preroarDuration,proto3" json:"preroar_duration,omitempty"`
	PrecastTigersFury  bool                   `protobuf:"varint,5,opt,name=precast_tigers_fury,json=precastTigersFury,proto3" json:"precast_tigers_fury,omitempty"`
	UseShredTrick      bool                   `protobuf:"varint,6,opt,name=use_shred_trick,json=useShredTrick,proto3" json:"use_shred_trick,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FeralDruid_Rotation) Reset() {
	*x = FeralDruid_Rotation{}
	mi := &file_druid_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeralDruid_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeralDruid_Rotation) ProtoMessage() {}

func (x *FeralDruid_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeralDruid_Rotation.ProtoReflect.Descriptor instead.
func (*FeralDruid_Rotation) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FeralDruid_Rotation) GetMaintainFaerieFire() bool {
	if x != nil {
		return x.MaintainFaerieFire
	}
	return false
}

func (x *FeralDruid_Rotation) GetMinCombosForRip() int32 {
	if x != nil {
		return x.MinCombosForRip
	}
	return 0
}

func (x *FeralDruid_Rotation) GetMaxWaitTime() float32 {
	if x != nil {
		return x.MaxWaitTime
	}
	return 0
}

func (x *FeralDruid_Rotation) GetPreroarDuration() float32 {
	if x != nil {
		return x.PreroarDuration
	}
	return 0
}

func (x *FeralDruid_Rotation) GetPrecastTigersFury() bool {
	if x != nil {
		return x.PrecastTigersFury
	}
	return false
}

func (x *FeralDruid_Rotation) GetUseShredTrick() bool {
	if x != nil {
		return x.UseShredTrick
	}
	return false
}

type FeralDruid_Options struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InnervateTarget   *UnitReference         `protobuf:"bytes,1,opt,name=innervate_target,json=innervateTarget,proto3" json:"innervate_target,omitempty"`
	LatencyMs         int32                  `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	AssumeBleedActive bool                   `protobuf:"varint,4,opt,name=assume_bleed_active,json=assumeBleedActive,proto3" json:"assume_bleed_active,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FeralDruid_Options) Reset() {
	*x = FeralDruid_Options{}
	mi := &file_druid_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeralDruid_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeralDruid_Options) ProtoMessage() {}

func (x *FeralDruid_Options) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeralDruid_Options.ProtoReflect.Descriptor instead.
func (*FeralDruid_Options) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{2, 1}
}

func (x *FeralDruid_Options) GetInnervateTarget() *UnitReference {
	if x != nil {
		return x.InnervateTarget
	}
	return nil
}

func (x *FeralDruid_Options) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *FeralDruid_Options) GetAssumeBleedActive() bool {
	if x != nil {
		return x.AssumeBleedActive
	}
	return false
}

type FeralTankDruid_Rotation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum rage to queue HS or Cleave.
	MaulRageThreshold        int32   `protobuf:"varint,1,opt,name=maul_rage_threshold,json=maulRageThreshold,proto3" json:"maul_rage_threshold,omitempty"`
	MaintainDemoralizingRoar bool    `protobuf:"varint,2,opt,name=maintain_demoralizing_roar,json=maintainDemoralizingRoar,proto3" json:"maintain_demoralizing_roar,omitempty"`
	LacerateTime             float64 `protobuf:"fixed64,3,opt,name=lacerate_time,json=lacerateTime,proto3" json:"lacerate_time,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *FeralTankDruid_Rotation) Reset() {
	*x = FeralTankDruid_Rotation{}
	mi := &file_druid_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeralTankDruid_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeralTankDruid_Rotation) ProtoMessage() {}

func (x *FeralTankDruid_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeralTankDruid_Rotation.ProtoReflect.Descriptor instead.
func (*FeralTankDruid_Rotation) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{3, 0}
}

func (x *FeralTankDruid_Rotation) GetMaulRageThreshold() int32 {
	if x != nil {
		return x.MaulRageThreshold
	}
	return 0
}

func (x *FeralTankDruid_Rotation) GetMaintainDemoralizingRoar() bool {
	if x != nil {
		return x.MaintainDemoralizingRoar
	}
	return false
}

func (x *FeralTankDruid_Rotation) GetLacerateTime() float64 {
	if x != nil {
		return x.LacerateTime
	}
	return 0
}

type FeralTankDruid_Options struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InnervateTarget *UnitReference         `protobuf:"bytes,1,opt,name=innervate_target,json=innervateTarget,proto3" json:"innervate_target,omitempty"`
	StartingRage    float64                `protobuf:"fixed64,2,opt,name=starting_rage,json=startingRage,proto3" json:"starting_rage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FeralTankDruid_Options) Reset() {
	*x = FeralTankDruid_Options{}
	mi := &file_druid_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeralTankDruid_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeralTankDruid_Options) ProtoMessage() {}

func (x *FeralTankDruid_Options) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeralTankDruid_Options.ProtoReflect.Descriptor instead.
func (*FeralTankDruid_Options) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{3, 1}
}

func (x *FeralTankDruid_Options) GetInnervateTarget() *UnitReference {
	if x != nil {
		return x.InnervateTarget
	}
	return nil
}

func (x *FeralTankDruid_Options) GetStartingRage() float64 {
	if x != nil {
		return x.StartingRage
	}
	return 0
}

type RestorationDruid_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestorationDruid_Rotation) Reset() {
	*x = RestorationDruid_Rotation{}
	mi := &file_druid_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestorationDruid_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestorationDruid_Rotation) ProtoMessage() {}

func (x *RestorationDruid_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestorationDruid_Rotation.ProtoReflect.Descriptor instead.
func (*RestorationDruid_Rotation) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{4, 0}
}

type RestorationDruid_Options struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InnervateTarget *UnitReference         `protobuf:"bytes,1,opt,name=innervate_target,json=innervateTarget,proto3" json:"innervate_target,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestorationDruid_Options) Reset() {
	*x = RestorationDruid_Options{}
	mi := &file_druid_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestorationDruid_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestorationDruid_Options) ProtoMessage() {}

func (x *RestorationDruid_Options) ProtoReflect() protoreflect.Message {
	mi := &file_druid_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestorationDruid_Options.ProtoReflect.Descriptor instead.
func (*RestorationDruid_Options) Descriptor() ([]byte, []int) {
	return file_druid_proto_rawDescGZIP(), []int{4, 1}
}

func (x *RestorationDruid_Options) GetInnervateTarget() *UnitReference {
	if x != nil {
		return x.InnervateTarget
	}
	return nil
}

var File_druid_proto protoreflect.FileDescriptor

const file_druid_proto_rawDesc = "" +
	"\n" +
	"\vdruid.proto\x12\x05proto\x1a\fcommon.proto\"\xde\x0e\n" +
	"\fDruidTalents\x12%\n" +
	"\x0eimproved_wrath\x18\x01 \x01(\x05R\rimprovedWrath\x12#\n" +
	"\rnatures_grasp\x18\x02 \x01(\bR\fnaturesGrasp\x124\n" +
	"\x16improved_natures_grasp\x18\x03 \x01(\x05R\x14improvedNaturesGrasp\x12:\n" +
	"\x19improved_entangling_roots\x18\x04 \x01(\x05R\x17improvedEntanglingRoots\x12+\n" +
	"\x11improved_moonfire\x18\x05 \x01(\x05R\x10improvedMoonfire\x12'\n" +
	"\x0fnatural_weapons\x18\x06 \x01(\x05R\x0enaturalWeapons\x121\n" +
	"\x14natural_shapeshifter\x18\a \x01(\x05R\x13naturalShapeshifter\x12'\n" +
	"\x0fimproved_thorns\x18\b \x01(\x05R\x0eimprovedThorns\x12&\n" +
	"\x0fomen_of_clarity\x18\t \x01(\bR\romenOfClarity\x12#\n" +
	"\rnatures_reach\x18\n" +
	" \x01(\x05R\fnaturesReach\x12\x1c\n" +
	"\tvengeance\x18\v \x01(\x05R\tvengeance\x12+\n" +
	"\x11improved_starfire\x18\f \x01(\x05R\x10improvedStarfire\x12#\n" +
	"\rnatures_grace\x18\r \x01(\bR\fnaturesGrace\x12\x1a\n" +
	"\bmoonglow\x18\x0e \x01(\x05R\bmoonglow\x12\x1a\n" +
	"\bmoonfury\x18\x0f \x01(\x05R\bmoonfury\x12!\n" +
	"\fmoonkin_form\x18\x10 \x01(\bR\vmoonkinForm\x12\x1a\n" +
	"\bferocity\x18\x11 \x01(\x05R\bferocity\x12)\n" +
	"\x10feral_aggression\x18\x12 \x01(\x05R\x0fferalAggression\x12%\n" +
	"\x0eferal_instinct\x18\x13 \x01(\x05R\rferalInstinct\x12#\n" +
	"\rbrutal_impact\x18\x14 \x01(\x05R\fbrutalImpact\x12\x1d\n" +
	"\n" +
	"thick_hide\x18\x15 \x01(\x05R\tthickHide\x12)\n" +
	"\x10feline_swiftness\x18\x16 \x01(\x05R\x0ffelineSwiftness\x12!\n" +
	"\fferal_charge\x18\x17 \x01(\bR\vferalCharge\x12'\n" +
	"\x0fsharpened_claws\x18\x18 \x01(\x05R\x0esharpenedClaws\x12%\n" +
	"\x0eimproved_shred\x18\x19 \x01(\x05R\rimprovedShred\x12+\n" +
	"\x11predatory_strikes\x18\x1a \x01(\x05R\x10predatoryStrikes\x12!\n" +
	"\fblood_frenzy\x18\x1b \x01(\x05R\vbloodFrenzy\x12\x1f\n" +
	"\vprimal_fury\x18\x1c \x01(\x05R\n" +
	"primalFury\x12\x1f\n" +
	"\vsavage_fury\x18\x1d \x01(\x05R\n" +
	"savageFury\x12*\n" +
	"\x11faerie_fire_feral\x18\x1e \x01(\bR\x0ffaerieFireFeral\x12)\n" +
	"\x11heart_of_the_wild\x18\x1f \x01(\x05R\x0eheartOfTheWild\x12+\n" +
	"\x12leader_of_the_pack\x18  \x01(\bR\x0fleaderOfThePack\x128\n" +
	"\x19improved_mark_of_the_wild\x18! \x01(\x05R\x15improvedMarkOfTheWild\x12\x14\n" +
	"\x05furor\x18\" \x01(\x05R\x05furor\x124\n" +
	"\x16improved_healing_touch\x18# \x01(\x05R\x14improvedHealingTouch\x12#\n" +
	"\rnatures_focus\x18$ \x01(\x05R\fnaturesFocus\x12'\n" +
	"\x0fimproved_enrage\x18% \x01(\x05R\x0eimprovedEnrage\x12\x1e\n" +
	"\n" +
	"reflection\x18& \x01(\x05R\n" +
	"reflection\x12!\n" +
	"\finsect_swarm\x18' \x01(\bR\vinsectSwarm\x12\x1a\n" +
	"\bsubtlety\x18( \x01(\x05R\bsubtlety\x12'\n" +
	"\x0ftranquil_spirit\x18) \x01(\x05R\x0etranquilSpirit\x123\n" +
	"\x15improved_rejuvenation\x18* \x01(\x05R\x14improvedRejuvenation\x12+\n" +
	"\x11natures_swiftness\x18+ \x01(\bR\x10naturesSwiftness\x12$\n" +
	"\x0egift_of_nature\x18, \x01(\x05R\fgiftOfNature\x121\n" +
	"\x14improved_tranquility\x18- \x01(\x05R\x13improvedTranquility\x12+\n" +
	"\x11improved_regrowth\x18. \x01(\x05R\x10improvedRegrowth\x12\x1c\n" +
	"\tswiftmend\x18/ \x01(\bR\tswiftmend\"\xbc\x01\n" +
	"\fBalanceDruid\x125\n" +
	"\aoptions\x18\x03 \x01(\v2\x1b.proto.BalanceDruid.OptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\x1ai\n" +
	"\aOptions\x12?\n" +
	"\x10innervate_target\x18\x01 \x01(\v2\x14.proto.UnitReferenceR\x0finnervateTarget\x12\x1d\n" +
	"\n" +
	"okf_uptime\x18\x02 \x01(\x02R\tokfUptime\"\xa8\x04\n" +
	"\n" +
	"FeralDruid\x126\n" +
	"\brotation\x18\x01 \x01(\v2\x1a.proto.FeralDruid.RotationR\brotation\x123\n" +
	"\aoptions\x18\x03 \x01(\v2\x19.proto.FeralDruid.OptionsR\aoptions\x1a\x90\x02\n" +
	"\bRotation\x120\n" +
	"\x14maintain_faerie_fire\x18\x01 \x01(\bR\x12maintainFaerieFire\x12+\n" +
	"\x12min_combos_for_rip\x18\x02 \x01(\x05R\x0fminCombosForRip\x12\"\n" +
	"\rmax_wait_time\x18\x03 \x01(\x02R\vmaxWaitTime\x12)\n" +
	"\x10preroar_duration\x18\x04 \x01(\x02R\x0fpreroarDuration\x12.\n" +
	"\x13precast_tigers_fury\x18\x05 \x01(\bR\x11precastTigersFury\x12&\n" +
	"\x0fuse_shred_trick\x18\x06 \x01(\bR\ruseShredTrick\x1a\x99\x01\n" +
	"\aOptions\x12?\n" +
	"\x10innervate_target\x18\x01 \x01(\v2\x14.proto.UnitReferenceR\x0finnervateTarget\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x05R\tlatencyMs\x12.\n" +
	"\x13assume_bleed_active\x18\x04 \x01(\bR\x11assumeBleedActive\"\xda\x02\n" +
	"\x0eFeralTankDruid\x127\n" +
	"\aoptions\x18\x03 \x01(\v2\x1d.proto.FeralTankDruid.OptionsR\aoptions\x1a\x9d\x01\n" +
	"\bRotation\x12.\n" +
	"\x13maul_rage_threshold\x18\x01 \x01(\x05R\x11maulRageThreshold\x12<\n" +
	"\x1amaintain_demoralizing_roar\x18\x02 \x01(\bR\x18maintainDemoralizingRoar\x12#\n" +
	"\rlacerate_time\x18\x03 \x01(\x01R\flacerateTime\x1ao\n" +
	"\aOptions\x12?\n" +
	"\x10innervate_target\x18\x01 \x01(\v2\x14.proto.UnitReferenceR\x0finnervateTarget\x12#\n" +
	"\rstarting_rage\x18\x02 \x01(\x01R\fstartingRage\"\xa5\x01\n" +
	"\x10RestorationDruid\x129\n" +
	"\aoptions\x18\x03 \x01(\v2\x1f.proto.RestorationDruid.OptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\x1aJ\n" +
	"\aOptions\x12?\n" +
	"\x10innervate_target\x18\x01 \x01(\v2\x14.proto.UnitReferenceR\x0finnervateTargetB\tZ\a./protob\x06proto3"

var (
	file_druid_proto_rawDescOnce sync.Once
	file_druid_proto_rawDescData []byte
)

func file_druid_proto_rawDescGZIP() []byte {
	file_druid_proto_rawDescOnce.Do(func() {
		file_druid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_druid_proto_rawDesc), len(file_druid_proto_rawDesc)))
	})
	return file_druid_proto_rawDescData
}

var file_druid_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_druid_proto_goTypes = []any{
	(*DruidTalents)(nil),              // 0: proto.DruidTalents
	(*BalanceDruid)(nil),              // 1: proto.BalanceDruid
	(*FeralDruid)(nil),                // 2: proto.FeralDruid
	(*FeralTankDruid)(nil),            // 3: proto.FeralTankDruid
	(*RestorationDruid)(nil),          // 4: proto.RestorationDruid
	(*BalanceDruid_Rotation)(nil),     // 5: proto.BalanceDruid.Rotation
	(*BalanceDruid_Options)(nil),      // 6: proto.BalanceDruid.Options
	(*FeralDruid_Rotation)(nil),       // 7: proto.FeralDruid.Rotation
	(*FeralDruid_Options)(nil),        // 8: proto.FeralDruid.Options
	(*FeralTankDruid_Rotation)(nil),   // 9: proto.FeralTankDruid.Rotation
	(*FeralTankDruid_Options)(nil),    // 10: proto.FeralTankDruid.Options
	(*RestorationDruid_Rotation)(nil), // 11: proto.RestorationDruid.Rotation
	(*RestorationDruid_Options)(nil),  // 12: proto.RestorationDruid.Options
	(*UnitReference)(nil),             // 13: proto.UnitReference
}
var file_druid_proto_depIdxs = []int32{
	6,  // 0: proto.BalanceDruid.options:type_name -> proto.BalanceDruid.Options
	7,  // 1: proto.FeralDruid.rotation:type_name -> proto.FeralDruid.Rotation
	8,  // 2: proto.FeralDruid.options:type_name -> proto.FeralDruid.Options
	10, // 3: proto.FeralTankDruid.options:type_name -> proto.FeralTankDruid.Options
	12, // 4: proto.RestorationDruid.options:type_name -> proto.RestorationDruid.Options
	13, // 5: proto.BalanceDruid.Options.innervate_target:type_name -> proto.UnitReference
	13, // 6: proto.FeralDruid.Options.innervate_target:type_name -> proto.UnitReference
	13, // 7: proto.FeralTankDruid.Options.innervate_target:type_name -> proto.UnitReference
	13, // 8: proto.RestorationDruid.Options.innervate_target:type_name -> proto.UnitReference
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_druid_proto_init() }
func file_druid_proto_init() {
	if File_druid_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_druid_proto_rawDesc), len(file_druid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_druid_proto_goTypes,
		DependencyIndexes: file_druid_proto_depIdxs,
		MessageInfos:      file_druid_proto_msgTypes,
	}.Build()
	File_druid_proto = out.File
	file_druid_proto_goTypes = nil
	file_druid_proto_depIdxs = nil
}
