// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: hunter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hunter_Rotation_RotationType int32

const (
	Hunter_Rotation_UnknownType  Hunter_Rotation_RotationType = 0
	Hunter_Rotation_SingleTarget Hunter_Rotation_RotationType = 1
	Hunter_Rotation_Aoe          Hunter_Rotation_RotationType = 3
	Hunter_Rotation_Custom       Hunter_Rotation_RotationType = 2
)

// Enum value maps for Hunter_Rotation_RotationType.
var (
	Hunter_Rotation_RotationType_name = map[int32]string{
		0: "UnknownType",
		1: "SingleTarget",
		3: "Aoe",
		2: "Custom",
	}
	Hunter_Rotation_RotationType_value = map[string]int32{
		"UnknownType":  0,
		"SingleTarget": 1,
		"Aoe":          3,
		"Custom":       2,
	}
)

func (x Hunter_Rotation_RotationType) Enum() *Hunter_Rotation_RotationType {
	p := new(Hunter_Rotation_RotationType)
	*p = x
	return p
}

func (x Hunter_Rotation_RotationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hunter_Rotation_RotationType) Descriptor() protoreflect.EnumDescriptor {
	return file_hunter_proto_enumTypes[0].Descriptor()
}

func (Hunter_Rotation_RotationType) Type() protoreflect.EnumType {
	return &file_hunter_proto_enumTypes[0]
}

func (x Hunter_Rotation_RotationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hunter_Rotation_RotationType.Descriptor instead.
func (Hunter_Rotation_RotationType) EnumDescriptor() ([]byte, []int) {
	return file_hunter_proto_rawDescGZIP(), []int{1, 0, 0}
}

type Hunter_Rotation_StingType int32

const (
	Hunter_Rotation_NoSting      Hunter_Rotation_StingType = 0
	Hunter_Rotation_ScorpidSting Hunter_Rotation_StingType = 1
	Hunter_Rotation_SerpentSting Hunter_Rotation_StingType = 2
)

// Enum value maps for Hunter_Rotation_StingType.
var (
	Hunter_Rotation_StingType_name = map[int32]string{
		0: "NoSting",
		1: "ScorpidSting",
		2: "SerpentSting",
	}
	Hunter_Rotation_StingType_value = map[string]int32{
		"NoSting":      0,
		"ScorpidSting": 1,
		"SerpentSting": 2,
	}
)

func (x Hunter_Rotation_StingType) Enum() *Hunter_Rotation_StingType {
	p := new(Hunter_Rotation_StingType)
	*p = x
	return p
}

func (x Hunter_Rotation_StingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hunter_Rotation_StingType) Descriptor() protoreflect.EnumDescriptor {
	return file_hunter_proto_enumTypes[1].Descriptor()
}

func (Hunter_Rotation_StingType) Type() protoreflect.EnumType {
	return &file_hunter_proto_enumTypes[1]
}

func (x Hunter_Rotation_StingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hunter_Rotation_StingType.Descriptor instead.
func (Hunter_Rotation_StingType) EnumDescriptor() ([]byte, []int) {
	return file_hunter_proto_rawDescGZIP(), []int{1, 0, 1}
}

type Hunter_Options_Ammo int32

const (
	Hunter_Options_AmmoNone Hunter_Options_Ammo = 0
	// 25
	Hunter_Options_RazorArrow Hunter_Options_Ammo = 1
	Hunter_Options_SolidShot  Hunter_Options_Ammo = 2
	// 40
	Hunter_Options_JaggedArrow   Hunter_Options_Ammo = 3
	Hunter_Options_AccurateSlugs Hunter_Options_Ammo = 4
	// 50
	Hunter_Options_MithrilGyroShot  Hunter_Options_Ammo = 5
	Hunter_Options_RockshardPellets Hunter_Options_Ammo = 6
	// 60
	Hunter_Options_IceThreadedArrow     Hunter_Options_Ammo = 7
	Hunter_Options_ThoriumHeadedArrow   Hunter_Options_Ammo = 8
	Hunter_Options_Doomshot             Hunter_Options_Ammo = 9
	Hunter_Options_IceThreadedBullet    Hunter_Options_Ammo = 10
	Hunter_Options_ThoriumShells        Hunter_Options_Ammo = 11
	Hunter_Options_MiniatureCannonBalls Hunter_Options_Ammo = 12
)

// Enum value maps for Hunter_Options_Ammo.
var (
	Hunter_Options_Ammo_name = map[int32]string{
		0:  "AmmoNone",
		1:  "RazorArrow",
		2:  "SolidShot",
		3:  "JaggedArrow",
		4:  "AccurateSlugs",
		5:  "MithrilGyroShot",
		6:  "RockshardPellets",
		7:  "IceThreadedArrow",
		8:  "ThoriumHeadedArrow",
		9:  "Doomshot",
		10: "IceThreadedBullet",
		11: "ThoriumShells",
		12: "MiniatureCannonBalls",
	}
	Hunter_Options_Ammo_value = map[string]int32{
		"AmmoNone":             0,
		"RazorArrow":           1,
		"SolidShot":            2,
		"JaggedArrow":          3,
		"AccurateSlugs":        4,
		"MithrilGyroShot":      5,
		"RockshardPellets":     6,
		"IceThreadedArrow":     7,
		"ThoriumHeadedArrow":   8,
		"Doomshot":             9,
		"IceThreadedBullet":    10,
		"ThoriumShells":        11,
		"MiniatureCannonBalls": 12,
	}
)

func (x Hunter_Options_Ammo) Enum() *Hunter_Options_Ammo {
	p := new(Hunter_Options_Ammo)
	*p = x
	return p
}

func (x Hunter_Options_Ammo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hunter_Options_Ammo) Descriptor() protoreflect.EnumDescriptor {
	return file_hunter_proto_enumTypes[2].Descriptor()
}

func (Hunter_Options_Ammo) Type() protoreflect.EnumType {
	return &file_hunter_proto_enumTypes[2]
}

func (x Hunter_Options_Ammo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hunter_Options_Ammo.Descriptor instead.
func (Hunter_Options_Ammo) EnumDescriptor() ([]byte, []int) {
	return file_hunter_proto_rawDescGZIP(), []int{1, 1, 0}
}

type Hunter_Options_QuiverBonus int32

const (
	Hunter_Options_QuiverNone Hunter_Options_QuiverBonus = 0
	Hunter_Options_Speed10    Hunter_Options_QuiverBonus = 1
	Hunter_Options_Speed11    Hunter_Options_QuiverBonus = 2
	Hunter_Options_Speed12    Hunter_Options_QuiverBonus = 3
	Hunter_Options_Speed13    Hunter_Options_QuiverBonus = 4
	Hunter_Options_Speed14    Hunter_Options_QuiverBonus = 5
	Hunter_Options_Speed15    Hunter_Options_QuiverBonus = 6
)

// Enum value maps for Hunter_Options_QuiverBonus.
var (
	Hunter_Options_QuiverBonus_name = map[int32]string{
		0: "QuiverNone",
		1: "Speed10",
		2: "Speed11",
		3: "Speed12",
		4: "Speed13",
		5: "Speed14",
		6: "Speed15",
	}
	Hunter_Options_QuiverBonus_value = map[string]int32{
		"QuiverNone": 0,
		"Speed10":    1,
		"Speed11":    2,
		"Speed12":    3,
		"Speed13":    4,
		"Speed14":    5,
		"Speed15":    6,
	}
)

func (x Hunter_Options_QuiverBonus) Enum() *Hunter_Options_QuiverBonus {
	p := new(Hunter_Options_QuiverBonus)
	*p = x
	return p
}

func (x Hunter_Options_QuiverBonus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hunter_Options_QuiverBonus) Descriptor() protoreflect.EnumDescriptor {
	return file_hunter_proto_enumTypes[3].Descriptor()
}

func (Hunter_Options_QuiverBonus) Type() protoreflect.EnumType {
	return &file_hunter_proto_enumTypes[3]
}

func (x Hunter_Options_QuiverBonus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hunter_Options_QuiverBonus.Descriptor instead.
func (Hunter_Options_QuiverBonus) EnumDescriptor() ([]byte, []int) {
	return file_hunter_proto_rawDescGZIP(), []int{1, 1, 1}
}

type Hunter_Options_PetType int32

const (
	Hunter_Options_PetNone     Hunter_Options_PetType = 0
	Hunter_Options_Cat         Hunter_Options_PetType = 1
	Hunter_Options_WindSerpent Hunter_Options_PetType = 2
	Hunter_Options_Wolf        Hunter_Options_PetType = 3
	Hunter_Options_Bat         Hunter_Options_PetType = 4
	Hunter_Options_Bear        Hunter_Options_PetType = 5
	Hunter_Options_Owl         Hunter_Options_PetType = 6
	Hunter_Options_Boar        Hunter_Options_PetType = 7
	Hunter_Options_CarrionBird Hunter_Options_PetType = 8
	Hunter_Options_Crab        Hunter_Options_PetType = 9
	Hunter_Options_Crocolisk   Hunter_Options_PetType = 10
	Hunter_Options_Gorilla     Hunter_Options_PetType = 11
	Hunter_Options_Hyena       Hunter_Options_PetType = 12
	Hunter_Options_Raptor      Hunter_Options_PetType = 13
	Hunter_Options_Scorpid     Hunter_Options_PetType = 14
	Hunter_Options_Spider      Hunter_Options_PetType = 15
	Hunter_Options_Tallstrider Hunter_Options_PetType = 16
	Hunter_Options_Turtle      Hunter_Options_PetType = 17
)

// Enum value maps for Hunter_Options_PetType.
var (
	Hunter_Options_PetType_name = map[int32]string{
		0:  "PetNone",
		1:  "Cat",
		2:  "WindSerpent",
		3:  "Wolf",
		4:  "Bat",
		5:  "Bear",
		6:  "Owl",
		7:  "Boar",
		8:  "CarrionBird",
		9:  "Crab",
		10: "Crocolisk",
		11: "Gorilla",
		12: "Hyena",
		13: "Raptor",
		14: "Scorpid",
		15: "Spider",
		16: "Tallstrider",
		17: "Turtle",
	}
	Hunter_Options_PetType_value = map[string]int32{
		"PetNone":     0,
		"Cat":         1,
		"WindSerpent": 2,
		"Wolf":        3,
		"Bat":         4,
		"Bear":        5,
		"Owl":         6,
		"Boar":        7,
		"CarrionBird": 8,
		"Crab":        9,
		"Crocolisk":   10,
		"Gorilla":     11,
		"Hyena":       12,
		"Raptor":      13,
		"Scorpid":     14,
		"Spider":      15,
		"Tallstrider": 16,
		"Turtle":      17,
	}
)

func (x Hunter_Options_PetType) Enum() *Hunter_Options_PetType {
	p := new(Hunter_Options_PetType)
	*p = x
	return p
}

func (x Hunter_Options_PetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hunter_Options_PetType) Descriptor() protoreflect.EnumDescriptor {
	return file_hunter_proto_enumTypes[4].Descriptor()
}

func (Hunter_Options_PetType) Type() protoreflect.EnumType {
	return &file_hunter_proto_enumTypes[4]
}

func (x Hunter_Options_PetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hunter_Options_PetType.Descriptor instead.
func (Hunter_Options_PetType) EnumDescriptor() ([]byte, []int) {
	return file_hunter_proto_rawDescGZIP(), []int{1, 1, 2}
}

type Hunter_Options_PetAttackSpeed int32

const (
	Hunter_Options_One      Hunter_Options_PetAttackSpeed = 0
	Hunter_Options_OneTwo   Hunter_Options_PetAttackSpeed = 1
	Hunter_Options_OneThree Hunter_Options_PetAttackSpeed = 2
	Hunter_Options_OneFour  Hunter_Options_PetAttackSpeed = 3
	Hunter_Options_OneFive  Hunter_Options_PetAttackSpeed = 4
	Hunter_Options_OneSix   Hunter_Options_PetAttackSpeed = 5
	Hunter_Options_OneSeven Hunter_Options_PetAttackSpeed = 6
	Hunter_Options_Two      Hunter_Options_PetAttackSpeed = 7
	Hunter_Options_TwoFour  Hunter_Options_PetAttackSpeed = 8
	Hunter_Options_TwoFive  Hunter_Options_PetAttackSpeed = 9
)

// Enum value maps for Hunter_Options_PetAttackSpeed.
var (
	Hunter_Options_PetAttackSpeed_name = map[int32]string{
		0: "One",
		1: "OneTwo",
		2: "OneThree",
		3: "OneFour",
		4: "OneFive",
		5: "OneSix",
		6: "OneSeven",
		7: "Two",
		8: "TwoFour",
		9: "TwoFive",
	}
	Hunter_Options_PetAttackSpeed_value = map[string]int32{
		"One":      0,
		"OneTwo":   1,
		"OneThree": 2,
		"OneFour":  3,
		"OneFive":  4,
		"OneSix":   5,
		"OneSeven": 6,
		"Two":      7,
		"TwoFour":  8,
		"TwoFive":  9,
	}
)

func (x Hunter_Options_PetAttackSpeed) Enum() *Hunter_Options_PetAttackSpeed {
	p := new(Hunter_Options_PetAttackSpeed)
	*p = x
	return p
}

func (x Hunter_Options_PetAttackSpeed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hunter_Options_PetAttackSpeed) Descriptor() protoreflect.EnumDescriptor {
	return file_hunter_proto_enumTypes[5].Descriptor()
}

func (Hunter_Options_PetAttackSpeed) Type() protoreflect.EnumType {
	return &file_hunter_proto_enumTypes[5]
}

func (x Hunter_Options_PetAttackSpeed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hunter_Options_PetAttackSpeed.Descriptor instead.
func (Hunter_Options_PetAttackSpeed) EnumDescriptor() ([]byte, []int) {
	return file_hunter_proto_rawDescGZIP(), []int{1, 1, 3}
}

type HunterTalents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Beast Mastery
	ImprovedAspectOfTheHawk   int32 `protobuf:"varint,1,opt,name=improved_aspect_of_the_hawk,json=improvedAspectOfTheHawk,proto3" json:"improved_aspect_of_the_hawk,omitempty"`
	EnduranceTraining         int32 `protobuf:"varint,2,opt,name=endurance_training,json=enduranceTraining,proto3" json:"endurance_training,omitempty"`
	ImprovedEyesOfTheBeast    int32 `protobuf:"varint,3,opt,name=improved_eyes_of_the_beast,json=improvedEyesOfTheBeast,proto3" json:"improved_eyes_of_the_beast,omitempty"`
	ImprovedAspectOfTheMonkey int32 `protobuf:"varint,4,opt,name=improved_aspect_of_the_monkey,json=improvedAspectOfTheMonkey,proto3" json:"improved_aspect_of_the_monkey,omitempty"`
	ThickHide                 int32 `protobuf:"varint,5,opt,name=thick_hide,json=thickHide,proto3" json:"thick_hide,omitempty"`
	ImprovedRevivePet         int32 `protobuf:"varint,6,opt,name=improved_revive_pet,json=improvedRevivePet,proto3" json:"improved_revive_pet,omitempty"`
	Pathfinding               int32 `protobuf:"varint,7,opt,name=pathfinding,proto3" json:"pathfinding,omitempty"`
	BestialSwiftness          bool  `protobuf:"varint,8,opt,name=bestial_swiftness,json=bestialSwiftness,proto3" json:"bestial_swiftness,omitempty"`
	UnleashedFury             int32 `protobuf:"varint,9,opt,name=unleashed_fury,json=unleashedFury,proto3" json:"unleashed_fury,omitempty"`
	ImprovedMendPet           int32 `protobuf:"varint,10,opt,name=improved_mend_pet,json=improvedMendPet,proto3" json:"improved_mend_pet,omitempty"`
	Ferocity                  int32 `protobuf:"varint,11,opt,name=ferocity,proto3" json:"ferocity,omitempty"`
	SpiritBond                int32 `protobuf:"varint,12,opt,name=spirit_bond,json=spiritBond,proto3" json:"spirit_bond,omitempty"`
	Intimidation              bool  `protobuf:"varint,13,opt,name=intimidation,proto3" json:"intimidation,omitempty"`
	BestialDiscipline         int32 `protobuf:"varint,14,opt,name=bestial_discipline,json=bestialDiscipline,proto3" json:"bestial_discipline,omitempty"`
	Frenzy                    int32 `protobuf:"varint,15,opt,name=frenzy,proto3" json:"frenzy,omitempty"`
	BestialWrath              bool  `protobuf:"varint,16,opt,name=bestial_wrath,json=bestialWrath,proto3" json:"bestial_wrath,omitempty"`
	// Marksmanship
	ImprovedConcussiveShot     int32 `protobuf:"varint,17,opt,name=improved_concussive_shot,json=improvedConcussiveShot,proto3" json:"improved_concussive_shot,omitempty"`
	Efficiency                 int32 `protobuf:"varint,18,opt,name=efficiency,proto3" json:"efficiency,omitempty"`
	ImprovedHuntersMark        int32 `protobuf:"varint,19,opt,name=improved_hunters_mark,json=improvedHuntersMark,proto3" json:"improved_hunters_mark,omitempty"`
	LethalShots                int32 `protobuf:"varint,20,opt,name=lethal_shots,json=lethalShots,proto3" json:"lethal_shots,omitempty"`
	AimedShot                  bool  `protobuf:"varint,21,opt,name=aimed_shot,json=aimedShot,proto3" json:"aimed_shot,omitempty"`
	ImprovedArcaneShot         int32 `protobuf:"varint,22,opt,name=improved_arcane_shot,json=improvedArcaneShot,proto3" json:"improved_arcane_shot,omitempty"`
	HawkEye                    int32 `protobuf:"varint,23,opt,name=hawk_eye,json=hawkEye,proto3" json:"hawk_eye,omitempty"`
	ImprovedSerpentSting       int32 `protobuf:"varint,24,opt,name=improved_serpent_sting,json=improvedSerpentSting,proto3" json:"improved_serpent_sting,omitempty"`
	MortalShots                int32 `protobuf:"varint,25,opt,name=mortal_shots,json=mortalShots,proto3" json:"mortal_shots,omitempty"`
	ScatterShot                bool  `protobuf:"varint,26,opt,name=scatter_shot,json=scatterShot,proto3" json:"scatter_shot,omitempty"`
	Barrage                    int32 `protobuf:"varint,27,opt,name=barrage,proto3" json:"barrage,omitempty"`
	ImprovedScorpidSting       int32 `protobuf:"varint,28,opt,name=improved_scorpid_sting,json=improvedScorpidSting,proto3" json:"improved_scorpid_sting,omitempty"`
	RangedWeaponSpecialization int32 `protobuf:"varint,29,opt,name=ranged_weapon_specialization,json=rangedWeaponSpecialization,proto3" json:"ranged_weapon_specialization,omitempty"`
	TrueshotAura               bool  `protobuf:"varint,30,opt,name=trueshot_aura,json=trueshotAura,proto3" json:"trueshot_aura,omitempty"`
	// Survival
	MonsterSlaying     int32 `protobuf:"varint,31,opt,name=monster_slaying,json=monsterSlaying,proto3" json:"monster_slaying,omitempty"`
	HumanoidSlaying    int32 `protobuf:"varint,32,opt,name=humanoid_slaying,json=humanoidSlaying,proto3" json:"humanoid_slaying,omitempty"`
	Deflection         int32 `protobuf:"varint,33,opt,name=deflection,proto3" json:"deflection,omitempty"`
	Entrapment         int32 `protobuf:"varint,34,opt,name=entrapment,proto3" json:"entrapment,omitempty"`
	SavageStrikes      int32 `protobuf:"varint,35,opt,name=savage_strikes,json=savageStrikes,proto3" json:"savage_strikes,omitempty"`
	ImprovedWingClip   int32 `protobuf:"varint,36,opt,name=improved_wing_clip,json=improvedWingClip,proto3" json:"improved_wing_clip,omitempty"`
	CleverTraps        int32 `protobuf:"varint,37,opt,name=clever_traps,json=cleverTraps,proto3" json:"clever_traps,omitempty"`
	Survivalist        int32 `protobuf:"varint,38,opt,name=survivalist,proto3" json:"survivalist,omitempty"`
	Deterrence         bool  `protobuf:"varint,39,opt,name=deterrence,proto3" json:"deterrence,omitempty"`
	TrapMastery        int32 `protobuf:"varint,40,opt,name=trap_mastery,json=trapMastery,proto3" json:"trap_mastery,omitempty"`
	Surefooted         int32 `protobuf:"varint,41,opt,name=surefooted,proto3" json:"surefooted,omitempty"`
	ImprovedFeignDeath int32 `protobuf:"varint,42,opt,name=improved_feign_death,json=improvedFeignDeath,proto3" json:"improved_feign_death,omitempty"`
	KillerInstinct     int32 `protobuf:"varint,43,opt,name=killer_instinct,json=killerInstinct,proto3" json:"killer_instinct,omitempty"`
	Counterattack      bool  `protobuf:"varint,44,opt,name=counterattack,proto3" json:"counterattack,omitempty"`
	LightningReflexes  int32 `protobuf:"varint,45,opt,name=lightning_reflexes,json=lightningReflexes,proto3" json:"lightning_reflexes,omitempty"`
	WyvernSting        bool  `protobuf:"varint,46,opt,name=wyvern_sting,json=wyvernSting,proto3" json:"wyvern_sting,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HunterTalents) Reset() {
	*x = HunterTalents{}
	mi := &file_hunter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HunterTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HunterTalents) ProtoMessage() {}

func (x *HunterTalents) ProtoReflect() protoreflect.Message {
	mi := &file_hunter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HunterTalents.ProtoReflect.Descriptor instead.
func (*HunterTalents) Descriptor() ([]byte, []int) {
	return file_hunter_proto_rawDescGZIP(), []int{0}
}

func (x *HunterTalents) GetImprovedAspectOfTheHawk() int32 {
	if x != nil {
		return x.ImprovedAspectOfTheHawk
	}
	return 0
}

func (x *HunterTalents) GetEnduranceTraining() int32 {
	if x != nil {
		return x.EnduranceTraining
	}
	return 0
}

func (x *HunterTalents) GetImprovedEyesOfTheBeast() int32 {
	if x != nil {
		return x.ImprovedEyesOfTheBeast
	}
	return 0
}

func (x *HunterTalents) GetImprovedAspectOfTheMonkey() int32 {
	if x != nil {
		return x.ImprovedAspectOfTheMonkey
	}
	return 0
}

func (x *HunterTalents) GetThickHide() int32 {
	if x != nil {
		return x.ThickHide
	}
	return 0
}

func (x *HunterTalents) GetImprovedRevivePet() int32 {
	if x != nil {
		return x.ImprovedRevivePet
	}
	return 0
}

func (x *HunterTalents) GetPathfinding() int32 {
	if x != nil {
		return x.Pathfinding
	}
	return 0
}

func (x *HunterTalents) GetBestialSwiftness() bool {
	if x != nil {
		return x.BestialSwiftness
	}
	return false
}

func (x *HunterTalents) GetUnleashedFury() int32 {
	if x != nil {
		return x.UnleashedFury
	}
	return 0
}

func (x *HunterTalents) GetImprovedMendPet() int32 {
	if x != nil {
		return x.ImprovedMendPet
	}
	return 0
}

func (x *HunterTalents) GetFerocity() int32 {
	if x != nil {
		return x.Ferocity
	}
	return 0
}

func (x *HunterTalents) GetSpiritBond() int32 {
	if x != nil {
		return x.SpiritBond
	}
	return 0
}

func (x *HunterTalents) GetIntimidation() bool {
	if x != nil {
		return x.Intimidation
	}
	return false
}

func (x *HunterTalents) GetBestialDiscipline() int32 {
	if x != nil {
		return x.BestialDiscipline
	}
	return 0
}

func (x *HunterTalents) GetFrenzy() int32 {
	if x != nil {
		return x.Frenzy
	}
	return 0
}

func (x *HunterTalents) GetBestialWrath() bool {
	if x != nil {
		return x.BestialWrath
	}
	return false
}

func (x *HunterTalents) GetImprovedConcussiveShot() int32 {
	if x != nil {
		return x.ImprovedConcussiveShot
	}
	return 0
}

func (x *HunterTalents) GetEfficiency() int32 {
	if x != nil {
		return x.Efficiency
	}
	return 0
}

func (x *HunterTalents) GetImprovedHuntersMark() int32 {
	if x != nil {
		return x.ImprovedHuntersMark
	}
	return 0
}

func (x *HunterTalents) GetLethalShots() int32 {
	if x != nil {
		return x.LethalShots
	}
	return 0
}

func (x *HunterTalents) GetAimedShot() bool {
	if x != nil {
		return x.AimedShot
	}
	return false
}

func (x *HunterTalents) GetImprovedArcaneShot() int32 {
	if x != nil {
		return x.ImprovedArcaneShot
	}
	return 0
}

func (x *HunterTalents) GetHawkEye() int32 {
	if x != nil {
		return x.HawkEye
	}
	return 0
}

func (x *HunterTalents) GetImprovedSerpentSting() int32 {
	if x != nil {
		return x.ImprovedSerpentSting
	}
	return 0
}

func (x *HunterTalents) GetMortalShots() int32 {
	if x != nil {
		return x.MortalShots
	}
	return 0
}

func (x *HunterTalents) GetScatterShot() bool {
	if x != nil {
		return x.ScatterShot
	}
	return false
}

func (x *HunterTalents) GetBarrage() int32 {
	if x != nil {
		return x.Barrage
	}
	return 0
}

func (x *HunterTalents) GetImprovedScorpidSting() int32 {
	if x != nil {
		return x.ImprovedScorpidSting
	}
	return 0
}

func (x *HunterTalents) GetRangedWeaponSpecialization() int32 {
	if x != nil {
		return x.RangedWeaponSpecialization
	}
	return 0
}

func (x *HunterTalents) GetTrueshotAura() bool {
	if x != nil {
		return x.TrueshotAura
	}
	return false
}

func (x *HunterTalents) GetMonsterSlaying() int32 {
	if x != nil {
		return x.MonsterSlaying
	}
	return 0
}

func (x *HunterTalents) GetHumanoidSlaying() int32 {
	if x != nil {
		return x.HumanoidSlaying
	}
	return 0
}

func (x *HunterTalents) GetDeflection() int32 {
	if x != nil {
		return x.Deflection
	}
	return 0
}

func (x *HunterTalents) GetEntrapment() int32 {
	if x != nil {
		return x.Entrapment
	}
	return 0
}

func (x *HunterTalents) GetSavageStrikes() int32 {
	if x != nil {
		return x.SavageStrikes
	}
	return 0
}

func (x *HunterTalents) GetImprovedWingClip() int32 {
	if x != nil {
		return x.ImprovedWingClip
	}
	return 0
}

func (x *HunterTalents) GetCleverTraps() int32 {
	if x != nil {
		return x.CleverTraps
	}
	return 0
}

func (x *HunterTalents) GetSurvivalist() int32 {
	if x != nil {
		return x.Survivalist
	}
	return 0
}

func (x *HunterTalents) GetDeterrence() bool {
	if x != nil {
		return x.Deterrence
	}
	return false
}

func (x *HunterTalents) GetTrapMastery() int32 {
	if x != nil {
		return x.TrapMastery
	}
	return 0
}

func (x *HunterTalents) GetSurefooted() int32 {
	if x != nil {
		return x.Surefooted
	}
	return 0
}

func (x *HunterTalents) GetImprovedFeignDeath() int32 {
	if x != nil {
		return x.ImprovedFeignDeath
	}
	return 0
}

func (x *HunterTalents) GetKillerInstinct() int32 {
	if x != nil {
		return x.KillerInstinct
	}
	return 0
}

func (x *HunterTalents) GetCounterattack() bool {
	if x != nil {
		return x.Counterattack
	}
	return false
}

func (x *HunterTalents) GetLightningReflexes() int32 {
	if x != nil {
		return x.LightningReflexes
	}
	return 0
}

func (x *HunterTalents) GetWyvernSting() bool {
	if x != nil {
		return x.WyvernSting
	}
	return false
}

type Hunter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *Hunter_Options        `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hunter) Reset() {
	*x = Hunter{}
	mi := &file_hunter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hunter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hunter) ProtoMessage() {}

func (x *Hunter) ProtoReflect() protoreflect.Message {
	mi := &file_hunter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hunter.ProtoReflect.Descriptor instead.
func (*Hunter) Descriptor() ([]byte, []int) {
	return file_hunter_proto_rawDescGZIP(), []int{1}
}

func (x *Hunter) GetOptions() *Hunter_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Hunter_Rotation struct {
	state                protoimpl.MessageState       `protogen:"open.v1"`
	Type                 Hunter_Rotation_RotationType `protobuf:"varint,9,opt,name=type,proto3,enum=proto.Hunter_Rotation_RotationType" json:"type,omitempty"`
	Sting                Hunter_Rotation_StingType    `protobuf:"varint,2,opt,name=sting,proto3,enum=proto.Hunter_Rotation_StingType" json:"sting,omitempty"`
	MultiDotSerpentSting bool                         `protobuf:"varint,3,opt,name=multi_dot_serpent_sting,json=multiDotSerpentSting,proto3" json:"multi_dot_serpent_sting,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Hunter_Rotation) Reset() {
	*x = Hunter_Rotation{}
	mi := &file_hunter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hunter_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hunter_Rotation) ProtoMessage() {}

func (x *Hunter_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_hunter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hunter_Rotation.ProtoReflect.Descriptor instead.
func (*Hunter_Rotation) Descriptor() ([]byte, []int) {
	return file_hunter_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Hunter_Rotation) GetType() Hunter_Rotation_RotationType {
	if x != nil {
		return x.Type
	}
	return Hunter_Rotation_UnknownType
}

func (x *Hunter_Rotation) GetSting() Hunter_Rotation_StingType {
	if x != nil {
		return x.Sting
	}
	return Hunter_Rotation_NoSting
}

func (x *Hunter_Rotation) GetMultiDotSerpentSting() bool {
	if x != nil {
		return x.MultiDotSerpentSting
	}
	return false
}

type Hunter_Options struct {
	state             protoimpl.MessageState        `protogen:"open.v1"`
	Ammo              Hunter_Options_Ammo           `protobuf:"varint,1,opt,name=ammo,proto3,enum=proto.Hunter_Options_Ammo" json:"ammo,omitempty"`
	QuiverBonus       Hunter_Options_QuiverBonus    `protobuf:"varint,2,opt,name=quiver_bonus,json=quiverBonus,proto3,enum=proto.Hunter_Options_QuiverBonus" json:"quiver_bonus,omitempty"`
	PetType           Hunter_Options_PetType        `protobuf:"varint,3,opt,name=pet_type,json=petType,proto3,enum=proto.Hunter_Options_PetType" json:"pet_type,omitempty"`
	PetUptime         float64                       `protobuf:"fixed64,4,opt,name=pet_uptime,json=petUptime,proto3" json:"pet_uptime,omitempty"`
	PetAttackSpeedOld float64                       `protobuf:"fixed64,5,opt,name=pet_attack_speed_old,json=petAttackSpeedOld,proto3" json:"pet_attack_speed_old,omitempty"`
	NewRaptorStrike   bool                          `protobuf:"varint,6,opt,name=new_raptor_strike,json=newRaptorStrike,proto3" json:"new_raptor_strike,omitempty"`
	PetAttackSpeed    Hunter_Options_PetAttackSpeed `protobuf:"varint,7,opt,name=pet_attack_speed,json=petAttackSpeed,proto3,enum=proto.Hunter_Options_PetAttackSpeed" json:"pet_attack_speed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Hunter_Options) Reset() {
	*x = Hunter_Options{}
	mi := &file_hunter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hunter_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hunter_Options) ProtoMessage() {}

func (x *Hunter_Options) ProtoReflect() protoreflect.Message {
	mi := &file_hunter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hunter_Options.ProtoReflect.Descriptor instead.
func (*Hunter_Options) Descriptor() ([]byte, []int) {
	return file_hunter_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Hunter_Options) GetAmmo() Hunter_Options_Ammo {
	if x != nil {
		return x.Ammo
	}
	return Hunter_Options_AmmoNone
}

func (x *Hunter_Options) GetQuiverBonus() Hunter_Options_QuiverBonus {
	if x != nil {
		return x.QuiverBonus
	}
	return Hunter_Options_QuiverNone
}

func (x *Hunter_Options) GetPetType() Hunter_Options_PetType {
	if x != nil {
		return x.PetType
	}
	return Hunter_Options_PetNone
}

func (x *Hunter_Options) GetPetUptime() float64 {
	if x != nil {
		return x.PetUptime
	}
	return 0
}

func (x *Hunter_Options) GetPetAttackSpeedOld() float64 {
	if x != nil {
		return x.PetAttackSpeedOld
	}
	return 0
}

func (x *Hunter_Options) GetNewRaptorStrike() bool {
	if x != nil {
		return x.NewRaptorStrike
	}
	return false
}

func (x *Hunter_Options) GetPetAttackSpeed() Hunter_Options_PetAttackSpeed {
	if x != nil {
		return x.PetAttackSpeed
	}
	return Hunter_Options_One
}

var File_hunter_proto protoreflect.FileDescriptor

const file_hunter_proto_rawDesc = "" +
	"\n" +
	"\fhunter.proto\x12\x05proto\"\xec\x0e\n" +
	"\rHunterTalents\x12<\n" +
	"\x1bimproved_aspect_of_the_hawk\x18\x01 \x01(\x05R\x17improvedAspectOfTheHawk\x12-\n" +
	"\x12endurance_training\x18\x02 \x01(\x05R\x11enduranceTraining\x12:\n" +
	"\x1aimproved_eyes_of_the_beast\x18\x03 \x01(\x05R\x16improvedEyesOfTheBeast\x12@\n" +
	"\x1dimproved_aspect_of_the_monkey\x18\x04 \x01(\x05R\x19improvedAspectOfTheMonkey\x12\x1d\n" +
	"\n" +
	"thick_hide\x18\x05 \x01(\x05R\tthickHide\x12.\n" +
	"\x13improved_revive_pet\x18\x06 \x01(\x05R\x11improvedRevivePet\x12 \n" +
	"\vpathfinding\x18\a \x01(\x05R\vpathfinding\x12+\n" +
	"\x11bestial_swiftness\x18\b \x01(\bR\x10bestialSwiftness\x12%\n" +
	"\x0eunleashed_fury\x18\t \x01(\x05R\runleashedFury\x12*\n" +
	"\x11improved_mend_pet\x18\n" +
	" \x01(\x05R\x0fimprovedMendPet\x12\x1a\n" +
	"\bferocity\x18\v \x01(\x05R\bferocity\x12\x1f\n" +
	"\vspirit_bond\x18\f \x01(\x05R\n" +
	"spiritBond\x12\"\n" +
	"\fintimidation\x18\r \x01(\bR\fintimidation\x12-\n" +
	"\x12bestial_discipline\x18\x0e \x01(\x05R\x11bestialDiscipline\x12\x16\n" +
	"\x06frenzy\x18\x0f \x01(\x05R\x06frenzy\x12#\n" +
	"\rbestial_wrath\x18\x10 \x01(\bR\fbestialWrath\x128\n" +
	"\x18improved_concussive_shot\x18\x11 \x01(\x05R\x16improvedConcussiveShot\x12\x1e\n" +
	"\n" +
	"efficiency\x18\x12 \x01(\x05R\n" +
	"efficiency\x122\n" +
	"\x15improved_hunters_mark\x18\x13 \x01(\x05R\x13improvedHuntersMark\x12!\n" +
	"\flethal_shots\x18\x14 \x01(\x05R\vlethalShots\x12\x1d\n" +
	"\n" +
	"aimed_shot\x18\x15 \x01(\bR\taimedShot\x120\n" +
	"\x14improved_arcane_shot\x18\x16 \x01(\x05R\x12improvedArcaneShot\x12\x19\n" +
	"\bhawk_eye\x18\x17 \x01(\x05R\ahawkEye\x124\n" +
	"\x16improved_serpent_sting\x18\x18 \x01(\x05R\x14improvedSerpentSting\x12!\n" +
	"\fmortal_shots\x18\x19 \x01(\x05R\vmortalShots\x12!\n" +
	"\fscatter_shot\x18\x1a \x01(\bR\vscatterShot\x12\x18\n" +
	"\abarrage\x18\x1b \x01(\x05R\abarrage\x124\n" +
	"\x16improved_scorpid_sting\x18\x1c \x01(\x05R\x14improvedScorpidSting\x12@\n" +
	"\x1cranged_weapon_specialization\x18\x1d \x01(\x05R\x1arangedWeaponSpecialization\x12#\n" +
	"\rtrueshot_aura\x18\x1e \x01(\bR\ftrueshotAura\x12'\n" +
	"\x0fmonster_slaying\x18\x1f \x01(\x05R\x0emonsterSlaying\x12)\n" +
	"\x10humanoid_slaying\x18  \x01(\x05R\x0fhumanoidSlaying\x12\x1e\n" +
	"\n" +
	"deflection\x18! \x01(\x05R\n" +
	"deflection\x12\x1e\n" +
	"\n" +
	"entrapment\x18\" \x01(\x05R\n" +
	"entrapment\x12%\n" +
	"\x0esavage_strikes\x18# \x01(\x05R\rsavageStrikes\x12,\n" +
	"\x12improved_wing_clip\x18$ \x01(\x05R\x10improvedWingClip\x12!\n" +
	"\fclever_traps\x18% \x01(\x05R\vcleverTraps\x12 \n" +
	"\vsurvivalist\x18& \x01(\x05R\vsurvivalist\x12\x1e\n" +
	"\n" +
	"deterrence\x18' \x01(\bR\n" +
	"deterrence\x12!\n" +
	"\ftrap_mastery\x18( \x01(\x05R\vtrapMastery\x12\x1e\n" +
	"\n" +
	"surefooted\x18) \x01(\x05R\n" +
	"surefooted\x120\n" +
	"\x14improved_feign_death\x18* \x01(\x05R\x12improvedFeignDeath\x12'\n" +
	"\x0fkiller_instinct\x18+ \x01(\x05R\x0ekillerInstinct\x12$\n" +
	"\rcounterattack\x18, \x01(\bR\rcounterattack\x12-\n" +
	"\x12lightning_reflexes\x18- \x01(\x05R\x11lightningReflexes\x12!\n" +
	"\fwyvern_sting\x18. \x01(\bR\vwyvernSting\"\xe2\v\n" +
	"\x06Hunter\x12/\n" +
	"\aoptions\x18\x02 \x01(\v2\x15.proto.Hunter.OptionsR\aoptions\x1a\xb8\x02\n" +
	"\bRotation\x127\n" +
	"\x04type\x18\t \x01(\x0e2#.proto.Hunter.Rotation.RotationTypeR\x04type\x126\n" +
	"\x05sting\x18\x02 \x01(\x0e2 .proto.Hunter.Rotation.StingTypeR\x05sting\x125\n" +
	"\x17multi_dot_serpent_sting\x18\x03 \x01(\bR\x14multiDotSerpentSting\"F\n" +
	"\fRotationType\x12\x0f\n" +
	"\vUnknownType\x10\x00\x12\x10\n" +
	"\fSingleTarget\x10\x01\x12\a\n" +
	"\x03Aoe\x10\x03\x12\n" +
	"\n" +
	"\x06Custom\x10\x02\"<\n" +
	"\tStingType\x12\v\n" +
	"\aNoSting\x10\x00\x12\x10\n" +
	"\fScorpidSting\x10\x01\x12\x10\n" +
	"\fSerpentSting\x10\x02\x1a\xeb\b\n" +
	"\aOptions\x12.\n" +
	"\x04ammo\x18\x01 \x01(\x0e2\x1a.proto.Hunter.Options.AmmoR\x04ammo\x12D\n" +
	"\fquiver_bonus\x18\x02 \x01(\x0e2!.proto.Hunter.Options.QuiverBonusR\vquiverBonus\x128\n" +
	"\bpet_type\x18\x03 \x01(\x0e2\x1d.proto.Hunter.Options.PetTypeR\apetType\x12\x1d\n" +
	"\n" +
	"pet_uptime\x18\x04 \x01(\x01R\tpetUptime\x12/\n" +
	"\x14pet_attack_speed_old\x18\x05 \x01(\x01R\x11petAttackSpeedOld\x12*\n" +
	"\x11new_raptor_strike\x18\x06 \x01(\bR\x0fnewRaptorStrike\x12N\n" +
	"\x10pet_attack_speed\x18\a \x01(\x0e2$.proto.Hunter.Options.PetAttackSpeedR\x0epetAttackSpeed\"\x82\x02\n" +
	"\x04Ammo\x12\f\n" +
	"\bAmmoNone\x10\x00\x12\x0e\n" +
	"\n" +
	"RazorArrow\x10\x01\x12\r\n" +
	"\tSolidShot\x10\x02\x12\x0f\n" +
	"\vJaggedArrow\x10\x03\x12\x11\n" +
	"\rAccurateSlugs\x10\x04\x12\x13\n" +
	"\x0fMithrilGyroShot\x10\x05\x12\x14\n" +
	"\x10RockshardPellets\x10\x06\x12\x14\n" +
	"\x10IceThreadedArrow\x10\a\x12\x16\n" +
	"\x12ThoriumHeadedArrow\x10\b\x12\f\n" +
	"\bDoomshot\x10\t\x12\x15\n" +
	"\x11IceThreadedBullet\x10\n" +
	"\x12\x11\n" +
	"\rThoriumShells\x10\v\x12\x18\n" +
	"\x14MiniatureCannonBalls\x10\f\"k\n" +
	"\vQuiverBonus\x12\x0e\n" +
	"\n" +
	"QuiverNone\x10\x00\x12\v\n" +
	"\aSpeed10\x10\x01\x12\v\n" +
	"\aSpeed11\x10\x02\x12\v\n" +
	"\aSpeed12\x10\x03\x12\v\n" +
	"\aSpeed13\x10\x04\x12\v\n" +
	"\aSpeed14\x10\x05\x12\v\n" +
	"\aSpeed15\x10\x06\"\xe4\x01\n" +
	"\aPetType\x12\v\n" +
	"\aPetNone\x10\x00\x12\a\n" +
	"\x03Cat\x10\x01\x12\x0f\n" +
	"\vWindSerpent\x10\x02\x12\b\n" +
	"\x04Wolf\x10\x03\x12\a\n" +
	"\x03Bat\x10\x04\x12\b\n" +
	"\x04Bear\x10\x05\x12\a\n" +
	"\x03Owl\x10\x06\x12\b\n" +
	"\x04Boar\x10\a\x12\x0f\n" +
	"\vCarrionBird\x10\b\x12\b\n" +
	"\x04Crab\x10\t\x12\r\n" +
	"\tCrocolisk\x10\n" +
	"\x12\v\n" +
	"\aGorilla\x10\v\x12\t\n" +
	"\x05Hyena\x10\f\x12\n" +
	"\n" +
	"\x06Raptor\x10\r\x12\v\n" +
	"\aScorpid\x10\x0e\x12\n" +
	"\n" +
	"\x06Spider\x10\x0f\x12\x0f\n" +
	"\vTallstrider\x10\x10\x12\n" +
	"\n" +
	"\x06Turtle\x10\x11\"\x8a\x01\n" +
	"\x0ePetAttackSpeed\x12\a\n" +
	"\x03One\x10\x00\x12\n" +
	"\n" +
	"\x06OneTwo\x10\x01\x12\f\n" +
	"\bOneThree\x10\x02\x12\v\n" +
	"\aOneFour\x10\x03\x12\v\n" +
	"\aOneFive\x10\x04\x12\n" +
	"\n" +
	"\x06OneSix\x10\x05\x12\f\n" +
	"\bOneSeven\x10\x06\x12\a\n" +
	"\x03Two\x10\a\x12\v\n" +
	"\aTwoFour\x10\b\x12\v\n" +
	"\aTwoFive\x10\tB\tZ\a./protob\x06proto3"

var (
	file_hunter_proto_rawDescOnce sync.Once
	file_hunter_proto_rawDescData []byte
)

func file_hunter_proto_rawDescGZIP() []byte {
	file_hunter_proto_rawDescOnce.Do(func() {
		file_hunter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hunter_proto_rawDesc), len(file_hunter_proto_rawDesc)))
	})
	return file_hunter_proto_rawDescData
}

var file_hunter_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_hunter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hunter_proto_goTypes = []any{
	(Hunter_Rotation_RotationType)(0),  // 0: proto.Hunter.Rotation.RotationType
	(Hunter_Rotation_StingType)(0),     // 1: proto.Hunter.Rotation.StingType
	(Hunter_Options_Ammo)(0),           // 2: proto.Hunter.Options.Ammo
	(Hunter_Options_QuiverBonus)(0),    // 3: proto.Hunter.Options.QuiverBonus
	(Hunter_Options_PetType)(0),        // 4: proto.Hunter.Options.PetType
	(Hunter_Options_PetAttackSpeed)(0), // 5: proto.Hunter.Options.PetAttackSpeed
	(*HunterTalents)(nil),              // 6: proto.HunterTalents
	(*Hunter)(nil),                     // 7: proto.Hunter
	(*Hunter_Rotation)(nil),            // 8: proto.Hunter.Rotation
	(*Hunter_Options)(nil),             // 9: proto.Hunter.Options
}
var file_hunter_proto_depIdxs = []int32{
	9, // 0: proto.Hunter.options:type_name -> proto.Hunter.Options
	0, // 1: proto.Hunter.Rotation.type:type_name -> proto.Hunter.Rotation.RotationType
	1, // 2: proto.Hunter.Rotation.sting:type_name -> proto.Hunter.Rotation.StingType
	2, // 3: proto.Hunter.Options.ammo:type_name -> proto.Hunter.Options.Ammo
	3, // 4: proto.Hunter.Options.quiver_bonus:type_name -> proto.Hunter.Options.QuiverBonus
	4, // 5: proto.Hunter.Options.pet_type:type_name -> proto.Hunter.Options.PetType
	5, // 6: proto.Hunter.Options.pet_attack_speed:type_name -> proto.Hunter.Options.PetAttackSpeed
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_hunter_proto_init() }
func file_hunter_proto_init() {
	if File_hunter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hunter_proto_rawDesc), len(file_hunter_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hunter_proto_goTypes,
		DependencyIndexes: file_hunter_proto_depIdxs,
		EnumInfos:         file_hunter_proto_enumTypes,
		MessageInfos:      file_hunter_proto_msgTypes,
	}.Build()
	File_hunter_proto = out.File
	file_hunter_proto_goTypes = nil
	file_hunter_proto_depIdxs = nil
}
