// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: mage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mage_Options_ArmorType int32

const (
	Mage_Options_NoArmor     Mage_Options_ArmorType = 0
	Mage_Options_IceArmor    Mage_Options_ArmorType = 1
	Mage_Options_MageArmor   Mage_Options_ArmorType = 2
	Mage_Options_MoltenArmor Mage_Options_ArmorType = 3
)

// Enum value maps for Mage_Options_ArmorType.
var (
	Mage_Options_ArmorType_name = map[int32]string{
		0: "NoArmor",
		1: "IceArmor",
		2: "MageArmor",
		3: "MoltenArmor",
	}
	Mage_Options_ArmorType_value = map[string]int32{
		"NoArmor":     0,
		"IceArmor":    1,
		"MageArmor":   2,
		"MoltenArmor": 3,
	}
)

func (x Mage_Options_ArmorType) Enum() *Mage_Options_ArmorType {
	p := new(Mage_Options_ArmorType)
	*p = x
	return p
}

func (x Mage_Options_ArmorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mage_Options_ArmorType) Descriptor() protoreflect.EnumDescriptor {
	return file_mage_proto_enumTypes[0].Descriptor()
}

func (Mage_Options_ArmorType) Type() protoreflect.EnumType {
	return &file_mage_proto_enumTypes[0]
}

func (x Mage_Options_ArmorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mage_Options_ArmorType.Descriptor instead.
func (Mage_Options_ArmorType) EnumDescriptor() ([]byte, []int) {
	return file_mage_proto_rawDescGZIP(), []int{1, 1, 0}
}

// Code generated by tools/talentgen from client build 1.60.1.69893. DO NOT EDIT.
// Field order is the talent string's order: the three trees in the
// client's own order, each tier then column. core.FillTalentsProto
// reads it positionally, so a reorder silently reads the wrong talent.
type MageTalents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arcane (tree 0, client id 81)
	// node 105815, tier 0 col 0, 2 rank(s), spell 6057
	WandSpecialization int32 `protobuf:"varint,1,opt,name=wand_specialization,json=wandSpecialization,proto3" json:"wand_specialization,omitempty"`
	// node 105814, tier 0 col 1, 5 rank(s), spell 11222
	ArcaneFocus int32 `protobuf:"varint,2,opt,name=arcane_focus,json=arcaneFocus,proto3" json:"arcane_focus,omitempty"`
	// node 105813, tier 0 col 2, 5 rank(s), spell 11237
	ImprovedChanneling int32 `protobuf:"varint,3,opt,name=improved_channeling,json=improvedChanneling,proto3" json:"improved_channeling,omitempty"`
	// node 105812, tier 1 col 0, 2 rank(s), spell 11210
	ArcaneSubtlety int32 `protobuf:"varint,4,opt,name=arcane_subtlety,json=arcaneSubtlety,proto3" json:"arcane_subtlety,omitempty"`
	// node 105811, tier 1 col 1, 2 rank(s), spell 29441
	MagicAbsorption int32 `protobuf:"varint,5,opt,name=magic_absorption,json=magicAbsorption,proto3" json:"magic_absorption,omitempty"`
	// node 105810, tier 1 col 2, 5 rank(s), spell 11213
	ArcaneConcentration int32 `protobuf:"varint,6,opt,name=arcane_concentration,json=arcaneConcentration,proto3" json:"arcane_concentration,omitempty"`
	// node 105809, tier 1 col 3, 2 rank(s), spell 28574
	ArcaneResilience int32 `protobuf:"varint,7,opt,name=arcane_resilience,json=arcaneResilience,proto3" json:"arcane_resilience,omitempty"`
	// node 105808, tier 2 col 0, 2 rank(s), spell 11247
	ArcaneGeometry int32 `protobuf:"varint,8,opt,name=arcane_geometry,json=arcaneGeometry,proto3" json:"arcane_geometry,omitempty"`
	// node 105807, tier 2 col 1, 3 rank(s), spell 11242
	ArcaneImpact int32 `protobuf:"varint,9,opt,name=arcane_impact,json=arcaneImpact,proto3" json:"arcane_impact,omitempty"`
	// node 105806, tier 2 col 3, 1 rank(s), spell 400574
	ArcaneBlast bool `protobuf:"varint,10,opt,name=arcane_blast,json=arcaneBlast,proto3" json:"arcane_blast,omitempty"`
	// node 105805, tier 3 col 0, 2 rank(s), spell 11252
	ArcaneShielding int32 `protobuf:"varint,11,opt,name=arcane_shielding,json=arcaneShielding,proto3" json:"arcane_shielding,omitempty"`
	// node 105804, tier 3 col 1, 2 rank(s), spell 11255
	ImprovedCounterspell int32 `protobuf:"varint,12,opt,name=improved_counterspell,json=improvedCounterspell,proto3" json:"improved_counterspell,omitempty"`
	// node 105803, tier 3 col 2, 3 rank(s), spell 18462
	ArcaneMeditation int32 `protobuf:"varint,13,opt,name=arcane_meditation,json=arcaneMeditation,proto3" json:"arcane_meditation,omitempty"`
	// node 105802, tier 3 col 3, 1 rank(s), spell 400588
	MissileBarrage bool `protobuf:"varint,14,opt,name=missile_barrage,json=missileBarrage,proto3" json:"missile_barrage,omitempty"`
	// node 105801, tier 4 col 1, 1 rank(s), spell 12043
	PresenceOfMind bool `protobuf:"varint,15,opt,name=presence_of_mind,json=presenceOfMind,proto3" json:"presence_of_mind,omitempty"`
	// node 105800, tier 4 col 2, 5 rank(s), spell 11232
	ArcaneMind int32 `protobuf:"varint,16,opt,name=arcane_mind,json=arcaneMind,proto3" json:"arcane_mind,omitempty"`
	// node 105799, tier 5 col 2, 3 rank(s), spell 15058
	ArcaneInstability int32 `protobuf:"varint,17,opt,name=arcane_instability,json=arcaneInstability,proto3" json:"arcane_instability,omitempty"`
	// node 105798, tier 6 col 1, 1 rank(s), spell 12042
	ArcanePower bool `protobuf:"varint,18,opt,name=arcane_power,json=arcanePower,proto3" json:"arcane_power,omitempty"`
	// Fire (tree 1, client id 41)
	// node 105797, tier 0 col 0, 2 rank(s), spell 11078
	WakeOfFire int32 `protobuf:"varint,19,opt,name=wake_of_fire,json=wakeOfFire,proto3" json:"wake_of_fire,omitempty"`
	// node 105796, tier 0 col 1, 3 rank(s), spell 18459
	Incineration int32 `protobuf:"varint,20,opt,name=incineration,proto3" json:"incineration,omitempty"`
	// node 105795, tier 0 col 2, 5 rank(s), spell 11069
	ImprovedFireball int32 `protobuf:"varint,21,opt,name=improved_fireball,json=improvedFireball,proto3" json:"improved_fireball,omitempty"`
	// node 105794, tier 1 col 0, 5 rank(s), spell 11119
	Ignite int32 `protobuf:"varint,22,opt,name=ignite,proto3" json:"ignite,omitempty"`
	// node 105793, tier 1 col 1, 2 rank(s), spell 11100
	FlameThrowing int32 `protobuf:"varint,23,opt,name=flame_throwing,json=flameThrowing,proto3" json:"flame_throwing,omitempty"`
	// node 105792, tier 1 col 2, 3 rank(s), spell 11103
	Impact int32 `protobuf:"varint,24,opt,name=impact,proto3" json:"impact,omitempty"`
	// node 105789, tier 2 col 0, 3 rank(s), spell 11083
	BurningSoul int32 `protobuf:"varint,25,opt,name=burning_soul,json=burningSoul,proto3" json:"burning_soul,omitempty"`
	// node 105791, tier 2 col 1, 3 rank(s), spell 11108
	ImprovedFlamestrike int32 `protobuf:"varint,26,opt,name=improved_flamestrike,json=improvedFlamestrike,proto3" json:"improved_flamestrike,omitempty"`
	// node 105790, tier 2 col 2, 1 rank(s), spell 11366
	Pyroblast bool `protobuf:"varint,27,opt,name=pyroblast,proto3" json:"pyroblast,omitempty"`
	// node 105788, tier 3 col 0, 3 rank(s), spell 11095
	ImprovedScorch int32 `protobuf:"varint,28,opt,name=improved_scorch,json=improvedScorch,proto3" json:"improved_scorch,omitempty"`
	// node 105787, tier 3 col 1, 2 rank(s), spell 11094
	ImprovedFireWard int32 `protobuf:"varint,29,opt,name=improved_fire_ward,json=improvedFireWard,proto3" json:"improved_fire_ward,omitempty"`
	// node 105786, tier 3 col 2, 1 rank(s), spell 400624
	HotStreak bool `protobuf:"varint,30,opt,name=hot_streak,json=hotStreak,proto3" json:"hot_streak,omitempty"`
	// node 105785, tier 3 col 3, 3 rank(s), spell 29074
	MasterOfElements int32 `protobuf:"varint,31,opt,name=master_of_elements,json=masterOfElements,proto3" json:"master_of_elements,omitempty"`
	// node 105784, tier 4 col 1, 3 rank(s), spell 11115
	CriticalMass int32 `protobuf:"varint,32,opt,name=critical_mass,json=criticalMass,proto3" json:"critical_mass,omitempty"`
	// node 105783, tier 4 col 2, 1 rank(s), spell 11113
	BlastWave bool `protobuf:"varint,33,opt,name=blast_wave,json=blastWave,proto3" json:"blast_wave,omitempty"`
	// node 105782, tier 5 col 2, 5 rank(s), spell 11124
	FirePower int32 `protobuf:"varint,34,opt,name=fire_power,json=firePower,proto3" json:"fire_power,omitempty"`
	// node 105781, tier 6 col 1, 1 rank(s), spell 11129
	Combustion bool `protobuf:"varint,35,opt,name=combustion,proto3" json:"combustion,omitempty"`
	// Frost (tree 2, client id 61)
	// node 105780, tier 0 col 0, 2 rank(s), spell 11189
	FrostWarding int32 `protobuf:"varint,36,opt,name=frost_warding,json=frostWarding,proto3" json:"frost_warding,omitempty"`
	// node 105779, tier 0 col 1, 5 rank(s), spell 11070
	ImprovedFrostbolt int32 `protobuf:"varint,37,opt,name=improved_frostbolt,json=improvedFrostbolt,proto3" json:"improved_frostbolt,omitempty"`
	// node 105778, tier 0 col 2, 5 rank(s), spell 29438
	ElementalPrecision int32 `protobuf:"varint,38,opt,name=elemental_precision,json=elementalPrecision,proto3" json:"elemental_precision,omitempty"`
	// node 105777, tier 1 col 0, 5 rank(s), spell 11207
	IceShards int32 `protobuf:"varint,39,opt,name=ice_shards,json=iceShards,proto3" json:"ice_shards,omitempty"`
	// node 105776, tier 1 col 1, 3 rank(s), spell 11175
	Permafrost int32 `protobuf:"varint,40,opt,name=permafrost,proto3" json:"permafrost,omitempty"`
	// node 105775, tier 1 col 2, 2 rank(s), spell 11165
	ImprovedFrostNova int32 `protobuf:"varint,41,opt,name=improved_frost_nova,json=improvedFrostNova,proto3" json:"improved_frost_nova,omitempty"`
	// node 105774, tier 1 col 3, 3 rank(s), spell 11071
	Frostbite int32 `protobuf:"varint,42,opt,name=frostbite,proto3" json:"frostbite,omitempty"`
	// node 105773, tier 2 col 0, 3 rank(s), spell 11151
	PiercingIce int32 `protobuf:"varint,43,opt,name=piercing_ice,json=piercingIce,proto3" json:"piercing_ice,omitempty"`
	// node 105772, tier 2 col 1, 3 rank(s), spell 11160
	FrostChanneling int32 `protobuf:"varint,44,opt,name=frost_channeling,json=frostChanneling,proto3" json:"frost_channeling,omitempty"`
	// node 105767, tier 2 col 2, 1 rank(s), spell 1312002
	IceLance bool `protobuf:"varint,45,opt,name=ice_lance,json=iceLance,proto3" json:"ice_lance,omitempty"`
	// node 105771, tier 2 col 3, 3 rank(s), spell 11185
	ImprovedBlizzard int32 `protobuf:"varint,46,opt,name=improved_blizzard,json=improvedBlizzard,proto3" json:"improved_blizzard,omitempty"`
	// node 105770, tier 3 col 0, 2 rank(s), spell 16757
	ArcticReach int32 `protobuf:"varint,47,opt,name=arctic_reach,json=arcticReach,proto3" json:"arctic_reach,omitempty"`
	// node 105769, tier 3 col 1, 1 rank(s), spell 11958
	IceBlock bool `protobuf:"varint,48,opt,name=ice_block,json=iceBlock,proto3" json:"ice_block,omitempty"`
	// node 105768, tier 3 col 3, 3 rank(s), spell 11170
	Shatter int32 `protobuf:"varint,49,opt,name=shatter,proto3" json:"shatter,omitempty"`
	// node 105765, tier 4 col 0, 3 rank(s), spell 11190
	ImprovedConeOfCold int32 `protobuf:"varint,50,opt,name=improved_cone_of_cold,json=improvedConeOfCold,proto3" json:"improved_cone_of_cold,omitempty"`
	// node 105766, tier 4 col 1, 1 rank(s), spell 12472
	ColdSnap bool `protobuf:"varint,51,opt,name=cold_snap,json=coldSnap,proto3" json:"cold_snap,omitempty"`
	// node 105764, tier 4 col 2, 2 rank(s), spell 400647
	FingersOfFrost int32 `protobuf:"varint,52,opt,name=fingers_of_frost,json=fingersOfFrost,proto3" json:"fingers_of_frost,omitempty"`
	// node 105763, tier 5 col 2, 5 rank(s), spell 11180
	WintersChill int32 `protobuf:"varint,53,opt,name=winters_chill,json=wintersChill,proto3" json:"winters_chill,omitempty"`
	// node 105762, tier 6 col 1, 1 rank(s), spell 11426
	IceBarrier    bool `protobuf:"varint,54,opt,name=ice_barrier,json=iceBarrier,proto3" json:"ice_barrier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MageTalents) Reset() {
	*x = MageTalents{}
	mi := &file_mage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MageTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MageTalents) ProtoMessage() {}

func (x *MageTalents) ProtoReflect() protoreflect.Message {
	mi := &file_mage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MageTalents.ProtoReflect.Descriptor instead.
func (*MageTalents) Descriptor() ([]byte, []int) {
	return file_mage_proto_rawDescGZIP(), []int{0}
}

func (x *MageTalents) GetWandSpecialization() int32 {
	if x != nil {
		return x.WandSpecialization
	}
	return 0
}

func (x *MageTalents) GetArcaneFocus() int32 {
	if x != nil {
		return x.ArcaneFocus
	}
	return 0
}

func (x *MageTalents) GetImprovedChanneling() int32 {
	if x != nil {
		return x.ImprovedChanneling
	}
	return 0
}

func (x *MageTalents) GetArcaneSubtlety() int32 {
	if x != nil {
		return x.ArcaneSubtlety
	}
	return 0
}

func (x *MageTalents) GetMagicAbsorption() int32 {
	if x != nil {
		return x.MagicAbsorption
	}
	return 0
}

func (x *MageTalents) GetArcaneConcentration() int32 {
	if x != nil {
		return x.ArcaneConcentration
	}
	return 0
}

func (x *MageTalents) GetArcaneResilience() int32 {
	if x != nil {
		return x.ArcaneResilience
	}
	return 0
}

func (x *MageTalents) GetArcaneGeometry() int32 {
	if x != nil {
		return x.ArcaneGeometry
	}
	return 0
}

func (x *MageTalents) GetArcaneImpact() int32 {
	if x != nil {
		return x.ArcaneImpact
	}
	return 0
}

func (x *MageTalents) GetArcaneBlast() bool {
	if x != nil {
		return x.ArcaneBlast
	}
	return false
}

func (x *MageTalents) GetArcaneShielding() int32 {
	if x != nil {
		return x.ArcaneShielding
	}
	return 0
}

func (x *MageTalents) GetImprovedCounterspell() int32 {
	if x != nil {
		return x.ImprovedCounterspell
	}
	return 0
}

func (x *MageTalents) GetArcaneMeditation() int32 {
	if x != nil {
		return x.ArcaneMeditation
	}
	return 0
}

func (x *MageTalents) GetMissileBarrage() bool {
	if x != nil {
		return x.MissileBarrage
	}
	return false
}

func (x *MageTalents) GetPresenceOfMind() bool {
	if x != nil {
		return x.PresenceOfMind
	}
	return false
}

func (x *MageTalents) GetArcaneMind() int32 {
	if x != nil {
		return x.ArcaneMind
	}
	return 0
}

func (x *MageTalents) GetArcaneInstability() int32 {
	if x != nil {
		return x.ArcaneInstability
	}
	return 0
}

func (x *MageTalents) GetArcanePower() bool {
	if x != nil {
		return x.ArcanePower
	}
	return false
}

func (x *MageTalents) GetWakeOfFire() int32 {
	if x != nil {
		return x.WakeOfFire
	}
	return 0
}

func (x *MageTalents) GetIncineration() int32 {
	if x != nil {
		return x.Incineration
	}
	return 0
}

func (x *MageTalents) GetImprovedFireball() int32 {
	if x != nil {
		return x.ImprovedFireball
	}
	return 0
}

func (x *MageTalents) GetIgnite() int32 {
	if x != nil {
		return x.Ignite
	}
	return 0
}

func (x *MageTalents) GetFlameThrowing() int32 {
	if x != nil {
		return x.FlameThrowing
	}
	return 0
}

func (x *MageTalents) GetImpact() int32 {
	if x != nil {
		return x.Impact
	}
	return 0
}

func (x *MageTalents) GetBurningSoul() int32 {
	if x != nil {
		return x.BurningSoul
	}
	return 0
}

func (x *MageTalents) GetImprovedFlamestrike() int32 {
	if x != nil {
		return x.ImprovedFlamestrike
	}
	return 0
}

func (x *MageTalents) GetPyroblast() bool {
	if x != nil {
		return x.Pyroblast
	}
	return false
}

func (x *MageTalents) GetImprovedScorch() int32 {
	if x != nil {
		return x.ImprovedScorch
	}
	return 0
}

func (x *MageTalents) GetImprovedFireWard() int32 {
	if x != nil {
		return x.ImprovedFireWard
	}
	return 0
}

func (x *MageTalents) GetHotStreak() bool {
	if x != nil {
		return x.HotStreak
	}
	return false
}

func (x *MageTalents) GetMasterOfElements() int32 {
	if x != nil {
		return x.MasterOfElements
	}
	return 0
}

func (x *MageTalents) GetCriticalMass() int32 {
	if x != nil {
		return x.CriticalMass
	}
	return 0
}

func (x *MageTalents) GetBlastWave() bool {
	if x != nil {
		return x.BlastWave
	}
	return false
}

func (x *MageTalents) GetFirePower() int32 {
	if x != nil {
		return x.FirePower
	}
	return 0
}

func (x *MageTalents) GetCombustion() bool {
	if x != nil {
		return x.Combustion
	}
	return false
}

func (x *MageTalents) GetFrostWarding() int32 {
	if x != nil {
		return x.FrostWarding
	}
	return 0
}

func (x *MageTalents) GetImprovedFrostbolt() int32 {
	if x != nil {
		return x.ImprovedFrostbolt
	}
	return 0
}

func (x *MageTalents) GetElementalPrecision() int32 {
	if x != nil {
		return x.ElementalPrecision
	}
	return 0
}

func (x *MageTalents) GetIceShards() int32 {
	if x != nil {
		return x.IceShards
	}
	return 0
}

func (x *MageTalents) GetPermafrost() int32 {
	if x != nil {
		return x.Permafrost
	}
	return 0
}

func (x *MageTalents) GetImprovedFrostNova() int32 {
	if x != nil {
		return x.ImprovedFrostNova
	}
	return 0
}

func (x *MageTalents) GetFrostbite() int32 {
	if x != nil {
		return x.Frostbite
	}
	return 0
}

func (x *MageTalents) GetPiercingIce() int32 {
	if x != nil {
		return x.PiercingIce
	}
	return 0
}

func (x *MageTalents) GetFrostChanneling() int32 {
	if x != nil {
		return x.FrostChanneling
	}
	return 0
}

func (x *MageTalents) GetIceLance() bool {
	if x != nil {
		return x.IceLance
	}
	return false
}

func (x *MageTalents) GetImprovedBlizzard() int32 {
	if x != nil {
		return x.ImprovedBlizzard
	}
	return 0
}

func (x *MageTalents) GetArcticReach() int32 {
	if x != nil {
		return x.ArcticReach
	}
	return 0
}

func (x *MageTalents) GetIceBlock() bool {
	if x != nil {
		return x.IceBlock
	}
	return false
}

func (x *MageTalents) GetShatter() int32 {
	if x != nil {
		return x.Shatter
	}
	return 0
}

func (x *MageTalents) GetImprovedConeOfCold() int32 {
	if x != nil {
		return x.ImprovedConeOfCold
	}
	return 0
}

func (x *MageTalents) GetColdSnap() bool {
	if x != nil {
		return x.ColdSnap
	}
	return false
}

func (x *MageTalents) GetFingersOfFrost() int32 {
	if x != nil {
		return x.FingersOfFrost
	}
	return 0
}

func (x *MageTalents) GetWintersChill() int32 {
	if x != nil {
		return x.WintersChill
	}
	return 0
}

func (x *MageTalents) GetIceBarrier() bool {
	if x != nil {
		return x.IceBarrier
	}
	return false
}

type Mage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *Mage_Options          `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mage) Reset() {
	*x = Mage{}
	mi := &file_mage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mage) ProtoMessage() {}

func (x *Mage) ProtoReflect() protoreflect.Message {
	mi := &file_mage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mage.ProtoReflect.Descriptor instead.
func (*Mage) Descriptor() ([]byte, []int) {
	return file_mage_proto_rawDescGZIP(), []int{1}
}

func (x *Mage) GetOptions() *Mage_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Mage_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mage_Rotation) Reset() {
	*x = Mage_Rotation{}
	mi := &file_mage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mage_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mage_Rotation) ProtoMessage() {}

func (x *Mage_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_mage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mage_Rotation.ProtoReflect.Descriptor instead.
func (*Mage_Rotation) Descriptor() ([]byte, []int) {
	return file_mage_proto_rawDescGZIP(), []int{1, 0}
}

type Mage_Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Armor         Mage_Options_ArmorType `protobuf:"varint,1,opt,name=armor,proto3,enum=proto.Mage_Options_ArmorType" json:"armor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mage_Options) Reset() {
	*x = Mage_Options{}
	mi := &file_mage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mage_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mage_Options) ProtoMessage() {}

func (x *Mage_Options) ProtoReflect() protoreflect.Message {
	mi := &file_mage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mage_Options.ProtoReflect.Descriptor instead.
func (*Mage_Options) Descriptor() ([]byte, []int) {
	return file_mage_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Mage_Options) GetArmor() Mage_Options_ArmorType {
	if x != nil {
		return x.Armor
	}
	return Mage_Options_NoArmor
}

var File_mage_proto protoreflect.FileDescriptor

const file_mage_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mage.proto\x12\x05proto\"\xb3\x10\n" +
	"\vMageTalents\x12/\n" +
	"\x13wand_specialization\x18\x01 \x01(\x05R\x12wandSpecialization\x12!\n" +
	"\farcane_focus\x18\x02 \x01(\x05R\varcaneFocus\x12/\n" +
	"\x13improved_channeling\x18\x03 \x01(\x05R\x12improvedChanneling\x12'\n" +
	"\x0farcane_subtlety\x18\x04 \x01(\x05R\x0earcaneSubtlety\x12)\n" +
	"\x10magic_absorption\x18\x05 \x01(\x05R\x0fmagicAbsorption\x121\n" +
	"\x14arcane_concentration\x18\x06 \x01(\x05R\x13arcaneConcentration\x12+\n" +
	"\x11arcane_resilience\x18\a \x01(\x05R\x10arcaneResilience\x12'\n" +
	"\x0farcane_geometry\x18\b \x01(\x05R\x0earcaneGeometry\x12#\n" +
	"\rarcane_impact\x18\t \x01(\x05R\farcaneImpact\x12!\n" +
	"\farcane_blast\x18\n" +
	" \x01(\bR\varcaneBlast\x12)\n" +
	"\x10arcane_shielding\x18\v \x01(\x05R\x0farcaneShielding\x123\n" +
	"\x15improved_counterspell\x18\f \x01(\x05R\x14improvedCounterspell\x12+\n" +
	"\x11arcane_meditation\x18\r \x01(\x05R\x10arcaneMeditation\x12'\n" +
	"\x0fmissile_barrage\x18\x0e \x01(\bR\x0emissileBarrage\x12(\n" +
	"\x10presence_of_mind\x18\x0f \x01(\bR\x0epresenceOfMind\x12\x1f\n" +
	"\varcane_mind\x18\x10 \x01(\x05R\n" +
	"arcaneMind\x12-\n" +
	"\x12arcane_instability\x18\x11 \x01(\x05R\x11arcaneInstability\x12!\n" +
	"\farcane_power\x18\x12 \x01(\bR\varcanePower\x12 \n" +
	"\fwake_of_fire\x18\x13 \x01(\x05R\n" +
	"wakeOfFire\x12\"\n" +
	"\fincineration\x18\x14 \x01(\x05R\fincineration\x12+\n" +
	"\x11improved_fireball\x18\x15 \x01(\x05R\x10improvedFireball\x12\x16\n" +
	"\x06ignite\x18\x16 \x01(\x05R\x06ignite\x12%\n" +
	"\x0eflame_throwing\x18\x17 \x01(\x05R\rflameThrowing\x12\x16\n" +
	"\x06impact\x18\x18 \x01(\x05R\x06impact\x12!\n" +
	"\fburning_soul\x18\x19 \x01(\x05R\vburningSoul\x121\n" +
	"\x14improved_flamestrike\x18\x1a \x01(\x05R\x13improvedFlamestrike\x12\x1c\n" +
	"\tpyroblast\x18\x1b \x01(\bR\tpyroblast\x12'\n" +
	"\x0fimproved_scorch\x18\x1c \x01(\x05R\x0eimprovedScorch\x12,\n" +
	"\x12improved_fire_ward\x18\x1d \x01(\x05R\x10improvedFireWard\x12\x1d\n" +
	"\n" +
	"hot_streak\x18\x1e \x01(\bR\thotStreak\x12,\n" +
	"\x12master_of_elements\x18\x1f \x01(\x05R\x10masterOfElements\x12#\n" +
	"\rcritical_mass\x18  \x01(\x05R\fcriticalMass\x12\x1d\n" +
	"\n" +
	"blast_wave\x18! \x01(\bR\tblastWave\x12\x1d\n" +
	"\n" +
	"fire_power\x18\" \x01(\x05R\tfirePower\x12\x1e\n" +
	"\n" +
	"combustion\x18# \x01(\bR\n" +
	"combustion\x12#\n" +
	"\rfrost_warding\x18$ \x01(\x05R\ffrostWarding\x12-\n" +
	"\x12improved_frostbolt\x18% \x01(\x05R\x11improvedFrostbolt\x12/\n" +
	"\x13elemental_precision\x18& \x01(\x05R\x12elementalPrecision\x12\x1d\n" +
	"\n" +
	"ice_shards\x18' \x01(\x05R\ticeShards\x12\x1e\n" +
	"\n" +
	"permafrost\x18( \x01(\x05R\n" +
	"permafrost\x12.\n" +
	"\x13improved_frost_nova\x18) \x01(\x05R\x11improvedFrostNova\x12\x1c\n" +
	"\tfrostbite\x18* \x01(\x05R\tfrostbite\x12!\n" +
	"\fpiercing_ice\x18+ \x01(\x05R\vpiercingIce\x12)\n" +
	"\x10frost_channeling\x18, \x01(\x05R\x0ffrostChanneling\x12\x1b\n" +
	"\tice_lance\x18- \x01(\bR\biceLance\x12+\n" +
	"\x11improved_blizzard\x18. \x01(\x05R\x10improvedBlizzard\x12!\n" +
	"\farctic_reach\x18/ \x01(\x05R\varcticReach\x12\x1b\n" +
	"\tice_block\x180 \x01(\bR\biceBlock\x12\x18\n" +
	"\ashatter\x181 \x01(\x05R\ashatter\x121\n" +
	"\x15improved_cone_of_cold\x182 \x01(\x05R\x12improvedConeOfCold\x12\x1b\n" +
	"\tcold_snap\x183 \x01(\bR\bcoldSnap\x12(\n" +
	"\x10fingers_of_frost\x184 \x01(\x05R\x0efingersOfFrost\x12#\n" +
	"\rwinters_chill\x185 \x01(\x05R\fwintersChill\x12\x1f\n" +
	"\vice_barrier\x186 \x01(\bR\n" +
	"iceBarrier\"\xca\x01\n" +
	"\x04Mage\x12-\n" +
	"\aoptions\x18\x03 \x01(\v2\x13.proto.Mage.OptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\x1a\x86\x01\n" +
	"\aOptions\x123\n" +
	"\x05armor\x18\x01 \x01(\x0e2\x1d.proto.Mage.Options.ArmorTypeR\x05armor\"F\n" +
	"\tArmorType\x12\v\n" +
	"\aNoArmor\x10\x00\x12\f\n" +
	"\bIceArmor\x10\x01\x12\r\n" +
	"\tMageArmor\x10\x02\x12\x0f\n" +
	"\vMoltenArmor\x10\x03B\tZ\a./protob\x06proto3"

var (
	file_mage_proto_rawDescOnce sync.Once
	file_mage_proto_rawDescData []byte
)

func file_mage_proto_rawDescGZIP() []byte {
	file_mage_proto_rawDescOnce.Do(func() {
		file_mage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_proto_rawDesc), len(file_mage_proto_rawDesc)))
	})
	return file_mage_proto_rawDescData
}

var file_mage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mage_proto_goTypes = []any{
	(Mage_Options_ArmorType)(0), // 0: proto.Mage.Options.ArmorType
	(*MageTalents)(nil),         // 1: proto.MageTalents
	(*Mage)(nil),                // 2: proto.Mage
	(*Mage_Rotation)(nil),       // 3: proto.Mage.Rotation
	(*Mage_Options)(nil),        // 4: proto.Mage.Options
}
var file_mage_proto_depIdxs = []int32{
	4, // 0: proto.Mage.options:type_name -> proto.Mage.Options
	0, // 1: proto.Mage.Options.armor:type_name -> proto.Mage.Options.ArmorType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mage_proto_init() }
func file_mage_proto_init() {
	if File_mage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_proto_rawDesc), len(file_mage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_proto_goTypes,
		DependencyIndexes: file_mage_proto_depIdxs,
		EnumInfos:         file_mage_proto_enumTypes,
		MessageInfos:      file_mage_proto_msgTypes,
	}.Build()
	File_mage_proto = out.File
	file_mage_proto_goTypes = nil
	file_mage_proto_depIdxs = nil
}
