// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: mage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mage_Options_ArmorType int32

const (
	Mage_Options_NoArmor     Mage_Options_ArmorType = 0
	Mage_Options_IceArmor    Mage_Options_ArmorType = 1
	Mage_Options_MageArmor   Mage_Options_ArmorType = 2
	Mage_Options_MoltenArmor Mage_Options_ArmorType = 3
)

// Enum value maps for Mage_Options_ArmorType.
var (
	Mage_Options_ArmorType_name = map[int32]string{
		0: "NoArmor",
		1: "IceArmor",
		2: "MageArmor",
		3: "MoltenArmor",
	}
	Mage_Options_ArmorType_value = map[string]int32{
		"NoArmor":     0,
		"IceArmor":    1,
		"MageArmor":   2,
		"MoltenArmor": 3,
	}
)

func (x Mage_Options_ArmorType) Enum() *Mage_Options_ArmorType {
	p := new(Mage_Options_ArmorType)
	*p = x
	return p
}

func (x Mage_Options_ArmorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mage_Options_ArmorType) Descriptor() protoreflect.EnumDescriptor {
	return file_mage_proto_enumTypes[0].Descriptor()
}

func (Mage_Options_ArmorType) Type() protoreflect.EnumType {
	return &file_mage_proto_enumTypes[0]
}

func (x Mage_Options_ArmorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mage_Options_ArmorType.Descriptor instead.
func (Mage_Options_ArmorType) EnumDescriptor() ([]byte, []int) {
	return file_mage_proto_rawDescGZIP(), []int{1, 1, 0}
}

type MageTalents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arcane
	ArcaneSubtlety          int32 `protobuf:"varint,1,opt,name=arcane_subtlety,json=arcaneSubtlety,proto3" json:"arcane_subtlety,omitempty"`
	ArcaneFocus             int32 `protobuf:"varint,2,opt,name=arcane_focus,json=arcaneFocus,proto3" json:"arcane_focus,omitempty"`
	ImprovedArcaneMissiles  int32 `protobuf:"varint,3,opt,name=improved_arcane_missiles,json=improvedArcaneMissiles,proto3" json:"improved_arcane_missiles,omitempty"`
	WandSpecialization      int32 `protobuf:"varint,4,opt,name=wand_specialization,json=wandSpecialization,proto3" json:"wand_specialization,omitempty"`
	MagicAbsorption         int32 `protobuf:"varint,5,opt,name=magic_absorption,json=magicAbsorption,proto3" json:"magic_absorption,omitempty"`
	ArcaneConcentration     int32 `protobuf:"varint,6,opt,name=arcane_concentration,json=arcaneConcentration,proto3" json:"arcane_concentration,omitempty"`
	MagicAttunement         int32 `protobuf:"varint,7,opt,name=magic_attunement,json=magicAttunement,proto3" json:"magic_attunement,omitempty"`
	ImprovedArcaneExplosion int32 `protobuf:"varint,8,opt,name=improved_arcane_explosion,json=improvedArcaneExplosion,proto3" json:"improved_arcane_explosion,omitempty"`
	ArcaneResilience        bool  `protobuf:"varint,9,opt,name=arcane_resilience,json=arcaneResilience,proto3" json:"arcane_resilience,omitempty"`
	ImprovedManaShield      int32 `protobuf:"varint,10,opt,name=improved_mana_shield,json=improvedManaShield,proto3" json:"improved_mana_shield,omitempty"`
	ImprovedCounterspell    int32 `protobuf:"varint,11,opt,name=improved_counterspell,json=improvedCounterspell,proto3" json:"improved_counterspell,omitempty"`
	ArcaneMeditation        int32 `protobuf:"varint,12,opt,name=arcane_meditation,json=arcaneMeditation,proto3" json:"arcane_meditation,omitempty"`
	PresenceOfMind          bool  `protobuf:"varint,13,opt,name=presence_of_mind,json=presenceOfMind,proto3" json:"presence_of_mind,omitempty"`
	ArcaneMind              int32 `protobuf:"varint,14,opt,name=arcane_mind,json=arcaneMind,proto3" json:"arcane_mind,omitempty"`
	ArcaneInstability       int32 `protobuf:"varint,15,opt,name=arcane_instability,json=arcaneInstability,proto3" json:"arcane_instability,omitempty"`
	ArcanePower             bool  `protobuf:"varint,16,opt,name=arcane_power,json=arcanePower,proto3" json:"arcane_power,omitempty"`
	// Fire
	ImprovedFireball    int32 `protobuf:"varint,17,opt,name=improved_fireball,json=improvedFireball,proto3" json:"improved_fireball,omitempty"`
	Impact              int32 `protobuf:"varint,18,opt,name=impact,proto3" json:"impact,omitempty"`
	Ignite              int32 `protobuf:"varint,19,opt,name=ignite,proto3" json:"ignite,omitempty"`
	FlameThrowing       int32 `protobuf:"varint,20,opt,name=flame_throwing,json=flameThrowing,proto3" json:"flame_throwing,omitempty"`
	ImprovedFireBlast   int32 `protobuf:"varint,21,opt,name=improved_fire_blast,json=improvedFireBlast,proto3" json:"improved_fire_blast,omitempty"`
	Incinerate          int32 `protobuf:"varint,22,opt,name=incinerate,proto3" json:"incinerate,omitempty"`
	ImprovedFlamestrike int32 `protobuf:"varint,23,opt,name=improved_flamestrike,json=improvedFlamestrike,proto3" json:"improved_flamestrike,omitempty"`
	Pyroblast           bool  `protobuf:"varint,24,opt,name=pyroblast,proto3" json:"pyroblast,omitempty"`
	BurningSoul         int32 `protobuf:"varint,25,opt,name=burning_soul,json=burningSoul,proto3" json:"burning_soul,omitempty"`
	ImprovedScorch      int32 `protobuf:"varint,26,opt,name=improved_scorch,json=improvedScorch,proto3" json:"improved_scorch,omitempty"`
	ImprovedFireWard    int32 `protobuf:"varint,27,opt,name=improved_fire_ward,json=improvedFireWard,proto3" json:"improved_fire_ward,omitempty"`
	MasterOfElements    int32 `protobuf:"varint,28,opt,name=master_of_elements,json=masterOfElements,proto3" json:"master_of_elements,omitempty"`
	CriticalMass        int32 `protobuf:"varint,29,opt,name=critical_mass,json=criticalMass,proto3" json:"critical_mass,omitempty"`
	BlastWave           bool  `protobuf:"varint,30,opt,name=blast_wave,json=blastWave,proto3" json:"blast_wave,omitempty"`
	FirePower           int32 `protobuf:"varint,31,opt,name=fire_power,json=firePower,proto3" json:"fire_power,omitempty"`
	Combustion          bool  `protobuf:"varint,32,opt,name=combustion,proto3" json:"combustion,omitempty"`
	// Frost
	FrostWarding       int32 `protobuf:"varint,33,opt,name=frost_warding,json=frostWarding,proto3" json:"frost_warding,omitempty"`
	ImprovedFrostbolt  int32 `protobuf:"varint,34,opt,name=improved_frostbolt,json=improvedFrostbolt,proto3" json:"improved_frostbolt,omitempty"`
	ElementalPrecision int32 `protobuf:"varint,35,opt,name=elemental_precision,json=elementalPrecision,proto3" json:"elemental_precision,omitempty"`
	IceShards          int32 `protobuf:"varint,36,opt,name=ice_shards,json=iceShards,proto3" json:"ice_shards,omitempty"`
	Frostbite          int32 `protobuf:"varint,37,opt,name=frostbite,proto3" json:"frostbite,omitempty"`
	ImprovedFrostNova  int32 `protobuf:"varint,38,opt,name=improved_frost_nova,json=improvedFrostNova,proto3" json:"improved_frost_nova,omitempty"`
	Permafrost         int32 `protobuf:"varint,39,opt,name=permafrost,proto3" json:"permafrost,omitempty"`
	PiercingIce        int32 `protobuf:"varint,40,opt,name=piercing_ice,json=piercingIce,proto3" json:"piercing_ice,omitempty"`
	ColdSnap           bool  `protobuf:"varint,41,opt,name=cold_snap,json=coldSnap,proto3" json:"cold_snap,omitempty"`
	ImprovedBlizzard   int32 `protobuf:"varint,42,opt,name=improved_blizzard,json=improvedBlizzard,proto3" json:"improved_blizzard,omitempty"`
	ArcticReach        int32 `protobuf:"varint,43,opt,name=arctic_reach,json=arcticReach,proto3" json:"arctic_reach,omitempty"`
	FrostChanneling    int32 `protobuf:"varint,44,opt,name=frost_channeling,json=frostChanneling,proto3" json:"frost_channeling,omitempty"`
	Shatter            int32 `protobuf:"varint,45,opt,name=shatter,proto3" json:"shatter,omitempty"`
	IceBlock           bool  `protobuf:"varint,46,opt,name=ice_block,json=iceBlock,proto3" json:"ice_block,omitempty"`
	ImprovedConeOfCold int32 `protobuf:"varint,47,opt,name=improved_cone_of_cold,json=improvedConeOfCold,proto3" json:"improved_cone_of_cold,omitempty"`
	WintersChill       int32 `protobuf:"varint,48,opt,name=winters_chill,json=wintersChill,proto3" json:"winters_chill,omitempty"`
	IceBarrier         bool  `protobuf:"varint,49,opt,name=ice_barrier,json=iceBarrier,proto3" json:"ice_barrier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MageTalents) Reset() {
	*x = MageTalents{}
	mi := &file_mage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MageTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MageTalents) ProtoMessage() {}

func (x *MageTalents) ProtoReflect() protoreflect.Message {
	mi := &file_mage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MageTalents.ProtoReflect.Descriptor instead.
func (*MageTalents) Descriptor() ([]byte, []int) {
	return file_mage_proto_rawDescGZIP(), []int{0}
}

func (x *MageTalents) GetArcaneSubtlety() int32 {
	if x != nil {
		return x.ArcaneSubtlety
	}
	return 0
}

func (x *MageTalents) GetArcaneFocus() int32 {
	if x != nil {
		return x.ArcaneFocus
	}
	return 0
}

func (x *MageTalents) GetImprovedArcaneMissiles() int32 {
	if x != nil {
		return x.ImprovedArcaneMissiles
	}
	return 0
}

func (x *MageTalents) GetWandSpecialization() int32 {
	if x != nil {
		return x.WandSpecialization
	}
	return 0
}

func (x *MageTalents) GetMagicAbsorption() int32 {
	if x != nil {
		return x.MagicAbsorption
	}
	return 0
}

func (x *MageTalents) GetArcaneConcentration() int32 {
	if x != nil {
		return x.ArcaneConcentration
	}
	return 0
}

func (x *MageTalents) GetMagicAttunement() int32 {
	if x != nil {
		return x.MagicAttunement
	}
	return 0
}

func (x *MageTalents) GetImprovedArcaneExplosion() int32 {
	if x != nil {
		return x.ImprovedArcaneExplosion
	}
	return 0
}

func (x *MageTalents) GetArcaneResilience() bool {
	if x != nil {
		return x.ArcaneResilience
	}
	return false
}

func (x *MageTalents) GetImprovedManaShield() int32 {
	if x != nil {
		return x.ImprovedManaShield
	}
	return 0
}

func (x *MageTalents) GetImprovedCounterspell() int32 {
	if x != nil {
		return x.ImprovedCounterspell
	}
	return 0
}

func (x *MageTalents) GetArcaneMeditation() int32 {
	if x != nil {
		return x.ArcaneMeditation
	}
	return 0
}

func (x *MageTalents) GetPresenceOfMind() bool {
	if x != nil {
		return x.PresenceOfMind
	}
	return false
}

func (x *MageTalents) GetArcaneMind() int32 {
	if x != nil {
		return x.ArcaneMind
	}
	return 0
}

func (x *MageTalents) GetArcaneInstability() int32 {
	if x != nil {
		return x.ArcaneInstability
	}
	return 0
}

func (x *MageTalents) GetArcanePower() bool {
	if x != nil {
		return x.ArcanePower
	}
	return false
}

func (x *MageTalents) GetImprovedFireball() int32 {
	if x != nil {
		return x.ImprovedFireball
	}
	return 0
}

func (x *MageTalents) GetImpact() int32 {
	if x != nil {
		return x.Impact
	}
	return 0
}

func (x *MageTalents) GetIgnite() int32 {
	if x != nil {
		return x.Ignite
	}
	return 0
}

func (x *MageTalents) GetFlameThrowing() int32 {
	if x != nil {
		return x.FlameThrowing
	}
	return 0
}

func (x *MageTalents) GetImprovedFireBlast() int32 {
	if x != nil {
		return x.ImprovedFireBlast
	}
	return 0
}

func (x *MageTalents) GetIncinerate() int32 {
	if x != nil {
		return x.Incinerate
	}
	return 0
}

func (x *MageTalents) GetImprovedFlamestrike() int32 {
	if x != nil {
		return x.ImprovedFlamestrike
	}
	return 0
}

func (x *MageTalents) GetPyroblast() bool {
	if x != nil {
		return x.Pyroblast
	}
	return false
}

func (x *MageTalents) GetBurningSoul() int32 {
	if x != nil {
		return x.BurningSoul
	}
	return 0
}

func (x *MageTalents) GetImprovedScorch() int32 {
	if x != nil {
		return x.ImprovedScorch
	}
	return 0
}

func (x *MageTalents) GetImprovedFireWard() int32 {
	if x != nil {
		return x.ImprovedFireWard
	}
	return 0
}

func (x *MageTalents) GetMasterOfElements() int32 {
	if x != nil {
		return x.MasterOfElements
	}
	return 0
}

func (x *MageTalents) GetCriticalMass() int32 {
	if x != nil {
		return x.CriticalMass
	}
	return 0
}

func (x *MageTalents) GetBlastWave() bool {
	if x != nil {
		return x.BlastWave
	}
	return false
}

func (x *MageTalents) GetFirePower() int32 {
	if x != nil {
		return x.FirePower
	}
	return 0
}

func (x *MageTalents) GetCombustion() bool {
	if x != nil {
		return x.Combustion
	}
	return false
}

func (x *MageTalents) GetFrostWarding() int32 {
	if x != nil {
		return x.FrostWarding
	}
	return 0
}

func (x *MageTalents) GetImprovedFrostbolt() int32 {
	if x != nil {
		return x.ImprovedFrostbolt
	}
	return 0
}

func (x *MageTalents) GetElementalPrecision() int32 {
	if x != nil {
		return x.ElementalPrecision
	}
	return 0
}

func (x *MageTalents) GetIceShards() int32 {
	if x != nil {
		return x.IceShards
	}
	return 0
}

func (x *MageTalents) GetFrostbite() int32 {
	if x != nil {
		return x.Frostbite
	}
	return 0
}

func (x *MageTalents) GetImprovedFrostNova() int32 {
	if x != nil {
		return x.ImprovedFrostNova
	}
	return 0
}

func (x *MageTalents) GetPermafrost() int32 {
	if x != nil {
		return x.Permafrost
	}
	return 0
}

func (x *MageTalents) GetPiercingIce() int32 {
	if x != nil {
		return x.PiercingIce
	}
	return 0
}

func (x *MageTalents) GetColdSnap() bool {
	if x != nil {
		return x.ColdSnap
	}
	return false
}

func (x *MageTalents) GetImprovedBlizzard() int32 {
	if x != nil {
		return x.ImprovedBlizzard
	}
	return 0
}

func (x *MageTalents) GetArcticReach() int32 {
	if x != nil {
		return x.ArcticReach
	}
	return 0
}

func (x *MageTalents) GetFrostChanneling() int32 {
	if x != nil {
		return x.FrostChanneling
	}
	return 0
}

func (x *MageTalents) GetShatter() int32 {
	if x != nil {
		return x.Shatter
	}
	return 0
}

func (x *MageTalents) GetIceBlock() bool {
	if x != nil {
		return x.IceBlock
	}
	return false
}

func (x *MageTalents) GetImprovedConeOfCold() int32 {
	if x != nil {
		return x.ImprovedConeOfCold
	}
	return 0
}

func (x *MageTalents) GetWintersChill() int32 {
	if x != nil {
		return x.WintersChill
	}
	return 0
}

func (x *MageTalents) GetIceBarrier() bool {
	if x != nil {
		return x.IceBarrier
	}
	return false
}

type Mage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *Mage_Options          `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mage) Reset() {
	*x = Mage{}
	mi := &file_mage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mage) ProtoMessage() {}

func (x *Mage) ProtoReflect() protoreflect.Message {
	mi := &file_mage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mage.ProtoReflect.Descriptor instead.
func (*Mage) Descriptor() ([]byte, []int) {
	return file_mage_proto_rawDescGZIP(), []int{1}
}

func (x *Mage) GetOptions() *Mage_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Mage_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mage_Rotation) Reset() {
	*x = Mage_Rotation{}
	mi := &file_mage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mage_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mage_Rotation) ProtoMessage() {}

func (x *Mage_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_mage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mage_Rotation.ProtoReflect.Descriptor instead.
func (*Mage_Rotation) Descriptor() ([]byte, []int) {
	return file_mage_proto_rawDescGZIP(), []int{1, 0}
}

type Mage_Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Armor         Mage_Options_ArmorType `protobuf:"varint,1,opt,name=armor,proto3,enum=proto.Mage_Options_ArmorType" json:"armor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mage_Options) Reset() {
	*x = Mage_Options{}
	mi := &file_mage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mage_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mage_Options) ProtoMessage() {}

func (x *Mage_Options) ProtoReflect() protoreflect.Message {
	mi := &file_mage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mage_Options.ProtoReflect.Descriptor instead.
func (*Mage_Options) Descriptor() ([]byte, []int) {
	return file_mage_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Mage_Options) GetArmor() Mage_Options_ArmorType {
	if x != nil {
		return x.Armor
	}
	return Mage_Options_NoArmor
}

var File_mage_proto protoreflect.FileDescriptor

const file_mage_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mage.proto\x12\x05proto\"\xb4\x0f\n" +
	"\vMageTalents\x12'\n" +
	"\x0farcane_subtlety\x18\x01 \x01(\x05R\x0earcaneSubtlety\x12!\n" +
	"\farcane_focus\x18\x02 \x01(\x05R\varcaneFocus\x128\n" +
	"\x18improved_arcane_missiles\x18\x03 \x01(\x05R\x16improvedArcaneMissiles\x12/\n" +
	"\x13wand_specialization\x18\x04 \x01(\x05R\x12wandSpecialization\x12)\n" +
	"\x10magic_absorption\x18\x05 \x01(\x05R\x0fmagicAbsorption\x121\n" +
	"\x14arcane_concentration\x18\x06 \x01(\x05R\x13arcaneConcentration\x12)\n" +
	"\x10magic_attunement\x18\a \x01(\x05R\x0fmagicAttunement\x12:\n" +
	"\x19improved_arcane_explosion\x18\b \x01(\x05R\x17improvedArcaneExplosion\x12+\n" +
	"\x11arcane_resilience\x18\t \x01(\bR\x10arcaneResilience\x120\n" +
	"\x14improved_mana_shield\x18\n" +
	" \x01(\x05R\x12improvedManaShield\x123\n" +
	"\x15improved_counterspell\x18\v \x01(\x05R\x14improvedCounterspell\x12+\n" +
	"\x11arcane_meditation\x18\f \x01(\x05R\x10arcaneMeditation\x12(\n" +
	"\x10presence_of_mind\x18\r \x01(\bR\x0epresenceOfMind\x12\x1f\n" +
	"\varcane_mind\x18\x0e \x01(\x05R\n" +
	"arcaneMind\x12-\n" +
	"\x12arcane_instability\x18\x0f \x01(\x05R\x11arcaneInstability\x12!\n" +
	"\farcane_power\x18\x10 \x01(\bR\varcanePower\x12+\n" +
	"\x11improved_fireball\x18\x11 \x01(\x05R\x10improvedFireball\x12\x16\n" +
	"\x06impact\x18\x12 \x01(\x05R\x06impact\x12\x16\n" +
	"\x06ignite\x18\x13 \x01(\x05R\x06ignite\x12%\n" +
	"\x0eflame_throwing\x18\x14 \x01(\x05R\rflameThrowing\x12.\n" +
	"\x13improved_fire_blast\x18\x15 \x01(\x05R\x11improvedFireBlast\x12\x1e\n" +
	"\n" +
	"incinerate\x18\x16 \x01(\x05R\n" +
	"incinerate\x121\n" +
	"\x14improved_flamestrike\x18\x17 \x01(\x05R\x13improvedFlamestrike\x12\x1c\n" +
	"\tpyroblast\x18\x18 \x01(\bR\tpyroblast\x12!\n" +
	"\fburning_soul\x18\x19 \x01(\x05R\vburningSoul\x12'\n" +
	"\x0fimproved_scorch\x18\x1a \x01(\x05R\x0eimprovedScorch\x12,\n" +
	"\x12improved_fire_ward\x18\x1b \x01(\x05R\x10improvedFireWard\x12,\n" +
	"\x12master_of_elements\x18\x1c \x01(\x05R\x10masterOfElements\x12#\n" +
	"\rcritical_mass\x18\x1d \x01(\x05R\fcriticalMass\x12\x1d\n" +
	"\n" +
	"blast_wave\x18\x1e \x01(\bR\tblastWave\x12\x1d\n" +
	"\n" +
	"fire_power\x18\x1f \x01(\x05R\tfirePower\x12\x1e\n" +
	"\n" +
	"combustion\x18  \x01(\bR\n" +
	"combustion\x12#\n" +
	"\rfrost_warding\x18! \x01(\x05R\ffrostWarding\x12-\n" +
	"\x12improved_frostbolt\x18\" \x01(\x05R\x11improvedFrostbolt\x12/\n" +
	"\x13elemental_precision\x18# \x01(\x05R\x12elementalPrecision\x12\x1d\n" +
	"\n" +
	"ice_shards\x18$ \x01(\x05R\ticeShards\x12\x1c\n" +
	"\tfrostbite\x18% \x01(\x05R\tfrostbite\x12.\n" +
	"\x13improved_frost_nova\x18& \x01(\x05R\x11improvedFrostNova\x12\x1e\n" +
	"\n" +
	"permafrost\x18' \x01(\x05R\n" +
	"permafrost\x12!\n" +
	"\fpiercing_ice\x18( \x01(\x05R\vpiercingIce\x12\x1b\n" +
	"\tcold_snap\x18) \x01(\bR\bcoldSnap\x12+\n" +
	"\x11improved_blizzard\x18* \x01(\x05R\x10improvedBlizzard\x12!\n" +
	"\farctic_reach\x18+ \x01(\x05R\varcticReach\x12)\n" +
	"\x10frost_channeling\x18, \x01(\x05R\x0ffrostChanneling\x12\x18\n" +
	"\ashatter\x18- \x01(\x05R\ashatter\x12\x1b\n" +
	"\tice_block\x18. \x01(\bR\biceBlock\x121\n" +
	"\x15improved_cone_of_cold\x18/ \x01(\x05R\x12improvedConeOfCold\x12#\n" +
	"\rwinters_chill\x180 \x01(\x05R\fwintersChill\x12\x1f\n" +
	"\vice_barrier\x181 \x01(\bR\n" +
	"iceBarrier\"\xca\x01\n" +
	"\x04Mage\x12-\n" +
	"\aoptions\x18\x03 \x01(\v2\x13.proto.Mage.OptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\x1a\x86\x01\n" +
	"\aOptions\x123\n" +
	"\x05armor\x18\x01 \x01(\x0e2\x1d.proto.Mage.Options.ArmorTypeR\x05armor\"F\n" +
	"\tArmorType\x12\v\n" +
	"\aNoArmor\x10\x00\x12\f\n" +
	"\bIceArmor\x10\x01\x12\r\n" +
	"\tMageArmor\x10\x02\x12\x0f\n" +
	"\vMoltenArmor\x10\x03B\tZ\a./protob\x06proto3"

var (
	file_mage_proto_rawDescOnce sync.Once
	file_mage_proto_rawDescData []byte
)

func file_mage_proto_rawDescGZIP() []byte {
	file_mage_proto_rawDescOnce.Do(func() {
		file_mage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mage_proto_rawDesc), len(file_mage_proto_rawDesc)))
	})
	return file_mage_proto_rawDescData
}

var file_mage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mage_proto_goTypes = []any{
	(Mage_Options_ArmorType)(0), // 0: proto.Mage.Options.ArmorType
	(*MageTalents)(nil),         // 1: proto.MageTalents
	(*Mage)(nil),                // 2: proto.Mage
	(*Mage_Rotation)(nil),       // 3: proto.Mage.Rotation
	(*Mage_Options)(nil),        // 4: proto.Mage.Options
}
var file_mage_proto_depIdxs = []int32{
	4, // 0: proto.Mage.options:type_name -> proto.Mage.Options
	0, // 1: proto.Mage.Options.armor:type_name -> proto.Mage.Options.ArmorType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mage_proto_init() }
func file_mage_proto_init() {
	if File_mage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mage_proto_rawDesc), len(file_mage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mage_proto_goTypes,
		DependencyIndexes: file_mage_proto_depIdxs,
		EnumInfos:         file_mage_proto_enumTypes,
		MessageInfos:      file_mage_proto_msgTypes,
	}.Build()
	File_mage_proto = out.File
	file_mage_proto_goTypes = nil
	file_mage_proto_depIdxs = nil
}
