// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: priest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShadowPriest_Options_Armor int32

const (
	ShadowPriest_Options_NoArmor   ShadowPriest_Options_Armor = 0
	ShadowPriest_Options_InnerFire ShadowPriest_Options_Armor = 1
)

// Enum value maps for ShadowPriest_Options_Armor.
var (
	ShadowPriest_Options_Armor_name = map[int32]string{
		0: "NoArmor",
		1: "InnerFire",
	}
	ShadowPriest_Options_Armor_value = map[string]int32{
		"NoArmor":   0,
		"InnerFire": 1,
	}
)

func (x ShadowPriest_Options_Armor) Enum() *ShadowPriest_Options_Armor {
	p := new(ShadowPriest_Options_Armor)
	*p = x
	return p
}

func (x ShadowPriest_Options_Armor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShadowPriest_Options_Armor) Descriptor() protoreflect.EnumDescriptor {
	return file_priest_proto_enumTypes[0].Descriptor()
}

func (ShadowPriest_Options_Armor) Type() protoreflect.EnumType {
	return &file_priest_proto_enumTypes[0]
}

func (x ShadowPriest_Options_Armor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShadowPriest_Options_Armor.Descriptor instead.
func (ShadowPriest_Options_Armor) EnumDescriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{1, 1, 0}
}

// Code generated by tools/talentgen from client build 1.60.1.69893. DO NOT EDIT.
// Field order is the talent string's order: the three trees in the
// client's own order, each tier then column. core.FillTalentsProto
// reads it positionally, so a reorder silently reads the wrong talent.
type PriestTalents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Discipline (tree 0, client id 201)
	// node 110853, tier 0 col 0, 5 rank(s), spell 1309969
	PowerInLight int32 `protobuf:"varint,1,opt,name=power_in_light,json=powerInLight,proto3" json:"power_in_light,omitempty"`
	// node 105850, tier 0 col 1, 2 rank(s), spell 14524
	WandSpecialization int32 `protobuf:"varint,2,opt,name=wand_specialization,json=wandSpecialization,proto3" json:"wand_specialization,omitempty"`
	// node 105849, tier 0 col 2, 5 rank(s), spell 1225132
	TwinDisciplines int32 `protobuf:"varint,3,opt,name=twin_disciplines,json=twinDisciplines,proto3" json:"twin_disciplines,omitempty"`
	// node 105848, tier 1 col 0, 3 rank(s), spell 14523
	SilentResolve int32 `protobuf:"varint,4,opt,name=silent_resolve,json=silentResolve,proto3" json:"silent_resolve,omitempty"`
	// node 110852, tier 1 col 1, 3 rank(s), spell 1309957
	HolyPrecision int32 `protobuf:"varint,5,opt,name=holy_precision,json=holyPrecision,proto3" json:"holy_precision,omitempty"`
	// node 105846, tier 1 col 2, 3 rank(s), spell 14748
	ImprovedPowerWordShield int32 `protobuf:"varint,6,opt,name=improved_power_word_shield,json=improvedPowerWordShield,proto3" json:"improved_power_word_shield,omitempty"`
	// node 105845, tier 1 col 3, 2 rank(s), spell 14531
	Martyrdom int32 `protobuf:"varint,7,opt,name=martyrdom,proto3" json:"martyrdom,omitempty"`
	// node 105842, tier 2 col 0, 3 rank(s), spell 14520
	MentalAgility int32 `protobuf:"varint,8,opt,name=mental_agility,json=mentalAgility,proto3" json:"mental_agility,omitempty"`
	// node 105844, tier 2 col 1, 1 rank(s), spell 14751
	InnerFocus bool `protobuf:"varint,9,opt,name=inner_focus,json=innerFocus,proto3" json:"inner_focus,omitempty"`
	// node 105843, tier 2 col 3, 3 rank(s), spell 14521
	Meditation int32 `protobuf:"varint,10,opt,name=meditation,proto3" json:"meditation,omitempty"`
	// node 105841, tier 3 col 0, 3 rank(s), spell 14747
	ImprovedInnerFire int32 `protobuf:"varint,11,opt,name=improved_inner_fire,json=improvedInnerFire,proto3" json:"improved_inner_fire,omitempty"`
	// node 105837, tier 3 col 1, 5 rank(s), spell 18551
	MentalStrength int32 `protobuf:"varint,12,opt,name=mental_strength,json=mentalStrength,proto3" json:"mental_strength,omitempty"`
	// node 105839, tier 3 col 2, 1 rank(s), spell 402000
	SoulWarding bool `protobuf:"varint,13,opt,name=soul_warding,json=soulWarding,proto3" json:"soul_warding,omitempty"`
	// node 105838, tier 3 col 3, 2 rank(s), spell 14750
	ImprovedManaBurn int32 `protobuf:"varint,14,opt,name=improved_mana_burn,json=improvedManaBurn,proto3" json:"improved_mana_burn,omitempty"`
	// node 105834, tier 4 col 1, 1 rank(s), spell 402174
	Penance bool `protobuf:"varint,15,opt,name=penance,proto3" json:"penance,omitempty"`
	// node 105835, tier 4 col 2, 5 rank(s), spell 425280
	RenewedHope int32 `protobuf:"varint,16,opt,name=renewed_hope,json=renewedHope,proto3" json:"renewed_hope,omitempty"`
	// node 105840, tier 5 col 2, 3 rank(s), spell 431622
	DivineAegis int32 `protobuf:"varint,17,opt,name=divine_aegis,json=divineAegis,proto3" json:"divine_aegis,omitempty"`
	// node 105836, tier 6 col 1, 1 rank(s), spell 10060
	PowerInfusion bool `protobuf:"varint,18,opt,name=power_infusion,json=powerInfusion,proto3" json:"power_infusion,omitempty"`
	// Holy (tree 1, client id 202)
	// node 105867, tier 0 col 0, 3 rank(s), spell 14913
	TwilightFocus int32 `protobuf:"varint,19,opt,name=twilight_focus,json=twilightFocus,proto3" json:"twilight_focus,omitempty"`
	// node 105866, tier 0 col 1, 3 rank(s), spell 14908
	ImprovedRenew int32 `protobuf:"varint,20,opt,name=improved_renew,json=improvedRenew,proto3" json:"improved_renew,omitempty"`
	// node 110855, tier 0 col 2, 5 rank(s), spell 14889
	HolySpecialization int32 `protobuf:"varint,21,opt,name=holy_specialization,json=holySpecialization,proto3" json:"holy_specialization,omitempty"`
	// node 105864, tier 1 col 1, 5 rank(s), spell 27900
	SpellWarding int32 `protobuf:"varint,22,opt,name=spell_warding,json=spellWarding,proto3" json:"spell_warding,omitempty"`
	// node 105863, tier 1 col 2, 5 rank(s), spell 18530
	DivineFury int32 `protobuf:"varint,23,opt,name=divine_fury,json=divineFury,proto3" json:"divine_fury,omitempty"`
	// node 105862, tier 2 col 0, 1 rank(s), spell 15237
	HolyNova bool `protobuf:"varint,24,opt,name=holy_nova,json=holyNova,proto3" json:"holy_nova,omitempty"`
	// node 105861, tier 2 col 1, 3 rank(s), spell 27811
	BlessedRecovery int32 `protobuf:"varint,25,opt,name=blessed_recovery,json=blessedRecovery,proto3" json:"blessed_recovery,omitempty"`
	// node 105860, tier 2 col 3, 3 rank(s), spell 14892
	Inspiration int32 `protobuf:"varint,26,opt,name=inspiration,proto3" json:"inspiration,omitempty"`
	// node 105859, tier 3 col 0, 2 rank(s), spell 27789
	HolyReach int32 `protobuf:"varint,27,opt,name=holy_reach,json=holyReach,proto3" json:"holy_reach,omitempty"`
	// node 105858, tier 3 col 1, 3 rank(s), spell 14912
	ImprovedHealing int32 `protobuf:"varint,28,opt,name=improved_healing,json=improvedHealing,proto3" json:"improved_healing,omitempty"`
	// node 105857, tier 3 col 2, 2 rank(s), spell 14909
	SearingLight int32 `protobuf:"varint,29,opt,name=searing_light,json=searingLight,proto3" json:"searing_light,omitempty"`
	// node 105856, tier 3 col 3, 1 rank(s), spell 401937
	BindingHeal bool `protobuf:"varint,30,opt,name=binding_heal,json=bindingHeal,proto3" json:"binding_heal,omitempty"`
	// node 105855, tier 4 col 0, 2 rank(s), spell 1317006
	LitanyOfLight int32 `protobuf:"varint,31,opt,name=litany_of_light,json=litanyOfLight,proto3" json:"litany_of_light,omitempty"`
	// node 105854, tier 4 col 1, 1 rank(s), spell 20711
	SpiritOfRedemption bool `protobuf:"varint,32,opt,name=spirit_of_redemption,json=spiritOfRedemption,proto3" json:"spirit_of_redemption,omitempty"`
	// node 105853, tier 4 col 2, 5 rank(s), spell 14901
	SpiritualGuidance int32 `protobuf:"varint,33,opt,name=spiritual_guidance,json=spiritualGuidance,proto3" json:"spiritual_guidance,omitempty"`
	// node 105852, tier 5 col 2, 3 rank(s), spell 14898
	SpiritualHealing int32 `protobuf:"varint,34,opt,name=spiritual_healing,json=spiritualHealing,proto3" json:"spiritual_healing,omitempty"`
	// node 105851, tier 6 col 1, 1 rank(s), spell 401859
	PrayerOfMending bool `protobuf:"varint,35,opt,name=prayer_of_mending,json=prayerOfMending,proto3" json:"prayer_of_mending,omitempty"`
	// Shadow (tree 2, client id 203)
	// node 110851, tier 0 col 0, 5 rank(s), spell 15260
	ShadowFocus int32 `protobuf:"varint,36,opt,name=shadow_focus,json=shadowFocus,proto3" json:"shadow_focus,omitempty"`
	// node 105832, tier 0 col 1, 5 rank(s), spell 15326
	Blackout int32 `protobuf:"varint,37,opt,name=blackout,proto3" json:"blackout,omitempty"`
	// node 105833, tier 0 col 2, 5 rank(s), spell 15270
	SpiritTap int32 `protobuf:"varint,38,opt,name=spirit_tap,json=spiritTap,proto3" json:"spirit_tap,omitempty"`
	// node 105831, tier 1 col 0, 3 rank(s), spell 15318
	ShadowAffinity int32 `protobuf:"varint,39,opt,name=shadow_affinity,json=shadowAffinity,proto3" json:"shadow_affinity,omitempty"`
	// node 105830, tier 1 col 2, 2 rank(s), spell 15275
	ImprovedShadowWordPain int32 `protobuf:"varint,40,opt,name=improved_shadow_word_pain,json=improvedShadowWordPain,proto3" json:"improved_shadow_word_pain,omitempty"`
	// node 105829, tier 1 col 3, 2 rank(s), spell 17322
	ShadowReach int32 `protobuf:"varint,41,opt,name=shadow_reach,json=shadowReach,proto3" json:"shadow_reach,omitempty"`
	// node 105827, tier 2 col 0, 5 rank(s), spell 15273
	ImprovedMindBlast int32 `protobuf:"varint,42,opt,name=improved_mind_blast,json=improvedMindBlast,proto3" json:"improved_mind_blast,omitempty"`
	// node 105828, tier 2 col 1, 2 rank(s), spell 15392
	ImprovedPsychicScream int32 `protobuf:"varint,43,opt,name=improved_psychic_scream,json=improvedPsychicScream,proto3" json:"improved_psychic_scream,omitempty"`
	// node 105826, tier 2 col 2, 1 rank(s), spell 15407
	MindFlay bool `protobuf:"varint,44,opt,name=mind_flay,json=mindFlay,proto3" json:"mind_flay,omitempty"`
	// node 105825, tier 2 col 3, 2 rank(s), spell 1225139
	ImprovedMindFlay int32 `protobuf:"varint,45,opt,name=improved_mind_flay,json=improvedMindFlay,proto3" json:"improved_mind_flay,omitempty"`
	// node 105823, tier 3 col 0, 2 rank(s), spell 15274
	ImprovedFade int32 `protobuf:"varint,46,opt,name=improved_fade,json=improvedFade,proto3" json:"improved_fade,omitempty"`
	// node 105820, tier 3 col 1, 1 rank(s), spell 15286
	VampiricEmbrace bool `protobuf:"varint,47,opt,name=vampiric_embrace,json=vampiricEmbrace,proto3" json:"vampiric_embrace,omitempty"`
	// node 105821, tier 3 col 2, 3 rank(s), spell 15257
	ShadowWeaving int32 `protobuf:"varint,48,opt,name=shadow_weaving,json=shadowWeaving,proto3" json:"shadow_weaving,omitempty"`
	// node 105824, tier 4 col 0, 1 rank(s), spell 15487
	Silence bool `protobuf:"varint,49,opt,name=silence,proto3" json:"silence,omitempty"`
	// node 105819, tier 4 col 2, 2 rank(s), spell 1309950
	DevouringContagion int32 `protobuf:"varint,50,opt,name=devouring_contagion,json=devouringContagion,proto3" json:"devouring_contagion,omitempty"`
	// node 110854, tier 5 col 0, 2 rank(s), spell 1310076
	EarlyDemise int32 `protobuf:"varint,51,opt,name=early_demise,json=earlyDemise,proto3" json:"early_demise,omitempty"`
	// node 105818, tier 5 col 2, 5 rank(s), spell 15259
	Darkness int32 `protobuf:"varint,52,opt,name=darkness,proto3" json:"darkness,omitempty"`
	// node 105817, tier 6 col 1, 1 rank(s), spell 15473
	Shadowform    bool `protobuf:"varint,53,opt,name=shadowform,proto3" json:"shadowform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriestTalents) Reset() {
	*x = PriestTalents{}
	mi := &file_priest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriestTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriestTalents) ProtoMessage() {}

func (x *PriestTalents) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriestTalents.ProtoReflect.Descriptor instead.
func (*PriestTalents) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{0}
}

func (x *PriestTalents) GetPowerInLight() int32 {
	if x != nil {
		return x.PowerInLight
	}
	return 0
}

func (x *PriestTalents) GetWandSpecialization() int32 {
	if x != nil {
		return x.WandSpecialization
	}
	return 0
}

func (x *PriestTalents) GetTwinDisciplines() int32 {
	if x != nil {
		return x.TwinDisciplines
	}
	return 0
}

func (x *PriestTalents) GetSilentResolve() int32 {
	if x != nil {
		return x.SilentResolve
	}
	return 0
}

func (x *PriestTalents) GetHolyPrecision() int32 {
	if x != nil {
		return x.HolyPrecision
	}
	return 0
}

func (x *PriestTalents) GetImprovedPowerWordShield() int32 {
	if x != nil {
		return x.ImprovedPowerWordShield
	}
	return 0
}

func (x *PriestTalents) GetMartyrdom() int32 {
	if x != nil {
		return x.Martyrdom
	}
	return 0
}

func (x *PriestTalents) GetMentalAgility() int32 {
	if x != nil {
		return x.MentalAgility
	}
	return 0
}

func (x *PriestTalents) GetInnerFocus() bool {
	if x != nil {
		return x.InnerFocus
	}
	return false
}

func (x *PriestTalents) GetMeditation() int32 {
	if x != nil {
		return x.Meditation
	}
	return 0
}

func (x *PriestTalents) GetImprovedInnerFire() int32 {
	if x != nil {
		return x.ImprovedInnerFire
	}
	return 0
}

func (x *PriestTalents) GetMentalStrength() int32 {
	if x != nil {
		return x.MentalStrength
	}
	return 0
}

func (x *PriestTalents) GetSoulWarding() bool {
	if x != nil {
		return x.SoulWarding
	}
	return false
}

func (x *PriestTalents) GetImprovedManaBurn() int32 {
	if x != nil {
		return x.ImprovedManaBurn
	}
	return 0
}

func (x *PriestTalents) GetPenance() bool {
	if x != nil {
		return x.Penance
	}
	return false
}

func (x *PriestTalents) GetRenewedHope() int32 {
	if x != nil {
		return x.RenewedHope
	}
	return 0
}

func (x *PriestTalents) GetDivineAegis() int32 {
	if x != nil {
		return x.DivineAegis
	}
	return 0
}

func (x *PriestTalents) GetPowerInfusion() bool {
	if x != nil {
		return x.PowerInfusion
	}
	return false
}

func (x *PriestTalents) GetTwilightFocus() int32 {
	if x != nil {
		return x.TwilightFocus
	}
	return 0
}

func (x *PriestTalents) GetImprovedRenew() int32 {
	if x != nil {
		return x.ImprovedRenew
	}
	return 0
}

func (x *PriestTalents) GetHolySpecialization() int32 {
	if x != nil {
		return x.HolySpecialization
	}
	return 0
}

func (x *PriestTalents) GetSpellWarding() int32 {
	if x != nil {
		return x.SpellWarding
	}
	return 0
}

func (x *PriestTalents) GetDivineFury() int32 {
	if x != nil {
		return x.DivineFury
	}
	return 0
}

func (x *PriestTalents) GetHolyNova() bool {
	if x != nil {
		return x.HolyNova
	}
	return false
}

func (x *PriestTalents) GetBlessedRecovery() int32 {
	if x != nil {
		return x.BlessedRecovery
	}
	return 0
}

func (x *PriestTalents) GetInspiration() int32 {
	if x != nil {
		return x.Inspiration
	}
	return 0
}

func (x *PriestTalents) GetHolyReach() int32 {
	if x != nil {
		return x.HolyReach
	}
	return 0
}

func (x *PriestTalents) GetImprovedHealing() int32 {
	if x != nil {
		return x.ImprovedHealing
	}
	return 0
}

func (x *PriestTalents) GetSearingLight() int32 {
	if x != nil {
		return x.SearingLight
	}
	return 0
}

func (x *PriestTalents) GetBindingHeal() bool {
	if x != nil {
		return x.BindingHeal
	}
	return false
}

func (x *PriestTalents) GetLitanyOfLight() int32 {
	if x != nil {
		return x.LitanyOfLight
	}
	return 0
}

func (x *PriestTalents) GetSpiritOfRedemption() bool {
	if x != nil {
		return x.SpiritOfRedemption
	}
	return false
}

func (x *PriestTalents) GetSpiritualGuidance() int32 {
	if x != nil {
		return x.SpiritualGuidance
	}
	return 0
}

func (x *PriestTalents) GetSpiritualHealing() int32 {
	if x != nil {
		return x.SpiritualHealing
	}
	return 0
}

func (x *PriestTalents) GetPrayerOfMending() bool {
	if x != nil {
		return x.PrayerOfMending
	}
	return false
}

func (x *PriestTalents) GetShadowFocus() int32 {
	if x != nil {
		return x.ShadowFocus
	}
	return 0
}

func (x *PriestTalents) GetBlackout() int32 {
	if x != nil {
		return x.Blackout
	}
	return 0
}

func (x *PriestTalents) GetSpiritTap() int32 {
	if x != nil {
		return x.SpiritTap
	}
	return 0
}

func (x *PriestTalents) GetShadowAffinity() int32 {
	if x != nil {
		return x.ShadowAffinity
	}
	return 0
}

func (x *PriestTalents) GetImprovedShadowWordPain() int32 {
	if x != nil {
		return x.ImprovedShadowWordPain
	}
	return 0
}

func (x *PriestTalents) GetShadowReach() int32 {
	if x != nil {
		return x.ShadowReach
	}
	return 0
}

func (x *PriestTalents) GetImprovedMindBlast() int32 {
	if x != nil {
		return x.ImprovedMindBlast
	}
	return 0
}

func (x *PriestTalents) GetImprovedPsychicScream() int32 {
	if x != nil {
		return x.ImprovedPsychicScream
	}
	return 0
}

func (x *PriestTalents) GetMindFlay() bool {
	if x != nil {
		return x.MindFlay
	}
	return false
}

func (x *PriestTalents) GetImprovedMindFlay() int32 {
	if x != nil {
		return x.ImprovedMindFlay
	}
	return 0
}

func (x *PriestTalents) GetImprovedFade() int32 {
	if x != nil {
		return x.ImprovedFade
	}
	return 0
}

func (x *PriestTalents) GetVampiricEmbrace() bool {
	if x != nil {
		return x.VampiricEmbrace
	}
	return false
}

func (x *PriestTalents) GetShadowWeaving() int32 {
	if x != nil {
		return x.ShadowWeaving
	}
	return 0
}

func (x *PriestTalents) GetSilence() bool {
	if x != nil {
		return x.Silence
	}
	return false
}

func (x *PriestTalents) GetDevouringContagion() int32 {
	if x != nil {
		return x.DevouringContagion
	}
	return 0
}

func (x *PriestTalents) GetEarlyDemise() int32 {
	if x != nil {
		return x.EarlyDemise
	}
	return 0
}

func (x *PriestTalents) GetDarkness() int32 {
	if x != nil {
		return x.Darkness
	}
	return 0
}

func (x *PriestTalents) GetShadowform() bool {
	if x != nil {
		return x.Shadowform
	}
	return false
}

type ShadowPriest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *ShadowPriest_Options  `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowPriest) Reset() {
	*x = ShadowPriest{}
	mi := &file_priest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowPriest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowPriest) ProtoMessage() {}

func (x *ShadowPriest) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowPriest.ProtoReflect.Descriptor instead.
func (*ShadowPriest) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{1}
}

func (x *ShadowPriest) GetOptions() *ShadowPriest_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type HealingPriest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *HealingPriest_Options `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealingPriest) Reset() {
	*x = HealingPriest{}
	mi := &file_priest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealingPriest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealingPriest) ProtoMessage() {}

func (x *HealingPriest) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealingPriest.ProtoReflect.Descriptor instead.
func (*HealingPriest) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{2}
}

func (x *HealingPriest) GetOptions() *HealingPriest_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type ShadowPriest_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowPriest_Rotation) Reset() {
	*x = ShadowPriest_Rotation{}
	mi := &file_priest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowPriest_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowPriest_Rotation) ProtoMessage() {}

func (x *ShadowPriest_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowPriest_Rotation.ProtoReflect.Descriptor instead.
func (*ShadowPriest_Rotation) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{1, 0}
}

type ShadowPriest_Options struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	UseShadowfiend      bool                       `protobuf:"varint,1,opt,name=use_shadowfiend,json=useShadowfiend,proto3" json:"use_shadowfiend,omitempty"`
	Armor               ShadowPriest_Options_Armor `protobuf:"varint,2,opt,name=armor,proto3,enum=proto.ShadowPriest_Options_Armor" json:"armor,omitempty"`
	UseMindBlast        bool                       `protobuf:"varint,4,opt,name=use_mind_blast,json=useMindBlast,proto3" json:"use_mind_blast,omitempty"`
	PowerInfusionTarget *UnitReference             `protobuf:"bytes,5,opt,name=power_infusion_target,json=powerInfusionTarget,proto3" json:"power_infusion_target,omitempty"`
	// Deprecated: Marked as deprecated in priest.proto.
	Latency       float64 `protobuf:"fixed64,6,opt,name=latency,proto3" json:"latency,omitempty"` // Latency between actions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowPriest_Options) Reset() {
	*x = ShadowPriest_Options{}
	mi := &file_priest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowPriest_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowPriest_Options) ProtoMessage() {}

func (x *ShadowPriest_Options) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowPriest_Options.ProtoReflect.Descriptor instead.
func (*ShadowPriest_Options) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ShadowPriest_Options) GetUseShadowfiend() bool {
	if x != nil {
		return x.UseShadowfiend
	}
	return false
}

func (x *ShadowPriest_Options) GetArmor() ShadowPriest_Options_Armor {
	if x != nil {
		return x.Armor
	}
	return ShadowPriest_Options_NoArmor
}

func (x *ShadowPriest_Options) GetUseMindBlast() bool {
	if x != nil {
		return x.UseMindBlast
	}
	return false
}

func (x *ShadowPriest_Options) GetPowerInfusionTarget() *UnitReference {
	if x != nil {
		return x.PowerInfusionTarget
	}
	return nil
}

// Deprecated: Marked as deprecated in priest.proto.
func (x *ShadowPriest_Options) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

type HealingPriest_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealingPriest_Rotation) Reset() {
	*x = HealingPriest_Rotation{}
	mi := &file_priest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealingPriest_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealingPriest_Rotation) ProtoMessage() {}

func (x *HealingPriest_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealingPriest_Rotation.ProtoReflect.Descriptor instead.
func (*HealingPriest_Rotation) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{2, 0}
}

type HealingPriest_Options struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UseInnerFire        bool                   `protobuf:"varint,2,opt,name=use_inner_fire,json=useInnerFire,proto3" json:"use_inner_fire,omitempty"`
	PowerInfusionTarget *UnitReference         `protobuf:"bytes,1,opt,name=power_infusion_target,json=powerInfusionTarget,proto3" json:"power_infusion_target,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealingPriest_Options) Reset() {
	*x = HealingPriest_Options{}
	mi := &file_priest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealingPriest_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealingPriest_Options) ProtoMessage() {}

func (x *HealingPriest_Options) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealingPriest_Options.ProtoReflect.Descriptor instead.
func (*HealingPriest_Options) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{2, 1}
}

func (x *HealingPriest_Options) GetUseInnerFire() bool {
	if x != nil {
		return x.UseInnerFire
	}
	return false
}

func (x *HealingPriest_Options) GetPowerInfusionTarget() *UnitReference {
	if x != nil {
		return x.PowerInfusionTarget
	}
	return nil
}

var File_priest_proto protoreflect.FileDescriptor

const file_priest_proto_rawDesc = "" +
	"\n" +
	"\fpriest.proto\x12\x05proto\x1a\fcommon.proto\"\xaf\x10\n" +
	"\rPriestTalents\x12$\n" +
	"\x0epower_in_light\x18\x01 \x01(\x05R\fpowerInLight\x12/\n" +
	"\x13wand_specialization\x18\x02 \x01(\x05R\x12wandSpecialization\x12)\n" +
	"\x10twin_disciplines\x18\x03 \x01(\x05R\x0ftwinDisciplines\x12%\n" +
	"\x0esilent_resolve\x18\x04 \x01(\x05R\rsilentResolve\x12%\n" +
	"\x0eholy_precision\x18\x05 \x01(\x05R\rholyPrecision\x12;\n" +
	"\x1aimproved_power_word_shield\x18\x06 \x01(\x05R\x17improvedPowerWordShield\x12\x1c\n" +
	"\tmartyrdom\x18\a \x01(\x05R\tmartyrdom\x12%\n" +
	"\x0emental_agility\x18\b \x01(\x05R\rmentalAgility\x12\x1f\n" +
	"\vinner_focus\x18\t \x01(\bR\n" +
	"innerFocus\x12\x1e\n" +
	"\n" +
	"meditation\x18\n" +
	" \x01(\x05R\n" +
	"meditation\x12.\n" +
	"\x13improved_inner_fire\x18\v \x01(\x05R\x11improvedInnerFire\x12'\n" +
	"\x0fmental_strength\x18\f \x01(\x05R\x0ementalStrength\x12!\n" +
	"\fsoul_warding\x18\r \x01(\bR\vsoulWarding\x12,\n" +
	"\x12improved_mana_burn\x18\x0e \x01(\x05R\x10improvedManaBurn\x12\x18\n" +
	"\apenance\x18\x0f \x01(\bR\apenance\x12!\n" +
	"\frenewed_hope\x18\x10 \x01(\x05R\vrenewedHope\x12!\n" +
	"\fdivine_aegis\x18\x11 \x01(\x05R\vdivineAegis\x12%\n" +
	"\x0epower_infusion\x18\x12 \x01(\bR\rpowerInfusion\x12%\n" +
	"\x0etwilight_focus\x18\x13 \x01(\x05R\rtwilightFocus\x12%\n" +
	"\x0eimproved_renew\x18\x14 \x01(\x05R\rimprovedRenew\x12/\n" +
	"\x13holy_specialization\x18\x15 \x01(\x05R\x12holySpecialization\x12#\n" +
	"\rspell_warding\x18\x16 \x01(\x05R\fspellWarding\x12\x1f\n" +
	"\vdivine_fury\x18\x17 \x01(\x05R\n" +
	"divineFury\x12\x1b\n" +
	"\tholy_nova\x18\x18 \x01(\bR\bholyNova\x12)\n" +
	"\x10blessed_recovery\x18\x19 \x01(\x05R\x0fblessedRecovery\x12 \n" +
	"\vinspiration\x18\x1a \x01(\x05R\vinspiration\x12\x1d\n" +
	"\n" +
	"holy_reach\x18\x1b \x01(\x05R\tholyReach\x12)\n" +
	"\x10improved_healing\x18\x1c \x01(\x05R\x0fimprovedHealing\x12#\n" +
	"\rsearing_light\x18\x1d \x01(\x05R\fsearingLight\x12!\n" +
	"\fbinding_heal\x18\x1e \x01(\bR\vbindingHeal\x12&\n" +
	"\x0flitany_of_light\x18\x1f \x01(\x05R\rlitanyOfLight\x120\n" +
	"\x14spirit_of_redemption\x18  \x01(\bR\x12spiritOfRedemption\x12-\n" +
	"\x12spiritual_guidance\x18! \x01(\x05R\x11spiritualGuidance\x12+\n" +
	"\x11spiritual_healing\x18\" \x01(\x05R\x10spiritualHealing\x12*\n" +
	"\x11prayer_of_mending\x18# \x01(\bR\x0fprayerOfMending\x12!\n" +
	"\fshadow_focus\x18$ \x01(\x05R\vshadowFocus\x12\x1a\n" +
	"\bblackout\x18% \x01(\x05R\bblackout\x12\x1d\n" +
	"\n" +
	"spirit_tap\x18& \x01(\x05R\tspiritTap\x12'\n" +
	"\x0fshadow_affinity\x18' \x01(\x05R\x0eshadowAffinity\x129\n" +
	"\x19improved_shadow_word_pain\x18( \x01(\x05R\x16improvedShadowWordPain\x12!\n" +
	"\fshadow_reach\x18) \x01(\x05R\vshadowReach\x12.\n" +
	"\x13improved_mind_blast\x18* \x01(\x05R\x11improvedMindBlast\x126\n" +
	"\x17improved_psychic_scream\x18+ \x01(\x05R\x15improvedPsychicScream\x12\x1b\n" +
	"\tmind_flay\x18, \x01(\bR\bmindFlay\x12,\n" +
	"\x12improved_mind_flay\x18- \x01(\x05R\x10improvedMindFlay\x12#\n" +
	"\rimproved_fade\x18. \x01(\x05R\fimprovedFade\x12)\n" +
	"\x10vampiric_embrace\x18/ \x01(\bR\x0fvampiricEmbrace\x12%\n" +
	"\x0eshadow_weaving\x180 \x01(\x05R\rshadowWeaving\x12\x18\n" +
	"\asilence\x181 \x01(\bR\asilence\x12/\n" +
	"\x13devouring_contagion\x182 \x01(\x05R\x12devouringContagion\x12!\n" +
	"\fearly_demise\x183 \x01(\x05R\vearlyDemise\x12\x1a\n" +
	"\bdarkness\x184 \x01(\x05R\bdarkness\x12\x1e\n" +
	"\n" +
	"shadowform\x185 \x01(\bR\n" +
	"shadowform\"\xf2\x02\n" +
	"\fShadowPriest\x125\n" +
	"\aoptions\x18\x03 \x01(\v2\x1b.proto.ShadowPriest.OptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\x1a\x9e\x02\n" +
	"\aOptions\x12'\n" +
	"\x0fuse_shadowfiend\x18\x01 \x01(\bR\x0euseShadowfiend\x127\n" +
	"\x05armor\x18\x02 \x01(\x0e2!.proto.ShadowPriest.Options.ArmorR\x05armor\x12$\n" +
	"\x0euse_mind_blast\x18\x04 \x01(\bR\fuseMindBlast\x12H\n" +
	"\x15power_infusion_target\x18\x05 \x01(\v2\x14.proto.UnitReferenceR\x13powerInfusionTarget\x12\x1c\n" +
	"\alatency\x18\x06 \x01(\x01B\x02\x18\x01R\alatency\"#\n" +
	"\x05Armor\x12\v\n" +
	"\aNoArmor\x10\x00\x12\r\n" +
	"\tInnerFire\x10\x01\"\xce\x01\n" +
	"\rHealingPriest\x126\n" +
	"\aoptions\x18\x03 \x01(\v2\x1c.proto.HealingPriest.OptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\x1ay\n" +
	"\aOptions\x12$\n" +
	"\x0euse_inner_fire\x18\x02 \x01(\bR\fuseInnerFire\x12H\n" +
	"\x15power_infusion_target\x18\x01 \x01(\v2\x14.proto.UnitReferenceR\x13powerInfusionTargetB\tZ\a./protob\x06proto3"

var (
	file_priest_proto_rawDescOnce sync.Once
	file_priest_proto_rawDescData []byte
)

func file_priest_proto_rawDescGZIP() []byte {
	file_priest_proto_rawDescOnce.Do(func() {
		file_priest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_priest_proto_rawDesc), len(file_priest_proto_rawDesc)))
	})
	return file_priest_proto_rawDescData
}

var file_priest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_priest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_priest_proto_goTypes = []any{
	(ShadowPriest_Options_Armor)(0), // 0: proto.ShadowPriest.Options.Armor
	(*PriestTalents)(nil),           // 1: proto.PriestTalents
	(*ShadowPriest)(nil),            // 2: proto.ShadowPriest
	(*HealingPriest)(nil),           // 3: proto.HealingPriest
	(*ShadowPriest_Rotation)(nil),   // 4: proto.ShadowPriest.Rotation
	(*ShadowPriest_Options)(nil),    // 5: proto.ShadowPriest.Options
	(*HealingPriest_Rotation)(nil),  // 6: proto.HealingPriest.Rotation
	(*HealingPriest_Options)(nil),   // 7: proto.HealingPriest.Options
	(*UnitReference)(nil),           // 8: proto.UnitReference
}
var file_priest_proto_depIdxs = []int32{
	5, // 0: proto.ShadowPriest.options:type_name -> proto.ShadowPriest.Options
	7, // 1: proto.HealingPriest.options:type_name -> proto.HealingPriest.Options
	0, // 2: proto.ShadowPriest.Options.armor:type_name -> proto.ShadowPriest.Options.Armor
	8, // 3: proto.ShadowPriest.Options.power_infusion_target:type_name -> proto.UnitReference
	8, // 4: proto.HealingPriest.Options.power_infusion_target:type_name -> proto.UnitReference
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_priest_proto_init() }
func file_priest_proto_init() {
	if File_priest_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_priest_proto_rawDesc), len(file_priest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_priest_proto_goTypes,
		DependencyIndexes: file_priest_proto_depIdxs,
		EnumInfos:         file_priest_proto_enumTypes,
		MessageInfos:      file_priest_proto_msgTypes,
	}.Build()
	File_priest_proto = out.File
	file_priest_proto_goTypes = nil
	file_priest_proto_depIdxs = nil
}
