// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: priest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShadowPriest_Options_Armor int32

const (
	ShadowPriest_Options_NoArmor   ShadowPriest_Options_Armor = 0
	ShadowPriest_Options_InnerFire ShadowPriest_Options_Armor = 1
)

// Enum value maps for ShadowPriest_Options_Armor.
var (
	ShadowPriest_Options_Armor_name = map[int32]string{
		0: "NoArmor",
		1: "InnerFire",
	}
	ShadowPriest_Options_Armor_value = map[string]int32{
		"NoArmor":   0,
		"InnerFire": 1,
	}
)

func (x ShadowPriest_Options_Armor) Enum() *ShadowPriest_Options_Armor {
	p := new(ShadowPriest_Options_Armor)
	*p = x
	return p
}

func (x ShadowPriest_Options_Armor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShadowPriest_Options_Armor) Descriptor() protoreflect.EnumDescriptor {
	return file_priest_proto_enumTypes[0].Descriptor()
}

func (ShadowPriest_Options_Armor) Type() protoreflect.EnumType {
	return &file_priest_proto_enumTypes[0]
}

func (x ShadowPriest_Options_Armor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShadowPriest_Options_Armor.Descriptor instead.
func (ShadowPriest_Options_Armor) EnumDescriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{1, 1, 0}
}

type PriestTalents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Discipline
	UnbreakableWill            int32 `protobuf:"varint,1,opt,name=unbreakable_will,json=unbreakableWill,proto3" json:"unbreakable_will,omitempty"`
	WandSpecialization         int32 `protobuf:"varint,2,opt,name=wand_specialization,json=wandSpecialization,proto3" json:"wand_specialization,omitempty"`
	SilentResolve              int32 `protobuf:"varint,3,opt,name=silent_resolve,json=silentResolve,proto3" json:"silent_resolve,omitempty"`
	ImprovedPowerWordFortitude int32 `protobuf:"varint,4,opt,name=improved_power_word_fortitude,json=improvedPowerWordFortitude,proto3" json:"improved_power_word_fortitude,omitempty"`
	ImprovedPowerWordShield    int32 `protobuf:"varint,5,opt,name=improved_power_word_shield,json=improvedPowerWordShield,proto3" json:"improved_power_word_shield,omitempty"`
	Martyrdom                  int32 `protobuf:"varint,6,opt,name=martyrdom,proto3" json:"martyrdom,omitempty"`
	InnerFocus                 bool  `protobuf:"varint,7,opt,name=inner_focus,json=innerFocus,proto3" json:"inner_focus,omitempty"`
	Meditation                 int32 `protobuf:"varint,8,opt,name=meditation,proto3" json:"meditation,omitempty"`
	ImprovedInnerFire          int32 `protobuf:"varint,9,opt,name=improved_inner_fire,json=improvedInnerFire,proto3" json:"improved_inner_fire,omitempty"`
	MentalAgility              int32 `protobuf:"varint,10,opt,name=mental_agility,json=mentalAgility,proto3" json:"mental_agility,omitempty"`
	ImprovedManaBurn           int32 `protobuf:"varint,11,opt,name=improved_mana_burn,json=improvedManaBurn,proto3" json:"improved_mana_burn,omitempty"`
	MentalStrength             int32 `protobuf:"varint,12,opt,name=mental_strength,json=mentalStrength,proto3" json:"mental_strength,omitempty"`
	DivineSpirit               bool  `protobuf:"varint,13,opt,name=divine_spirit,json=divineSpirit,proto3" json:"divine_spirit,omitempty"`
	ForceOfWill                int32 `protobuf:"varint,14,opt,name=force_of_will,json=forceOfWill,proto3" json:"force_of_will,omitempty"`
	PowerInfusion              bool  `protobuf:"varint,15,opt,name=power_infusion,json=powerInfusion,proto3" json:"power_infusion,omitempty"`
	// Holy
	HealingFocus            int32 `protobuf:"varint,16,opt,name=healing_focus,json=healingFocus,proto3" json:"healing_focus,omitempty"`
	ImprovedRenew           int32 `protobuf:"varint,17,opt,name=improved_renew,json=improvedRenew,proto3" json:"improved_renew,omitempty"`
	HolySpecialization      int32 `protobuf:"varint,18,opt,name=holy_specialization,json=holySpecialization,proto3" json:"holy_specialization,omitempty"`
	SpellWarding            int32 `protobuf:"varint,19,opt,name=spell_warding,json=spellWarding,proto3" json:"spell_warding,omitempty"`
	DivineFury              int32 `protobuf:"varint,20,opt,name=divine_fury,json=divineFury,proto3" json:"divine_fury,omitempty"`
	HolyNova                bool  `protobuf:"varint,21,opt,name=holy_nova,json=holyNova,proto3" json:"holy_nova,omitempty"`
	BlessedRecovery         int32 `protobuf:"varint,22,opt,name=blessed_recovery,json=blessedRecovery,proto3" json:"blessed_recovery,omitempty"`
	Inspiration             int32 `protobuf:"varint,23,opt,name=inspiration,proto3" json:"inspiration,omitempty"`
	HolyReach               int32 `protobuf:"varint,24,opt,name=holy_reach,json=holyReach,proto3" json:"holy_reach,omitempty"`
	ImprovedHealing         int32 `protobuf:"varint,25,opt,name=improved_healing,json=improvedHealing,proto3" json:"improved_healing,omitempty"`
	SearingLight            int32 `protobuf:"varint,26,opt,name=searing_light,json=searingLight,proto3" json:"searing_light,omitempty"`
	ImprovedPrayerOfHealing int32 `protobuf:"varint,27,opt,name=improved_prayer_of_healing,json=improvedPrayerOfHealing,proto3" json:"improved_prayer_of_healing,omitempty"`
	SpiritOfRedemption      bool  `protobuf:"varint,28,opt,name=spirit_of_redemption,json=spiritOfRedemption,proto3" json:"spirit_of_redemption,omitempty"`
	SpiritualGuidance       int32 `protobuf:"varint,29,opt,name=spiritual_guidance,json=spiritualGuidance,proto3" json:"spiritual_guidance,omitempty"`
	SpiritualHealing        int32 `protobuf:"varint,30,opt,name=spiritual_healing,json=spiritualHealing,proto3" json:"spiritual_healing,omitempty"`
	Lightwell               bool  `protobuf:"varint,31,opt,name=lightwell,proto3" json:"lightwell,omitempty"`
	// Shadow
	SpiritTap               int32 `protobuf:"varint,32,opt,name=spirit_tap,json=spiritTap,proto3" json:"spirit_tap,omitempty"`
	Blackout                int32 `protobuf:"varint,33,opt,name=blackout,proto3" json:"blackout,omitempty"`
	ShadowAffinity          int32 `protobuf:"varint,34,opt,name=shadow_affinity,json=shadowAffinity,proto3" json:"shadow_affinity,omitempty"`
	ImprovedShadowWordPain  int32 `protobuf:"varint,35,opt,name=improved_shadow_word_pain,json=improvedShadowWordPain,proto3" json:"improved_shadow_word_pain,omitempty"`
	ShadowFocus             int32 `protobuf:"varint,36,opt,name=shadow_focus,json=shadowFocus,proto3" json:"shadow_focus,omitempty"`
	ImprovedPsychicScream   int32 `protobuf:"varint,37,opt,name=improved_psychic_scream,json=improvedPsychicScream,proto3" json:"improved_psychic_scream,omitempty"`
	ImprovedMindBlast       int32 `protobuf:"varint,38,opt,name=improved_mind_blast,json=improvedMindBlast,proto3" json:"improved_mind_blast,omitempty"`
	MindFlay                bool  `protobuf:"varint,39,opt,name=mind_flay,json=mindFlay,proto3" json:"mind_flay,omitempty"`
	ImprovedFade            int32 `protobuf:"varint,40,opt,name=improved_fade,json=improvedFade,proto3" json:"improved_fade,omitempty"`
	ShadowReach             int32 `protobuf:"varint,41,opt,name=shadow_reach,json=shadowReach,proto3" json:"shadow_reach,omitempty"`
	ShadowWeaving           int32 `protobuf:"varint,42,opt,name=shadow_weaving,json=shadowWeaving,proto3" json:"shadow_weaving,omitempty"`
	Silence                 bool  `protobuf:"varint,43,opt,name=silence,proto3" json:"silence,omitempty"`
	VampiricEmbrace         bool  `protobuf:"varint,44,opt,name=vampiric_embrace,json=vampiricEmbrace,proto3" json:"vampiric_embrace,omitempty"`
	ImprovedVampiricEmbrace int32 `protobuf:"varint,45,opt,name=improved_vampiric_embrace,json=improvedVampiricEmbrace,proto3" json:"improved_vampiric_embrace,omitempty"`
	Darkness                int32 `protobuf:"varint,46,opt,name=darkness,proto3" json:"darkness,omitempty"`
	Shadowform              bool  `protobuf:"varint,47,opt,name=shadowform,proto3" json:"shadowform,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PriestTalents) Reset() {
	*x = PriestTalents{}
	mi := &file_priest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriestTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriestTalents) ProtoMessage() {}

func (x *PriestTalents) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriestTalents.ProtoReflect.Descriptor instead.
func (*PriestTalents) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{0}
}

func (x *PriestTalents) GetUnbreakableWill() int32 {
	if x != nil {
		return x.UnbreakableWill
	}
	return 0
}

func (x *PriestTalents) GetWandSpecialization() int32 {
	if x != nil {
		return x.WandSpecialization
	}
	return 0
}

func (x *PriestTalents) GetSilentResolve() int32 {
	if x != nil {
		return x.SilentResolve
	}
	return 0
}

func (x *PriestTalents) GetImprovedPowerWordFortitude() int32 {
	if x != nil {
		return x.ImprovedPowerWordFortitude
	}
	return 0
}

func (x *PriestTalents) GetImprovedPowerWordShield() int32 {
	if x != nil {
		return x.ImprovedPowerWordShield
	}
	return 0
}

func (x *PriestTalents) GetMartyrdom() int32 {
	if x != nil {
		return x.Martyrdom
	}
	return 0
}

func (x *PriestTalents) GetInnerFocus() bool {
	if x != nil {
		return x.InnerFocus
	}
	return false
}

func (x *PriestTalents) GetMeditation() int32 {
	if x != nil {
		return x.Meditation
	}
	return 0
}

func (x *PriestTalents) GetImprovedInnerFire() int32 {
	if x != nil {
		return x.ImprovedInnerFire
	}
	return 0
}

func (x *PriestTalents) GetMentalAgility() int32 {
	if x != nil {
		return x.MentalAgility
	}
	return 0
}

func (x *PriestTalents) GetImprovedManaBurn() int32 {
	if x != nil {
		return x.ImprovedManaBurn
	}
	return 0
}

func (x *PriestTalents) GetMentalStrength() int32 {
	if x != nil {
		return x.MentalStrength
	}
	return 0
}

func (x *PriestTalents) GetDivineSpirit() bool {
	if x != nil {
		return x.DivineSpirit
	}
	return false
}

func (x *PriestTalents) GetForceOfWill() int32 {
	if x != nil {
		return x.ForceOfWill
	}
	return 0
}

func (x *PriestTalents) GetPowerInfusion() bool {
	if x != nil {
		return x.PowerInfusion
	}
	return false
}

func (x *PriestTalents) GetHealingFocus() int32 {
	if x != nil {
		return x.HealingFocus
	}
	return 0
}

func (x *PriestTalents) GetImprovedRenew() int32 {
	if x != nil {
		return x.ImprovedRenew
	}
	return 0
}

func (x *PriestTalents) GetHolySpecialization() int32 {
	if x != nil {
		return x.HolySpecialization
	}
	return 0
}

func (x *PriestTalents) GetSpellWarding() int32 {
	if x != nil {
		return x.SpellWarding
	}
	return 0
}

func (x *PriestTalents) GetDivineFury() int32 {
	if x != nil {
		return x.DivineFury
	}
	return 0
}

func (x *PriestTalents) GetHolyNova() bool {
	if x != nil {
		return x.HolyNova
	}
	return false
}

func (x *PriestTalents) GetBlessedRecovery() int32 {
	if x != nil {
		return x.BlessedRecovery
	}
	return 0
}

func (x *PriestTalents) GetInspiration() int32 {
	if x != nil {
		return x.Inspiration
	}
	return 0
}

func (x *PriestTalents) GetHolyReach() int32 {
	if x != nil {
		return x.HolyReach
	}
	return 0
}

func (x *PriestTalents) GetImprovedHealing() int32 {
	if x != nil {
		return x.ImprovedHealing
	}
	return 0
}

func (x *PriestTalents) GetSearingLight() int32 {
	if x != nil {
		return x.SearingLight
	}
	return 0
}

func (x *PriestTalents) GetImprovedPrayerOfHealing() int32 {
	if x != nil {
		return x.ImprovedPrayerOfHealing
	}
	return 0
}

func (x *PriestTalents) GetSpiritOfRedemption() bool {
	if x != nil {
		return x.SpiritOfRedemption
	}
	return false
}

func (x *PriestTalents) GetSpiritualGuidance() int32 {
	if x != nil {
		return x.SpiritualGuidance
	}
	return 0
}

func (x *PriestTalents) GetSpiritualHealing() int32 {
	if x != nil {
		return x.SpiritualHealing
	}
	return 0
}

func (x *PriestTalents) GetLightwell() bool {
	if x != nil {
		return x.Lightwell
	}
	return false
}

func (x *PriestTalents) GetSpiritTap() int32 {
	if x != nil {
		return x.SpiritTap
	}
	return 0
}

func (x *PriestTalents) GetBlackout() int32 {
	if x != nil {
		return x.Blackout
	}
	return 0
}

func (x *PriestTalents) GetShadowAffinity() int32 {
	if x != nil {
		return x.ShadowAffinity
	}
	return 0
}

func (x *PriestTalents) GetImprovedShadowWordPain() int32 {
	if x != nil {
		return x.ImprovedShadowWordPain
	}
	return 0
}

func (x *PriestTalents) GetShadowFocus() int32 {
	if x != nil {
		return x.ShadowFocus
	}
	return 0
}

func (x *PriestTalents) GetImprovedPsychicScream() int32 {
	if x != nil {
		return x.ImprovedPsychicScream
	}
	return 0
}

func (x *PriestTalents) GetImprovedMindBlast() int32 {
	if x != nil {
		return x.ImprovedMindBlast
	}
	return 0
}

func (x *PriestTalents) GetMindFlay() bool {
	if x != nil {
		return x.MindFlay
	}
	return false
}

func (x *PriestTalents) GetImprovedFade() int32 {
	if x != nil {
		return x.ImprovedFade
	}
	return 0
}

func (x *PriestTalents) GetShadowReach() int32 {
	if x != nil {
		return x.ShadowReach
	}
	return 0
}

func (x *PriestTalents) GetShadowWeaving() int32 {
	if x != nil {
		return x.ShadowWeaving
	}
	return 0
}

func (x *PriestTalents) GetSilence() bool {
	if x != nil {
		return x.Silence
	}
	return false
}

func (x *PriestTalents) GetVampiricEmbrace() bool {
	if x != nil {
		return x.VampiricEmbrace
	}
	return false
}

func (x *PriestTalents) GetImprovedVampiricEmbrace() int32 {
	if x != nil {
		return x.ImprovedVampiricEmbrace
	}
	return 0
}

func (x *PriestTalents) GetDarkness() int32 {
	if x != nil {
		return x.Darkness
	}
	return 0
}

func (x *PriestTalents) GetShadowform() bool {
	if x != nil {
		return x.Shadowform
	}
	return false
}

type ShadowPriest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *ShadowPriest_Options  `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowPriest) Reset() {
	*x = ShadowPriest{}
	mi := &file_priest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowPriest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowPriest) ProtoMessage() {}

func (x *ShadowPriest) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowPriest.ProtoReflect.Descriptor instead.
func (*ShadowPriest) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{1}
}

func (x *ShadowPriest) GetOptions() *ShadowPriest_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type HealingPriest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *HealingPriest_Options `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealingPriest) Reset() {
	*x = HealingPriest{}
	mi := &file_priest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealingPriest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealingPriest) ProtoMessage() {}

func (x *HealingPriest) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealingPriest.ProtoReflect.Descriptor instead.
func (*HealingPriest) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{2}
}

func (x *HealingPriest) GetOptions() *HealingPriest_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type ShadowPriest_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowPriest_Rotation) Reset() {
	*x = ShadowPriest_Rotation{}
	mi := &file_priest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowPriest_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowPriest_Rotation) ProtoMessage() {}

func (x *ShadowPriest_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowPriest_Rotation.ProtoReflect.Descriptor instead.
func (*ShadowPriest_Rotation) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{1, 0}
}

type ShadowPriest_Options struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	UseShadowfiend      bool                       `protobuf:"varint,1,opt,name=use_shadowfiend,json=useShadowfiend,proto3" json:"use_shadowfiend,omitempty"`
	Armor               ShadowPriest_Options_Armor `protobuf:"varint,2,opt,name=armor,proto3,enum=proto.ShadowPriest_Options_Armor" json:"armor,omitempty"`
	UseMindBlast        bool                       `protobuf:"varint,4,opt,name=use_mind_blast,json=useMindBlast,proto3" json:"use_mind_blast,omitempty"`
	PowerInfusionTarget *UnitReference             `protobuf:"bytes,5,opt,name=power_infusion_target,json=powerInfusionTarget,proto3" json:"power_infusion_target,omitempty"`
	// Deprecated: Marked as deprecated in priest.proto.
	Latency       float64 `protobuf:"fixed64,6,opt,name=latency,proto3" json:"latency,omitempty"` // Latency between actions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShadowPriest_Options) Reset() {
	*x = ShadowPriest_Options{}
	mi := &file_priest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShadowPriest_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowPriest_Options) ProtoMessage() {}

func (x *ShadowPriest_Options) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowPriest_Options.ProtoReflect.Descriptor instead.
func (*ShadowPriest_Options) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ShadowPriest_Options) GetUseShadowfiend() bool {
	if x != nil {
		return x.UseShadowfiend
	}
	return false
}

func (x *ShadowPriest_Options) GetArmor() ShadowPriest_Options_Armor {
	if x != nil {
		return x.Armor
	}
	return ShadowPriest_Options_NoArmor
}

func (x *ShadowPriest_Options) GetUseMindBlast() bool {
	if x != nil {
		return x.UseMindBlast
	}
	return false
}

func (x *ShadowPriest_Options) GetPowerInfusionTarget() *UnitReference {
	if x != nil {
		return x.PowerInfusionTarget
	}
	return nil
}

// Deprecated: Marked as deprecated in priest.proto.
func (x *ShadowPriest_Options) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

type HealingPriest_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealingPriest_Rotation) Reset() {
	*x = HealingPriest_Rotation{}
	mi := &file_priest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealingPriest_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealingPriest_Rotation) ProtoMessage() {}

func (x *HealingPriest_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealingPriest_Rotation.ProtoReflect.Descriptor instead.
func (*HealingPriest_Rotation) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{2, 0}
}

type HealingPriest_Options struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UseInnerFire        bool                   `protobuf:"varint,2,opt,name=use_inner_fire,json=useInnerFire,proto3" json:"use_inner_fire,omitempty"`
	PowerInfusionTarget *UnitReference         `protobuf:"bytes,1,opt,name=power_infusion_target,json=powerInfusionTarget,proto3" json:"power_infusion_target,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealingPriest_Options) Reset() {
	*x = HealingPriest_Options{}
	mi := &file_priest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealingPriest_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealingPriest_Options) ProtoMessage() {}

func (x *HealingPriest_Options) ProtoReflect() protoreflect.Message {
	mi := &file_priest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealingPriest_Options.ProtoReflect.Descriptor instead.
func (*HealingPriest_Options) Descriptor() ([]byte, []int) {
	return file_priest_proto_rawDescGZIP(), []int{2, 1}
}

func (x *HealingPriest_Options) GetUseInnerFire() bool {
	if x != nil {
		return x.UseInnerFire
	}
	return false
}

func (x *HealingPriest_Options) GetPowerInfusionTarget() *UnitReference {
	if x != nil {
		return x.PowerInfusionTarget
	}
	return nil
}

var File_priest_proto protoreflect.FileDescriptor

const file_priest_proto_rawDesc = "" +
	"\n" +
	"\fpriest.proto\x12\x05proto\x1a\fcommon.proto\"\x87\x0f\n" +
	"\rPriestTalents\x12)\n" +
	"\x10unbreakable_will\x18\x01 \x01(\x05R\x0funbreakableWill\x12/\n" +
	"\x13wand_specialization\x18\x02 \x01(\x05R\x12wandSpecialization\x12%\n" +
	"\x0esilent_resolve\x18\x03 \x01(\x05R\rsilentResolve\x12A\n" +
	"\x1dimproved_power_word_fortitude\x18\x04 \x01(\x05R\x1aimprovedPowerWordFortitude\x12;\n" +
	"\x1aimproved_power_word_shield\x18\x05 \x01(\x05R\x17improvedPowerWordShield\x12\x1c\n" +
	"\tmartyrdom\x18\x06 \x01(\x05R\tmartyrdom\x12\x1f\n" +
	"\vinner_focus\x18\a \x01(\bR\n" +
	"innerFocus\x12\x1e\n" +
	"\n" +
	"meditation\x18\b \x01(\x05R\n" +
	"meditation\x12.\n" +
	"\x13improved_inner_fire\x18\t \x01(\x05R\x11improvedInnerFire\x12%\n" +
	"\x0emental_agility\x18\n" +
	" \x01(\x05R\rmentalAgility\x12,\n" +
	"\x12improved_mana_burn\x18\v \x01(\x05R\x10improvedManaBurn\x12'\n" +
	"\x0fmental_strength\x18\f \x01(\x05R\x0ementalStrength\x12#\n" +
	"\rdivine_spirit\x18\r \x01(\bR\fdivineSpirit\x12\"\n" +
	"\rforce_of_will\x18\x0e \x01(\x05R\vforceOfWill\x12%\n" +
	"\x0epower_infusion\x18\x0f \x01(\bR\rpowerInfusion\x12#\n" +
	"\rhealing_focus\x18\x10 \x01(\x05R\fhealingFocus\x12%\n" +
	"\x0eimproved_renew\x18\x11 \x01(\x05R\rimprovedRenew\x12/\n" +
	"\x13holy_specialization\x18\x12 \x01(\x05R\x12holySpecialization\x12#\n" +
	"\rspell_warding\x18\x13 \x01(\x05R\fspellWarding\x12\x1f\n" +
	"\vdivine_fury\x18\x14 \x01(\x05R\n" +
	"divineFury\x12\x1b\n" +
	"\tholy_nova\x18\x15 \x01(\bR\bholyNova\x12)\n" +
	"\x10blessed_recovery\x18\x16 \x01(\x05R\x0fblessedRecovery\x12 \n" +
	"\vinspiration\x18\x17 \x01(\x05R\vinspiration\x12\x1d\n" +
	"\n" +
	"holy_reach\x18\x18 \x01(\x05R\tholyReach\x12)\n" +
	"\x10improved_healing\x18\x19 \x01(\x05R\x0fimprovedHealing\x12#\n" +
	"\rsearing_light\x18\x1a \x01(\x05R\fsearingLight\x12;\n" +
	"\x1aimproved_prayer_of_healing\x18\x1b \x01(\x05R\x17improvedPrayerOfHealing\x120\n" +
	"\x14spirit_of_redemption\x18\x1c \x01(\bR\x12spiritOfRedemption\x12-\n" +
	"\x12spiritual_guidance\x18\x1d \x01(\x05R\x11spiritualGuidance\x12+\n" +
	"\x11spiritual_healing\x18\x1e \x01(\x05R\x10spiritualHealing\x12\x1c\n" +
	"\tlightwell\x18\x1f \x01(\bR\tlightwell\x12\x1d\n" +
	"\n" +
	"spirit_tap\x18  \x01(\x05R\tspiritTap\x12\x1a\n" +
	"\bblackout\x18! \x01(\x05R\bblackout\x12'\n" +
	"\x0fshadow_affinity\x18\" \x01(\x05R\x0eshadowAffinity\x129\n" +
	"\x19improved_shadow_word_pain\x18# \x01(\x05R\x16improvedShadowWordPain\x12!\n" +
	"\fshadow_focus\x18$ \x01(\x05R\vshadowFocus\x126\n" +
	"\x17improved_psychic_scream\x18% \x01(\x05R\x15improvedPsychicScream\x12.\n" +
	"\x13improved_mind_blast\x18& \x01(\x05R\x11improvedMindBlast\x12\x1b\n" +
	"\tmind_flay\x18' \x01(\bR\bmindFlay\x12#\n" +
	"\rimproved_fade\x18( \x01(\x05R\fimprovedFade\x12!\n" +
	"\fshadow_reach\x18) \x01(\x05R\vshadowReach\x12%\n" +
	"\x0eshadow_weaving\x18* \x01(\x05R\rshadowWeaving\x12\x18\n" +
	"\asilence\x18+ \x01(\bR\asilence\x12)\n" +
	"\x10vampiric_embrace\x18, \x01(\bR\x0fvampiricEmbrace\x12:\n" +
	"\x19improved_vampiric_embrace\x18- \x01(\x05R\x17improvedVampiricEmbrace\x12\x1a\n" +
	"\bdarkness\x18. \x01(\x05R\bdarkness\x12\x1e\n" +
	"\n" +
	"shadowform\x18/ \x01(\bR\n" +
	"shadowform\"\xf2\x02\n" +
	"\fShadowPriest\x125\n" +
	"\aoptions\x18\x03 \x01(\v2\x1b.proto.ShadowPriest.OptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\x1a\x9e\x02\n" +
	"\aOptions\x12'\n" +
	"\x0fuse_shadowfiend\x18\x01 \x01(\bR\x0euseShadowfiend\x127\n" +
	"\x05armor\x18\x02 \x01(\x0e2!.proto.ShadowPriest.Options.ArmorR\x05armor\x12$\n" +
	"\x0euse_mind_blast\x18\x04 \x01(\bR\fuseMindBlast\x12H\n" +
	"\x15power_infusion_target\x18\x05 \x01(\v2\x14.proto.UnitReferenceR\x13powerInfusionTarget\x12\x1c\n" +
	"\alatency\x18\x06 \x01(\x01B\x02\x18\x01R\alatency\"#\n" +
	"\x05Armor\x12\v\n" +
	"\aNoArmor\x10\x00\x12\r\n" +
	"\tInnerFire\x10\x01\"\xce\x01\n" +
	"\rHealingPriest\x126\n" +
	"\aoptions\x18\x03 \x01(\v2\x1c.proto.HealingPriest.OptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\x1ay\n" +
	"\aOptions\x12$\n" +
	"\x0euse_inner_fire\x18\x02 \x01(\bR\fuseInnerFire\x12H\n" +
	"\x15power_infusion_target\x18\x01 \x01(\v2\x14.proto.UnitReferenceR\x13powerInfusionTargetB\tZ\a./protob\x06proto3"

var (
	file_priest_proto_rawDescOnce sync.Once
	file_priest_proto_rawDescData []byte
)

func file_priest_proto_rawDescGZIP() []byte {
	file_priest_proto_rawDescOnce.Do(func() {
		file_priest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_priest_proto_rawDesc), len(file_priest_proto_rawDesc)))
	})
	return file_priest_proto_rawDescData
}

var file_priest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_priest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_priest_proto_goTypes = []any{
	(ShadowPriest_Options_Armor)(0), // 0: proto.ShadowPriest.Options.Armor
	(*PriestTalents)(nil),           // 1: proto.PriestTalents
	(*ShadowPriest)(nil),            // 2: proto.ShadowPriest
	(*HealingPriest)(nil),           // 3: proto.HealingPriest
	(*ShadowPriest_Rotation)(nil),   // 4: proto.ShadowPriest.Rotation
	(*ShadowPriest_Options)(nil),    // 5: proto.ShadowPriest.Options
	(*HealingPriest_Rotation)(nil),  // 6: proto.HealingPriest.Rotation
	(*HealingPriest_Options)(nil),   // 7: proto.HealingPriest.Options
	(*UnitReference)(nil),           // 8: proto.UnitReference
}
var file_priest_proto_depIdxs = []int32{
	5, // 0: proto.ShadowPriest.options:type_name -> proto.ShadowPriest.Options
	7, // 1: proto.HealingPriest.options:type_name -> proto.HealingPriest.Options
	0, // 2: proto.ShadowPriest.Options.armor:type_name -> proto.ShadowPriest.Options.Armor
	8, // 3: proto.ShadowPriest.Options.power_infusion_target:type_name -> proto.UnitReference
	8, // 4: proto.HealingPriest.Options.power_infusion_target:type_name -> proto.UnitReference
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_priest_proto_init() }
func file_priest_proto_init() {
	if File_priest_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_priest_proto_rawDesc), len(file_priest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_priest_proto_goTypes,
		DependencyIndexes: file_priest_proto_depIdxs,
		EnumInfos:         file_priest_proto_enumTypes,
		MessageInfos:      file_priest_proto_msgTypes,
	}.Build()
	File_priest_proto = out.File
	file_priest_proto_goTypes = nil
	file_priest_proto_depIdxs = nil
}
