// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: rogue.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Code generated by tools/talentgen from client build 1.60.1.69893. DO NOT EDIT.
// Field order is the talent string's order: the three trees in the
// client's own order, each tier then column. core.FillTalentsProto
// reads it positionally, so a reorder silently reads the wrong talent.
type RogueTalents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assassination (tree 0, client id 182)
	// node 105742, tier 0 col 0, 3 rank(s), spell 13741
	ImprovedGouge int32 `protobuf:"varint,1,opt,name=improved_gouge,json=improvedGouge,proto3" json:"improved_gouge,omitempty"`
	// node 105723, tier 0 col 1, 2 rank(s), spell 14144
	RemorselessAttacks int32 `protobuf:"varint,2,opt,name=remorseless_attacks,json=remorselessAttacks,proto3" json:"remorseless_attacks,omitempty"`
	// node 105722, tier 0 col 2, 5 rank(s), spell 14138
	Malice int32 `protobuf:"varint,3,opt,name=malice,proto3" json:"malice,omitempty"`
	// node 105721, tier 1 col 0, 3 rank(s), spell 14156
	Ruthlessness int32 `protobuf:"varint,4,opt,name=ruthlessness,proto3" json:"ruthlessness,omitempty"`
	// node 105720, tier 1 col 1, 2 rank(s), spell 14158
	Murder int32 `protobuf:"varint,5,opt,name=murder,proto3" json:"murder,omitempty"`
	// node 105739, tier 1 col 3, 3 rank(s), spell 14165
	ImprovedSliceAndDice int32 `protobuf:"varint,6,opt,name=improved_slice_and_dice,json=improvedSliceAndDice,proto3" json:"improved_slice_and_dice,omitempty"`
	// node 105759, tier 2 col 0, 1 rank(s), spell 14179
	RelentlessStrikes bool `protobuf:"varint,7,opt,name=relentless_strikes,json=relentlessStrikes,proto3" json:"relentless_strikes,omitempty"`
	// node 105717, tier 2 col 1, 2 rank(s), spell 14168
	ImprovedExposeArmor int32 `protobuf:"varint,8,opt,name=improved_expose_armor,json=improvedExposeArmor,proto3" json:"improved_expose_armor,omitempty"`
	// node 105716, tier 2 col 2, 5 rank(s), spell 14128
	Lethality int32 `protobuf:"varint,9,opt,name=lethality,proto3" json:"lethality,omitempty"`
	// node 105714, tier 3 col 0, 5 rank(s), spell 16513
	VilePoisons int32 `protobuf:"varint,10,opt,name=vile_poisons,json=vilePoisons,proto3" json:"vile_poisons,omitempty"`
	// node 105715, tier 3 col 1, 1 rank(s), spell 14177
	ColdBlood bool `protobuf:"varint,11,opt,name=cold_blood,json=coldBlood,proto3" json:"cold_blood,omitempty"`
	// node 105713, tier 3 col 2, 5 rank(s), spell 14113
	ImprovedPoisons int32 `protobuf:"varint,12,opt,name=improved_poisons,json=improvedPoisons,proto3" json:"improved_poisons,omitempty"`
	// node 105718, tier 4 col 0, 2 rank(s), spell 14983
	Vigor int32 `protobuf:"varint,13,opt,name=vigor,proto3" json:"vigor,omitempty"`
	// node 105709, tier 4 col 1, 1 rank(s), spell 1310707
	Mutilate bool `protobuf:"varint,14,opt,name=mutilate,proto3" json:"mutilate,omitempty"`
	// node 105711, tier 4 col 2, 2 rank(s), spell 14174
	ImprovedKidneyShot int32 `protobuf:"varint,15,opt,name=improved_kidney_shot,json=improvedKidneyShot,proto3" json:"improved_kidney_shot,omitempty"`
	// node 105710, tier 5 col 2, 5 rank(s), spell 14186
	SealFate int32 `protobuf:"varint,16,opt,name=seal_fate,json=sealFate,proto3" json:"seal_fate,omitempty"`
	// node 105712, tier 6 col 1, 1 rank(s), spell 1310703
	Venom bool `protobuf:"varint,17,opt,name=venom,proto3" json:"venom,omitempty"`
	// Combat (tree 1, client id 181)
	// node 105708, tier 0 col 0, 3 rank(s), spell 14162
	ImprovedEviscerate int32 `protobuf:"varint,18,opt,name=improved_eviscerate,json=improvedEviscerate,proto3" json:"improved_eviscerate,omitempty"`
	// node 105741, tier 0 col 1, 2 rank(s), spell 13732
	ImprovedSinisterStrike int32 `protobuf:"varint,19,opt,name=improved_sinister_strike,json=improvedSinisterStrike,proto3" json:"improved_sinister_strike,omitempty"`
	// node 113398, tier 0 col 2, 5 rank(s), spell 13712
	LightningReflexes int32 `protobuf:"varint,20,opt,name=lightning_reflexes,json=lightningReflexes,proto3" json:"lightning_reflexes,omitempty"`
	// node 105719, tier 1 col 0, 3 rank(s), spell 1224716
	PuncturingWounds int32 `protobuf:"varint,21,opt,name=puncturing_wounds,json=puncturingWounds,proto3" json:"puncturing_wounds,omitempty"`
	// node 105738, tier 1 col 1, 3 rank(s), spell 13713
	Deflection int32 `protobuf:"varint,22,opt,name=deflection,proto3" json:"deflection,omitempty"`
	// node 105737, tier 1 col 2, 3 rank(s), spell 13705
	Precision int32 `protobuf:"varint,23,opt,name=precision,proto3" json:"precision,omitempty"`
	// node 105736, tier 2 col 0, 2 rank(s), spell 13742
	Endurance int32 `protobuf:"varint,24,opt,name=endurance,proto3" json:"endurance,omitempty"`
	// node 105735, tier 2 col 1, 1 rank(s), spell 14251
	Riposte bool `protobuf:"varint,25,opt,name=riposte,proto3" json:"riposte,omitempty"`
	// node 105732, tier 2 col 3, 2 rank(s), spell 13743
	ImprovedSprint int32 `protobuf:"varint,26,opt,name=improved_sprint,json=improvedSprint,proto3" json:"improved_sprint,omitempty"`
	// node 105733, tier 3 col 0, 2 rank(s), spell 13754
	ImprovedKick int32 `protobuf:"varint,27,opt,name=improved_kick,json=improvedKick,proto3" json:"improved_kick,omitempty"`
	// node 108100, tier 3 col 1, 1 rank(s), spell 1310711
	FlawlessExecution bool `protobuf:"varint,28,opt,name=flawless_execution,json=flawlessExecution,proto3" json:"flawless_execution,omitempty"`
	// node 105740, tier 3 col 2, 5 rank(s), spell 13715
	DualWieldSpecialization int32 `protobuf:"varint,29,opt,name=dual_wield_specialization,json=dualWieldSpecialization,proto3" json:"dual_wield_specialization,omitempty"`
	// node 105728, tier 4 col 1, 1 rank(s), spell 13877
	BladeFlurry bool `protobuf:"varint,30,opt,name=blade_flurry,json=bladeFlurry,proto3" json:"blade_flurry,omitempty"`
	// node 105727, tier 4 col 2, 5 rank(s), spell 13960
	HackAndSlash int32 `protobuf:"varint,31,opt,name=hack_and_slash,json=hackAndSlash,proto3" json:"hack_and_slash,omitempty"`
	// node 105726, tier 5 col 1, 2 rank(s), spell 30919
	WeaponExpertise int32 `protobuf:"varint,32,opt,name=weapon_expertise,json=weaponExpertise,proto3" json:"weapon_expertise,omitempty"`
	// node 105730, tier 5 col 2, 3 rank(s), spell 18427
	Aggression int32 `protobuf:"varint,33,opt,name=aggression,proto3" json:"aggression,omitempty"`
	// node 105724, tier 6 col 1, 1 rank(s), spell 13750
	AdrenalineRush bool `protobuf:"varint,34,opt,name=adrenaline_rush,json=adrenalineRush,proto3" json:"adrenaline_rush,omitempty"`
	// Subtlety (tree 2, client id 183)
	// node 105756, tier 0 col 0, 5 rank(s), spell 13975
	Camouflage int32 `protobuf:"varint,35,opt,name=camouflage,proto3" json:"camouflage,omitempty"`
	// node 105761, tier 0 col 1, 3 rank(s), spell 13958
	MasterOfDeception int32 `protobuf:"varint,36,opt,name=master_of_deception,json=masterOfDeception,proto3" json:"master_of_deception,omitempty"`
	// node 105760, tier 0 col 2, 2 rank(s), spell 14057
	Opportunity int32 `protobuf:"varint,37,opt,name=opportunity,proto3" json:"opportunity,omitempty"`
	// node 105751, tier 1 col 0, 3 rank(s), spell 13983
	Setup int32 `protobuf:"varint,38,opt,name=setup,proto3" json:"setup,omitempty"`
	// node 105753, tier 1 col 1, 2 rank(s), spell 13981
	Elusiveness int32 `protobuf:"varint,39,opt,name=elusiveness,proto3" json:"elusiveness,omitempty"`
	// node 105757, tier 1 col 2, 2 rank(s), spell 1224782
	DirtyTricks int32 `protobuf:"varint,40,opt,name=dirty_tricks,json=dirtyTricks,proto3" json:"dirty_tricks,omitempty"`
	// node 105749, tier 1 col 3, 3 rank(s), spell 14079
	ImprovedAmbush int32 `protobuf:"varint,41,opt,name=improved_ambush,json=improvedAmbush,proto3" json:"improved_ambush,omitempty"`
	// node 105755, tier 2 col 0, 3 rank(s), spell 13976
	Initiative int32 `protobuf:"varint,42,opt,name=initiative,proto3" json:"initiative,omitempty"`
	// node 105754, tier 2 col 1, 1 rank(s), spell 14278
	GhostlyStrike bool `protobuf:"varint,43,opt,name=ghostly_strike,json=ghostlyStrike,proto3" json:"ghostly_strike,omitempty"`
	// node 110868, tier 2 col 2, 2 rank(s), spell 14084
	ImprovedDistract int32 `protobuf:"varint,44,opt,name=improved_distract,json=improvedDistract,proto3" json:"improved_distract,omitempty"`
	// node 105747, tier 3 col 0, 2 rank(s), spell 30894
	HeightenedSenses int32 `protobuf:"varint,45,opt,name=heightened_senses,json=heightenedSenses,proto3" json:"heightened_senses,omitempty"`
	// node 105743, tier 3 col 1, 1 rank(s), spell 14183
	Premeditation bool `protobuf:"varint,46,opt,name=premeditation,proto3" json:"premeditation,omitempty"`
	// node 105752, tier 3 col 2, 3 rank(s), spell 14171
	SerratedBlades int32 `protobuf:"varint,47,opt,name=serrated_blades,json=serratedBlades,proto3" json:"serrated_blades,omitempty"`
	// node 105745, tier 4 col 0, 2 rank(s), spell 14082
	DirtyDeeds int32 `protobuf:"varint,48,opt,name=dirty_deeds,json=dirtyDeeds,proto3" json:"dirty_deeds,omitempty"`
	// node 105746, tier 4 col 1, 1 rank(s), spell 14185
	Preparation bool `protobuf:"varint,49,opt,name=preparation,proto3" json:"preparation,omitempty"`
	// node 105748, tier 4 col 2, 1 rank(s), spell 16511
	Hemorrhage bool `protobuf:"varint,50,opt,name=hemorrhage,proto3" json:"hemorrhage,omitempty"`
	// node 110867, tier 5 col 0, 5 rank(s), spell 1310728
	Quietus int32 `protobuf:"varint,51,opt,name=quietus,proto3" json:"quietus,omitempty"`
	// node 105750, tier 5 col 2, 5 rank(s), spell 462708
	Cutthroat int32 `protobuf:"varint,52,opt,name=cutthroat,proto3" json:"cutthroat,omitempty"`
	// node 110866, tier 6 col 1, 1 rank(s), spell 1310721
	ThousandCuts  bool `protobuf:"varint,53,opt,name=thousand_cuts,json=thousandCuts,proto3" json:"thousand_cuts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RogueTalents) Reset() {
	*x = RogueTalents{}
	mi := &file_rogue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RogueTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RogueTalents) ProtoMessage() {}

func (x *RogueTalents) ProtoReflect() protoreflect.Message {
	mi := &file_rogue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RogueTalents.ProtoReflect.Descriptor instead.
func (*RogueTalents) Descriptor() ([]byte, []int) {
	return file_rogue_proto_rawDescGZIP(), []int{0}
}

func (x *RogueTalents) GetImprovedGouge() int32 {
	if x != nil {
		return x.ImprovedGouge
	}
	return 0
}

func (x *RogueTalents) GetRemorselessAttacks() int32 {
	if x != nil {
		return x.RemorselessAttacks
	}
	return 0
}

func (x *RogueTalents) GetMalice() int32 {
	if x != nil {
		return x.Malice
	}
	return 0
}

func (x *RogueTalents) GetRuthlessness() int32 {
	if x != nil {
		return x.Ruthlessness
	}
	return 0
}

func (x *RogueTalents) GetMurder() int32 {
	if x != nil {
		return x.Murder
	}
	return 0
}

func (x *RogueTalents) GetImprovedSliceAndDice() int32 {
	if x != nil {
		return x.ImprovedSliceAndDice
	}
	return 0
}

func (x *RogueTalents) GetRelentlessStrikes() bool {
	if x != nil {
		return x.RelentlessStrikes
	}
	return false
}

func (x *RogueTalents) GetImprovedExposeArmor() int32 {
	if x != nil {
		return x.ImprovedExposeArmor
	}
	return 0
}

func (x *RogueTalents) GetLethality() int32 {
	if x != nil {
		return x.Lethality
	}
	return 0
}

func (x *RogueTalents) GetVilePoisons() int32 {
	if x != nil {
		return x.VilePoisons
	}
	return 0
}

func (x *RogueTalents) GetColdBlood() bool {
	if x != nil {
		return x.ColdBlood
	}
	return false
}

func (x *RogueTalents) GetImprovedPoisons() int32 {
	if x != nil {
		return x.ImprovedPoisons
	}
	return 0
}

func (x *RogueTalents) GetVigor() int32 {
	if x != nil {
		return x.Vigor
	}
	return 0
}

func (x *RogueTalents) GetMutilate() bool {
	if x != nil {
		return x.Mutilate
	}
	return false
}

func (x *RogueTalents) GetImprovedKidneyShot() int32 {
	if x != nil {
		return x.ImprovedKidneyShot
	}
	return 0
}

func (x *RogueTalents) GetSealFate() int32 {
	if x != nil {
		return x.SealFate
	}
	return 0
}

func (x *RogueTalents) GetVenom() bool {
	if x != nil {
		return x.Venom
	}
	return false
}

func (x *RogueTalents) GetImprovedEviscerate() int32 {
	if x != nil {
		return x.ImprovedEviscerate
	}
	return 0
}

func (x *RogueTalents) GetImprovedSinisterStrike() int32 {
	if x != nil {
		return x.ImprovedSinisterStrike
	}
	return 0
}

func (x *RogueTalents) GetLightningReflexes() int32 {
	if x != nil {
		return x.LightningReflexes
	}
	return 0
}

func (x *RogueTalents) GetPuncturingWounds() int32 {
	if x != nil {
		return x.PuncturingWounds
	}
	return 0
}

func (x *RogueTalents) GetDeflection() int32 {
	if x != nil {
		return x.Deflection
	}
	return 0
}

func (x *RogueTalents) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *RogueTalents) GetEndurance() int32 {
	if x != nil {
		return x.Endurance
	}
	return 0
}

func (x *RogueTalents) GetRiposte() bool {
	if x != nil {
		return x.Riposte
	}
	return false
}

func (x *RogueTalents) GetImprovedSprint() int32 {
	if x != nil {
		return x.ImprovedSprint
	}
	return 0
}

func (x *RogueTalents) GetImprovedKick() int32 {
	if x != nil {
		return x.ImprovedKick
	}
	return 0
}

func (x *RogueTalents) GetFlawlessExecution() bool {
	if x != nil {
		return x.FlawlessExecution
	}
	return false
}

func (x *RogueTalents) GetDualWieldSpecialization() int32 {
	if x != nil {
		return x.DualWieldSpecialization
	}
	return 0
}

func (x *RogueTalents) GetBladeFlurry() bool {
	if x != nil {
		return x.BladeFlurry
	}
	return false
}

func (x *RogueTalents) GetHackAndSlash() int32 {
	if x != nil {
		return x.HackAndSlash
	}
	return 0
}

func (x *RogueTalents) GetWeaponExpertise() int32 {
	if x != nil {
		return x.WeaponExpertise
	}
	return 0
}

func (x *RogueTalents) GetAggression() int32 {
	if x != nil {
		return x.Aggression
	}
	return 0
}

func (x *RogueTalents) GetAdrenalineRush() bool {
	if x != nil {
		return x.AdrenalineRush
	}
	return false
}

func (x *RogueTalents) GetCamouflage() int32 {
	if x != nil {
		return x.Camouflage
	}
	return 0
}

func (x *RogueTalents) GetMasterOfDeception() int32 {
	if x != nil {
		return x.MasterOfDeception
	}
	return 0
}

func (x *RogueTalents) GetOpportunity() int32 {
	if x != nil {
		return x.Opportunity
	}
	return 0
}

func (x *RogueTalents) GetSetup() int32 {
	if x != nil {
		return x.Setup
	}
	return 0
}

func (x *RogueTalents) GetElusiveness() int32 {
	if x != nil {
		return x.Elusiveness
	}
	return 0
}

func (x *RogueTalents) GetDirtyTricks() int32 {
	if x != nil {
		return x.DirtyTricks
	}
	return 0
}

func (x *RogueTalents) GetImprovedAmbush() int32 {
	if x != nil {
		return x.ImprovedAmbush
	}
	return 0
}

func (x *RogueTalents) GetInitiative() int32 {
	if x != nil {
		return x.Initiative
	}
	return 0
}

func (x *RogueTalents) GetGhostlyStrike() bool {
	if x != nil {
		return x.GhostlyStrike
	}
	return false
}

func (x *RogueTalents) GetImprovedDistract() int32 {
	if x != nil {
		return x.ImprovedDistract
	}
	return 0
}

func (x *RogueTalents) GetHeightenedSenses() int32 {
	if x != nil {
		return x.HeightenedSenses
	}
	return 0
}

func (x *RogueTalents) GetPremeditation() bool {
	if x != nil {
		return x.Premeditation
	}
	return false
}

func (x *RogueTalents) GetSerratedBlades() int32 {
	if x != nil {
		return x.SerratedBlades
	}
	return 0
}

func (x *RogueTalents) GetDirtyDeeds() int32 {
	if x != nil {
		return x.DirtyDeeds
	}
	return 0
}

func (x *RogueTalents) GetPreparation() bool {
	if x != nil {
		return x.Preparation
	}
	return false
}

func (x *RogueTalents) GetHemorrhage() bool {
	if x != nil {
		return x.Hemorrhage
	}
	return false
}

func (x *RogueTalents) GetQuietus() int32 {
	if x != nil {
		return x.Quietus
	}
	return 0
}

func (x *RogueTalents) GetCutthroat() int32 {
	if x != nil {
		return x.Cutthroat
	}
	return 0
}

func (x *RogueTalents) GetThousandCuts() bool {
	if x != nil {
		return x.ThousandCuts
	}
	return false
}

type RogueOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RogueOptions) Reset() {
	*x = RogueOptions{}
	mi := &file_rogue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RogueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RogueOptions) ProtoMessage() {}

func (x *RogueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_rogue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RogueOptions.ProtoReflect.Descriptor instead.
func (*RogueOptions) Descriptor() ([]byte, []int) {
	return file_rogue_proto_rawDescGZIP(), []int{1}
}

type Rogue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *RogueOptions          `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rogue) Reset() {
	*x = Rogue{}
	mi := &file_rogue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rogue) ProtoMessage() {}

func (x *Rogue) ProtoReflect() protoreflect.Message {
	mi := &file_rogue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rogue.ProtoReflect.Descriptor instead.
func (*Rogue) Descriptor() ([]byte, []int) {
	return file_rogue_proto_rawDescGZIP(), []int{2}
}

func (x *Rogue) GetOptions() *RogueOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type TankRogue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *RogueOptions          `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TankRogue) Reset() {
	*x = TankRogue{}
	mi := &file_rogue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TankRogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankRogue) ProtoMessage() {}

func (x *TankRogue) ProtoReflect() protoreflect.Message {
	mi := &file_rogue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankRogue.ProtoReflect.Descriptor instead.
func (*TankRogue) Descriptor() ([]byte, []int) {
	return file_rogue_proto_rawDescGZIP(), []int{3}
}

func (x *TankRogue) GetOptions() *RogueOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type Rogue_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rogue_Rotation) Reset() {
	*x = Rogue_Rotation{}
	mi := &file_rogue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rogue_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rogue_Rotation) ProtoMessage() {}

func (x *Rogue_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_rogue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rogue_Rotation.ProtoReflect.Descriptor instead.
func (*Rogue_Rotation) Descriptor() ([]byte, []int) {
	return file_rogue_proto_rawDescGZIP(), []int{2, 0}
}

type TankRogue_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TankRogue_Rotation) Reset() {
	*x = TankRogue_Rotation{}
	mi := &file_rogue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TankRogue_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankRogue_Rotation) ProtoMessage() {}

func (x *TankRogue_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_rogue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankRogue_Rotation.ProtoReflect.Descriptor instead.
func (*TankRogue_Rotation) Descriptor() ([]byte, []int) {
	return file_rogue_proto_rawDescGZIP(), []int{3, 0}
}

var File_rogue_proto protoreflect.FileDescriptor

const file_rogue_proto_rawDesc = "" +
	"\n" +
	"\vrogue.proto\x12\x05proto\"\xcf\x0f\n" +
	"\fRogueTalents\x12%\n" +
	"\x0eimproved_gouge\x18\x01 \x01(\x05R\rimprovedGouge\x12/\n" +
	"\x13remorseless_attacks\x18\x02 \x01(\x05R\x12remorselessAttacks\x12\x16\n" +
	"\x06malice\x18\x03 \x01(\x05R\x06malice\x12\"\n" +
	"\fruthlessness\x18\x04 \x01(\x05R\fruthlessness\x12\x16\n" +
	"\x06murder\x18\x05 \x01(\x05R\x06murder\x125\n" +
	"\x17improved_slice_and_dice\x18\x06 \x01(\x05R\x14improvedSliceAndDice\x12-\n" +
	"\x12relentless_strikes\x18\a \x01(\bR\x11relentlessStrikes\x122\n" +
	"\x15improved_expose_armor\x18\b \x01(\x05R\x13improvedExposeArmor\x12\x1c\n" +
	"\tlethality\x18\t \x01(\x05R\tlethality\x12!\n" +
	"\fvile_poisons\x18\n" +
	" \x01(\x05R\vvilePoisons\x12\x1d\n" +
	"\n" +
	"cold_blood\x18\v \x01(\bR\tcoldBlood\x12)\n" +
	"\x10improved_poisons\x18\f \x01(\x05R\x0fimprovedPoisons\x12\x14\n" +
	"\x05vigor\x18\r \x01(\x05R\x05vigor\x12\x1a\n" +
	"\bmutilate\x18\x0e \x01(\bR\bmutilate\x120\n" +
	"\x14improved_kidney_shot\x18\x0f \x01(\x05R\x12improvedKidneyShot\x12\x1b\n" +
	"\tseal_fate\x18\x10 \x01(\x05R\bsealFate\x12\x14\n" +
	"\x05venom\x18\x11 \x01(\bR\x05venom\x12/\n" +
	"\x13improved_eviscerate\x18\x12 \x01(\x05R\x12improvedEviscerate\x128\n" +
	"\x18improved_sinister_strike\x18\x13 \x01(\x05R\x16improvedSinisterStrike\x12-\n" +
	"\x12lightning_reflexes\x18\x14 \x01(\x05R\x11lightningReflexes\x12+\n" +
	"\x11puncturing_wounds\x18\x15 \x01(\x05R\x10puncturingWounds\x12\x1e\n" +
	"\n" +
	"deflection\x18\x16 \x01(\x05R\n" +
	"deflection\x12\x1c\n" +
	"\tprecision\x18\x17 \x01(\x05R\tprecision\x12\x1c\n" +
	"\tendurance\x18\x18 \x01(\x05R\tendurance\x12\x18\n" +
	"\ariposte\x18\x19 \x01(\bR\ariposte\x12'\n" +
	"\x0fimproved_sprint\x18\x1a \x01(\x05R\x0eimprovedSprint\x12#\n" +
	"\rimproved_kick\x18\x1b \x01(\x05R\fimprovedKick\x12-\n" +
	"\x12flawless_execution\x18\x1c \x01(\bR\x11flawlessExecution\x12:\n" +
	"\x19dual_wield_specialization\x18\x1d \x01(\x05R\x17dualWieldSpecialization\x12!\n" +
	"\fblade_flurry\x18\x1e \x01(\bR\vbladeFlurry\x12$\n" +
	"\x0ehack_and_slash\x18\x1f \x01(\x05R\fhackAndSlash\x12)\n" +
	"\x10weapon_expertise\x18  \x01(\x05R\x0fweaponExpertise\x12\x1e\n" +
	"\n" +
	"aggression\x18! \x01(\x05R\n" +
	"aggression\x12'\n" +
	"\x0fadrenaline_rush\x18\" \x01(\bR\x0eadrenalineRush\x12\x1e\n" +
	"\n" +
	"camouflage\x18# \x01(\x05R\n" +
	"camouflage\x12.\n" +
	"\x13master_of_deception\x18$ \x01(\x05R\x11masterOfDeception\x12 \n" +
	"\vopportunity\x18% \x01(\x05R\vopportunity\x12\x14\n" +
	"\x05setup\x18& \x01(\x05R\x05setup\x12 \n" +
	"\velusiveness\x18' \x01(\x05R\velusiveness\x12!\n" +
	"\fdirty_tricks\x18( \x01(\x05R\vdirtyTricks\x12'\n" +
	"\x0fimproved_ambush\x18) \x01(\x05R\x0eimprovedAmbush\x12\x1e\n" +
	"\n" +
	"initiative\x18* \x01(\x05R\n" +
	"initiative\x12%\n" +
	"\x0eghostly_strike\x18+ \x01(\bR\rghostlyStrike\x12+\n" +
	"\x11improved_distract\x18, \x01(\x05R\x10improvedDistract\x12+\n" +
	"\x11heightened_senses\x18- \x01(\x05R\x10heightenedSenses\x12$\n" +
	"\rpremeditation\x18. \x01(\bR\rpremeditation\x12'\n" +
	"\x0fserrated_blades\x18/ \x01(\x05R\x0eserratedBlades\x12\x1f\n" +
	"\vdirty_deeds\x180 \x01(\x05R\n" +
	"dirtyDeeds\x12 \n" +
	"\vpreparation\x181 \x01(\bR\vpreparation\x12\x1e\n" +
	"\n" +
	"hemorrhage\x182 \x01(\bR\n" +
	"hemorrhage\x12\x18\n" +
	"\aquietus\x183 \x01(\x05R\aquietus\x12\x1c\n" +
	"\tcutthroat\x184 \x01(\x05R\tcutthroat\x12#\n" +
	"\rthousand_cuts\x185 \x01(\bR\fthousandCuts\"\x0e\n" +
	"\fRogueOptions\"B\n" +
	"\x05Rogue\x12-\n" +
	"\aoptions\x18\x02 \x01(\v2\x13.proto.RogueOptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\"F\n" +
	"\tTankRogue\x12-\n" +
	"\aoptions\x18\x02 \x01(\v2\x13.proto.RogueOptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotationB\tZ\a./protob\x06proto3"

var (
	file_rogue_proto_rawDescOnce sync.Once
	file_rogue_proto_rawDescData []byte
)

func file_rogue_proto_rawDescGZIP() []byte {
	file_rogue_proto_rawDescOnce.Do(func() {
		file_rogue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rogue_proto_rawDesc), len(file_rogue_proto_rawDesc)))
	})
	return file_rogue_proto_rawDescData
}

var file_rogue_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rogue_proto_goTypes = []any{
	(*RogueTalents)(nil),       // 0: proto.RogueTalents
	(*RogueOptions)(nil),       // 1: proto.RogueOptions
	(*Rogue)(nil),              // 2: proto.Rogue
	(*TankRogue)(nil),          // 3: proto.TankRogue
	(*Rogue_Rotation)(nil),     // 4: proto.Rogue.Rotation
	(*TankRogue_Rotation)(nil), // 5: proto.TankRogue.Rotation
}
var file_rogue_proto_depIdxs = []int32{
	1, // 0: proto.Rogue.options:type_name -> proto.RogueOptions
	1, // 1: proto.TankRogue.options:type_name -> proto.RogueOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rogue_proto_init() }
func file_rogue_proto_init() {
	if File_rogue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rogue_proto_rawDesc), len(file_rogue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rogue_proto_goTypes,
		DependencyIndexes: file_rogue_proto_depIdxs,
		MessageInfos:      file_rogue_proto_msgTypes,
	}.Build()
	File_rogue_proto = out.File
	file_rogue_proto_goTypes = nil
	file_rogue_proto_depIdxs = nil
}
