// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: warlock.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WarlockOptions_Summon int32

const (
	WarlockOptions_NoSummon   WarlockOptions_Summon = 0
	WarlockOptions_Imp        WarlockOptions_Summon = 1
	WarlockOptions_Voidwalker WarlockOptions_Summon = 2
	WarlockOptions_Succubus   WarlockOptions_Summon = 3
	WarlockOptions_Felhunter  WarlockOptions_Summon = 4
)

// Enum value maps for WarlockOptions_Summon.
var (
	WarlockOptions_Summon_name = map[int32]string{
		0: "NoSummon",
		1: "Imp",
		2: "Voidwalker",
		3: "Succubus",
		4: "Felhunter",
	}
	WarlockOptions_Summon_value = map[string]int32{
		"NoSummon":   0,
		"Imp":        1,
		"Voidwalker": 2,
		"Succubus":   3,
		"Felhunter":  4,
	}
)

func (x WarlockOptions_Summon) Enum() *WarlockOptions_Summon {
	p := new(WarlockOptions_Summon)
	*p = x
	return p
}

func (x WarlockOptions_Summon) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarlockOptions_Summon) Descriptor() protoreflect.EnumDescriptor {
	return file_warlock_proto_enumTypes[0].Descriptor()
}

func (WarlockOptions_Summon) Type() protoreflect.EnumType {
	return &file_warlock_proto_enumTypes[0]
}

func (x WarlockOptions_Summon) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WarlockOptions_Summon.Descriptor instead.
func (WarlockOptions_Summon) EnumDescriptor() ([]byte, []int) {
	return file_warlock_proto_rawDescGZIP(), []int{2, 0}
}

type WarlockOptions_Armor int32

const (
	WarlockOptions_NoArmor    WarlockOptions_Armor = 0
	WarlockOptions_DemonArmor WarlockOptions_Armor = 1
)

// Enum value maps for WarlockOptions_Armor.
var (
	WarlockOptions_Armor_name = map[int32]string{
		0: "NoArmor",
		1: "DemonArmor",
	}
	WarlockOptions_Armor_value = map[string]int32{
		"NoArmor":    0,
		"DemonArmor": 1,
	}
)

func (x WarlockOptions_Armor) Enum() *WarlockOptions_Armor {
	p := new(WarlockOptions_Armor)
	*p = x
	return p
}

func (x WarlockOptions_Armor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarlockOptions_Armor) Descriptor() protoreflect.EnumDescriptor {
	return file_warlock_proto_enumTypes[1].Descriptor()
}

func (WarlockOptions_Armor) Type() protoreflect.EnumType {
	return &file_warlock_proto_enumTypes[1]
}

func (x WarlockOptions_Armor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WarlockOptions_Armor.Descriptor instead.
func (WarlockOptions_Armor) EnumDescriptor() ([]byte, []int) {
	return file_warlock_proto_rawDescGZIP(), []int{2, 1}
}

type WarlockOptions_WeaponImbue int32

const (
	WarlockOptions_NoWeaponImbue WarlockOptions_WeaponImbue = 0
	WarlockOptions_Spellstone    WarlockOptions_WeaponImbue = 1
	WarlockOptions_Firestone     WarlockOptions_WeaponImbue = 2
)

// Enum value maps for WarlockOptions_WeaponImbue.
var (
	WarlockOptions_WeaponImbue_name = map[int32]string{
		0: "NoWeaponImbue",
		1: "Spellstone",
		2: "Firestone",
	}
	WarlockOptions_WeaponImbue_value = map[string]int32{
		"NoWeaponImbue": 0,
		"Spellstone":    1,
		"Firestone":     2,
	}
)

func (x WarlockOptions_WeaponImbue) Enum() *WarlockOptions_WeaponImbue {
	p := new(WarlockOptions_WeaponImbue)
	*p = x
	return p
}

func (x WarlockOptions_WeaponImbue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarlockOptions_WeaponImbue) Descriptor() protoreflect.EnumDescriptor {
	return file_warlock_proto_enumTypes[2].Descriptor()
}

func (WarlockOptions_WeaponImbue) Type() protoreflect.EnumType {
	return &file_warlock_proto_enumTypes[2]
}

func (x WarlockOptions_WeaponImbue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WarlockOptions_WeaponImbue.Descriptor instead.
func (WarlockOptions_WeaponImbue) EnumDescriptor() ([]byte, []int) {
	return file_warlock_proto_rawDescGZIP(), []int{2, 2}
}

type WarlockOptions_MaxFireboltRank int32

const (
	WarlockOptions_NoMaximum WarlockOptions_MaxFireboltRank = 0
	WarlockOptions_Rank1     WarlockOptions_MaxFireboltRank = 1
	WarlockOptions_Rank2     WarlockOptions_MaxFireboltRank = 2
	WarlockOptions_Rank3     WarlockOptions_MaxFireboltRank = 3
	WarlockOptions_Rank4     WarlockOptions_MaxFireboltRank = 4
	WarlockOptions_Rank5     WarlockOptions_MaxFireboltRank = 5
	WarlockOptions_Rank6     WarlockOptions_MaxFireboltRank = 6
	WarlockOptions_Rank7     WarlockOptions_MaxFireboltRank = 7
	WarlockOptions_Rank8     WarlockOptions_MaxFireboltRank = 8
)

// Enum value maps for WarlockOptions_MaxFireboltRank.
var (
	WarlockOptions_MaxFireboltRank_name = map[int32]string{
		0: "NoMaximum",
		1: "Rank1",
		2: "Rank2",
		3: "Rank3",
		4: "Rank4",
		5: "Rank5",
		6: "Rank6",
		7: "Rank7",
		8: "Rank8",
	}
	WarlockOptions_MaxFireboltRank_value = map[string]int32{
		"NoMaximum": 0,
		"Rank1":     1,
		"Rank2":     2,
		"Rank3":     3,
		"Rank4":     4,
		"Rank5":     5,
		"Rank6":     6,
		"Rank7":     7,
		"Rank8":     8,
	}
)

func (x WarlockOptions_MaxFireboltRank) Enum() *WarlockOptions_MaxFireboltRank {
	p := new(WarlockOptions_MaxFireboltRank)
	*p = x
	return p
}

func (x WarlockOptions_MaxFireboltRank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarlockOptions_MaxFireboltRank) Descriptor() protoreflect.EnumDescriptor {
	return file_warlock_proto_enumTypes[3].Descriptor()
}

func (WarlockOptions_MaxFireboltRank) Type() protoreflect.EnumType {
	return &file_warlock_proto_enumTypes[3]
}

func (x WarlockOptions_MaxFireboltRank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WarlockOptions_MaxFireboltRank.Descriptor instead.
func (WarlockOptions_MaxFireboltRank) EnumDescriptor() ([]byte, []int) {
	return file_warlock_proto_rawDescGZIP(), []int{2, 3}
}

type WarlockTalents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Affliction
	Suppression               int32 `protobuf:"varint,1,opt,name=suppression,proto3" json:"suppression,omitempty"`
	ImprovedCorruption        int32 `protobuf:"varint,2,opt,name=improved_corruption,json=improvedCorruption,proto3" json:"improved_corruption,omitempty"`
	ImprovedCurseOfWeakness   int32 `protobuf:"varint,3,opt,name=improved_curse_of_weakness,json=improvedCurseOfWeakness,proto3" json:"improved_curse_of_weakness,omitempty"`
	ImprovedDrainSoul         int32 `protobuf:"varint,4,opt,name=improved_drain_soul,json=improvedDrainSoul,proto3" json:"improved_drain_soul,omitempty"`
	ImprovedLifeTap           int32 `protobuf:"varint,5,opt,name=improved_life_tap,json=improvedLifeTap,proto3" json:"improved_life_tap,omitempty"`
	ImprovedDrainLife         int32 `protobuf:"varint,6,opt,name=improved_drain_life,json=improvedDrainLife,proto3" json:"improved_drain_life,omitempty"`
	ImprovedCurseOfAgony      int32 `protobuf:"varint,7,opt,name=improved_curse_of_agony,json=improvedCurseOfAgony,proto3" json:"improved_curse_of_agony,omitempty"`
	FelConcentration          int32 `protobuf:"varint,8,opt,name=fel_concentration,json=felConcentration,proto3" json:"fel_concentration,omitempty"`
	AmplifyCurse              bool  `protobuf:"varint,9,opt,name=amplify_curse,json=amplifyCurse,proto3" json:"amplify_curse,omitempty"`
	GrimReach                 int32 `protobuf:"varint,10,opt,name=grim_reach,json=grimReach,proto3" json:"grim_reach,omitempty"`
	Nightfall                 int32 `protobuf:"varint,11,opt,name=nightfall,proto3" json:"nightfall,omitempty"`
	ImprovedDrainMana         int32 `protobuf:"varint,12,opt,name=improved_drain_mana,json=improvedDrainMana,proto3" json:"improved_drain_mana,omitempty"`
	SiphonLife                bool  `protobuf:"varint,13,opt,name=siphon_life,json=siphonLife,proto3" json:"siphon_life,omitempty"`
	CurseOfExhaustion         bool  `protobuf:"varint,14,opt,name=curse_of_exhaustion,json=curseOfExhaustion,proto3" json:"curse_of_exhaustion,omitempty"`
	ImprovedCurseOfExhaustion int32 `protobuf:"varint,15,opt,name=improved_curse_of_exhaustion,json=improvedCurseOfExhaustion,proto3" json:"improved_curse_of_exhaustion,omitempty"`
	ShadowMastery             int32 `protobuf:"varint,16,opt,name=shadow_mastery,json=shadowMastery,proto3" json:"shadow_mastery,omitempty"`
	DarkPact                  bool  `protobuf:"varint,17,opt,name=dark_pact,json=darkPact,proto3" json:"dark_pact,omitempty"`
	// Demonology
	ImprovedHealthstone    int32 `protobuf:"varint,18,opt,name=improved_healthstone,json=improvedHealthstone,proto3" json:"improved_healthstone,omitempty"`
	ImprovedImp            int32 `protobuf:"varint,19,opt,name=improved_imp,json=improvedImp,proto3" json:"improved_imp,omitempty"`
	DemonicEmbrace         int32 `protobuf:"varint,20,opt,name=demonic_embrace,json=demonicEmbrace,proto3" json:"demonic_embrace,omitempty"`
	ImprovedHealthFunnel   int32 `protobuf:"varint,21,opt,name=improved_health_funnel,json=improvedHealthFunnel,proto3" json:"improved_health_funnel,omitempty"`
	ImprovedVoidwalker     int32 `protobuf:"varint,22,opt,name=improved_voidwalker,json=improvedVoidwalker,proto3" json:"improved_voidwalker,omitempty"`
	FelIntellect           int32 `protobuf:"varint,23,opt,name=fel_intellect,json=felIntellect,proto3" json:"fel_intellect,omitempty"`
	ImprovedSayaad         int32 `protobuf:"varint,24,opt,name=improved_sayaad,json=improvedSayaad,proto3" json:"improved_sayaad,omitempty"`
	FelDomination          bool  `protobuf:"varint,25,opt,name=fel_domination,json=felDomination,proto3" json:"fel_domination,omitempty"`
	FelStamina             int32 `protobuf:"varint,26,opt,name=fel_stamina,json=felStamina,proto3" json:"fel_stamina,omitempty"`
	MasterSummoner         int32 `protobuf:"varint,27,opt,name=master_summoner,json=masterSummoner,proto3" json:"master_summoner,omitempty"`
	UnholyPower            int32 `protobuf:"varint,28,opt,name=unholy_power,json=unholyPower,proto3" json:"unholy_power,omitempty"`
	ImprovedSubjugateDemon int32 `protobuf:"varint,29,opt,name=improved_subjugate_demon,json=improvedSubjugateDemon,proto3" json:"improved_subjugate_demon,omitempty"`
	DemonicSacrifice       bool  `protobuf:"varint,30,opt,name=demonic_sacrifice,json=demonicSacrifice,proto3" json:"demonic_sacrifice,omitempty"`
	ImprovedFirestone      int32 `protobuf:"varint,31,opt,name=improved_firestone,json=improvedFirestone,proto3" json:"improved_firestone,omitempty"`
	MasterDemonologist     int32 `protobuf:"varint,32,opt,name=master_demonologist,json=masterDemonologist,proto3" json:"master_demonologist,omitempty"`
	SoulLink               bool  `protobuf:"varint,33,opt,name=soul_link,json=soulLink,proto3" json:"soul_link,omitempty"`
	ImprovedSpellstone     int32 `protobuf:"varint,34,opt,name=improved_spellstone,json=improvedSpellstone,proto3" json:"improved_spellstone,omitempty"`
	// Destruction
	ImprovedShadowBolt  int32 `protobuf:"varint,35,opt,name=improved_shadow_bolt,json=improvedShadowBolt,proto3" json:"improved_shadow_bolt,omitempty"`
	Cataclysm           int32 `protobuf:"varint,36,opt,name=cataclysm,proto3" json:"cataclysm,omitempty"`
	Bane                int32 `protobuf:"varint,37,opt,name=bane,proto3" json:"bane,omitempty"`
	Aftermath           int32 `protobuf:"varint,38,opt,name=aftermath,proto3" json:"aftermath,omitempty"`
	ImprovedFirebolt    int32 `protobuf:"varint,39,opt,name=improved_firebolt,json=improvedFirebolt,proto3" json:"improved_firebolt,omitempty"`
	ImprovedLashOfPain  int32 `protobuf:"varint,40,opt,name=improved_lash_of_pain,json=improvedLashOfPain,proto3" json:"improved_lash_of_pain,omitempty"`
	Devastation         int32 `protobuf:"varint,41,opt,name=devastation,proto3" json:"devastation,omitempty"`
	Shadowburn          bool  `protobuf:"varint,42,opt,name=shadowburn,proto3" json:"shadowburn,omitempty"`
	Intensity           int32 `protobuf:"varint,43,opt,name=intensity,proto3" json:"intensity,omitempty"`
	DestructiveReach    int32 `protobuf:"varint,44,opt,name=destructive_reach,json=destructiveReach,proto3" json:"destructive_reach,omitempty"`
	ImprovedSearingPain int32 `protobuf:"varint,45,opt,name=improved_searing_pain,json=improvedSearingPain,proto3" json:"improved_searing_pain,omitempty"`
	Pyroclasm           int32 `protobuf:"varint,46,opt,name=pyroclasm,proto3" json:"pyroclasm,omitempty"`
	ImprovedImmolate    int32 `protobuf:"varint,47,opt,name=improved_immolate,json=improvedImmolate,proto3" json:"improved_immolate,omitempty"`
	Ruin                bool  `protobuf:"varint,48,opt,name=ruin,proto3" json:"ruin,omitempty"`
	Emberstorm          int32 `protobuf:"varint,49,opt,name=emberstorm,proto3" json:"emberstorm,omitempty"`
	Conflagrate         bool  `protobuf:"varint,50,opt,name=conflagrate,proto3" json:"conflagrate,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WarlockTalents) Reset() {
	*x = WarlockTalents{}
	mi := &file_warlock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarlockTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarlockTalents) ProtoMessage() {}

func (x *WarlockTalents) ProtoReflect() protoreflect.Message {
	mi := &file_warlock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarlockTalents.ProtoReflect.Descriptor instead.
func (*WarlockTalents) Descriptor() ([]byte, []int) {
	return file_warlock_proto_rawDescGZIP(), []int{0}
}

func (x *WarlockTalents) GetSuppression() int32 {
	if x != nil {
		return x.Suppression
	}
	return 0
}

func (x *WarlockTalents) GetImprovedCorruption() int32 {
	if x != nil {
		return x.ImprovedCorruption
	}
	return 0
}

func (x *WarlockTalents) GetImprovedCurseOfWeakness() int32 {
	if x != nil {
		return x.ImprovedCurseOfWeakness
	}
	return 0
}

func (x *WarlockTalents) GetImprovedDrainSoul() int32 {
	if x != nil {
		return x.ImprovedDrainSoul
	}
	return 0
}

func (x *WarlockTalents) GetImprovedLifeTap() int32 {
	if x != nil {
		return x.ImprovedLifeTap
	}
	return 0
}

func (x *WarlockTalents) GetImprovedDrainLife() int32 {
	if x != nil {
		return x.ImprovedDrainLife
	}
	return 0
}

func (x *WarlockTalents) GetImprovedCurseOfAgony() int32 {
	if x != nil {
		return x.ImprovedCurseOfAgony
	}
	return 0
}

func (x *WarlockTalents) GetFelConcentration() int32 {
	if x != nil {
		return x.FelConcentration
	}
	return 0
}

func (x *WarlockTalents) GetAmplifyCurse() bool {
	if x != nil {
		return x.AmplifyCurse
	}
	return false
}

func (x *WarlockTalents) GetGrimReach() int32 {
	if x != nil {
		return x.GrimReach
	}
	return 0
}

func (x *WarlockTalents) GetNightfall() int32 {
	if x != nil {
		return x.Nightfall
	}
	return 0
}

func (x *WarlockTalents) GetImprovedDrainMana() int32 {
	if x != nil {
		return x.ImprovedDrainMana
	}
	return 0
}

func (x *WarlockTalents) GetSiphonLife() bool {
	if x != nil {
		return x.SiphonLife
	}
	return false
}

func (x *WarlockTalents) GetCurseOfExhaustion() bool {
	if x != nil {
		return x.CurseOfExhaustion
	}
	return false
}

func (x *WarlockTalents) GetImprovedCurseOfExhaustion() int32 {
	if x != nil {
		return x.ImprovedCurseOfExhaustion
	}
	return 0
}

func (x *WarlockTalents) GetShadowMastery() int32 {
	if x != nil {
		return x.ShadowMastery
	}
	return 0
}

func (x *WarlockTalents) GetDarkPact() bool {
	if x != nil {
		return x.DarkPact
	}
	return false
}

func (x *WarlockTalents) GetImprovedHealthstone() int32 {
	if x != nil {
		return x.ImprovedHealthstone
	}
	return 0
}

func (x *WarlockTalents) GetImprovedImp() int32 {
	if x != nil {
		return x.ImprovedImp
	}
	return 0
}

func (x *WarlockTalents) GetDemonicEmbrace() int32 {
	if x != nil {
		return x.DemonicEmbrace
	}
	return 0
}

func (x *WarlockTalents) GetImprovedHealthFunnel() int32 {
	if x != nil {
		return x.ImprovedHealthFunnel
	}
	return 0
}

func (x *WarlockTalents) GetImprovedVoidwalker() int32 {
	if x != nil {
		return x.ImprovedVoidwalker
	}
	return 0
}

func (x *WarlockTalents) GetFelIntellect() int32 {
	if x != nil {
		return x.FelIntellect
	}
	return 0
}

func (x *WarlockTalents) GetImprovedSayaad() int32 {
	if x != nil {
		return x.ImprovedSayaad
	}
	return 0
}

func (x *WarlockTalents) GetFelDomination() bool {
	if x != nil {
		return x.FelDomination
	}
	return false
}

func (x *WarlockTalents) GetFelStamina() int32 {
	if x != nil {
		return x.FelStamina
	}
	return 0
}

func (x *WarlockTalents) GetMasterSummoner() int32 {
	if x != nil {
		return x.MasterSummoner
	}
	return 0
}

func (x *WarlockTalents) GetUnholyPower() int32 {
	if x != nil {
		return x.UnholyPower
	}
	return 0
}

func (x *WarlockTalents) GetImprovedSubjugateDemon() int32 {
	if x != nil {
		return x.ImprovedSubjugateDemon
	}
	return 0
}

func (x *WarlockTalents) GetDemonicSacrifice() bool {
	if x != nil {
		return x.DemonicSacrifice
	}
	return false
}

func (x *WarlockTalents) GetImprovedFirestone() int32 {
	if x != nil {
		return x.ImprovedFirestone
	}
	return 0
}

func (x *WarlockTalents) GetMasterDemonologist() int32 {
	if x != nil {
		return x.MasterDemonologist
	}
	return 0
}

func (x *WarlockTalents) GetSoulLink() bool {
	if x != nil {
		return x.SoulLink
	}
	return false
}

func (x *WarlockTalents) GetImprovedSpellstone() int32 {
	if x != nil {
		return x.ImprovedSpellstone
	}
	return 0
}

func (x *WarlockTalents) GetImprovedShadowBolt() int32 {
	if x != nil {
		return x.ImprovedShadowBolt
	}
	return 0
}

func (x *WarlockTalents) GetCataclysm() int32 {
	if x != nil {
		return x.Cataclysm
	}
	return 0
}

func (x *WarlockTalents) GetBane() int32 {
	if x != nil {
		return x.Bane
	}
	return 0
}

func (x *WarlockTalents) GetAftermath() int32 {
	if x != nil {
		return x.Aftermath
	}
	return 0
}

func (x *WarlockTalents) GetImprovedFirebolt() int32 {
	if x != nil {
		return x.ImprovedFirebolt
	}
	return 0
}

func (x *WarlockTalents) GetImprovedLashOfPain() int32 {
	if x != nil {
		return x.ImprovedLashOfPain
	}
	return 0
}

func (x *WarlockTalents) GetDevastation() int32 {
	if x != nil {
		return x.Devastation
	}
	return 0
}

func (x *WarlockTalents) GetShadowburn() bool {
	if x != nil {
		return x.Shadowburn
	}
	return false
}

func (x *WarlockTalents) GetIntensity() int32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

func (x *WarlockTalents) GetDestructiveReach() int32 {
	if x != nil {
		return x.DestructiveReach
	}
	return 0
}

func (x *WarlockTalents) GetImprovedSearingPain() int32 {
	if x != nil {
		return x.ImprovedSearingPain
	}
	return 0
}

func (x *WarlockTalents) GetPyroclasm() int32 {
	if x != nil {
		return x.Pyroclasm
	}
	return 0
}

func (x *WarlockTalents) GetImprovedImmolate() int32 {
	if x != nil {
		return x.ImprovedImmolate
	}
	return 0
}

func (x *WarlockTalents) GetRuin() bool {
	if x != nil {
		return x.Ruin
	}
	return false
}

func (x *WarlockTalents) GetEmberstorm() int32 {
	if x != nil {
		return x.Emberstorm
	}
	return 0
}

func (x *WarlockTalents) GetConflagrate() bool {
	if x != nil {
		return x.Conflagrate
	}
	return false
}

type WarlockRotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarlockRotation) Reset() {
	*x = WarlockRotation{}
	mi := &file_warlock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarlockRotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarlockRotation) ProtoMessage() {}

func (x *WarlockRotation) ProtoReflect() protoreflect.Message {
	mi := &file_warlock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarlockRotation.ProtoReflect.Descriptor instead.
func (*WarlockRotation) Descriptor() ([]byte, []int) {
	return file_warlock_proto_rawDescGZIP(), []int{1}
}

type WarlockOptions struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	Armor           WarlockOptions_Armor           `protobuf:"varint,1,opt,name=armor,proto3,enum=proto.WarlockOptions_Armor" json:"armor,omitempty"`
	Summon          WarlockOptions_Summon          `protobuf:"varint,2,opt,name=summon,proto3,enum=proto.WarlockOptions_Summon" json:"summon,omitempty"`
	WeaponImbue     WarlockOptions_WeaponImbue     `protobuf:"varint,3,opt,name=weapon_imbue,json=weaponImbue,proto3,enum=proto.WarlockOptions_WeaponImbue" json:"weapon_imbue,omitempty"`
	MaxFireboltRank WarlockOptions_MaxFireboltRank `protobuf:"varint,4,opt,name=max_firebolt_rank,json=maxFireboltRank,proto3,enum=proto.WarlockOptions_MaxFireboltRank" json:"max_firebolt_rank,omitempty"`
	PetPoolMana     bool                           `protobuf:"varint,5,opt,name=pet_pool_mana,json=petPoolMana,proto3" json:"pet_pool_mana,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WarlockOptions) Reset() {
	*x = WarlockOptions{}
	mi := &file_warlock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarlockOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarlockOptions) ProtoMessage() {}

func (x *WarlockOptions) ProtoReflect() protoreflect.Message {
	mi := &file_warlock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarlockOptions.ProtoReflect.Descriptor instead.
func (*WarlockOptions) Descriptor() ([]byte, []int) {
	return file_warlock_proto_rawDescGZIP(), []int{2}
}

func (x *WarlockOptions) GetArmor() WarlockOptions_Armor {
	if x != nil {
		return x.Armor
	}
	return WarlockOptions_NoArmor
}

func (x *WarlockOptions) GetSummon() WarlockOptions_Summon {
	if x != nil {
		return x.Summon
	}
	return WarlockOptions_NoSummon
}

func (x *WarlockOptions) GetWeaponImbue() WarlockOptions_WeaponImbue {
	if x != nil {
		return x.WeaponImbue
	}
	return WarlockOptions_NoWeaponImbue
}

func (x *WarlockOptions) GetMaxFireboltRank() WarlockOptions_MaxFireboltRank {
	if x != nil {
		return x.MaxFireboltRank
	}
	return WarlockOptions_NoMaximum
}

func (x *WarlockOptions) GetPetPoolMana() bool {
	if x != nil {
		return x.PetPoolMana
	}
	return false
}

type Warlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *WarlockOptions        `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warlock) Reset() {
	*x = Warlock{}
	mi := &file_warlock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warlock) ProtoMessage() {}

func (x *Warlock) ProtoReflect() protoreflect.Message {
	mi := &file_warlock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warlock.ProtoReflect.Descriptor instead.
func (*Warlock) Descriptor() ([]byte, []int) {
	return file_warlock_proto_rawDescGZIP(), []int{3}
}

func (x *Warlock) GetOptions() *WarlockOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type TankWarlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *WarlockOptions        `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TankWarlock) Reset() {
	*x = TankWarlock{}
	mi := &file_warlock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TankWarlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankWarlock) ProtoMessage() {}

func (x *TankWarlock) ProtoReflect() protoreflect.Message {
	mi := &file_warlock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankWarlock.ProtoReflect.Descriptor instead.
func (*TankWarlock) Descriptor() ([]byte, []int) {
	return file_warlock_proto_rawDescGZIP(), []int{4}
}

func (x *TankWarlock) GetOptions() *WarlockOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_warlock_proto protoreflect.FileDescriptor

const file_warlock_proto_rawDesc = "" +
	"\n" +
	"\rwarlock.proto\x12\x05proto\"\x99\x10\n" +
	"\x0eWarlockTalents\x12 \n" +
	"\vsuppression\x18\x01 \x01(\x05R\vsuppression\x12/\n" +
	"\x13improved_corruption\x18\x02 \x01(\x05R\x12improvedCorruption\x12;\n" +
	"\x1aimproved_curse_of_weakness\x18\x03 \x01(\x05R\x17improvedCurseOfWeakness\x12.\n" +
	"\x13improved_drain_soul\x18\x04 \x01(\x05R\x11improvedDrainSoul\x12*\n" +
	"\x11improved_life_tap\x18\x05 \x01(\x05R\x0fimprovedLifeTap\x12.\n" +
	"\x13improved_drain_life\x18\x06 \x01(\x05R\x11improvedDrainLife\x125\n" +
	"\x17improved_curse_of_agony\x18\a \x01(\x05R\x14improvedCurseOfAgony\x12+\n" +
	"\x11fel_concentration\x18\b \x01(\x05R\x10felConcentration\x12#\n" +
	"\ramplify_curse\x18\t \x01(\bR\famplifyCurse\x12\x1d\n" +
	"\n" +
	"grim_reach\x18\n" +
	" \x01(\x05R\tgrimReach\x12\x1c\n" +
	"\tnightfall\x18\v \x01(\x05R\tnightfall\x12.\n" +
	"\x13improved_drain_mana\x18\f \x01(\x05R\x11improvedDrainMana\x12\x1f\n" +
	"\vsiphon_life\x18\r \x01(\bR\n" +
	"siphonLife\x12.\n" +
	"\x13curse_of_exhaustion\x18\x0e \x01(\bR\x11curseOfExhaustion\x12?\n" +
	"\x1cimproved_curse_of_exhaustion\x18\x0f \x01(\x05R\x19improvedCurseOfExhaustion\x12%\n" +
	"\x0eshadow_mastery\x18\x10 \x01(\x05R\rshadowMastery\x12\x1b\n" +
	"\tdark_pact\x18\x11 \x01(\bR\bdarkPact\x121\n" +
	"\x14improved_healthstone\x18\x12 \x01(\x05R\x13improvedHealthstone\x12!\n" +
	"\fimproved_imp\x18\x13 \x01(\x05R\vimprovedImp\x12'\n" +
	"\x0fdemonic_embrace\x18\x14 \x01(\x05R\x0edemonicEmbrace\x124\n" +
	"\x16improved_health_funnel\x18\x15 \x01(\x05R\x14improvedHealthFunnel\x12/\n" +
	"\x13improved_voidwalker\x18\x16 \x01(\x05R\x12improvedVoidwalker\x12#\n" +
	"\rfel_intellect\x18\x17 \x01(\x05R\ffelIntellect\x12'\n" +
	"\x0fimproved_sayaad\x18\x18 \x01(\x05R\x0eimprovedSayaad\x12%\n" +
	"\x0efel_domination\x18\x19 \x01(\bR\rfelDomination\x12\x1f\n" +
	"\vfel_stamina\x18\x1a \x01(\x05R\n" +
	"felStamina\x12'\n" +
	"\x0fmaster_summoner\x18\x1b \x01(\x05R\x0emasterSummoner\x12!\n" +
	"\funholy_power\x18\x1c \x01(\x05R\vunholyPower\x128\n" +
	"\x18improved_subjugate_demon\x18\x1d \x01(\x05R\x16improvedSubjugateDemon\x12+\n" +
	"\x11demonic_sacrifice\x18\x1e \x01(\bR\x10demonicSacrifice\x12-\n" +
	"\x12improved_firestone\x18\x1f \x01(\x05R\x11improvedFirestone\x12/\n" +
	"\x13master_demonologist\x18  \x01(\x05R\x12masterDemonologist\x12\x1b\n" +
	"\tsoul_link\x18! \x01(\bR\bsoulLink\x12/\n" +
	"\x13improved_spellstone\x18\" \x01(\x05R\x12improvedSpellstone\x120\n" +
	"\x14improved_shadow_bolt\x18# \x01(\x05R\x12improvedShadowBolt\x12\x1c\n" +
	"\tcataclysm\x18$ \x01(\x05R\tcataclysm\x12\x12\n" +
	"\x04bane\x18% \x01(\x05R\x04bane\x12\x1c\n" +
	"\taftermath\x18& \x01(\x05R\taftermath\x12+\n" +
	"\x11improved_firebolt\x18' \x01(\x05R\x10improvedFirebolt\x121\n" +
	"\x15improved_lash_of_pain\x18( \x01(\x05R\x12improvedLashOfPain\x12 \n" +
	"\vdevastation\x18) \x01(\x05R\vdevastation\x12\x1e\n" +
	"\n" +
	"shadowburn\x18* \x01(\bR\n" +
	"shadowburn\x12\x1c\n" +
	"\tintensity\x18+ \x01(\x05R\tintensity\x12+\n" +
	"\x11destructive_reach\x18, \x01(\x05R\x10destructiveReach\x122\n" +
	"\x15improved_searing_pain\x18- \x01(\x05R\x13improvedSearingPain\x12\x1c\n" +
	"\tpyroclasm\x18. \x01(\x05R\tpyroclasm\x12+\n" +
	"\x11improved_immolate\x18/ \x01(\x05R\x10improvedImmolate\x12\x12\n" +
	"\x04ruin\x180 \x01(\bR\x04ruin\x12\x1e\n" +
	"\n" +
	"emberstorm\x181 \x01(\x05R\n" +
	"emberstorm\x12 \n" +
	"\vconflagrate\x182 \x01(\bR\vconflagrate\"\x11\n" +
	"\x0fWarlockRotation\"\xe5\x04\n" +
	"\x0eWarlockOptions\x121\n" +
	"\x05armor\x18\x01 \x01(\x0e2\x1b.proto.WarlockOptions.ArmorR\x05armor\x124\n" +
	"\x06summon\x18\x02 \x01(\x0e2\x1c.proto.WarlockOptions.SummonR\x06summon\x12D\n" +
	"\fweapon_imbue\x18\x03 \x01(\x0e2!.proto.WarlockOptions.WeaponImbueR\vweaponImbue\x12Q\n" +
	"\x11max_firebolt_rank\x18\x04 \x01(\x0e2%.proto.WarlockOptions.MaxFireboltRankR\x0fmaxFireboltRank\x12\"\n" +
	"\rpet_pool_mana\x18\x05 \x01(\bR\vpetPoolMana\"L\n" +
	"\x06Summon\x12\f\n" +
	"\bNoSummon\x10\x00\x12\a\n" +
	"\x03Imp\x10\x01\x12\x0e\n" +
	"\n" +
	"Voidwalker\x10\x02\x12\f\n" +
	"\bSuccubus\x10\x03\x12\r\n" +
	"\tFelhunter\x10\x04\"$\n" +
	"\x05Armor\x12\v\n" +
	"\aNoArmor\x10\x00\x12\x0e\n" +
	"\n" +
	"DemonArmor\x10\x01\"?\n" +
	"\vWeaponImbue\x12\x11\n" +
	"\rNoWeaponImbue\x10\x00\x12\x0e\n" +
	"\n" +
	"Spellstone\x10\x01\x12\r\n" +
	"\tFirestone\x10\x02\"x\n" +
	"\x0fMaxFireboltRank\x12\r\n" +
	"\tNoMaximum\x10\x00\x12\t\n" +
	"\x05Rank1\x10\x01\x12\t\n" +
	"\x05Rank2\x10\x02\x12\t\n" +
	"\x05Rank3\x10\x03\x12\t\n" +
	"\x05Rank4\x10\x04\x12\t\n" +
	"\x05Rank5\x10\x05\x12\t\n" +
	"\x05Rank6\x10\x06\x12\t\n" +
	"\x05Rank7\x10\a\x12\t\n" +
	"\x05Rank8\x10\b\":\n" +
	"\aWarlock\x12/\n" +
	"\aoptions\x18\x02 \x01(\v2\x15.proto.WarlockOptionsR\aoptions\">\n" +
	"\vTankWarlock\x12/\n" +
	"\aoptions\x18\x02 \x01(\v2\x15.proto.WarlockOptionsR\aoptionsB\tZ\a./protob\x06proto3"

var (
	file_warlock_proto_rawDescOnce sync.Once
	file_warlock_proto_rawDescData []byte
)

func file_warlock_proto_rawDescGZIP() []byte {
	file_warlock_proto_rawDescOnce.Do(func() {
		file_warlock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warlock_proto_rawDesc), len(file_warlock_proto_rawDesc)))
	})
	return file_warlock_proto_rawDescData
}

var file_warlock_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_warlock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_warlock_proto_goTypes = []any{
	(WarlockOptions_Summon)(0),          // 0: proto.WarlockOptions.Summon
	(WarlockOptions_Armor)(0),           // 1: proto.WarlockOptions.Armor
	(WarlockOptions_WeaponImbue)(0),     // 2: proto.WarlockOptions.WeaponImbue
	(WarlockOptions_MaxFireboltRank)(0), // 3: proto.WarlockOptions.MaxFireboltRank
	(*WarlockTalents)(nil),              // 4: proto.WarlockTalents
	(*WarlockRotation)(nil),             // 5: proto.WarlockRotation
	(*WarlockOptions)(nil),              // 6: proto.WarlockOptions
	(*Warlock)(nil),                     // 7: proto.Warlock
	(*TankWarlock)(nil),                 // 8: proto.TankWarlock
}
var file_warlock_proto_depIdxs = []int32{
	1, // 0: proto.WarlockOptions.armor:type_name -> proto.WarlockOptions.Armor
	0, // 1: proto.WarlockOptions.summon:type_name -> proto.WarlockOptions.Summon
	2, // 2: proto.WarlockOptions.weapon_imbue:type_name -> proto.WarlockOptions.WeaponImbue
	3, // 3: proto.WarlockOptions.max_firebolt_rank:type_name -> proto.WarlockOptions.MaxFireboltRank
	6, // 4: proto.Warlock.options:type_name -> proto.WarlockOptions
	6, // 5: proto.TankWarlock.options:type_name -> proto.WarlockOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_warlock_proto_init() }
func file_warlock_proto_init() {
	if File_warlock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warlock_proto_rawDesc), len(file_warlock_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_warlock_proto_goTypes,
		DependencyIndexes: file_warlock_proto_depIdxs,
		EnumInfos:         file_warlock_proto_enumTypes,
		MessageInfos:      file_warlock_proto_msgTypes,
	}.Build()
	File_warlock_proto = out.File
	file_warlock_proto_goTypes = nil
	file_warlock_proto_depIdxs = nil
}
