// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: warrior.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WarriorShout int32

const (
	WarriorShout_WarriorShoutNone       WarriorShout = 0
	WarriorShout_WarriorShoutBattle     WarriorShout = 1
	WarriorShout_WarriorShoutCommanding WarriorShout = 2
)

// Enum value maps for WarriorShout.
var (
	WarriorShout_name = map[int32]string{
		0: "WarriorShoutNone",
		1: "WarriorShoutBattle",
		2: "WarriorShoutCommanding",
	}
	WarriorShout_value = map[string]int32{
		"WarriorShoutNone":       0,
		"WarriorShoutBattle":     1,
		"WarriorShoutCommanding": 2,
	}
)

func (x WarriorShout) Enum() *WarriorShout {
	p := new(WarriorShout)
	*p = x
	return p
}

func (x WarriorShout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarriorShout) Descriptor() protoreflect.EnumDescriptor {
	return file_warrior_proto_enumTypes[0].Descriptor()
}

func (WarriorShout) Type() protoreflect.EnumType {
	return &file_warrior_proto_enumTypes[0]
}

func (x WarriorShout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WarriorShout.Descriptor instead.
func (WarriorShout) EnumDescriptor() ([]byte, []int) {
	return file_warrior_proto_rawDescGZIP(), []int{0}
}

type WarriorStance int32

const (
	WarriorStance_WarriorStanceNone      WarriorStance = 0
	WarriorStance_WarriorStanceBattle    WarriorStance = 1
	WarriorStance_WarriorStanceDefensive WarriorStance = 2
	WarriorStance_WarriorStanceBerserker WarriorStance = 3
	WarriorStance_WarriorStanceGladiator WarriorStance = 4
)

// Enum value maps for WarriorStance.
var (
	WarriorStance_name = map[int32]string{
		0: "WarriorStanceNone",
		1: "WarriorStanceBattle",
		2: "WarriorStanceDefensive",
		3: "WarriorStanceBerserker",
		4: "WarriorStanceGladiator",
	}
	WarriorStance_value = map[string]int32{
		"WarriorStanceNone":      0,
		"WarriorStanceBattle":    1,
		"WarriorStanceDefensive": 2,
		"WarriorStanceBerserker": 3,
		"WarriorStanceGladiator": 4,
	}
)

func (x WarriorStance) Enum() *WarriorStance {
	p := new(WarriorStance)
	*p = x
	return p
}

func (x WarriorStance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WarriorStance) Descriptor() protoreflect.EnumDescriptor {
	return file_warrior_proto_enumTypes[1].Descriptor()
}

func (WarriorStance) Type() protoreflect.EnumType {
	return &file_warrior_proto_enumTypes[1]
}

func (x WarriorStance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WarriorStance.Descriptor instead.
func (WarriorStance) EnumDescriptor() ([]byte, []int) {
	return file_warrior_proto_rawDescGZIP(), []int{1}
}

// Code generated by tools/talentgen from client build 1.60.1.69893. DO NOT EDIT.
// Field order is the talent string's order: the three trees in the
// client's own order, each tier then column. core.FillTalentsProto
// reads it positionally, so a reorder silently reads the wrong talent.
type WarriorTalents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arms (tree 0, client id 161)
	// node 105958, tier 0 col 0, 3 rank(s), spell 12282
	ImprovedHeroicStrike int32 `protobuf:"varint,1,opt,name=improved_heroic_strike,json=improvedHeroicStrike,proto3" json:"improved_heroic_strike,omitempty"`
	// node 105957, tier 0 col 1, 5 rank(s), spell 16462
	Deflection int32 `protobuf:"varint,2,opt,name=deflection,proto3" json:"deflection,omitempty"`
	// node 105956, tier 0 col 2, 3 rank(s), spell 12286
	ImprovedRend int32 `protobuf:"varint,3,opt,name=improved_rend,json=improvedRend,proto3" json:"improved_rend,omitempty"`
	// node 105955, tier 1 col 0, 2 rank(s), spell 12285
	ImprovedCharge int32 `protobuf:"varint,4,opt,name=improved_charge,json=improvedCharge,proto3" json:"improved_charge,omitempty"`
	// node 105954, tier 1 col 1, 5 rank(s), spell 12295
	ImprovedTacticalMastery int32 `protobuf:"varint,5,opt,name=improved_tactical_mastery,json=improvedTacticalMastery,proto3" json:"improved_tactical_mastery,omitempty"`
	// node 105952, tier 1 col 3, 2 rank(s), spell 12290
	ImprovedOverpower int32 `protobuf:"varint,6,opt,name=improved_overpower,json=improvedOverpower,proto3" json:"improved_overpower,omitempty"`
	// node 105951, tier 2 col 1, 1 rank(s), spell 12296
	AngerManagement bool `protobuf:"varint,7,opt,name=anger_management,json=angerManagement,proto3" json:"anger_management,omitempty"`
	// node 105950, tier 2 col 2, 3 rank(s), spell 12834
	DeepWounds int32 `protobuf:"varint,8,opt,name=deep_wounds,json=deepWounds,proto3" json:"deep_wounds,omitempty"`
	// node 105949, tier 3 col 0, 1 rank(s), spell 1310222
	SpearingStrike bool `protobuf:"varint,9,opt,name=spearing_strike,json=spearingStrike,proto3" json:"spearing_strike,omitempty"`
	// node 105948, tier 3 col 1, 3 rank(s), spell 12163
	TwoHandedWeaponSpecialization int32 `protobuf:"varint,10,opt,name=two_handed_weapon_specialization,json=twoHandedWeaponSpecialization,proto3" json:"two_handed_weapon_specialization,omitempty"`
	// node 105947, tier 3 col 2, 2 rank(s), spell 16493
	Impale int32 `protobuf:"varint,11,opt,name=impale,proto3" json:"impale,omitempty"`
	// node 110524, tier 4 col 0, 5 rank(s), spell 1289682
	Bloodthrill int32 `protobuf:"varint,12,opt,name=bloodthrill,proto3" json:"bloodthrill,omitempty"`
	// node 105945, tier 4 col 1, 1 rank(s), spell 12292
	SweepingStrikes bool `protobuf:"varint,13,opt,name=sweeping_strikes,json=sweepingStrikes,proto3" json:"sweeping_strikes,omitempty"`
	// node 105944, tier 4 col 2, 5 rank(s), spell 1290261
	Weaponmaster int32 `protobuf:"varint,14,opt,name=weaponmaster,proto3" json:"weaponmaster,omitempty"`
	// node 110858, tier 5 col 0, 2 rank(s), spell 12862
	ImprovedSlam int32 `protobuf:"varint,15,opt,name=improved_slam,json=improvedSlam,proto3" json:"improved_slam,omitempty"`
	// node 105942, tier 5 col 2, 3 rank(s), spell 12289
	ImprovedHamstring int32 `protobuf:"varint,16,opt,name=improved_hamstring,json=improvedHamstring,proto3" json:"improved_hamstring,omitempty"`
	// node 105941, tier 6 col 1, 1 rank(s), spell 12294
	MortalStrike bool `protobuf:"varint,17,opt,name=mortal_strike,json=mortalStrike,proto3" json:"mortal_strike,omitempty"`
	// Fury (tree 1, client id 164)
	// node 105938, tier 0 col 1, 5 rank(s), spell 12321
	BoomingVoice int32 `protobuf:"varint,18,opt,name=booming_voice,json=boomingVoice,proto3" json:"booming_voice,omitempty"`
	// node 105939, tier 0 col 2, 5 rank(s), spell 12320
	Cruelty int32 `protobuf:"varint,19,opt,name=cruelty,proto3" json:"cruelty,omitempty"`
	// node 110857, tier 1 col 1, 5 rank(s), spell 12962
	IronWill int32 `protobuf:"varint,20,opt,name=iron_will,json=ironWill,proto3" json:"iron_will,omitempty"`
	// node 105937, tier 1 col 2, 5 rank(s), spell 12322
	UnbridledWrath int32 `protobuf:"varint,21,opt,name=unbridled_wrath,json=unbridledWrath,proto3" json:"unbridled_wrath,omitempty"`
	// node 105936, tier 2 col 0, 3 rank(s), spell 12329
	ImprovedCleave int32 `protobuf:"varint,22,opt,name=improved_cleave,json=improvedCleave,proto3" json:"improved_cleave,omitempty"`
	// node 105935, tier 2 col 1, 1 rank(s), spell 12323
	PiercingHowl bool `protobuf:"varint,23,opt,name=piercing_howl,json=piercingHowl,proto3" json:"piercing_howl,omitempty"`
	// node 105934, tier 2 col 2, 3 rank(s), spell 16487
	BloodCraze int32 `protobuf:"varint,24,opt,name=blood_craze,json=bloodCraze,proto3" json:"blood_craze,omitempty"`
	// node 105953, tier 2 col 3, 3 rank(s), spell 1310236
	BoundlessRage int32 `protobuf:"varint,25,opt,name=boundless_rage,json=boundlessRage,proto3" json:"boundless_rage,omitempty"`
	// node 105933, tier 3 col 0, 5 rank(s), spell 23584
	DualWieldSpecialization int32 `protobuf:"varint,26,opt,name=dual_wield_specialization,json=dualWieldSpecialization,proto3" json:"dual_wield_specialization,omitempty"`
	// node 105977, tier 3 col 1, 1 rank(s), spell 1310315
	RagingBlows bool `protobuf:"varint,27,opt,name=raging_blows,json=ragingBlows,proto3" json:"raging_blows,omitempty"`
	// node 105931, tier 3 col 2, 5 rank(s), spell 12317
	Enrage int32 `protobuf:"varint,28,opt,name=enrage,proto3" json:"enrage,omitempty"`
	// node 105932, tier 3 col 3, 2 rank(s), spell 20502
	ImprovedExecute int32 `protobuf:"varint,29,opt,name=improved_execute,json=improvedExecute,proto3" json:"improved_execute,omitempty"`
	// node 105929, tier 4 col 0, 3 rank(s), spell 1225295
	Precision int32 `protobuf:"varint,30,opt,name=precision,proto3" json:"precision,omitempty"`
	// node 105927, tier 4 col 1, 1 rank(s), spell 12328
	DeathWish bool `protobuf:"varint,31,opt,name=death_wish,json=deathWish,proto3" json:"death_wish,omitempty"`
	// node 105926, tier 4 col 3, 2 rank(s), spell 20504
	ImprovedIntercept int32 `protobuf:"varint,32,opt,name=improved_intercept,json=improvedIntercept,proto3" json:"improved_intercept,omitempty"`
	// node 105978, tier 5 col 0, 2 rank(s), spell 20500
	ImprovedBerserkerRage int32 `protobuf:"varint,33,opt,name=improved_berserker_rage,json=improvedBerserkerRage,proto3" json:"improved_berserker_rage,omitempty"`
	// node 105928, tier 5 col 2, 5 rank(s), spell 12319
	Flurry int32 `protobuf:"varint,34,opt,name=flurry,proto3" json:"flurry,omitempty"`
	// node 105930, tier 6 col 1, 1 rank(s), spell 23881
	Bloodthirst bool `protobuf:"varint,35,opt,name=bloodthirst,proto3" json:"bloodthirst,omitempty"`
	// Protection (tree 2, client id 163)
	// node 105976, tier 0 col 1, 5 rank(s), spell 12298
	ShieldSpecialization int32 `protobuf:"varint,36,opt,name=shield_specialization,json=shieldSpecialization,proto3" json:"shield_specialization,omitempty"`
	// node 105975, tier 0 col 2, 5 rank(s), spell 12297
	Anticipation int32 `protobuf:"varint,37,opt,name=anticipation,proto3" json:"anticipation,omitempty"`
	// node 105974, tier 1 col 0, 2 rank(s), spell 12301
	ImprovedBloodrage int32 `protobuf:"varint,38,opt,name=improved_bloodrage,json=improvedBloodrage,proto3" json:"improved_bloodrage,omitempty"`
	// node 105973, tier 1 col 2, 5 rank(s), spell 12299
	Toughness int32 `protobuf:"varint,39,opt,name=toughness,proto3" json:"toughness,omitempty"`
	// node 105972, tier 1 col 3, 3 rank(s), spell 12287
	ImprovedThunderClap int32 `protobuf:"varint,40,opt,name=improved_thunder_clap,json=improvedThunderClap,proto3" json:"improved_thunder_clap,omitempty"`
	// node 105970, tier 2 col 0, 1 rank(s), spell 12975
	LastStand bool `protobuf:"varint,41,opt,name=last_stand,json=lastStand,proto3" json:"last_stand,omitempty"`
	// node 105971, tier 2 col 1, 2 rank(s), spell 1310316
	MasterOfDefense int32 `protobuf:"varint,42,opt,name=master_of_defense,json=masterOfDefense,proto3" json:"master_of_defense,omitempty"`
	// node 105969, tier 2 col 2, 3 rank(s), spell 12797
	ImprovedRevenge int32 `protobuf:"varint,43,opt,name=improved_revenge,json=improvedRevenge,proto3" json:"improved_revenge,omitempty"`
	// node 110856, tier 2 col 3, 3 rank(s), spell 12792
	Defiance int32 `protobuf:"varint,44,opt,name=defiance,proto3" json:"defiance,omitempty"`
	// node 105968, tier 3 col 0, 3 rank(s), spell 12308
	ImprovedSunderArmor int32 `protobuf:"varint,45,opt,name=improved_sunder_armor,json=improvedSunderArmor,proto3" json:"improved_sunder_armor,omitempty"`
	// node 105967, tier 3 col 1, 3 rank(s), spell 12313
	ImprovedDisarm int32 `protobuf:"varint,46,opt,name=improved_disarm,json=improvedDisarm,proto3" json:"improved_disarm,omitempty"`
	// node 105966, tier 3 col 2, 1 rank(s), spell 1310317
	Vanguard bool `protobuf:"varint,47,opt,name=vanguard,proto3" json:"vanguard,omitempty"`
	// node 105964, tier 4 col 0, 2 rank(s), spell 12312
	ImprovedShieldWall int32 `protobuf:"varint,48,opt,name=improved_shield_wall,json=improvedShieldWall,proto3" json:"improved_shield_wall,omitempty"`
	// node 105965, tier 4 col 1, 1 rank(s), spell 12809
	ConcussionBlow bool `protobuf:"varint,49,opt,name=concussion_blow,json=concussionBlow,proto3" json:"concussion_blow,omitempty"`
	// node 105963, tier 4 col 2, 2 rank(s), spell 12311
	ImprovedShieldBash int32 `protobuf:"varint,50,opt,name=improved_shield_bash,json=improvedShieldBash,proto3" json:"improved_shield_bash,omitempty"`
	// node 105962, tier 4 col 3, 5 rank(s), spell 16538
	Bastion int32 `protobuf:"varint,51,opt,name=bastion,proto3" json:"bastion,omitempty"`
	// node 105961, tier 5 col 2, 3 rank(s), spell 29787
	FocusedRage int32 `protobuf:"varint,52,opt,name=focused_rage,json=focusedRage,proto3" json:"focused_rage,omitempty"`
	// node 105959, tier 6 col 1, 1 rank(s), spell 23922
	ShieldSlam    bool `protobuf:"varint,53,opt,name=shield_slam,json=shieldSlam,proto3" json:"shield_slam,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarriorTalents) Reset() {
	*x = WarriorTalents{}
	mi := &file_warrior_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarriorTalents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarriorTalents) ProtoMessage() {}

func (x *WarriorTalents) ProtoReflect() protoreflect.Message {
	mi := &file_warrior_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarriorTalents.ProtoReflect.Descriptor instead.
func (*WarriorTalents) Descriptor() ([]byte, []int) {
	return file_warrior_proto_rawDescGZIP(), []int{0}
}

func (x *WarriorTalents) GetImprovedHeroicStrike() int32 {
	if x != nil {
		return x.ImprovedHeroicStrike
	}
	return 0
}

func (x *WarriorTalents) GetDeflection() int32 {
	if x != nil {
		return x.Deflection
	}
	return 0
}

func (x *WarriorTalents) GetImprovedRend() int32 {
	if x != nil {
		return x.ImprovedRend
	}
	return 0
}

func (x *WarriorTalents) GetImprovedCharge() int32 {
	if x != nil {
		return x.ImprovedCharge
	}
	return 0
}

func (x *WarriorTalents) GetImprovedTacticalMastery() int32 {
	if x != nil {
		return x.ImprovedTacticalMastery
	}
	return 0
}

func (x *WarriorTalents) GetImprovedOverpower() int32 {
	if x != nil {
		return x.ImprovedOverpower
	}
	return 0
}

func (x *WarriorTalents) GetAngerManagement() bool {
	if x != nil {
		return x.AngerManagement
	}
	return false
}

func (x *WarriorTalents) GetDeepWounds() int32 {
	if x != nil {
		return x.DeepWounds
	}
	return 0
}

func (x *WarriorTalents) GetSpearingStrike() bool {
	if x != nil {
		return x.SpearingStrike
	}
	return false
}

func (x *WarriorTalents) GetTwoHandedWeaponSpecialization() int32 {
	if x != nil {
		return x.TwoHandedWeaponSpecialization
	}
	return 0
}

func (x *WarriorTalents) GetImpale() int32 {
	if x != nil {
		return x.Impale
	}
	return 0
}

func (x *WarriorTalents) GetBloodthrill() int32 {
	if x != nil {
		return x.Bloodthrill
	}
	return 0
}

func (x *WarriorTalents) GetSweepingStrikes() bool {
	if x != nil {
		return x.SweepingStrikes
	}
	return false
}

func (x *WarriorTalents) GetWeaponmaster() int32 {
	if x != nil {
		return x.Weaponmaster
	}
	return 0
}

func (x *WarriorTalents) GetImprovedSlam() int32 {
	if x != nil {
		return x.ImprovedSlam
	}
	return 0
}

func (x *WarriorTalents) GetImprovedHamstring() int32 {
	if x != nil {
		return x.ImprovedHamstring
	}
	return 0
}

func (x *WarriorTalents) GetMortalStrike() bool {
	if x != nil {
		return x.MortalStrike
	}
	return false
}

func (x *WarriorTalents) GetBoomingVoice() int32 {
	if x != nil {
		return x.BoomingVoice
	}
	return 0
}

func (x *WarriorTalents) GetCruelty() int32 {
	if x != nil {
		return x.Cruelty
	}
	return 0
}

func (x *WarriorTalents) GetIronWill() int32 {
	if x != nil {
		return x.IronWill
	}
	return 0
}

func (x *WarriorTalents) GetUnbridledWrath() int32 {
	if x != nil {
		return x.UnbridledWrath
	}
	return 0
}

func (x *WarriorTalents) GetImprovedCleave() int32 {
	if x != nil {
		return x.ImprovedCleave
	}
	return 0
}

func (x *WarriorTalents) GetPiercingHowl() bool {
	if x != nil {
		return x.PiercingHowl
	}
	return false
}

func (x *WarriorTalents) GetBloodCraze() int32 {
	if x != nil {
		return x.BloodCraze
	}
	return 0
}

func (x *WarriorTalents) GetBoundlessRage() int32 {
	if x != nil {
		return x.BoundlessRage
	}
	return 0
}

func (x *WarriorTalents) GetDualWieldSpecialization() int32 {
	if x != nil {
		return x.DualWieldSpecialization
	}
	return 0
}

func (x *WarriorTalents) GetRagingBlows() bool {
	if x != nil {
		return x.RagingBlows
	}
	return false
}

func (x *WarriorTalents) GetEnrage() int32 {
	if x != nil {
		return x.Enrage
	}
	return 0
}

func (x *WarriorTalents) GetImprovedExecute() int32 {
	if x != nil {
		return x.ImprovedExecute
	}
	return 0
}

func (x *WarriorTalents) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *WarriorTalents) GetDeathWish() bool {
	if x != nil {
		return x.DeathWish
	}
	return false
}

func (x *WarriorTalents) GetImprovedIntercept() int32 {
	if x != nil {
		return x.ImprovedIntercept
	}
	return 0
}

func (x *WarriorTalents) GetImprovedBerserkerRage() int32 {
	if x != nil {
		return x.ImprovedBerserkerRage
	}
	return 0
}

func (x *WarriorTalents) GetFlurry() int32 {
	if x != nil {
		return x.Flurry
	}
	return 0
}

func (x *WarriorTalents) GetBloodthirst() bool {
	if x != nil {
		return x.Bloodthirst
	}
	return false
}

func (x *WarriorTalents) GetShieldSpecialization() int32 {
	if x != nil {
		return x.ShieldSpecialization
	}
	return 0
}

func (x *WarriorTalents) GetAnticipation() int32 {
	if x != nil {
		return x.Anticipation
	}
	return 0
}

func (x *WarriorTalents) GetImprovedBloodrage() int32 {
	if x != nil {
		return x.ImprovedBloodrage
	}
	return 0
}

func (x *WarriorTalents) GetToughness() int32 {
	if x != nil {
		return x.Toughness
	}
	return 0
}

func (x *WarriorTalents) GetImprovedThunderClap() int32 {
	if x != nil {
		return x.ImprovedThunderClap
	}
	return 0
}

func (x *WarriorTalents) GetLastStand() bool {
	if x != nil {
		return x.LastStand
	}
	return false
}

func (x *WarriorTalents) GetMasterOfDefense() int32 {
	if x != nil {
		return x.MasterOfDefense
	}
	return 0
}

func (x *WarriorTalents) GetImprovedRevenge() int32 {
	if x != nil {
		return x.ImprovedRevenge
	}
	return 0
}

func (x *WarriorTalents) GetDefiance() int32 {
	if x != nil {
		return x.Defiance
	}
	return 0
}

func (x *WarriorTalents) GetImprovedSunderArmor() int32 {
	if x != nil {
		return x.ImprovedSunderArmor
	}
	return 0
}

func (x *WarriorTalents) GetImprovedDisarm() int32 {
	if x != nil {
		return x.ImprovedDisarm
	}
	return 0
}

func (x *WarriorTalents) GetVanguard() bool {
	if x != nil {
		return x.Vanguard
	}
	return false
}

func (x *WarriorTalents) GetImprovedShieldWall() int32 {
	if x != nil {
		return x.ImprovedShieldWall
	}
	return 0
}

func (x *WarriorTalents) GetConcussionBlow() bool {
	if x != nil {
		return x.ConcussionBlow
	}
	return false
}

func (x *WarriorTalents) GetImprovedShieldBash() int32 {
	if x != nil {
		return x.ImprovedShieldBash
	}
	return 0
}

func (x *WarriorTalents) GetBastion() int32 {
	if x != nil {
		return x.Bastion
	}
	return 0
}

func (x *WarriorTalents) GetFocusedRage() int32 {
	if x != nil {
		return x.FocusedRage
	}
	return 0
}

func (x *WarriorTalents) GetShieldSlam() bool {
	if x != nil {
		return x.ShieldSlam
	}
	return false
}

type Warrior struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *Warrior_Options       `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warrior) Reset() {
	*x = Warrior{}
	mi := &file_warrior_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warrior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warrior) ProtoMessage() {}

func (x *Warrior) ProtoReflect() protoreflect.Message {
	mi := &file_warrior_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warrior.ProtoReflect.Descriptor instead.
func (*Warrior) Descriptor() ([]byte, []int) {
	return file_warrior_proto_rawDescGZIP(), []int{1}
}

func (x *Warrior) GetOptions() *Warrior_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type TankWarrior struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *TankWarrior_Options   `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TankWarrior) Reset() {
	*x = TankWarrior{}
	mi := &file_warrior_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TankWarrior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankWarrior) ProtoMessage() {}

func (x *TankWarrior) ProtoReflect() protoreflect.Message {
	mi := &file_warrior_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankWarrior.ProtoReflect.Descriptor instead.
func (*TankWarrior) Descriptor() ([]byte, []int) {
	return file_warrior_proto_rawDescGZIP(), []int{2}
}

func (x *TankWarrior) GetOptions() *TankWarrior_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type Warrior_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warrior_Rotation) Reset() {
	*x = Warrior_Rotation{}
	mi := &file_warrior_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warrior_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warrior_Rotation) ProtoMessage() {}

func (x *Warrior_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_warrior_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warrior_Rotation.ProtoReflect.Descriptor instead.
func (*Warrior_Rotation) Descriptor() ([]byte, []int) {
	return file_warrior_proto_rawDescGZIP(), []int{1, 0}
}

type Warrior_Options struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartingRage   float64                `protobuf:"fixed64,1,opt,name=starting_rage,json=startingRage,proto3" json:"starting_rage,omitempty"`
	StanceSnapshot bool                   `protobuf:"varint,6,opt,name=stance_snapshot,json=stanceSnapshot,proto3" json:"stance_snapshot,omitempty"`
	QueueDelay     int32                  `protobuf:"varint,8,opt,name=queue_delay,json=queueDelay,proto3" json:"queue_delay,omitempty"`
	Shout          WarriorShout           `protobuf:"varint,3,opt,name=shout,proto3,enum=proto.WarriorShout" json:"shout,omitempty"`
	Stance         WarriorStance          `protobuf:"varint,7,opt,name=stance,proto3,enum=proto.WarriorStance" json:"stance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Warrior_Options) Reset() {
	*x = Warrior_Options{}
	mi := &file_warrior_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warrior_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warrior_Options) ProtoMessage() {}

func (x *Warrior_Options) ProtoReflect() protoreflect.Message {
	mi := &file_warrior_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warrior_Options.ProtoReflect.Descriptor instead.
func (*Warrior_Options) Descriptor() ([]byte, []int) {
	return file_warrior_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Warrior_Options) GetStartingRage() float64 {
	if x != nil {
		return x.StartingRage
	}
	return 0
}

func (x *Warrior_Options) GetStanceSnapshot() bool {
	if x != nil {
		return x.StanceSnapshot
	}
	return false
}

func (x *Warrior_Options) GetQueueDelay() int32 {
	if x != nil {
		return x.QueueDelay
	}
	return 0
}

func (x *Warrior_Options) GetShout() WarriorShout {
	if x != nil {
		return x.Shout
	}
	return WarriorShout_WarriorShoutNone
}

func (x *Warrior_Options) GetStance() WarriorStance {
	if x != nil {
		return x.Stance
	}
	return WarriorStance_WarriorStanceNone
}

type TankWarrior_Rotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TankWarrior_Rotation) Reset() {
	*x = TankWarrior_Rotation{}
	mi := &file_warrior_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TankWarrior_Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankWarrior_Rotation) ProtoMessage() {}

func (x *TankWarrior_Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_warrior_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankWarrior_Rotation.ProtoReflect.Descriptor instead.
func (*TankWarrior_Rotation) Descriptor() ([]byte, []int) {
	return file_warrior_proto_rawDescGZIP(), []int{2, 0}
}

type TankWarrior_Options struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartingRage   float64                `protobuf:"fixed64,1,opt,name=starting_rage,json=startingRage,proto3" json:"starting_rage,omitempty"`
	StanceSnapshot bool                   `protobuf:"varint,6,opt,name=stance_snapshot,json=stanceSnapshot,proto3" json:"stance_snapshot,omitempty"`
	QueueDelay     int32                  `protobuf:"varint,8,opt,name=queue_delay,json=queueDelay,proto3" json:"queue_delay,omitempty"`
	Shout          WarriorShout           `protobuf:"varint,3,opt,name=shout,proto3,enum=proto.WarriorShout" json:"shout,omitempty"`
	Stance         WarriorStance          `protobuf:"varint,7,opt,name=stance,proto3,enum=proto.WarriorStance" json:"stance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TankWarrior_Options) Reset() {
	*x = TankWarrior_Options{}
	mi := &file_warrior_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TankWarrior_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankWarrior_Options) ProtoMessage() {}

func (x *TankWarrior_Options) ProtoReflect() protoreflect.Message {
	mi := &file_warrior_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankWarrior_Options.ProtoReflect.Descriptor instead.
func (*TankWarrior_Options) Descriptor() ([]byte, []int) {
	return file_warrior_proto_rawDescGZIP(), []int{2, 1}
}

func (x *TankWarrior_Options) GetStartingRage() float64 {
	if x != nil {
		return x.StartingRage
	}
	return 0
}

func (x *TankWarrior_Options) GetStanceSnapshot() bool {
	if x != nil {
		return x.StanceSnapshot
	}
	return false
}

func (x *TankWarrior_Options) GetQueueDelay() int32 {
	if x != nil {
		return x.QueueDelay
	}
	return 0
}

func (x *TankWarrior_Options) GetShout() WarriorShout {
	if x != nil {
		return x.Shout
	}
	return WarriorShout_WarriorShoutNone
}

func (x *TankWarrior_Options) GetStance() WarriorStance {
	if x != nil {
		return x.Stance
	}
	return WarriorStance_WarriorStanceNone
}

var File_warrior_proto protoreflect.FileDescriptor

const file_warrior_proto_rawDesc = "" +
	"\n" +
	"\rwarrior.proto\x12\x05proto\"\xca\x10\n" +
	"\x0eWarriorTalents\x124\n" +
	"\x16improved_heroic_strike\x18\x01 \x01(\x05R\x14improvedHeroicStrike\x12\x1e\n" +
	"\n" +
	"deflection\x18\x02 \x01(\x05R\n" +
	"deflection\x12#\n" +
	"\rimproved_rend\x18\x03 \x01(\x05R\fimprovedRend\x12'\n" +
	"\x0fimproved_charge\x18\x04 \x01(\x05R\x0eimprovedCharge\x12:\n" +
	"\x19improved_tactical_mastery\x18\x05 \x01(\x05R\x17improvedTacticalMastery\x12-\n" +
	"\x12improved_overpower\x18\x06 \x01(\x05R\x11improvedOverpower\x12)\n" +
	"\x10anger_management\x18\a \x01(\bR\x0fangerManagement\x12\x1f\n" +
	"\vdeep_wounds\x18\b \x01(\x05R\n" +
	"deepWounds\x12'\n" +
	"\x0fspearing_strike\x18\t \x01(\bR\x0espearingStrike\x12G\n" +
	" two_handed_weapon_specialization\x18\n" +
	" \x01(\x05R\x1dtwoHandedWeaponSpecialization\x12\x16\n" +
	"\x06impale\x18\v \x01(\x05R\x06impale\x12 \n" +
	"\vbloodthrill\x18\f \x01(\x05R\vbloodthrill\x12)\n" +
	"\x10sweeping_strikes\x18\r \x01(\bR\x0fsweepingStrikes\x12\"\n" +
	"\fweaponmaster\x18\x0e \x01(\x05R\fweaponmaster\x12#\n" +
	"\rimproved_slam\x18\x0f \x01(\x05R\fimprovedSlam\x12-\n" +
	"\x12improved_hamstring\x18\x10 \x01(\x05R\x11improvedHamstring\x12#\n" +
	"\rmortal_strike\x18\x11 \x01(\bR\fmortalStrike\x12#\n" +
	"\rbooming_voice\x18\x12 \x01(\x05R\fboomingVoice\x12\x18\n" +
	"\acruelty\x18\x13 \x01(\x05R\acruelty\x12\x1b\n" +
	"\tiron_will\x18\x14 \x01(\x05R\bironWill\x12'\n" +
	"\x0funbridled_wrath\x18\x15 \x01(\x05R\x0eunbridledWrath\x12'\n" +
	"\x0fimproved_cleave\x18\x16 \x01(\x05R\x0eimprovedCleave\x12#\n" +
	"\rpiercing_howl\x18\x17 \x01(\bR\fpiercingHowl\x12\x1f\n" +
	"\vblood_craze\x18\x18 \x01(\x05R\n" +
	"bloodCraze\x12%\n" +
	"\x0eboundless_rage\x18\x19 \x01(\x05R\rboundlessRage\x12:\n" +
	"\x19dual_wield_specialization\x18\x1a \x01(\x05R\x17dualWieldSpecialization\x12!\n" +
	"\fraging_blows\x18\x1b \x01(\bR\vragingBlows\x12\x16\n" +
	"\x06enrage\x18\x1c \x01(\x05R\x06enrage\x12)\n" +
	"\x10improved_execute\x18\x1d \x01(\x05R\x0fimprovedExecute\x12\x1c\n" +
	"\tprecision\x18\x1e \x01(\x05R\tprecision\x12\x1d\n" +
	"\n" +
	"death_wish\x18\x1f \x01(\bR\tdeathWish\x12-\n" +
	"\x12improved_intercept\x18  \x01(\x05R\x11improvedIntercept\x126\n" +
	"\x17improved_berserker_rage\x18! \x01(\x05R\x15improvedBerserkerRage\x12\x16\n" +
	"\x06flurry\x18\" \x01(\x05R\x06flurry\x12 \n" +
	"\vbloodthirst\x18# \x01(\bR\vbloodthirst\x123\n" +
	"\x15shield_specialization\x18$ \x01(\x05R\x14shieldSpecialization\x12\"\n" +
	"\fanticipation\x18% \x01(\x05R\fanticipation\x12-\n" +
	"\x12improved_bloodrage\x18& \x01(\x05R\x11improvedBloodrage\x12\x1c\n" +
	"\ttoughness\x18' \x01(\x05R\ttoughness\x122\n" +
	"\x15improved_thunder_clap\x18( \x01(\x05R\x13improvedThunderClap\x12\x1d\n" +
	"\n" +
	"last_stand\x18) \x01(\bR\tlastStand\x12*\n" +
	"\x11master_of_defense\x18* \x01(\x05R\x0fmasterOfDefense\x12)\n" +
	"\x10improved_revenge\x18+ \x01(\x05R\x0fimprovedRevenge\x12\x1a\n" +
	"\bdefiance\x18, \x01(\x05R\bdefiance\x122\n" +
	"\x15improved_sunder_armor\x18- \x01(\x05R\x13improvedSunderArmor\x12'\n" +
	"\x0fimproved_disarm\x18. \x01(\x05R\x0eimprovedDisarm\x12\x1a\n" +
	"\bvanguard\x18/ \x01(\bR\bvanguard\x120\n" +
	"\x14improved_shield_wall\x180 \x01(\x05R\x12improvedShieldWall\x12'\n" +
	"\x0fconcussion_blow\x181 \x01(\bR\x0econcussionBlow\x120\n" +
	"\x14improved_shield_bash\x182 \x01(\x05R\x12improvedShieldBash\x12\x18\n" +
	"\abastion\x183 \x01(\x05R\abastion\x12!\n" +
	"\ffocused_rage\x184 \x01(\x05R\vfocusedRage\x12\x1f\n" +
	"\vshield_slam\x185 \x01(\bR\n" +
	"shieldSlam\"\xb3\x02\n" +
	"\aWarrior\x120\n" +
	"\aoptions\x18\x03 \x01(\v2\x16.proto.Warrior.OptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\x1a\xe9\x01\n" +
	"\aOptions\x12#\n" +
	"\rstarting_rage\x18\x01 \x01(\x01R\fstartingRage\x12'\n" +
	"\x0fstance_snapshot\x18\x06 \x01(\bR\x0estanceSnapshot\x12\x1f\n" +
	"\vqueue_delay\x18\b \x01(\x05R\n" +
	"queueDelay\x12)\n" +
	"\x05shout\x18\x03 \x01(\x0e2\x13.proto.WarriorShoutR\x05shout\x12,\n" +
	"\x06stance\x18\a \x01(\x0e2\x14.proto.WarriorStanceR\x06stanceJ\x04\b\x02\x10\x03R\x10use_recklessness\"\xa3\x02\n" +
	"\vTankWarrior\x124\n" +
	"\aoptions\x18\x03 \x01(\v2\x1a.proto.TankWarrior.OptionsR\aoptions\x1a\n" +
	"\n" +
	"\bRotation\x1a\xd1\x01\n" +
	"\aOptions\x12#\n" +
	"\rstarting_rage\x18\x01 \x01(\x01R\fstartingRage\x12'\n" +
	"\x0fstance_snapshot\x18\x06 \x01(\bR\x0estanceSnapshot\x12\x1f\n" +
	"\vqueue_delay\x18\b \x01(\x05R\n" +
	"queueDelay\x12)\n" +
	"\x05shout\x18\x03 \x01(\x0e2\x13.proto.WarriorShoutR\x05shout\x12,\n" +
	"\x06stance\x18\a \x01(\x0e2\x14.proto.WarriorStanceR\x06stance*X\n" +
	"\fWarriorShout\x12\x14\n" +
	"\x10WarriorShoutNone\x10\x00\x12\x16\n" +
	"\x12WarriorShoutBattle\x10\x01\x12\x1a\n" +
	"\x16WarriorShoutCommanding\x10\x02*\x93\x01\n" +
	"\rWarriorStance\x12\x15\n" +
	"\x11WarriorStanceNone\x10\x00\x12\x17\n" +
	"\x13WarriorStanceBattle\x10\x01\x12\x1a\n" +
	"\x16WarriorStanceDefensive\x10\x02\x12\x1a\n" +
	"\x16WarriorStanceBerserker\x10\x03\x12\x1a\n" +
	"\x16WarriorStanceGladiator\x10\x04B\tZ\a./protob\x06proto3"

var (
	file_warrior_proto_rawDescOnce sync.Once
	file_warrior_proto_rawDescData []byte
)

func file_warrior_proto_rawDescGZIP() []byte {
	file_warrior_proto_rawDescOnce.Do(func() {
		file_warrior_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warrior_proto_rawDesc), len(file_warrior_proto_rawDesc)))
	})
	return file_warrior_proto_rawDescData
}

var file_warrior_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_warrior_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_warrior_proto_goTypes = []any{
	(WarriorShout)(0),            // 0: proto.WarriorShout
	(WarriorStance)(0),           // 1: proto.WarriorStance
	(*WarriorTalents)(nil),       // 2: proto.WarriorTalents
	(*Warrior)(nil),              // 3: proto.Warrior
	(*TankWarrior)(nil),          // 4: proto.TankWarrior
	(*Warrior_Rotation)(nil),     // 5: proto.Warrior.Rotation
	(*Warrior_Options)(nil),      // 6: proto.Warrior.Options
	(*TankWarrior_Rotation)(nil), // 7: proto.TankWarrior.Rotation
	(*TankWarrior_Options)(nil),  // 8: proto.TankWarrior.Options
}
var file_warrior_proto_depIdxs = []int32{
	6, // 0: proto.Warrior.options:type_name -> proto.Warrior.Options
	8, // 1: proto.TankWarrior.options:type_name -> proto.TankWarrior.Options
	0, // 2: proto.Warrior.Options.shout:type_name -> proto.WarriorShout
	1, // 3: proto.Warrior.Options.stance:type_name -> proto.WarriorStance
	0, // 4: proto.TankWarrior.Options.shout:type_name -> proto.WarriorShout
	1, // 5: proto.TankWarrior.Options.stance:type_name -> proto.WarriorStance
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_warrior_proto_init() }
func file_warrior_proto_init() {
	if File_warrior_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warrior_proto_rawDesc), len(file_warrior_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_warrior_proto_goTypes,
		DependencyIndexes: file_warrior_proto_depIdxs,
		EnumInfos:         file_warrior_proto_enumTypes,
		MessageInfos:      file_warrior_proto_msgTypes,
	}.Build()
	File_warrior_proto = out.File
	file_warrior_proto_goTypes = nil
	file_warrior_proto_depIdxs = nil
}
